chore: add Madhavi Mandalia
EddieHubCommunity/LinkFree pull request #1020
Opened 2022-01-22 06:14 UTC by MadhaviMandalia

- Add profile Madhavi Mandalia

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

2022-01-22 06:34 UTC, syedsohan requested changes

2022-01-22 06:34 UTC, syedsohan commented on public/data/MadhaviMandalia.json
> +  "bio": "Open Source Enthusiast | Sotware Engineer | YouTuber ",
```suggestion
  "bio": "Open Source Enthusiast | Software Engineer | YouTuber",
```

2022-01-22 09:48 UTC, krshdev approved these changes

2022-01-22 12:04 UTC, syedsohan approved these changes

2022-01-22 14:07 UTC, Shivansh-yadav13 approved these changes

2022-01-22 16:20 UTC, vikasganiga05 approved these changes

2022-01-22 22:37 UTC, ssensalo approved these changes

2022-01-23 03:06 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-23 03:06 UTC, merged