adding my profile to LinkFree
EddieHubCommunity/LinkFree pull request #1050
Opened 2022-01-31 06:42 UTC by nurakmal920207

2022-01-31 08:49 UTC, krshdev approved these changes

2022-01-31 09:53 UTC, syedsohan approved these changes

2022-01-31 15:24 UTC, Panquesito7 requested changes

2022-02-03 04:48 UTC, Pradumnasaraf requested changes
Hey! **nurakmal**  there is still a need of some changes, you can also click on commit suggestion for committing it :)
Thank YOu.

2022-02-03 04:48 UTC, Pradumnasaraf commented on public/data/nurakmal920207.json
> +      "icon": "graduation hat",
```suggestion
      "icon": "graduation-hat",
```

2022-02-03 05:29 UTC, Panquesito7 approved these changes

2022-02-03 07:10 UTC, KendallDoesCoding commented
@nurakmal920207 Your still missing a dash.

2022-02-03 07:10 UTC, KendallDoesCoding commented on public/data/nurakmal920207.json
> +      "icon": "graduation hat",
@nurakmal920207 Please commit this into the project ASAP

2022-02-03 07:11 UTC, KendallDoesCoding approved these changes

2022-02-03 07:11 UTC, KendallDoesCoding commented
Please ignore my above comments, now deleted, saw the first commit instead of the latest commit.

2022-02-03 07:19 UTC, KendallDoesCoding commented
@Panquesito7 @emmalearnscode LGTM ✅

2022-02-03 07:21 UTC, Pradumnasaraf approved these changes
LGTM!, Thank you for your contribution:D

2022-02-03 07:33 UTC, nurakmal920207 commented
Thank you for all your  helps and comments. This is my first pull request so I am not sure what should I do next. Can I close this pull request now? Is it successfully merged to the main branch? Appreciate helps in this. Thank you.

2022-02-03 07:40 UTC, emmalearnscode approved these changes

2022-02-03 07:41 UTC, emmalearnscode commented
> Thank you for all your helps and comments. This is my first pull request so I am not sure what should I do next. Can I close this pull request now? Is it successfully merged to the main branch? Appreciate helps in this. Thank you.

You wait for a maintainer to merge it, which I will do now. thanks for contributing!

2022-02-03 07:41 UTC, merged

2022-02-03 07:42 UTC, Pradumnasaraf commented
> Thank you for all your  helps and comments. This is my first pull request so I am not sure what should I do next. Can I close this pull request now? Is it successfully merged to the main branch? Appreciate helps in this. Thank you.

Hey, you need not to close this pull request as it is not merged yet. You only close PR if there is some issue with the PR or the changes are not required in the project.

2022-02-03 07:49 UTC, nurakmal920207 commented
> You wait for a maintainer to merge it, which I will do now. thanks for contributing!

Thank you! I can find my file in the main branch now. However, when I search for my name in the Linkfree, I cannot find it. Any idea why?

2022-02-03 07:49 UTC, nurakmal920207 commented
> Hey, you need not to close this pull request. You only close PR if there is some issue with the PR or the changes are not required in the project.

Thank you for the clarification!

2022-02-03 07:51 UTC, KendallDoesCoding commented
> > You wait for a maintainer to merge it, which I will do now. thanks for contributing!
> 
> Thank you! I can find my file in the main branch now. However, when I search for my name in the Linkfree, I cannot find it. Any idea why?

It deploys by release, the last release was 6 days ago, whenever this repo adds a new feature and makes a new release, your name will show up then.

2022-02-03 07:55 UTC, emmalearnscode commented
Yes, it'll show up next time a fix or a feature is deployed :)

2022-02-03 07:55 UTC, nurakmal920207 commented
I see. I understand now. Thank you so much everyone!