Create elviscoly.json
EddieHubCommunity/LinkFree pull request #1051
Opened 2022-01-31 15:46 UTC by elviscoly

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-01-31 16:39 UTC, kumarsonsoff3 commented
Commit all these changes, and then you have done with this 🙃

2022-01-31 19:34 UTC, syedsohan commented on public/data/elviscoly.json
> +  "bio": "Open Source Enthusiast!",
Provide your bio.

2022-01-31 19:38 UTC, syedsohan requested changes
Provide Title, Date and Description of your Milestone too!

2022-01-31 19:38 UTC, syedsohan commented on public/data/elviscoly.json
> +  "name": "YOUR NAME",
```suggestion
  "name": "Iria Elvis",
```

2022-01-31 19:38 UTC, syedsohan commented on public/data/elviscoly.json
> +  "bio": "Open Source Enthusiast!",
Provide your bio.

2022-01-31 19:38 UTC, syedsohan commented on public/data/elviscoly.json
> +  "avatar": "https://github.com/YOUR_GITHUB_USERNAME.png",
```suggestion
  "avatar": "https://github.com/elviscoly.png",
```

2022-01-31 19:38 UTC, syedsohan commented on public/data/elviscoly.json
> +      "url": "https://github.com/YOUR_GITHUB_USERNAME",
```suggestion
      "url": "https://github.com/elviscoly",
```

2022-01-31 19:38 UTC, syedsohan commented on public/data/elviscoly.json
> +      "url": "https://twitter.com/YOUR_TWITTER_USERNAME",
Provide your Twitter profile link if you have one!

2022-02-01 03:33 UTC, krshdev requested changes
Looks like you haven't edited the template, can you update it with your info?

2022-02-01 09:00 UTC, closed without merging