Added json file for yash-0025
EddieHubCommunity/LinkFree pull request #1065
Opened 2022-02-05 14:54 UTC by yash-0025

Added Json file for yash-0025

2022-02-05 16:08 UTC, syedsohan requested changes

2022-02-05 16:08 UTC, syedsohan commented on public/data/yash-0025.json
> +
```suggestion
```

2022-02-05 16:08 UTC, syedsohan commented on public/data/yash-0025.json
> +  }
```suggestion
}
```

2022-02-05 17:26 UTC, KendallDoesCoding reviewed
Maybe consider the file name being YashPatil.json or Yash0025.json

According to me both these look good, instead of the - and capitalize text properly so pick one you like.

2022-02-05 17:40 UTC, Pradumnasaraf approved these changes
LGTM!, thanks for your contribution :+1:

2022-02-05 17:42 UTC, syedsohan approved these changes

2022-02-06 01:13 UTC, Panquesito7 approved these changes

2022-02-06 01:17 UTC, merged