feat: Functionality to cache and reuse dependencies before build
EddieHubCommunity/LinkFree pull request #1124
Opened 2022-02-12 19:47 UTC by Pranav016

## Fixes Issue
Closes #1118 

## Changes proposed
- Add functionality to cache dependencies and reuse the cache if the dependencies haven't change.
- This makes the build process much faster (we can build within seconds)
- Since for free tier, only 2000 build minutes/month are allotted on GitHub action servers, if in future the project becomes very large, we can take advantage of caching and keep the build times low.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-02-21 06:59 UTC, Pranav016 commented
@eddiejaoude can you pls review this PR? 🙂

2022-03-01 17:32 UTC, nhcarrigan requested changes
My understanding is we actually need to check if the cache step has a hit, and skip the install step if it does.

2022-03-01 17:32 UTC, nhcarrigan commented on .github/workflows/build.yml
> +        uses: actions/cache@v2
```suggestion
      - name: cache lookup
        id: cache
        uses: actions/cache@v2
```

2022-03-01 17:32 UTC, nhcarrigan commented on .github/workflows/build.yml
>          run: npm ci
```suggestion
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
```

2022-03-01 17:32 UTC, nhcarrigan commented on .github/workflows/build.yml
>          run: npm ci
```suggestion
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
```

2022-03-03 06:42 UTC, krshdev reviewed
I looked up the documentation for this, and I had a question, did you have a look at these? 

![image](https://user-images.githubusercontent.com/91655303/156510845-085e2bae-268d-47f9-b8ac-a1ea8449d7e0.png)

2022-03-03 06:56 UTC, Pranav016 commented
> I looked up the documentation for this, and I had a question, did you have a look at these?
> 
> ![image](https://user-images.githubusercontent.com/91655303/156510845-085e2bae-268d-47f9-b8ac-a1ea8449d7e0.png)

It only breaks if we are never updating the cache(which usually happens with our local cache) but in this case we are updating the cache whenever our lock file is changed and we store cache even for different node versions if we decide to test on multiple. I have cached my dependencies in the past, even with `npm ci` and they haven't given any issues..
Can you also provide a link to the reference docs, I couldn't find the dedicated note.

2022-03-03 15:05 UTC, krshdev commented
> Can you also provide a link to the reference docs, I couldn't find the dedicated note.

https://github.com/actions/cache/blob/main/examples.md#node---npm

2022-03-03 15:47 UTC, nhcarrigan commented
That's a good catch @krshdev! It sounds like this isn't an approach we want to take, then.

2022-06-19 20:35 UTC, nhcarrigan commented
Going to close this per Eddie's comment above. Thanks for your interest in contributing!!!

2022-06-19 20:35 UTC, closed without merging