Added profile sshiv5768
EddieHubCommunity/LinkFree pull request #1131
Opened 2022-02-16 13:05 UTC by sshiv5768

## Fixes Issue

## Changes proposed

- [x] Added new ``sshiv5768.json`` file.
- [x] Added necessary details like ``name``, ``bio``, ``avatar``.
- [x] Added social media handles. 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
![LinkFreeprofile](https://user-images.githubusercontent.com/40575397/154270368-e1f10835-e335-4d41-a67b-f76b2507d406.png)

## Note to reviewers

2022-02-16 13:06 UTC, KendallDoesCoding approved these changes
LGTM ✔️

2022-02-16 14:28 UTC, Panquesito7 commented on public/data/sshiv5768.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-02-16 18:16 UTC, kabir0x17 approved these changes
Looks good to me 👍

2022-02-16 18:19 UTC, ssensalo approved these changes

2022-02-17 04:01 UTC, krshdev approved these changes

2022-02-17 13:37 UTC, vikasganiga05 requested changes
Your JSON file is not formatted correctly. Also missing endline. You can use an online JSON formatter or vscode prettier extension to format correctly.

2022-02-17 14:46 UTC, Panquesito7 commented on public/data/sshiv5768.json
> +    ]
Formatting will be done automatically by GitHub Actions.

2022-02-17 15:42 UTC, Pradumnasaraf approved these changes
LGTM!

2022-02-18 18:43 UTC, emmalearnscode approved these changes

2022-02-18 18:43 UTC, merged