profile json added
EddieHubCommunity/LinkFree pull request #114
Opened 2021-09-13 16:22 UTC by theMillenniumFalcon

2021-09-13 16:25 UTC, FayasNoushad approved these changes

2021-09-13 16:55 UTC, nhcarrigan requested changes
Just a quick nitpick for EOF NL

2021-09-13 16:55 UTC, nhcarrigan commented on public/data/theMillenniumFalcon.json
> +}
```suggestion
}

```

2021-09-13 17:19 UTC, theMillenniumFalcon commented on public/data/theMillenniumFalcon.json
> +}
new-line added

2021-09-13 18:35 UTC, nhcarrigan commented
This will need a rebase:

https://www.nhcarrigan.com/notes/#/git-commands/rebase-branch

2021-09-27 18:51 UTC, eddiejaoude commented
Closing as seems like another PR was created https://github.com/EddieHubCommunity/LinkFree/pull/271

2021-09-27 18:51 UTC, closed without merging