Add profile benjaminmichaelis.json
EddieHubCommunity/LinkFree pull request #1162
Opened 2022-03-05 04:14 UTC by BenjaminMichaelis

Adding Benjamin Michaelis profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-03-05 05:09 UTC, kumarsonsoff3 approved these changes
You are requested to perform these changes!

2022-03-05 05:09 UTC, kumarsonsoff3 commented on public/data/benjaminmichaelis.json
> +      "color": "#gray",
Please use the correct **_Hex code_** for color!

```suggestion
      "color": "#787777",
```

2022-03-05 05:09 UTC, kumarsonsoff3 commented on public/data/benjaminmichaelis.json
> +  "bio": "Full time student, part-time adventure seeker/traveler",
It seems more attractive

```suggestion
  "bio": "Full time Student | Part-time adventure seeker | Traveler",
```

2022-03-05 05:28 UTC, kumarsonsoff3 requested changes
You are Requested to perform these Changes

2022-03-05 05:28 UTC, kumarsonsoff3 commented on public/data/benjaminmichaelis.json
> +  "bio": "Full time student, part-time adventure seeker/traveler",
It seems more attractive

```suggestion
  "bio": "Full time Student | Part-time Adventure seeker | Traveler",
```

2022-03-05 05:28 UTC, kumarsonsoff3 commented on public/data/benjaminmichaelis.json
> +      "color": "#gray",
Please use the correct **_Hex code_** for color!

```suggestion
      "color": "#787777",
```

2022-03-05 05:28 UTC, kumarsonsoff3 commented on public/data/benjaminmichaelis.json
> +      "icon": "code",
There is no icon for `"code"`.
**you can use `"Codewars"`, or `"Codeforces"` instead!**

2022-03-05 16:35 UTC, kumarsonsoff3 approved these changes
**Nicely Done! 😀**

2022-03-05 21:10 UTC, ssensalo approved these changes

2022-03-06 07:47 UTC, Panquesito7 approved these changes

2022-03-06 07:48 UTC, merged