#866-align version and input field on small screen
EddieHubCommunity/LinkFree pull request #1180
Opened 2022-03-14 20:12 UTC by YuriDevAT

## Fixes Issue

Closes #866 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
![input-version-centered](https://user-images.githubusercontent.com/54622834/158252960-c7a51e38-3574-4701-b6c7-662dcf58af09.png)

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-03-15 04:52 UTC, krshdev approved these changes
Looks good, thanks for the contribution 👍

2022-03-15 14:08 UTC, Panquesito7 approved these changes

2022-03-15 16:15 UTC, ssensalo approved these changes

2022-03-15 21:36 UTC, emmalearnscode requested changes
There appears to be a ```padding-right: 0.5rem !important;``` on the div containing the github icon and version which just throws off the central alignment slightly.

2022-03-17 11:24 UTC, emmalearnscode approved these changes

2022-03-17 11:25 UTC, merged