CSS changes acc to Issue#948
EddieHubCommunity/LinkFree pull request #1189
Opened 2022-03-21 04:07 UTC by vish-han

## Fixes Issue
#948 

Closes #948 
## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

Removed This piece of code from Links.css 
https://user-images.githubusercontent.com/57045550/148688461-efae8a09-e7df-41f0-b003-e6fbef402e23.png
Added this code in Links.js
https://user-images.githubusercontent.com/57045550/148688485-54d1f9ae-5859-4b4a-a921-e6ee23871cae.png

## Note to reviewers

2022-03-21 19:31 UTC, emmalearnscode requested changes
Hi Vishal! I just merged your profile in the other PR you created but unfortunately it has created a conflict in this PR, otherwise the CSS file looks good. If you can solve the merge conflict and let us know when you're done we can take another look at this PR and get it merged. If you need help with the conflict don't hesitate to ask :)

2022-03-24 08:26 UTC, schmelto requested changes

2022-03-24 08:26 UTC, schmelto commented on public/data/vishalchauhan.json
> +  "bio": "OpenSource Enthusiast interested in Cloud Native Technologies
```suggestion
  "bio": "OpenSource Enthusiast interested in Cloud Native Technologies",
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-03-24 12:29 UTC, vish-han commented
@schmelto  and @emmalearnscode  i have tried to resolve the merge conflict , can you please review the PR now.😊

2022-03-24 13:20 UTC, schmelto approved these changes
LGTM.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

2022-03-27 08:39 UTC, krshdev approved these changes

2022-03-27 11:30 UTC, Pradumnasaraf approved these changes
LGTM, thank you for your contribution :rocket: :smile: 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient, Elegant

2022-03-27 12:02 UTC, emmalearnscode approved these changes

2022-03-27 12:03 UTC, merged