feat: move icons to icons.md from readme.md
EddieHubCommunity/LinkFree pull request #1200
Opened 2022-03-26 13:09 UTC by kishoreandra

Move icons from readme.md to a separate file (icons.md) and add link to navigate to the same from readme.

## Fixes Issue #1195 

## Changes proposed

- [x]  Move icons to seperate file; marked as done

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-03-26 13:33 UTC, schmelto requested changes

2022-03-26 13:33 UTC, schmelto commented on README.md
> +Check [Icons.md](/icons.md) for the all the supported icons
```suggestion
Check [Icons.md](/icons.md) for all the supported icons.
```

2022-03-26 17:38 UTC, schmelto approved these changes
Lgtm

2022-03-26 18:32 UTC, vikasganiga05 approved these changes
LGTM :+1: Thanks! for your contribution :tada:

2022-03-26 20:49 UTC, ssensalo approved these changes

2022-03-27 03:23 UTC, kishoreandra commented
@vikasganiga05 @schmelto 
Great 😃 Thank you

2022-03-27 08:06 UTC, schmelto commented
> @vikasganiga05 @schmelto 
> 
> Great 😃 Thank you, what would be the next steps 🤔 

Waiting for another maintainer to approve and than the pr will get merged. No need from you side to do something.

2022-03-27 08:21 UTC, kishoreandra commented
> > @vikasganiga05 @schmelto
> > Great 😃 Thank you, what would be the next steps 🤔
> 
> Waiting for another maintainer to approve and than the pr will get merged. No need from you side to do something.

Awesome 😎

2022-03-27 10:06 UTC, emmalearnscode approved these changes
Looks good, thanks for contributing!

2022-03-27 10:06 UTC, merged

2022-03-27 10:40 UTC, kishoreandra commented
> Looks good, thanks for contributing!

Thank you 😊, my pleasure