How about adding linkedin and Instagram Link as well
EddieHubCommunity/LinkFree pull request #126
Opened 2021-09-13 16:41 UTC by Recognizeyourself

Adding every social media link

2021-09-13 16:45 UTC, rohan-kulkarni-25 requested changes
Linkedin Spelling is wrong please fix it

2021-09-13 16:47 UTC, FayasNoushad approved these changes

2021-09-13 17:07 UTC, nhcarrigan commented on src/Components/Links.js
> +    linkdin: 'blue'
```suggestion
    linkedin: 'blue',
```

Fix the lint issue so the build passes, and correct spelling mistake.

2021-09-13 17:07 UTC, nhcarrigan requested changes
refer to comment 🙂

2021-09-17 18:55 UTC, BOLT04 approved these changes
LGTM 👍

2021-09-18 16:58 UTC, nhcarrigan commented
Could you resolve the conflicts please? :)

2021-09-27 21:05 UTC, eddiejaoude commented
I resolved the conflict so we can get it merged in 🤓

2021-09-27 21:05 UTC, merged