profile link added for ihtisham
EddieHubCommunity/LinkFree pull request #1261
Opened 2022-05-01 00:51 UTC by ihtishamKhan

I have added my profile link also some missing icons that I needed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

The package.json file is added to the commit, it is because of my code editor added some tab space

Also, I have added a couple of missing icons that I needed

I was not able to `npm start` it was giving an error so I have to modify the script like: `"start": "react-scripts --openssl-legacy-provider start",` which I removed before commit

2022-05-02 17:06 UTC, Pradumnasaraf requested changes
Hey! please revert changes in  `package-lock.json`, `package-lock.json.`.

Also, create a separate PR for adding Icons.

2022-05-04 11:55 UTC, ihtishamKhan commented
Hey! can someone guide me what is the correct way to revert these changes in the `package.json` and `package-lock.json` files?

Should I delete this PR and submit another one?

2022-05-05 02:32 UTC, kumarsonsoff3 requested changes

2022-05-05 02:32 UTC, kumarsonsoff3 commented on public/data/ihtishamKhan.json
> +      "icon": "graduation-cap",
`graduation-cap` is an incorrect keyword, use `graduation-hat` instead! 

```suggestion
      "icon": "graduation-hat",
```

2022-05-05 02:42 UTC, kumarsonsoff3 commented
Also, I suggest you to use other icons in place of the **language icons** you have used until we add those icons to our [icons.md](https://github.com/EddieHubCommunity/LinkFree/blob/main/icons.md).

It would be great if you create an issue for adding new icons to linkfree, and create a PR with reference to that issue.
<hr/>

**What do other Reviewers think in this regard??**

2022-05-06 18:58 UTC, emmalearnscode approved these changes

2022-05-06 18:59 UTC, emmalearnscode commented
> Also, I suggest you to use other icons in place of the **language icons** you have used until we add those icons to our [icons.md](https://github.com/EddieHubCommunity/LinkFree/blob/main/icons.md).
> 
> It would be great if you create an issue for adding new icons to linkfree, and create a PR with reference to that issue.
> 
> **What do other Reviewers think in this regard??**

We have a default icon in case the icons don’t yet exist and since a new issue has been raised I’d suggest leaving the icon names as they are. The default icon will be shown to start with but as soon as someone tackles the issue and adds the icons then they’ll be shown instead and no need for this file to be updated.

2022-05-07 03:03 UTC, Pradumnasaraf approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-07 03:32 UTC, kumarsonsoff3 approved these changes
LGTM 👍 Good to goo! 🚀

2022-05-08 00:07 UTC, Panquesito7 approved these changes

2022-05-08 00:11 UTC, merged

2022-05-08 07:16 UTC, ihtishamKhan commented
@kumarsonsoff3 @emmalearnscode 
I can't see my code in the main branch, although it is merged

2022-05-08 07:18 UTC, emmalearnscode commented
@ihtishamKhan merging doesn’t automatically deploy it, it’ll appear next time the site gets deployed

2022-05-08 07:22 UTC, ihtishamKhan commented
@emmalearnscode just want to know that the file I have added is not even in the main branch, this one also to appear later when the site gets deployed?

2022-05-08 07:35 UTC, emmalearnscode commented
@ihtishamKhan I can see it on the main branch under public/data (they’re alphabetical but small letters come after capitals so make sure you scroll down to i and not I )

2022-05-08 07:50 UTC, ihtishamKhan commented
I didn't know about this type of sorting, Thank you so much @emmalearnscode