Created johan237.json file
EddieHubCommunity/LinkFree pull request #1262
Opened 2022-05-01 09:42 UTC by johan237

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-01 10:05 UTC, kumarsonsoff3 requested changes
Looks good, but **minor fixes are required.** 👨‍💻

**Please perform the following changes, then you are Good to goo!**

2022-05-01 10:05 UTC, kumarsonsoff3 commented on public/data/johan237.json
> +      "icon": "blog",
We don't have an icon for the keyword **`blog`**, instead, use **`hashnode`.** 

```suggestion
      "icon": "hashnode",
```

2022-05-02 07:40 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-05-02 13:14 UTC, kumarsonsoff3 approved these changes

2022-05-02 17:02 UTC, Pradumnasaraf approved these changes
Looks good to me!!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-05-02 17:07 UTC, emmalearnscode approved these changes

2022-05-02 17:08 UTC, merged