README.md Update
EddieHubCommunity/LinkFree pull request #1266
Opened 2022-05-03 05:38 UTC by shivam-sharma7

## Changes proposed
Installation Steps
- Clone the project `git clone <url>`

2022-05-03 12:18 UTC, kumarsonsoff3 requested changes

2022-05-03 12:18 UTC, kumarsonsoff3 commented on README.md
> +- Contributions make the open source community such an amazing place to learn, inspire,collaboration and create.
There is a missing space and a grammatical error!

```suggestion
- Contributions make the open source community such an amazing place to learn, inspire, collaborate, and create.
```

2022-05-03 14:33 UTC, vikasganiga05 requested changes
Hi, my suggestion is to add the full URL template for the forked repository.

2022-05-03 14:33 UTC, vikasganiga05 commented on README.md
> +2. Clone the project `git clone <url>`
```suggestion
2. Clone the project `git clone https://github.com/<your-github-username>/LinkFree`
```

2022-05-04 17:57 UTC, emmalearnscode commented
This change only demonstrates cloning with https. I wonder if instead a screenshot would be better of where to find the git clone instruction under the code button?

2022-05-05 00:30 UTC, closed without merging