Add abubakar
EddieHubCommunity/LinkFree pull request #1268
Opened 2022-05-04 00:49 UTC by Abubakarsadiqq

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-04 02:57 UTC, Panquesito7 commented on public/data/abubakar.json
> +         "name":"follow me on github",
I recommend capitalizing the `h` and the `g`. What do you think?
```suggestion
         "name":"follow me on GitHub",
```

2022-05-04 16:06 UTC, kabir0x23 requested changes
Looks good 
but there are two small issues.
1. remove the `package-lock.json` file
2. rename yourname.json file to username.json
abubakar.json -> abubakarsadiqq.json

that's it

2022-05-05 02:24 UTC, kumarsonsoff3 requested changes
Could you please **Revert** the changes in `package-lock.json`, just:

1. Copy the content from this [package-lock.json](https://github.com/EddieHubCommunity/LinkFree/blob/main/package-lock.json)
2. Paste in place of the code in the `package-lock.json` file of your fork!

⚠ Also, Change your filename to `Abubakarsadiqq.json`

2022-05-07 04:33 UTC, Abubakarsadiqq commented
> Looks good but there are two small issues.
> 
> 1. remove the `package-lock.json` file
> 2. rename yourname.json file to username.json
>    abubakar.json -> abubakarsadiqq.json
> 
> that's it


Done boss

2022-05-07 04:59 UTC, kabir0x23 approved these changes
Looks good ✨ 
```diff
+ abubakarsadiqq.json
```

2022-05-07 05:05 UTC, kabir0x23 reviewed
Last thing you have to do.
You just removed that file from your project, instead of from your commit

![image](https://user-images.githubusercontent.com/44284877/167239590-a0a63980-a605-4bfa-9c1d-6cb051d15614.png)

```diff
+ 1. Just add that file back and commit only the username.json file.
+ This file -> https://github.com/EddieHubCommunity/LinkFree/blob/main/package-lock.json 
```
That's it

2022-05-08 11:17 UTC, kumarsonsoff3 commented
Hey @Abubakarsadiqq,  

Unfortunately, you have deleted the `package-lock.json` file from your fork. (They said to **Revert** the changes)

No worries, I've restored the file for you, you just need to **merge the [PR #1](https://github.com/Abubakarsadiqq/LinkFree/pull/1/files) to your fork.** Rest will take care of itself!

2022-05-10 14:15 UTC, ahmed82 requested changes
To avoid committing changes to other files such as 'package-lock.json'  when you're willing to stage your new profile file just do $:/> git add abubakarsadiqq.json
NOT
$:/> git add . or -A

2022-05-11 04:28 UTC, Abubakarsadiqq commented
Thank you alll for helping it's been greate learning from you guys , yay!!

2022-05-13 10:50 UTC, kumarsonsoff3 approved these changes

2022-05-13 13:53 UTC, Panquesito7 approved these changes

2022-05-14 09:25 UTC, Vyvy-vi approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-14 09:26 UTC, merged