Soham Ratnaparkhi
EddieHubCommunity/LinkFree pull request #1269
Opened 2022-05-04 05:24 UTC by SohamRatnaparkhi

Hello, I am **Soham Ratnaparkhi** and I intend to start my open-source contributions journey through LinkFree. Thank you!

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-05-04 17:49 UTC, emmalearnscode requested changes
There’s a failing test due to an invalid character in line 20, if you could fix it and push your changes this should be good to go.

2022-05-05 02:09 UTC, kumarsonsoff3 requested changes
Minor fixes required!

2022-05-05 02:09 UTC, kumarsonsoff3 commented on public/data/SohamRatnaparkhi.json
> +      "icon": "LinkedIn	"
```suggestion
      "icon": "LinkedIn"
```

2022-05-14 09:22 UTC, Vyvy-vi reviewed
There was a duplicate PR for the same, that was merged a few days ago (#1271)
We're closing this PR, as your profile has been added to LinkFree! - http://linkfree.eddiehub.org/SohamRatnaparkhi

2022-05-14 09:22 UTC, closed without merging