adding a new profile
EddieHubCommunity/LinkFree pull request #1270
Opened 2022-05-04 07:17 UTC by dunyanong

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-04 15:02 UTC, Panquesito7 requested changes

2022-05-04 15:02 UTC, Panquesito7 commented on public/data/dunyanong.json
> +  }
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-04 17:47 UTC, emmalearnscode approved these changes

2022-05-05 02:05 UTC, kumarsonsoff3 approved these changes

2022-05-05 02:16 UTC, vikasganiga05 approved these changes
LGTM :+1:

2022-05-06 00:52 UTC, Panquesito7 requested changes

2022-05-06 00:52 UTC, Panquesito7 commented on public/data/dunyanong.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-06 11:19 UTC, krshkodes approved these changes
Looks awesome! Endline to be handled by bot!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-05-07 04:02 UTC, Pradumnasaraf approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-05-07 10:23 UTC, merged