added my profile
EddieHubCommunity/LinkFree pull request #1276
Opened 2022-05-07 09:28 UTC by Santosh1176

Added my profile to /public/data

2022-05-07 10:16 UTC, emmalearnscode approved these changes
The icons that you've listed in your milestones are not currently available in the project so they will default to a globe for the time being. Please feel free to raise separate issues for the icons you wish to be added and as soon as they are added your profile will show the correct icons.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-07 11:10 UTC, Santosh1176 commented
👍

2022-05-08 00:13 UTC, Panquesito7 requested changes

2022-05-08 00:13 UTC, Panquesito7 commented on public/data/santoshdts.json
> +
```suggestion
}
```

2022-05-08 02:38 UTC, kabir0x23 approved these changes
Looks Good 🧨

2022-05-09 02:16 UTC, kumarsonsoff3 approved these changes
Looks Good to me! 🚀

2022-05-09 16:53 UTC, Santosh1176 commented
Hi, do I need to change the milestone icons to default available ones?

2022-05-09 18:17 UTC, emmalearnscode commented
> Hi, do I need to change the milestone icons to default available ones?

No, there is an automatic default built in. However, you should open an issue asking for them to be added. Once they’re added they’ll automatically show correctly

2022-05-09 20:53 UTC, Santosh1176 commented
That's great !
👍

2022-05-09 21:48 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-05-10 10:36 UTC, Pradumnasaraf approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-10 11:43 UTC, merged