add jhohannes profile
EddieHubCommunity/LinkFree pull request #1283
Opened 2022-05-09 02:02 UTC by JhohannesK

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-09 02:07 UTC, Panquesito7 requested changes
Please revert the changes in the `package-lock.json` file. Let us know if you need any help. :)

2022-05-09 02:15 UTC, JhohannesK commented
> Please revert the changes in the `package-lock.json` file. Let us know if you need any help. :)

how do I that?

2022-05-09 19:06 UTC, ahmed82 approved these changes
Looks Ok.

2022-05-09 19:10 UTC, ahmed82 requested changes
You should make the change < adding new file only that contain your name>, not the 'package-lock.json'

2022-05-09 19:13 UTC, ahmed82 commented on package-lock.json
>        "license": "MIT",
The change is the version that you need to revert.

2022-05-09 19:53 UTC, JhohannesK commented
I have reverted the file please

2022-05-09 21:47 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-05-09 22:56 UTC, Panquesito7 approved these changes

2022-05-10 06:06 UTC, kumarsonsoff3 approved these changes

2022-05-10 10:35 UTC, Pradumnasaraf approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-05-10 11:45 UTC, merged