added profile
EddieHubCommunity/LinkFree pull request #1293
Opened 2022-05-13 14:46 UTC by sachinparihar

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-13 14:50 UTC, Panquesito7 requested changes

2022-05-13 14:50 UTC, Panquesito7 commented on public/data/sachinparihar.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-13 15:44 UTC, kabir0x23 approved these changes
Looks good 🌠

👇 If you like to correct this (Optional), + blank line at the end

2022-05-13 15:44 UTC, kabir0x23 commented on public/data/sachinparihar.json
> +    "bio": "I am Sachin Parihar.Currently, I am pursuing my graduation in Computer Science from GJU College.I am a Open Source Enthusiast! & Also, interested in DevOps!",
```suggestion
    "bio": "I am Sachin Parihar.Currently, I am pursuing my graduation in Computer Science from GJU College. I am an Open Source Enthusiast! & Also, interested in DevOps!",
```

2022-05-13 16:23 UTC, sachinparihar commented on public/data/sachinparihar.json
> +    "bio": "I am Sachin Parihar.Currently, I am pursuing my graduation in Computer Science from GJU College.I am a Open Source Enthusiast! & Also, interested in DevOps!",
> Looks good 🌠
> 
> 👇 If you like to correct this (Optional), + blank line at the end

done!

2022-05-14 01:41 UTC, kumarsonsoff3 approved these changes
looks Good to me 👍 Thanks for your contribution! 🚀

2022-05-14 03:10 UTC, Pradumnasaraf approved these changes
Looks good to me!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-15 04:03 UTC, Panquesito7 approved these changes

2022-05-15 04:05 UTC, merged