remove profile images on homepage
EddieHubCommunity/LinkFree pull request #1306
Opened 2022-05-20 03:08 UTC by ekand

As mentioned in issue #1264, the front page currently loads
avatars from github, which can hit rate limits on the api.
This commit removes the images on from the front page

mentions #1264 

## Changes proposed

remove images from the front page

[x] - Correct; marked as done
[X] - Correct; marked as done

[ ] - Not correct; marked as **not** done
-->

## Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screen Shot 2022-05-19 at 10 06 11 PM](https://user-images.githubusercontent.com/52926724/169442497-1fb21387-31a5-4a39-bc88-279a311dd128.png)

## Note to reviewers

2022-05-20 07:19 UTC, eddiejaoude commented
On hover it doesn't look quite right, see screenshot...

<img width="495" alt="Screenshot 2022-05-20 at 08 15 57" src="https://user-images.githubusercontent.com/624760/169474128-ffa86352-f953-4603-9aec-bd670a899651.png">

I think `Avatar` is the main component being used and expects an image https://www.primefaces.org/primereact/avatar/

Maybe look at switching to `Chip` without an image https://www.primefaces.org/primereact/chip/

2022-05-20 07:19 UTC, eddiejaoude requested changes
Left a comment - any questions let us know

2022-05-20 14:34 UTC, ekand commented
Thanks for the feedback. I see the issue, and I will try out the 'Chip' option.

2022-05-21 00:39 UTC, ekand commented
Here it is with Chip instead of Avatar:
![Screen Shot 2022-05-20 at 7 38 30 PM](https://user-images.githubusercontent.com/52926724/169627397-bd568a86-5f78-4860-bcaf-0b8318edda6e.png)

2022-05-21 00:41 UTC, ekand commented
Oh wait, I ended up putting a Chip inside of a Chip. I'm not sure that's quite right.

2022-05-21 00:56 UTC, ekand commented
Well, that was chaotic. I think I'll stop at this point for now. It has chip with in chip, and hover looks right to me, though I don't have a screen shot of the mouse hover.

![Screen Shot 2022-05-20 at 7 55 10 PM](https://user-images.githubusercontent.com/52926724/169628178-4cc374c2-ece7-40be-be52-8da025ab9f77.png)

Would you like me to squash my commits and force push, or leave the commits as is?

2022-05-21 17:54 UTC, emmalearnscode requested changes

2022-05-21 17:54 UTC, emmalearnscode commented on src/Components/Home/Users.js
> +                    <Chip
Great work so far. I think we can go a little further in order to simplify this as much as possible and get rid of any unused code so would you be able to update the template to just this:

`template={
                  <span className="text-overflow-ellipsis white-space-nowrap overflow-hidden">{user.name}</span>
                }`

Also, it's fine to delete the unused imports Avatar, and also Badge and Utils once the template is updated as that keeps the file as clean as possible and reduces tech debt. Let us know if you have any questions.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-05-21 17:54 UTC, emmalearnscode commented on src/Components/Home/Users.js
> +// import { Avatar } from 'primereact/avatar'
Please delete unused imports 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-05-21 19:13 UTC, ekand commented
@emmalearnscode Thanks for the feedback. I'll make those changes now.

2022-05-21 19:29 UTC, ekand commented
Here it is with the simplified template, as @emmalearnscode suggested.

Screen shot:
![Screen Shot 2022-05-21 at 2 17 09 PM](https://user-images.githubusercontent.com/52926724/169666507-d67accee-4941-45b5-ae62-5d0dab6399a0.png)

2022-05-21 19:32 UTC, emmalearnscode approved these changes
Looks like it works well! Thank you for your help!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-25 09:58 UTC, eddiejaoude approved these changes
Looks great! Awesome collaboration 🔥

2022-05-25 09:59 UTC, merged