Add Shivendu-Kumar.json
EddieHubCommunity/LinkFree pull request #1309
Opened 2022-05-21 04:41 UTC by Shivendu-Kumar

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-21 08:05 UTC, kumarsonsoff3 requested changes

2022-05-21 08:05 UTC, kumarsonsoff3 commented on public/data/Shivendu-Kumar.json
> +
Rest looks good to me! 

```suggestion
```

2022-05-21 08:05 UTC, kumarsonsoff3 commented on public/data/Shivendu-Kumar.json
> +  }
```suggestion
}
```

2022-05-21 08:26 UTC, emmalearnscode approved these changes

2022-05-21 11:48 UTC, kumarsonsoff3 approved these changes

2022-05-22 01:00 UTC, Panquesito7 requested changes

2022-05-22 01:00 UTC, Panquesito7 commented on public/data/Shivendu-Kumar.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-05-26 04:29 UTC, Shivendu-Kumar commented
Please let me know if there is any problem with merging my PR.

2022-05-26 05:30 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-05-26 05:49 UTC, Shivendu-Kumar commented
> LGTM 🚀 Thank you for your contribution! 😄👍
Thank You for the approval 😊

2022-05-26 08:31 UTC, merged