Added personal linkfree
EddieHubCommunity/LinkFree pull request #1319
Opened 2022-05-24 10:26 UTC by hasnainmakada-99

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-05-24 15:30 UTC, vikasganiga05 requested changes
There is no icon named `portfolio`. Change it to `globe`.

2022-05-24 15:41 UTC, hasnainmakada-99 commented
Ok

2022-05-25 04:18 UTC, hasnainmakada-99 commented on public/data/hasnainmakada-99.json
> +      "icon": "portfolio"
The changes have been made

2022-05-25 04:22 UTC, Panquesito7 approved these changes

2022-05-25 04:22 UTC, kumarsonsoff3 approved these changes
LGTM 👍  Thanks for your contribution! 🚀

2022-05-25 09:16 UTC, emmalearnscode approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-25 09:17 UTC, merged