Add profile info
EddieHubCommunity/LinkFree pull request #1383
Opened 2022-06-13 10:14 UTC by ianskie26

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1383"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-06-13 15:24 UTC, Panquesito7 requested changes

2022-06-13 15:24 UTC, Panquesito7 commented on public/data/ianskie26.json
> +    },
Please remove this comma. It should fix the CI errors. 🙂
```suggestion
    }
```

2022-06-14 03:35 UTC, kumarsonsoff3 approved these changes

2022-06-14 20:21 UTC, Panquesito7 approved these changes

2022-06-14 20:24 UTC, merged

2022-07-04 14:57 UTC, vincekashaka commented
__
 
  Summary: 👌 This code looks good