I have updated CONTRIBUTING.md
EddieHubCommunity/LinkFree pull request #1387
Opened 2022-06-13 18:55 UTC by PritamSarbajna

## Fixes Issue
Closes #1386

## Changes proposed

-  It is now more clear that why we use `git add public` as I have also mentioned that we can also use specific name of the folder we just changed
-  Added commit point separately 
-  made `Instead, stage your changes for each file/folder` line as note and also added `By using public path it means it will add all files and folders under that folder, it is better to be specific` to it

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
### *It is looking like this after updating*

![Screenshot (115)](https://user-images.githubusercontent.com/90236635/173423330-c89b54d3-07dd-48ce-8d46-1294533830f1.png)

## Note to reviewers

2022-06-15 20:11 UTC, emmalearnscode requested changes
Just a couple of small changes, then this will be good to go.

2022-06-15 20:11 UTC, emmalearnscode commented on CONTRIBUTING.md
>  ---
Removing the first two lines of the document messes up the formatting of the first section.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-16 01:33 UTC, PritamSarbajna commented on CONTRIBUTING.md
> +> Instead, stage your changes for each file/folder
Please let me know if this is better
![Screenshot (122)](https://user-images.githubusercontent.com/90236635/173972390-00f215a8-daa1-4c95-9dfc-102a527edd3d.png)

2022-06-19 18:07 UTC, emmalearnscode commented on CONTRIBUTING.md
> +> Instead, stage your changes for each file/folder
Yes, this looks better.

2022-06-19 19:05 UTC, PritamSarbajna commented on CONTRIBUTING.md
> +> Instead, stage your changes for each file/folder
can you merge it

2022-07-12 18:07 UTC, emmalearnscode approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-12 18:08 UTC, merged