Add Atharv-777
EddieHubCommunity/LinkFree pull request #1388
Opened 2022-06-14 05:51 UTC by Atharv-777

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-06-14 20:19 UTC, Panquesito7 requested changes
Hey there! Please revert the changes in the `package-lock.json` and `package.json` files. Let us know if you need any help. Thanks. :)

2022-06-15 06:55 UTC, Pradumnasaraf approved these changes
Thank you for the changes. Looks good to merge 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

2022-06-15 16:12 UTC, Pradumnasaraf commented on public/data/Atharv-777.json
> +
Hey! David. Don't the action the will fix that?

2022-06-15 20:01 UTC, emmalearnscode approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-06-17 08:29 UTC, Pradumnasaraf approved these changes
Looks good to merge

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-06-17 16:35 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-06-17 16:36 UTC, merged