Added Abhishikth.json file
EddieHubCommunity/LinkFree pull request #1420
Opened 2022-06-30 11:48 UTC by Abhishikth3330

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-06-30 16:14 UTC, Panquesito7 approved these changes
Thank you for contributing!


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-07-01 12:56 UTC, Abhishikth3330 commented
> Thank you for contributing!
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 👌 This code looks good  |  **Tags:** Maintainable

When will this profile be seen on LinkFree Site ?

2022-07-01 12:59 UTC, eddiejaoude commented on public/data/Abhishikth.json
> +}
Please add ending blank line as suggested by github

2022-07-01 13:26 UTC, Abhishikth3330 commented
> 

Eddie You are Amazinggggg !
My journey with Git & Github has started recently and you are the Motivation.
Thanks 😄

2022-07-01 13:27 UTC, eddiejaoude commented on public/data/Abhishikth.json
> +            "url": "",
If you do not have a linkedin URL, you can remove this object

2022-07-01 13:27 UTC, eddiejaoude commented on public/data/Abhishikth.json
> +            "url": "",
If you do not have a Twitter URL, you can remove this object

2022-07-01 13:27 UTC, eddiejaoude requested changes
Missing URLs for Twitter and LinkedIn socials

2022-07-01 13:50 UTC, eddiejaoude approved these changes
Looks good 👍

2022-07-01 15:10 UTC, merged