added profile
EddieHubCommunity/LinkFree pull request #1423
Opened 2022-06-30 16:18 UTC by ayushlohmod

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-06-30 16:21 UTC, Panquesito7 requested changes
Hey there! Thanks for submitting a PR. Please revert the changes in the `package-lock.json` file.
Let us know if you need any help with that! Thanks. 🙂


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-06-30 17:12 UTC, ayushlohmod reviewed
reverted the changes please review it!

2022-06-30 18:36 UTC, Panquesito7 commented
> reverted the changes please review it!

Hmm, I can still see the same `package-lock.json` changes in your PR. 👀

2022-07-01 19:16 UTC, Panquesito7 commented on public/data/ayushlohmod.json
> +      "title": "Started Full Stack development ",
There's an extra space here. Might want to remove it.
```suggestion
      "title": "Started Full Stack development",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-07-02 16:58 UTC, ayushlohmod commented
Hey! @Panquesito7  can you tell me why this package-lock.json keep modified by itself

2022-07-02 18:50 UTC, emmalearnscode commented
> Hey! @Panquesito7 can you tell me why this package-lock.json keep modified by itself

Sometimes it will automatically update the release when you do npm install. The important thing is to be careful when committing your code not to use the command `git add .` as then you accidentally commit the changes made to the file. Only ever add and commit the files you want to by using more granular commands like 'git add public' to only add changes made within the public folder (and as outlined in the instructions on the contributing page).

You should be able to fix the changes to package-lock by copying the file from the Eddiehub repo and pasting it into your fork. When you do that and commit the changes the files should match and that should remove it from the pull requesst.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-03 16:23 UTC, ayushlohmod commented
Thanks @

> > Hey! @Panquesito7 can you tell me why this package-lock.json keep modified by itself
> 
> Sometimes it will automatically update the release when you do npm install. The important thing is to be careful when committing your code not to use the command `git add .` as then you accidentally commit the changes made to the file. Only ever add and commit the files you want to by using more granular commands like 'git add public' to only add changes made within the public folder (and as outlined in the instructions on the contributing page).
> 
> You should be able to fix the changes to package-lock by copying the file from the Eddiehub repo and pasting it into your fork. When you do that and commit the changes the files should match and that should remove it from the pull requesst.
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

2022-07-03 16:23 UTC, closed without merging

2022-07-03 16:25 UTC, ayushlohmod commented
Thanks @emmalearnscode for the help i do git add . all this time