feat: nav bar added
EddieHubCommunity/LinkFree pull request #143
Opened 2021-09-13 17:37 UTC by Soham041201

Added a basic Nav-bar with a basic links and dummy links

2021-09-13 17:47 UTC, nhcarrigan requested changes

2021-09-13 17:47 UTC, nhcarrigan commented on src/Components/NavBar.js
> +      <h1>Blog website</h1>
```suggestion
      <h1>LinkFree</h1>
```

2021-09-13 17:47 UTC, nhcarrigan commented on src/index.css
> +/* =========Navbar Start==========*/
```suggestion
/* =========Navbar End==========*/
```

2021-09-13 17:47 UTC, nhcarrigan commented
Also please remove your changes to the `package.json` and `package-lock.json`

2021-09-13 18:15 UTC, Soham041201 commented
Made the required changes

2021-09-13 18:20 UTC, Soham041201 reviewed
Made Changes

2021-09-14 14:24 UTC, qwe123coder requested changes
hey, nice work :rocket: Thanks for your contribution
*  the files are Conflicted :( 
*  I suggest read [Resolving a merge conflictt](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts)

2021-09-15 03:19 UTC, Soham041201 commented
I have resolved the conflict. There was just a small conflict of lines of code. Some one had written code on the same line on which I had written and also this code was not related to mine. Please review once

2021-09-16 04:03 UTC, rohan-kulkarni-25 requested changes
Please try to add CSS from [Prime React ](https://www.primefaces.org/primereact/) as we are using it for whole project that will easier. 
If CSS is custom them keep it same else try to find some prime react alternative which will reduce css code

2021-09-16 04:07 UTC, Soham041201 commented
I did try to find a prime react component to add the Navbar. But I was not able to find one. That's why I did it through CSS.

2021-09-16 04:13 UTC, rohan-kulkarni-25 commented
> Okay Cool! Will make the changes

If not found such classes through prime react then its ok we can take it as plain css

2021-09-16 04:19 UTC, krishdevdb requested changes
This [component](https://www.primefaces.org/primereact/showcase/#/menubar) shall be used rather than custom css

2021-09-16 04:21 UTC, krishdevdb reviewed
Its okay for this pr, but in the future consider making different pull requests for different changes 👍🏻

2021-09-16 04:25 UTC, Soham041201 commented
> Its okay for this pr, but in the future consider making different pull requests for different changes 👍🏻
Yess! Just saw this component trying to inlude it. But unabe to apply styling. Should I just add the Nav-bar here and the styling can be done in other PR?

2021-09-16 07:27 UTC, krishdevdb approved these changes

2021-09-16 07:27 UTC, krishdevdb commented
Seems good to me, let's wait for @nhcarrigan to review once?

2021-09-16 07:30 UTC, Soham041201 commented
> Seems good to me, let's wait for @nhcarrigan to review once?

Yess !

2021-09-18 15:31 UTC, nhcarrigan commented
This will require a rebase :)

2021-09-19 11:00 UTC, Soham041201 commented
> This will require a rebase :)

Performed rebase :)

2021-09-19 14:41 UTC, krishdevdb commented
What happened? So many commits?

2021-09-19 14:57 UTC, CodingSpecies commented
I am not sure but I would close this pr and create a fresh one with one single commit will all the changes thanks

2021-09-19 14:59 UTC, Soham041201 commented
> I am not sure but I would close this pr and create a fresh one with one single commit will all the changes thanks

Yess Will do the same...

2021-09-19 14:59 UTC, closed without merging