added ayushlohmod.json
EddieHubCommunity/LinkFree pull request #1436
Opened 2022-07-03 17:22 UTC by ayushlohmod

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-07-03 17:53 UTC, Panquesito7 requested changes

2022-07-03 17:53 UTC, Panquesito7 commented on public/data/ayushlohmod.json
> +
There's a missing `{` here.
```suggestion
{
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-04 16:30 UTC, ayushlohmod reviewed
added "{" in file please review it!

2022-07-04 18:34 UTC, ayushlohmod reviewed
removed extra space

2022-07-04 18:45 UTC, Panquesito7 approved these changes
Thanks for contributing! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-07-05 07:56 UTC, kumarsonsoff3 requested changes
All your links are broken. You should copy and paste the correct links instead of typing them manually to avoid unnecessary typos. 

Make sure you update all these links of _**Twitter, LinkedIn, Github page**_ with the correct ones as suggested to get your PR approved. 🛠
<hr/>

⚠ **_Summary:_** This code needs a Fix 🛠

2022-07-05 07:56 UTC, kumarsonsoff3 commented on public/data/ayushlohmod.json
> +      "url": "https://twitter.com/ayushlohmod_",
There is a **broken link**.  Please update it to the correct one! 
![image](https://user-images.githubusercontent.com/88786642/177276279-3dd0a577-ece6-4fe0-b756-af9e82495cd9.png)

2022-07-05 07:56 UTC, kumarsonsoff3 commented on public/data/ayushlohmod.json
> +      "url": "https://linkedin.com/in/ayushlohmod",
Your LinkedIn profile link doesn't bring any results. _**Please update it with the correct one!**_

![image](https://user-images.githubusercontent.com/88786642/177276631-1a85692c-1a8f-4fcf-9f57-491feb92f307.png)

2022-07-05 07:56 UTC, kumarsonsoff3 commented on public/data/ayushlohmod.json
> +      "url": "https://ayushlohmod.github.com/oscar"
There is another _**broken link**_. Please update it with the correct one! 

![image](https://user-images.githubusercontent.com/88786642/177277103-02b65114-1364-4a38-bf04-6761e2e96df3.png)

2022-07-06 16:16 UTC, ayushlohmod reviewed
Fixed broken links

2022-07-07 02:15 UTC, kumarsonsoff3 approved these changes
LGTM 👍  Good to Goo! 🚀

2022-07-08 20:06 UTC, emmalearnscode approved these changes

2022-07-08 20:07 UTC, merged