added JoBaHP user
EddieHubCommunity/LinkFree pull request #1490
Opened 2022-07-13 16:33 UTC by JoBaHP

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-07-13 18:18 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-07-13 18:52 UTC, kumarsonsoff3 requested changes

2022-07-13 18:52 UTC, kumarsonsoff3 commented on public/data/JoBaHP.json
> +      "url": "http://build-up.us",
Minor fix! Your website is using a secure protocol. 🛠

```suggestion
      "url": "https://build-up.us",
```

2022-07-13 18:52 UTC, kumarsonsoff3 commented on public/data/JoBaHP.json
> +      "url": "https://twitter.com/https://twitter.com/joccoo",
Broken link, seems like you have pasted the original link after typing the half link manually.

Small fix! 🛠

```suggestion
      "url": "https://twitter.com/joccoo",
```

2022-07-14 09:55 UTC, kumarsonsoff3 approved these changes
Looks Good! 👍  Thanks for contributing! 🚀

2022-07-14 20:05 UTC, merged