added Niravprajapati1
EddieHubCommunity/LinkFree pull request #1503
Opened 2022-07-16 07:34 UTC by Niravprajapati1

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-07-16 11:26 UTC, kumarsonsoff3 requested changes
Minor Fixes Required! 🛠

2022-07-16 11:26 UTC, kumarsonsoff3 commented on public/data/Niravprajapati1.json
> +      "icon": "global",
You might wanted to add `globe` here!? 🛠

```suggestion
      "icon": "globe",
```

2022-07-16 11:26 UTC, kumarsonsoff3 commented on public/data/Niravprajapati1.json
> +      "url": "https://coursera.org/verif y/TFQD5ZKM7MEZ"
**There is a broken link!** Please remove the space from the link! 🛠

```suggestion
      "url": "https://coursera.org/verify/TFQD5ZKM7MEZ"
```

2022-07-16 11:48 UTC, Niravprajapati1 commented
I changed global to globe and updated broken link

2022-07-16 20:04 UTC, Vyvy-vi approved these changes
LGTM! Thanks for adding your profile to LinkFree!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-17 00:45 UTC, Niravprajapati1 commented
Thanks 🙌

2022-07-17 04:42 UTC, kumarsonsoff3 approved these changes
Thanks for the changes! LGTM 👍

2022-07-17 05:43 UTC, Panquesito7 approved these changes
Thanks for contributing!

2022-07-17 05:44 UTC, merged