made my profile for Linkfree
EddieHubCommunity/LinkFree pull request #1509
Opened 2022-07-19 05:55 UTC by itsomsarraf

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/1509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-07-19 09:17 UTC, kumarsonsoff3 requested changes

2022-07-19 09:17 UTC, kumarsonsoff3 commented on public/data/itsomsarraf_.json
> +        "url": "https://www.linkedin.com/in/itsomsarraf/?_l=en_US",
```suggestion
        "url": "https://www.linkedin.com/in/itsomsarraf/",
```

2022-07-19 16:17 UTC, Panquesito7 commented on public/data/itsomsarraf_.json
> +        "name": "Connect with me on Linkedin",
What do you think about capitalizing `i` here?
```suggestion
        "name": "Connect with me on LinkedIn",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

2022-07-19 17:02 UTC, Panquesito7 approved these changes
Thanks for contributing!


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-07-19 23:10 UTC, jaynarayan-vaishnav approved these changes
LGTM🚀

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-20 03:31 UTC, kumarsonsoff3 approved these changes

2022-07-20 03:34 UTC, merged