added my profile
EddieHubCommunity/LinkFree pull request #1512
Opened 2022-07-20 10:59 UTC by amanchauhann

2022-07-20 11:30 UTC, kumarsonsoff3 commented on public/data/amanchauhann.json
> +      "description": "trying to break into tech",
What do you think about capitalizing these! 
```suggestion
      "description": "Trying to break into Tech",
```

2022-07-20 11:33 UTC, kumarsonsoff3 requested changes
Unfortunately you have committed into `package-lock.json`. 

Please Revert the changes from the `package-lock.json` file. Let us know if you need any help!

2022-07-24 20:44 UTC, EmmaDawsonDev requested changes
Please revert changes to package-lock file then this should be ready to merge.

2022-07-31 19:52 UTC, EmmaDawsonDev commented
Do you need any help with this @amanchauhann ?

2022-08-01 18:14 UTC, Kartik2220 approved these changes
code looks good 👍.

2022-08-28 17:32 UTC, kumarsonsoff3 commented
It's more than a month @amanchauhann, since you responded. So we are closing this PR! 
Feel free to **re-poen** this and make changes or create a new PR containing only your file! Let us know if your need any help with this! 🙂

2022-08-28 17:32 UTC, closed without merging