Creating my Profile in Bonganibendi.json
EddieHubCommunity/LinkFree pull request #1515
Opened 2022-07-21 11:52 UTC by Bonganibendi

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot 2022-07-21 at 13 47 19](https://user-images.githubusercontent.com/58882596/180206511-e3349728-59eb-4f08-b940-dcd71a02a1eb.png)

## Note to reviewers

I created a new fork for this project.

I fixed the errors from my previous pull request: #1514.

2022-07-21 19:38 UTC, SohamRatnaparkhi commented
Looks good to me! Thank you for contributing.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-22 04:35 UTC, Panquesito7 requested changes

2022-07-22 04:35 UTC, Panquesito7 commented on public/data/Bonganibendi.json
> +  "avatar": "https://avatars.githubusercontent.com/u/58882596?s=400&u=85fa39e4c5bf28dcce96a22eae70f1a8e45565f2&v=4",
It is best to use it this way, to have the link shorter and work better.
```suggestion
  "avatar": "https://github.com/Bonganibendi.png",
```

2022-07-22 19:43 UTC, kumarsonsoff3 approved these changes
LGTM 👍 
Thanks for contributing! 🚀

2022-07-23 03:01 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

2022-07-23 03:02 UTC, merged