Add my data to public/data
EddieHubCommunity/LinkFree pull request #152
Opened 2021-09-13 20:39 UTC by Pulkit007

Fixes #

## Proposed Changes

  -
  -
  -

## Screenshots

2021-09-14 01:16 UTC, FayasNoushad approved these changes

2021-09-14 04:06 UTC, Recognizeyourself approved these changes

2021-09-14 07:09 UTC, schmelto approved these changes

2021-09-14 07:10 UTC, schmelto commented
could you resolve the merge conflict? If you need any help please let us know

2021-09-15 08:01 UTC, schmelto requested changes

2021-09-15 08:01 UTC, schmelto commented on public/data/_list.json
> +  { "username": "Pulkit007", "avatar": "https://github.com/Pulkit007.png" }
This one is not necessary anymore and will be updated automatically

2021-09-27 21:09 UTC, eddiejaoude commented
I will merge into a temporary branch and fix

2021-09-27 21:11 UTC, eddiejaoude commented
Unfortunately it won't let me do it. So I have created a patch and I will add it manually to the `main` branch but I have to close this PR

2021-09-27 21:11 UTC, closed without merging

2021-09-27 21:12 UTC, eddiejaoude commented
Done. Here is the commit https://github.com/EddieHubCommunity/LinkFree/commit/35105ccd06dd77dd459f0514301cacff141f0b46