fix open links in deferent tabs
EddieHubCommunity/LinkFree pull request #153
Opened 2021-09-13 20:39 UTC by mohammad4kh

Fix open links in different tabs
## Proposed Changes

  - remove goToLinkHandle function
  - add window.open to Link onChange directly
 
## Screenshots
### before:
![link_open_1](https://user-images.githubusercontent.com/6501582/133152937-593d97be-e6da-44dc-8064-5ccea6c02eb7.gif)

### after:
![link_open_2](https://user-images.githubusercontent.com/6501582/133153100-d157d091-5082-4051-9312-b0a866781952.gif)

2021-09-14 03:22 UTC, abhay0908 commented
add window.open to Link onChange directly

2021-09-14 03:40 UTC, Recognizeyourself approved these changes

2021-09-14 03:49 UTC, Recognizeyourself requested changes
It's not able to fix links, I tried on my repo.

2021-09-16 03:54 UTC, rohan-kulkarni-25 requested changes

2021-09-16 03:54 UTC, rohan-kulkarni-25 commented on src/Components/Links.js
> +              onClick={() => window.open(link.url)}
I think you need to do this way 
`onClick={()=> window.open(link.url,"_blank")}`

2021-10-24 02:35 UTC, krishguptadev commented
## Merge Conflict

Thank you for your contribution. Your pull request currently has conflicting changes with our `main` branch. In order to review this pull request, we will need those conflicts to be resolved.

We recommend doing this with the `git rebase` command. If you are unsure of how to fix this, let us know and we would be happy to assist you.

2021-11-15 18:26 UTC, emmalearnscode commented
@mohammad4kh are you still working on this? Let us know if you need help resolving the merge conflicts.

2021-11-27 11:00 UTC, CodingSpecies commented
@mohammad4kh is there any updates on this? Please see the comments and reviews above.
Thank you.

2021-11-27 11:15 UTC, krishguptadev commented
Hey there, do you need any help? 🙂

2021-11-28 04:48 UTC, Panquesito7 requested changes
Please see the comments above.

2021-12-06 15:08 UTC, emmalearnscode commented
Thanks for your contribution. I'll close this PR for now as there are merge conflicts that need fixing and it has not been worked on for a long time. Feel free to open it up again if you get the time to fix the conflicts and work on it again and of course, you're welcome back to tackle more issues in the future :-)

2021-12-06 15:08 UTC, closed without merging