added my profile `@theabhayprajapati`
EddieHubCommunity/LinkFree pull request #1540
Opened 2022-07-30 12:44 UTC by theabhayprajapati

2022-07-30 12:50 UTC, theabhayprajapati reviewed
added my profile

2022-07-31 03:06 UTC, kumarsonsoff3 requested changes
Few Fixes required! 🧰 

- Change your filename to `theabhayprajapati.json`
- Update the link as suggested
- Remove the empty space from the end! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-07-31 03:06 UTC, kumarsonsoff3 commented on public/data/abhayprajapati.json
> +        "url": "http://abhayprajapati.me",
Your link is using a secure protocol! 

```suggestion
        "url": "https://abhayprajapati.me",

```

2022-07-31 03:25 UTC, theabhayprajapati reviewed
checked the changes

2022-07-31 05:29 UTC, kumarsonsoff3 requested changes
**Still you need to -**

- Change your filename to from `abhayprajapati.json` to `theabhayprajapati.json`
- Edit the description of your PR. ( Description could not be empty )

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-07-31 15:18 UTC, theabhayprajapati reviewed
updated the file name to usename

2022-07-31 19:55 UTC, EmmaDawsonDev approved these changes

2022-08-01 03:16 UTC, kumarsonsoff3 approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

2022-08-01 03:18 UTC, merged