Added aaryachopkar.json
EddieHubCommunity/LinkFree pull request #1549
Opened 2022-08-01 05:31 UTC by accodes21

## My First Contribution to EddieHub Community

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot (260)](https://user-images.githubusercontent.com/101868279/182078406-5b328a48-2e23-4671-85a1-1ba9b42435a5.png)

## Note to reviewers

Thank you in advance!

2022-08-01 05:39 UTC, Kartik2220 approved these changes
code looks good

2022-08-01 20:16 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-02 04:11 UTC, kumarsonsoff3 requested changes
- Update your filename to your `username.json`, which should be `accodes21.json`
- Correct the small typo below! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-02 04:11 UTC, kumarsonsoff3 commented on public/data/aaryachopkar.json
> +        "name": "Connect with me on LikedIN",
```suggestion
        "name": "Connect with me on LinkedIn",
```

2022-08-02 06:18 UTC, accodes21 commented
All mentioned Changed were made.
Thank you!

2022-08-02 07:40 UTC, kumarsonsoff3 requested changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-02 07:40 UTC, kumarsonsoff3 commented on public/data/accodes21.json
> +        "name": "Connect with me on LikedIn",
Same typo again! 

```suggestion
        "name": "Connect with me on LinkedIn",
```

2022-08-02 08:38 UTC, accodes21 commented
Sorry for the typo
Thanks for your patience and help!

2022-08-02 09:47 UTC, kumarsonsoff3 approved these changes
Good to goo! 🚀

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

2022-08-02 09:47 UTC, merged