create[data]: add vedanshi.json
EddieHubCommunity/LinkFree pull request #1550
Opened 2022-08-01 06:04 UTC by Tokio3012

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-01 15:23 UTC, Kartik2220 approved these changes
nice code looks good

2022-08-01 18:12 UTC, Tokio3012 commented
@Kartik2220 😁 thanks!

2022-08-01 20:27 UTC, Panquesito7 requested changes

2022-08-01 20:27 UTC, Panquesito7 commented on public/data/vedanshi.json
> +    },
There's a trailing comma in here.
```suggestion
    }
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not secure

2022-08-02 03:50 UTC, kumarsonsoff3 requested changes
Few Fixes Required! 

- Update the filename with your `username.json` which should be `Tokio3012.json`
- Update your discord link with the correct one! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-02 03:50 UTC, kumarsonsoff3 commented on public/data/vedanshi.json
> +      "url": "https://discordapp.com/tokio/7761/",
There is a broken link, please update it with the correct one! 🛠

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-02 04:16 UTC, kumarsonsoff3 approved these changes
Thanks for contributing! 🚀 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-02 05:41 UTC, Panquesito7 approved these changes
Thanks for contributing! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-02 05:42 UTC, merged