Twitters-color
EddieHubCommunity/LinkFree pull request #1551
Opened 2022-08-01 11:57 UTC by KarlGusta

## Fixes Issue

## Changes proposed
Changing the twitter color to the original one.

Also, just practicing PR here TBH. 

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-02 03:40 UTC, kumarsonsoff3 requested changes
Your PR should only contain the file in which you are making changes! So revert the changes from the `GetIcons.js`. 
As per my knowledge we've already merged your another PR sorting the icons! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-02 03:40 UTC, kumarsonsoff3 commented on src/config/links.json
> +    "twitter": "#1D9BF0",
The official color for Twitter is `rgb(29, 155, 240)` which is `#1d9bf0`. It should be 👇 
```suggestion
    "twitter": "#1d9bf0",
```

2022-08-07 03:40 UTC, kumarsonsoff3 commented
Hey @KarlGusta, I see your [fork](https://github.com/KarlGusta/LinkFree/tree/twitters-color) is behind the main branch, so this PR shows 2 files changed! 

Please Sync you fork with the linkfree main! let us know if you need any help with this!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-03 10:09 UTC, SaptarshiSarkar12 commented
@KarlGusta Please resolve the branch conflicts.

2022-09-05 12:16 UTC, KarlGusta commented
Thank you for your patience @kumarsonsoff3 and @SaptarshiSarkar12 . I'm only seeing this now. It appears I wasn't getting any notification on this until today. Let me do a sync then do another PR. I'll close this for now.

2022-09-05 12:16 UTC, closed without merging