Abhishinde24
EddieHubCommunity/LinkFree pull request #1555
Opened 2022-08-02 07:09 UTC by abhishinde24

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-02 07:09 UTC, abhishinde24 commented
adding profile

2022-08-02 15:16 UTC, Kartik2220 requested changes
kindly add your avatar....

2022-08-03 04:15 UTC, aparna2071 requested changes

2022-08-03 04:15 UTC, aparna2071 commented on public/data/abhishinde24.json
> +  }
Kindly add a new line at the end(line 29) so that there is no Prettier issue.

2022-08-03 13:14 UTC, kumarsonsoff3 requested changes
**Will be Good to go after these changes!**

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-03 13:14 UTC, kumarsonsoff3 commented on public/data/abhishinde24.json
> +        "url": "#"
Kindly add your URL here, If you don't have a URL you can simply remove the line no `25`

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-03 13:52 UTC, kumarsonsoff3 approved these changes
Looks Good to me! 🚀

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

2022-08-03 13:53 UTC, merged