chore: add Trust Onye
EddieHubCommunity/LinkFree pull request #1566
Opened 2022-08-03 22:25 UTC by code-with-onye

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-08-03 23:17 UTC, Panquesito7 requested changes
Hey there! Please revert the changes in the `package-lock.json` file.
Let us know if you need any help with that! 🙂


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Not maintainable

2022-08-04 00:38 UTC, code-with-onye commented
Yes, please I need help

2022-08-04 03:08 UTC, kumarsonsoff3 requested changes
Please make the following changes **++** Rename your file name to your `username.json` which should be `code-with-onye.json`.

I've specified the changes needed, Let us know if you need any other help with these! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-04 03:08 UTC, kumarsonsoff3 commented on src/Components/Milestones.js
> +      style={{ borderRadius: '20px' }}
Another PR to add the border radius is already underReview! So Revert the changes from `Milestone.js`
```suggestion
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-08-04 03:08 UTC, kumarsonsoff3 commented on src/Components/Milestones.js
> +      className="my-5 md:mx-5 shadow-8  "
```suggestion
      className="my-5 md:mx-5 shadow-8"
```

2022-08-04 16:26 UTC, Pradumnasaraf requested changes
Hey, please revert the `package-lock.json` changes. If you need help, do let's know

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-08-06 03:54 UTC, kumarsonsoff3 approved these changes
Hopefully good to go now! 🚀

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Maintainable

2022-08-06 06:55 UTC, EmmaDawsonDev approved these changes

2022-08-06 06:55 UTC, merged