My Name Json File added
EddieHubCommunity/LinkFree pull request #1584
Opened 2022-08-09 09:13 UTC by Ranamalsingh12

This PR is for adding [Rana Mal Singh](https://github.com/Ranamalsingh12) Json.

2022-08-09 09:14 UTC, Ranamalsingh12 commented
This PR is to add [Rana Mal Singh](https://github.com/Ranamalsingh12)Json in public folder.

2022-08-09 09:24 UTC, kumarsonsoff3 requested changes
Profile data looks good to me! 

But please Revert the changes from `package-lock.json` file, then it's good to go! 🛠

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-09 09:43 UTC, Ranamalsingh12 commented
Ok i will do it .

2022-08-09 09:57 UTC, Ranamalsingh12 commented
Hey @kumarsonsoff3 i have reverted the changes in the package-lock.json file. Can you check it now? and thanks for your response earlier

2022-08-09 14:22 UTC, aparna2071 approved these changes
Your code looks good to me

2022-08-09 16:07 UTC, kumarsonsoff3 approved these changes
LGTM! Thanks for contributing! 🚀

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-08-09 16:12 UTC, Panquesito7 commented on public/data/Ranamalsingh12.json
> +      "name": "Follow me on Linkedin",
I recommend capitalizing the `i` here. What do you think?
```suggestion
      "name": "Follow me on LinkedIn",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-19 18:45 UTC, EmmaDawsonDev approved these changes

2022-08-19 18:46 UTC, merged