Add pranavarora1895
EddieHubCommunity/LinkFree pull request #1587
Opened 2022-08-12 06:37 UTC by pranavarora1895

Kindly Add my profile to the main project.
Account - [pranavarora1895](https://github.com/pranavarora1895)
Name - Pranav Arora

2022-08-12 11:49 UTC, kumarsonsoff3 requested changes
- Please Revert the changes from the `package-lock.json` file.
- Also, make the following changes in your file. 

Let us know if you need any help with this!


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant, Not maintainable

2022-08-12 11:49 UTC, kumarsonsoff3 commented on public/data/pranavarora1895.json
> +      "name": "Follow me on Linkedin",
What do you think on capitalizing `i` here!?

```suggestion
      "name": "Follow me on LinkedIn",
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Inelegant

2022-08-13 16:24 UTC, kumarsonsoff3 commented
@pranavarora1895 Changes in `package-lock.json` file are not required! So please revert the changes from `package-lock.json` file! Let us know if you need any help! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-14 06:44 UTC, Pradumnasaraf requested changes
Hey,
The `package-lock.json` file is still in the PR. If you need any help, feel to ping us.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-15 11:04 UTC, pranavarora1895 commented
> Hey, The `package-lock.json` file is still in the PR. If you need any help, feel to ping us.
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Hi. I am not able to revert the changes and put it back to this PR. Kindly let me know how to do it. Thanks.

2022-08-15 19:55 UTC, Panquesito7 commented
> > Hey, The `package-lock.json` file is still in the PR. If you need any help, feel to ping us.
> > __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  🛠️ This code needs a fix
> 
> Hi. I am not able to revert the changes and put it back to this PR. Kindly let me know how to do it. Thanks.

Just copy the contents from the [original `package-lock.json`](https://raw.githubusercontent.com/EddieHubCommunity/LinkFree/main/package-lock.json), paste them into your `package-lock.json` branch, commit, then push. You might have to revert the changes first if you're using a service such as Gitpod or running NPM each time you start the editor. Let us know if you need any help. 🙂

2022-08-17 03:59 UTC, kumarsonsoff3 requested changes
Hey @pranavarora1895, Just remove the `empty endline` from the `package-lock.json` file! 

### ⚠ Remember: 
If you're using a service such as Gitpod or running `NPM` each time you start the editor, then you have to follow what @Panquesito7 said! 😄
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-31 02:58 UTC, kumarsonsoff3 commented
Do you need any help with this @pranavarora1895 !?

2022-09-10 14:58 UTC, EmmaDawsonDev commented
Since there is no answer on this for a while I will close it. Please feel free to make a new pull request adding your portfolio without the package-lock file.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Tags:** Not reusable

2022-09-10 14:58 UTC, closed without merging