Add my profile
EddieHubCommunity/LinkFree pull request #1608
Opened 2022-08-15 07:04 UTC by rhen99

I just added my profile, rhen99.json

2022-08-15 09:35 UTC, Pradumnasaraf requested changes
Hey,
Revert the `package-lock.json` file changes. If you have issues, feel free to reach us out.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-16 06:52 UTC, rhen99 commented
I didn't change anything in the `package.lock.json`. I just forgot to commit it. That's all.

2022-08-16 08:46 UTC, kumarsonsoff3 requested changes
Yea @rhen99, you didn't made any changes there, but since you run `npm` when you start, it automatically updates the package version to the latest, so it is! 

You should have only commit the file you're changing, but no worries! ~~
<hr/>

Just make these 2 changes now, it will then good to go! 
- Change the package version back to the initial (line no `9`) as suggested below!
- Remove the `empty endline` from the `package-lock.json` file! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-16 08:46 UTC, kumarsonsoff3 commented on package-lock.json
> +      "version": "0.70.17",
Revert the package version back to the one in base branch! 
```suggestion
      "version": "0.70.1",
```

2022-08-19 18:33 UTC, EmmaDawsonDev commented
Did you need any help @rhen99 ?

2022-09-10 15:00 UTC, EmmaDawsonDev commented
Since there's been no progress on this for almost 3 weeks I'll close it. Please feel free to open a new pull request with your profile but not including the package-lock file.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-10 15:00 UTC, closed without merging