Add AnanjayGurjar.json
EddieHubCommunity/LinkFree pull request #1622
Opened 2022-08-17 16:13 UTC by AnanjayGurjar

Please, Add my profile to the main project. Open for suggestions on how to make it better.
P.S. It's my first contribution to any open source project.

2022-08-17 19:10 UTC, Panquesito7 requested changes

2022-08-17 19:10 UTC, Panquesito7 commented on public/data/AnanjayGurjar.json
> +
There's an extra line here.
```suggestion
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-18 05:40 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-08-18 08:55 UTC, kumarsonsoff3 requested changes

2022-08-18 08:55 UTC, kumarsonsoff3 commented on public/data/AnanjayGurjar.json
> +        "description": "Worked with Meduto as Android Developer Intern where I worked on the ",
This sentence seems to be incomplete, please complete it or modify it! 🛠

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-18 19:38 UTC, Panquesito7 approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-19 04:12 UTC, kumarsonsoff3 approved these changes
Looks Good! 👍 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-08-19 04:12 UTC, merged