Created my profile.
EddieHubCommunity/LinkFree pull request #1636
Opened 2022-08-20 12:15 UTC by OmAvhad

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-20 13:06 UTC, SaptarshiSarkar12 approved these changes
LGTM 👍 . The changes are ready to be merged.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant, Reusable, Maintainable

2022-08-21 16:59 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-08-26 15:18 UTC, Pradumnasaraf requested changes
Using the `https://github.com/OmAvhad.png` will me more dynamic as you change your profile picture in the future.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-08-26 15:18 UTC, Pradumnasaraf commented on public/data/OmAvhad.json
> +  "avatar": "https://avatars.githubusercontent.com/u/89376666?v=4",
```suggestion
  "avatar": "https://github.com/OmAvhad.png",
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-02 12:49 UTC, SaptarshiSarkar12 commented
@Panquesito7 @kumarsonsoff3 Please check if this PR is ready to be merged.

2022-09-02 16:25 UTC, kumarsonsoff3 approved these changes
Looks Good to me! 👍 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-09-04 14:40 UTC, OmAvhad commented
Hello,

Can some one help me with this, Format test is failing !
@SaptarshiSarkar12 @Pradumnasaraf

2022-09-04 15:23 UTC, kumarsonsoff3 commented
No worries @OmAvhad, this issue is resolved last day! This PR is good to goo! 

It will re-run when we'll push your PR!! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-09-04 15:24 UTC, merged