Create Nonso.json
EddieHubCommunity/LinkFree pull request #1637
Opened 2022-08-20 12:55 UTC by Arndy345

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-21 16:42 UTC, Panquesito7 requested changes

2022-08-21 16:42 UTC, Panquesito7 commented on public/data/Nonso.json
> +   "milestones": []
There's a missing comma in here.
```suggestion
   "milestones": [],
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-08-21 17:18 UTC, Arndy345 commented
Thanks @Panquesito7

2022-08-21 17:36 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-22 10:41 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-22 15:35 UTC, merged