Create 7flash.json
EddieHubCommunity/LinkFree pull request #1645
Opened 2022-08-22 02:43 UTC by 7flash

2022-08-22 03:12 UTC, Panquesito7 commented on public/data/7flash.json
> +        "title": "Joined Github",
I recommend capitalizing the `h` here. What do you think?
```suggestion
        "title": "Joined GitHub",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

2022-08-22 15:16 UTC, Panquesito7 requested changes

2022-08-22 15:16 UTC, Panquesito7 commented on public/data/7flash.json
> +  "avatar": "https://avatars.githubusercontent.com/u/4569866?v=4",
It is best to use this link as it's shorter and updates automatically.
```suggestion
  "avatar": "https://github.com/7flash.png",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-22 21:40 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-09-02 18:21 UTC, eddiejaoude commented on public/data/7flash.json
> +        "title": "Joined GitHub",
This data needs to be wrapped in an object `{}`

For example

```json
      "milestones": [{
         "title": "Joined GitHub",
         "date": "December 2013"
       }]
```

2022-09-03 03:14 UTC, kumarsonsoff3 approved these changes
Looks Good! 👍 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-09-03 03:18 UTC, merged