Fixing issue: [BUG] Update the Discord icon in the readme #1698
EddieHubCommunity/LinkFree pull request #1699
Opened 2022-08-31 14:51 UTC by Pathholder1806

## Fixes Issue

Closes #1698

## Changes proposed

I have updated the discord icon in the 'icons.md' file
New Icon Link: https://assets-global.website-files.com/6257adef93867e50d84d30e2/625e5f775305fb9733389e0f_Discord-Logo-Black%20(1).png
Ref: https://discord.com/branding

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-31 16:23 UTC, Panquesito7 commented on icons.md
> +|   Discord   |   discord   | <img src="https://assets-global.website-files.com/6257adef93867e50d84d30e2/625e5f775305fb9733389e0f_Discord-Logo-Black%20(1).png" width=65% height=30%>
This is a more black version of the icon. 🙂
```suggestion
|   Discord   |   discord   | <img src="https://user-images.githubusercontent.com/51391473/187728370-34aac260-8fea-4d41-aaeb-06b1643ccd9a.png" width=50% height=30%>                       |     Dollar     |     dollar     | <img src="https://user-images.githubusercontent.com/76985777/145393429-c03c5c3e-0416-4d28-be21-8a01a0c3dff5.png" width=100% height=30%> |
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-31 16:30 UTC, Panquesito7 approved these changes
Awesome! Thank you. 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-31 16:37 UTC, Pathholder1806 commented
Thank you @Panquesito7 for your input on my change! Valuable inputs are always great way to learn. 🔥
Hoping to get the PR merged now soon😀

2022-09-01 15:39 UTC, kumarsonsoff3 commented
Please resolve the merge conflicts with your branch, let us know if you need any help with this! 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-09-02 17:53 UTC, EmmaDawsonDev requested changes
The changes to the icon look good. Please separate your profile into a separate pull request as the changes are not related.

2022-09-02 20:57 UTC, Panquesito7 commented
> The changes to the icon look good. Please separate your profile into a separate pull request as the changes are not related.

It seems the CI automatically made those changes. You can see the commit co-author is GitHub Actions.
We should merge it because if we revert the changes, the CI will make the appropriate changes again.

2022-09-03 03:06 UTC, kumarsonsoff3 requested changes
These changes in profile are may be because the issues with prettier last day! 

I believe, you need to **Sync your fork**, this issue must be resolved then! ⚒

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-03 03:36 UTC, Pathholder1806 commented
I have synced my fork @kumarsonsoff3 !

2022-09-03 04:03 UTC, kumarsonsoff3 commented
Hey @Pathholder1806, Probably I was unclear! 🤦‍♂️ 
I mean with the branch from which the PR is coming, which is 9 commits behind!

![image](https://user-images.githubusercontent.com/88786642/188255171-f78b192a-5650-42af-9820-4fb28eed0600.png)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-03 04:07 UTC, Pathholder1806 commented
Hey @kumarsonsoff3 !
Thanks for clarifying. I have updated the **patch-1** branch too!

2022-09-03 04:58 UTC, kumarsonsoff3 approved these changes
Looks Good, Thanks for contributing! 👍

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-09-03 05:01 UTC, merged