Add profile
EddieHubCommunity/LinkFree pull request #1709
Opened 2022-08-31 20:52 UTC by Varunmnx

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-08-31 23:17 UTC, Panquesito7 approved these changes
Thanks for contributing! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-09-01 03:11 UTC, kumarsonsoff3 requested changes

2022-09-01 03:11 UTC, kumarsonsoff3 commented on public/data/VarunNarayanan.json
> +      },
Please remove this Trailing comma from here! 
```suggestion
      }
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-01 10:40 UTC, Varunmnx commented
Done

2022-09-01 12:06 UTC, kumarsonsoff3 approved these changes
LGTM! 👍 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-09-01 12:06 UTC, merged