Updated LinkFree Profile
EddieHubCommunity/LinkFree pull request #1742
Opened 2022-09-10 07:53 UTC by izzarzn

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-09-10 15:03 UTC, EmmaDawsonDev commented on public/data/izzarzn.json
> +      "url": "izzarzn.github.io",
```suggestion
      "url": "https://izzarzn.github.io",
```

2022-09-10 15:04 UTC, EmmaDawsonDev requested changes
Please update the url on line 19

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-10 16:56 UTC, izzarzn commented
> Please update the url on line 19
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Updated

2022-09-11 01:44 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Elegant

2022-09-11 02:42 UTC, kumarsonsoff3 requested changes

2022-09-11 02:42 UTC, kumarsonsoff3 commented on public/data/izzarzn.json
> +      "url": "https://izzarzn.github.io",
There is a broken link, check whether there is a typo, or you've placed the correct URL!!

Please update it with the correct one!! 🛠

![image](https://user-images.githubusercontent.com/88786642/189509987-aeb9ccd1-1ca0-4e92-821d-120ca3c2b632.png)



__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant, Not maintainable

2022-09-11 03:32 UTC, closed without merging