Create cchow33.json
EddieHubCommunity/LinkFree pull request #1755
Opened 2022-09-13 14:45 UTC by cchow33

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-09-13 15:26 UTC, Panquesito7 requested changes

2022-09-13 15:26 UTC, Panquesito7 commented on public/data/cchow33.json
> +    },
There's an extra comma in here.
```suggestion
    }
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-09-13 19:25 UTC, Njong392 commented on public/data/cchow33.json
> +      "description": "Looking forward to accelerating my learning!",
Oops. There seems to be a comma at the end of line 18 that is not required. Feel free to remove it :smiley: 
```suggestion
      "description": "Looking forward to accelerating my learning!"
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-18 19:32 UTC, RealSollyM requested changes
Trailing commas found in JSON file. Please fix and re-submit.

2022-10-04 16:58 UTC, EmmaDawsonDev commented
@cchow33 im closing this for now as it seems to have been abandoned. Feel free to make the requested changes and open a new pr if you still wish to contribute

2022-10-04 16:58 UTC, closed without merging