My json file is added
EddieHubCommunity/LinkFree pull request #1764
Opened 2022-09-17 16:39 UTC by Saha-7

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-09-18 00:25 UTC, Panquesito7 requested changes

2022-09-18 00:25 UTC, Panquesito7 commented on public/data/PritamSaha7.json
> +    "avatar": "https://github.com/kaiwalyakoparkar.png",
It seems this is the wrong link.
```suggestion
    "avatar": "https://github.com/Saha-7.png",
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-09-18 04:34 UTC, Saha-7 commented
Dear maintainers,
I am really sorry for the mistakes. I have changed it committed directly to
the patch1. Should I have to Pull request again from scratch?

On Sun, 18 Sep 2022, 5:56 am David Leal, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In public/data/PritamSaha7.json
> <https://github.com/EddieHubCommunity/LinkFree/pull/1764#discussion_r973642575>
> :
>
> > @@ -0,0 +1,18 @@
>
> +{
>
> +    "name": "Pritam Saha",
>
> +    "type": "personal",
>
> +    "bio": "I am pritam Saha, Computer Science graduate from Adamas University",
>
> +    "avatar": "https://github.com/kaiwalyakoparkar.png",
>
>
> It seems this is the wrong link.
> ⬇️ Suggested change
>
> -    "avatar": "https://github.com/kaiwalyakoparkar.png",
>
> +    "avatar": "https://github.com/Saha-7.png",
>
>
> __
> [image: sema-logo] <https://semasoftware.com/gh>  *Summary:* 🛠️ This
> code needs a fix  |  *Tags:* Not maintainable
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/LinkFree/pull/1764#pullrequestreview-1111479721>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYZSFAH3Q42VEN3FGWZLBMDV6ZORVANCNFSM6AAAAAAQPCHGL4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-18 04:50 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉 


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-09-18 05:06 UTC, Saha-7 commented
Thanks for the approval. Can you assign me in the issue number #1728?
I am ready with my forked repo with the updated Readme.MD file that will
help the beginners to add their profile.
Waiting for your reply
Thank you

On Sun, 18 Sep 2022, 10:20 am David Leal, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Looks good. Thanks! 🎉
>
> __
> [image: sema-logo] <https://semasoftware.com/gh>  *Summary:* 👌 This code
> looks good
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/LinkFree/pull/1764#pullrequestreview-1111490557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYZSFAFMB6YXQOU2SP5R62LV62NSVANCNFSM6AAAAAAQPCHGL4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-18 08:13 UTC, Pradumnasaraf commented
Closing this PR. As the issue link to this PR is already assigned to someone else.

2022-09-20 03:27 UTC, Pradumnasaraf commented
Applogies

2022-09-20 03:27 UTC, closed without merging