add ZainMhrez.json
EddieHubCommunity/LinkFree pull request #1771
Opened 2022-09-19 16:54 UTC by ZainMhrez

add ZainMhrez.json

2022-09-19 17:52 UTC, Panquesito7 requested changes

2022-09-19 17:52 UTC, Panquesito7 commented on public/data/ZainMhrez.json
> +  ],
There's an extra comma in here.
```suggestion
  ]
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not maintainable

2022-09-22 15:08 UTC, Panquesito7 requested changes

2022-09-22 15:08 UTC, Panquesito7 commented on public/data/ZainMhrez.json
> +  "avatar": "https://github.com/YOUR_GITHUB_USERNAME.png",
```suggestion
  "avatar": "https://github.com/https://github.com/ZainMhrez.png",
```

2022-09-23 03:12 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2022-09-23 06:10 UTC, kumarsonsoff3 approved these changes
Looks Good! 🎉

2022-09-23 06:11 UTC, merged