Beginners guide to add their profile from scratch with step by step guide.
EddieHubCommunity/LinkFree pull request #1800
Opened 2022-09-25 18:50 UTC by Saha-7

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-09-26 08:08 UTC, Saha-7 commented
Maintainers can you please check it once !

2022-09-28 18:23 UTC, 404Nikhil approved these changes

2022-09-30 09:51 UTC, Vyvy-vi reviewed
The text repeats the steps written a few lines above, and ideally, instructions about adding the profile shouldn't go in the CONTRIBUTING.md file.

2022-10-01 01:08 UTC, Saha-7 commented
I previously added it to the README.md file but Maintainer @EmmaDawsonDev told me to add it to the CONTRIBUTING.md file.

2022-10-03 10:49 UTC, E-fais requested changes
Command for opening vs code
“ code  . “

2022-10-03 10:49 UTC, E-fais commented on CONTRIBUTING.md
> +- Then open VS code by using this command `code `. hit enter.
Typo: 
Change this  “code” .  
to 
“ code . “  
To open vs code.

2022-10-04 10:25 UTC, Saha-7 commented
Thanks, mistakes solved.

2022-10-04 15:15 UTC, EmmaDawsonDev commented
Hang tight with this pull request. We (the maintainers) are just reorganising the folder struccture so that this has a proper place to live. Once everything is in place we'll let you know so it can be moved to the correct folder.

2022-10-07 14:33 UTC, EmmaDawsonDev commented
Ok, can you move this into the docs/contributing folder and name it contributing-your-profile.md ?

2022-10-07 15:49 UTC, Saha-7 commented
Sure.

2022-10-07 16:37 UTC, Saha-7 commented
PR raised in docs/contributing folder #1916

2022-10-16 20:26 UTC, closed without merging