added my  profile
EddieHubCommunity/LinkFree pull request #1823
Opened 2022-09-28 16:13 UTC by raeeceip

## Added my profile details

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/98179907/192831207-f5231552-6b48-49d8-9318-b488ceab54e6.png)

## Note to reviewers

2022-09-28 17:09 UTC, Rahul-Prasad-07 approved these changes

2022-09-29 01:18 UTC, kumarsonsoff3 requested changes

2022-09-29 19:19 UTC, Panquesito7 approved these changes
Looks good. Thanks for contributing! 🎉

2022-09-30 01:02 UTC, kumarsonsoff3 approved these changes
Looks good to me! 🚀🚀

2022-09-30 01:03 UTC, merged