Added profile
EddieHubCommunity/LinkFree pull request #1826
Opened 2022-09-29 12:30 UTC by kayjilesen

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-09-29 13:04 UTC, AbbeyIT approved these changes
LGTM

2022-09-29 19:22 UTC, Panquesito7 requested changes

2022-09-29 19:22 UTC, Panquesito7 commented on public/data/kayjilesen.json
> +      "icon": "robot-happy-outline",
This seems like an invalid icon. Please choose an icon within our [**icon list**](https://github.com/EddieHubCommunity/LinkFree/blob/main/icons.md).

2022-10-04 17:09 UTC, EmmaDawsonDev approved these changes

2022-10-04 17:10 UTC, merged