Created the Shivam-officials.json file
EddieHubCommunity/LinkFree pull request #1864
Opened 2022-10-02 16:07 UTC by Shivam-officials

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-10-02 16:08 UTC, Panquesito7 commented on public/data/Shivam-officials.json
> +      "url": "https://github.com/YOUR_GITHUB_USERNAME",
```suggestion
      "url": "https://github.com/Shivam-officials",
```

2022-10-03 04:25 UTC, Panquesito7 requested changes

2022-10-03 04:25 UTC, Panquesito7 commented on public/data/Shivam-officials.json
> +      "url": "https://www.eddiejaoude.io/"
You might want to remove or update this link here.

2022-10-06 15:33 UTC, Shivam-officials reviewed
i updated the url plz add review it once more

2022-10-06 16:57 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2022-10-07 07:19 UTC, kumarsonsoff3 approved these changes

2022-10-07 07:20 UTC, merged