update profile: Pranay202
EddieHubCommunity/LinkFree pull request #1877
Opened 2022-10-03 18:59 UTC by pranay202

update: milestones
fix: Linkedin brand logo

2022-10-03 19:29 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/1877/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](http://discord.eddiehub.org). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

2022-10-07 15:14 UTC, EmmaDawsonDev approved these changes

2022-10-11 17:56 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-10-11 17:59 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-10-11 17:59 UTC, merged