[DOCS] Contributing to next js branch #1908
EddieHubCommunity/LinkFree pull request #1914
Opened 2022-10-06 18:13 UTC by irfanariyaz

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-10-07 14:51 UTC, EmmaDawsonDev requested changes
There are a few changes in order to tailor this to the next js branch specifically

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +- [Prime React](https://www.primefaces.org/primereact/)
```suggestion

```

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +- [Prime React](https://www.primefaces.org/primereact/)
Prime react should be removed and links to Next and Tailwind should be added

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +## ⭐ HOW TO MAKE A PULL REQUEST:
```suggestion
```

Remove all of this

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +
I think the person needs to checkout the next-js branch first and then make their branch from that branch instead of main

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +
These lines are only relevant when adding a profile. They can be removed here

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +**11.** Create a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)!
Maybe worth adding here to check that the base branch is Linkfree/next-js branch and not main

2022-10-07 14:51 UTC, EmmaDawsonDev commented on docs/contributing/contributing-to-nextJS-branch.md
> +
The testing will probably fail for now so best to remove this section

2022-10-10 05:54 UTC, irfanariyaz commented
HI @EmmaDawsonDev ,I have added the required changes for the file .  To Sync the forked repository with origin repository, we use the commands git fetch upstream   and git merge upstream/nextjs  right?
Also I have one doubt, I was not able to make a pull request on the changes I made to the file- contributing-to-nextJs-branch.md . Is it like if I commit , it automatically make a pull request? Are you able to see my changes to the file?

2022-10-16 20:19 UTC, EmmaDawsonDev approved these changes

2022-10-16 20:21 UTC, EmmaDawsonDev commented
> HI @EmmaDawsonDev ,I have added the required changes for the file . To Sync the forked repository with origin repository, we use the commands git fetch upstream and git merge upstream/nextjs right?
> Also I have one doubt, I was not able to make a pull request on the changes I made to the file- contributing-to-nextJs-branch.md . Is it like if I commit , it automatically make a pull request? Are you able to see my changes to the file?

Sorry for the late reply! Yes, when a pull request is already open any new commits automatically update the PR.

2022-10-16 20:23 UTC, merged