Added my profile
EddieHubCommunity/LinkFree pull request #1943
Opened 2022-10-11 05:42 UTC by jainpatel25

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-10-11 06:37 UTC, kumarsonsoff3 requested changes
Please make the following changes as suggested below, let us know if you need any help!

2022-10-11 06:37 UTC, kumarsonsoff3 commented on public/data/jainpatel.json
> +    "avatar": "",
Please use a valid Avatar link! 🛠
```suggestion
    "avatar": "https://github.com/jainpatel25.png",
```

2022-10-11 06:37 UTC, kumarsonsoff3 commented on public/data/jainpatel.json
> +        "icon": "",
Use a valid icon here from the list of icons available in our docs [icon.md](https://github.com/EddieHubCommunity/LinkFree/blob/main/icons.md)

2022-10-11 11:53 UTC, imran1509 reviewed
Please use a valid icon from the list of icons suggested by  @kumarsonsoff3 
other than that everything looks good to me

2022-10-20 05:49 UTC, neerajrathore commented
changes looks fine

2022-11-07 12:20 UTC, Pradumnasaraf reviewed
Hey, 
Thank you for raising the PR and for your contribution. 

Sad to say we can't merge this PR, as we have done huge changes to this repo ([**Migrated to Next.js**](https://github.com/EddieHubCommunity/LinkFree/releases/tag/v1.1.0)), and the path to profile addition has been changed. So please raise a new PR and we will try to merge it ASAP. 

You can find the updated instruction with the new path in the [README](https://github.com/EddieHubCommunity/LinkFree#-contributing). If you have any doubts feel free to reach us out on the [EddieHub Discord](http://discord.eddiehub.org/)

NOTE: Fetch/sync/pull new changes then go for the PR.

**Thank you**

2022-11-07 12:20 UTC, closed without merging