adding my profile to the public/data
EddieHubCommunity/LinkFree pull request #2003
Opened 2022-10-20 00:48 UTC by philling1

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-10-20 03:04 UTC, Panquesito7 requested changes

2022-10-20 03:04 UTC, Panquesito7 commented on public/data/philling1.json
> +      "url": ""
Please remove these empty unused fields.

2022-10-20 04:45 UTC, imran1509 reviewed
Please use the blank fields for your other links or else delete the unused fields

2022-10-20 09:30 UTC, accodes21 reviewed
Remove Unused Links rest all is good.

2022-10-22 15:37 UTC, philling1 reviewed
done thanks

2022-10-22 16:49 UTC, Pradumnasaraf approved these changes

2022-10-22 16:49 UTC, Pradumnasaraf commented on public/data/philling1.json
> +  "type": "Personal",
```suggestion
  "name": "Phil",
  "type": "personal",
```

2022-11-07 12:41 UTC, schmelto approved these changes
## Looking good to me

Your suggested changes looking good to me.

---
**Summary:** :ok_hand: This code looks good

2022-11-07 12:41 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-11-07 13:00 UTC, merged