Created Anirudh.json
EddieHubCommunity/LinkFree pull request #202
Opened 2021-09-16 03:23 UTC by qwe123coder

Fixes #173 

## Proposed Changes

  -
  -
  -

## Screenshots

2021-09-16 03:40 UTC, FayasNoushad approved these changes

2021-09-16 03:42 UTC, rohan-kulkarni-25 approved these changes

2021-09-16 03:59 UTC, MukulKolpe approved these changes

2021-09-16 09:04 UTC, schmelto commented
Is polywork supported yet?

2021-09-16 10:19 UTC, qwe123coder commented
> Is poly work supported yet?

it is not and Eddie told it will get filtered out and not showed (ig that is what he meant in my other or )

2021-09-21 07:17 UTC, rohan-kulkarni-25 requested changes

2021-09-21 07:17 UTC, rohan-kulkarni-25 commented on public/data/Anirudh.json
> +      "url": "http://github.com/qwe123coder",
Please add `https` for Github URL

2021-09-22 14:42 UTC, Panquesito7 commented on public/data/Anirudh.json
> +  "bio": "I am Anirudh Anup, A passionate 13 year old developer from India, I am always open to collaborating on projects",
```suggestion
  "bio": "A passionate 13-year-old developer from India. I am always open to collaborating on projects",
```

2021-09-22 15:02 UTC, Panquesito7 requested changes

2021-09-22 15:02 UTC, Panquesito7 commented on public/data/Anirudh.json
> +      "url": "http://github.com/qwe123coder",
```suggestion
      "url": "https://github.com/qwe123coder",
```

2021-09-26 10:30 UTC, eddiejaoude commented on public/data/Anirudh.json
> +      "url": "http://github.com/qwe123coder",
GitHub will redirect to https

2021-09-26 10:31 UTC, eddiejaoude commented
Any links not supported will not be shown, but later when support will be shown.

I merged the Polywork PR that allows people to add milestones/achievements like in Polywork

2021-09-26 10:31 UTC, merged