add : adding profile picture in chip
EddieHubCommunity/LinkFree pull request #2024
Opened 2022-10-23 14:36 UTC by kartikgajjar7

## Changes proposed

1) profile picture for particular user added in chips in the search page .

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-10-23 18:07 UTC, kartikgajjar7 commented
it hit the rate limit of GitHub's API, share your views how can we solve this issue....

2022-10-28 10:58 UTC, kartikgajjar7 commented
@kumarsonsoff3

2022-10-29 03:46 UTC, kartikgajjar7 commented
@Panquesito7

2022-10-29 15:56 UTC, eddiejaoude commented
When visiting the search page it still flickers with the skeletons - I think you need to remove the `Placeholders` component

2022-10-29 16:56 UTC, kartikgajjar7 commented
state is "false" for skeleton so now skeleton is not visible..

2022-10-29 20:25 UTC, eddiejaoude commented
But is the skeleton component still required now? 🤔

2022-10-30 13:05 UTC, kartikgajjar7 commented
> But is the skeleton component still required now? 🤔

yes it is not needed now ..removed it

2022-10-30 18:55 UTC, eddiejaoude commented
Btw there are some lint errors

2022-10-30 18:57 UTC, kartikgajjar7 commented
> Btw there are some lint errors

Can you explain little bit more about it?? I will figure it put

2022-10-30 19:02 UTC, kartikgajjar7 commented
> Btw there are some lint errors

Do you mean extra spaces and all ?

2022-10-30 19:02 UTC, kartikgajjar7 commented
> > Btw there are some lint errors
> 
> Do you mean extra spaces and all ? (I m not familiar with lint errors)

2022-10-31 06:31 UTC, kartikgajjar7 commented
> Btw there are some lint errors
fixed it,thanks

2022-10-31 08:09 UTC, eddiejaoude commented
When you click on details next to the failing GitHub Action (test), it shows more details

It says `expected '<main>' to contain 'Eddie Jaoude'`, so I guess the component changed and the tests need to be updated so that it can find the text it is looking for. Here is the file to the failing test https://github.com/EddieHubCommunity/LinkFree/blob/da344679874084c1c8a0a8210dc8fa2f8a8feaa5/cypress/integration/search.feature

2022-10-31 08:12 UTC, kartikgajjar7 commented
> When you click on details next to the failing GitHub Action (test), it shows more details
> 
> It says `expected '<main>' to contain 'Eddie Jaoude'`, so I guess the component changed and the tests need to be updated so that it can find the text it is looking for. Here is the file to the failing test https://github.com/EddieHubCommunity/LinkFree/blob/da344679874084c1c8a0a8210dc8fa2f8a8feaa5/cypress/integration/search.feature

oh yes.main doesn't contain  eddie jaounde because the result will come only after 3 character

2022-10-31 08:43 UTC, eddiejaoude commented
So I think you can update those lines to test the names do not appear yet

2022-11-02 10:57 UTC, kartikgajjar7 commented
> So I think you can update those lines to test the names do not appear yet

hey eddie can you explain me  briefly what i exactly have to do , i m not familiar with testing at all so it will be good if you guide me more

2022-11-02 20:39 UTC, eddiejaoude commented
Have a try, the tests are written in English, you can run them locally to see if they pass or not after you make changes

For example, I think these lines are no longer needed, as the results do not appear until after the typing https://github.com/EddieHubCommunity/LinkFree/blob/da344679874084c1c8a0a8210dc8fa2f8a8feaa5/cypress/integration/search.feature#L16-L17

2022-11-03 04:46 UTC, kartikgajjar7 commented
> 

kindly review  changes for tests

2022-11-03 06:23 UTC, kartikgajjar7 commented
> Have a try, the tests are written in English, you can run them locally to see if they pass or not after you make changes
> 
> For example, I think these lines are no longer needed, as the results do not appear until after the typing
> 
> https://github.com/EddieHubCommunity/LinkFree/blob/da344679874084c1c8a0a8210dc8fa2f8a8feaa5/cypress/integration/search.feature#L16-L17

<img width="887" alt="gitttttttttttttthub" src="https://user-images.githubusercontent.com/97971066/199658660-185e7a59-a5fc-4023-a741-16cd412159a8.png">

2022-11-03 06:35 UTC, eddiejaoude approved these changes
Looks good 👍

2022-11-03 06:47 UTC, eddiejaoude requested changes
The GitHub Action seems still be failing, did you commit all your changes?

2022-11-03 06:54 UTC, eddiejaoude commented
I found the issue, the other `search` test will need updating also https://github.com/EddieHubCommunity/LinkFree/pull/2024/files#diff-ba0ca755d18ebab091579ac0895278a868b0d3ed71c265bcf6d8c219dd687febR22

2022-11-03 07:19 UTC, kartikgajjar7 commented
> The GitHub Action seems still be failing, did you commit all your changes?

oh yes my bad i didn't commit my last change..
take a look now

2022-11-03 07:41 UTC, eddiejaoude approved these changes
Looks good 👍  thank you

2022-11-03 07:42 UTC, merged