Added my profile data for the link to be generated
EddieHubCommunity/LinkFree pull request #2077
Opened 2022-10-31 10:13 UTC by Jaideep25-tech

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/2077"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-10-31 19:37 UTC, Panquesito7 requested changes

2022-10-31 19:37 UTC, Panquesito7 commented on public/data/jaideepSingh.json
> +    }
Missing comma.
```suggestion
    },
```

2022-10-31 19:37 UTC, Panquesito7 commented on public/data/jaideepSingh.json
> +      "description": "Building cross platform mobile application in flutter using state management and firebase",
```suggestion
      "description": "Building a cross-platform mobile application in Flutter using state management and Firebase"
```

2022-10-31 19:37 UTC, Panquesito7 commented on public/data/jaideepSingh.json
> +      "description": "Building cross platform mobile application in flutter integrating AR/VR built in unity into Application and working with API ",
```suggestion
      "description": "Building cross-platform mobile application in Flutter integrating AR/VR built in Unity into Application and working with APIs"
```

2022-10-31 19:37 UTC, Panquesito7 commented on public/data/jaideepSingh.json
> +      "description": "Became the program manger of the open source program SWOC"
Spelling error.
```suggestion
      "description": "Became the program manager of the open source program SWOC"
```

2022-11-07 13:06 UTC, Pradumnasaraf reviewed
Hey, 
Thank you for raising the PR and for your contribution. 

Sad to say we can't merge this PR, as we have done huge changes to this repo ([**Migrated to Next.js**](https://github.com/EddieHubCommunity/LinkFree/releases/tag/v1.1.0)), and the path to profile addition has been changed. So please raise a new PR and we will try to merge it ASAP. 

You can find the updated instruction with the new path in the [README](https://github.com/EddieHubCommunity/LinkFree#-contributing). If you have any doubts feel free to reach us out on the [EddieHub Discord](http://discord.eddiehub.org/)

NOTE: Fetch/sync/pull new changes then go for the PR.

**Thank you**

2022-11-07 13:06 UTC, closed without merging