Made profile
EddieHubCommunity/LinkFree pull request #2096
Opened 2022-11-02 10:12 UTC by Akshay-bendadi

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-11-02 16:07 UTC, Panquesito7 requested changes

2022-11-02 16:07 UTC, Panquesito7 commented on public/data/Akshay-bendadi.json
> +      "url": ""
I recommend removing these unused empty fields.

2022-11-03 14:05 UTC, kumarsonsoff3 approved these changes
Looks Good, Thanks! 👍

2022-11-04 16:23 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-11-04 16:24 UTC, merged