Create yashsharma999.json
EddieHubCommunity/LinkFree pull request #2099
Opened 2022-11-03 01:36 UTC by yashsharma999

add my profile in public/data

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-11-03 13:57 UTC, kumarsonsoff3 requested changes

2022-11-03 13:57 UTC, kumarsonsoff3 commented on public/data/yashsharma999.json
> +  "avatar": "https://github.com/yashsharma.png",
I believe it should be `yashsharma999.png`. Please update it with the correct one! 

```suggestion
  "avatar": "https://github.com/yashsharma999.png",
```

2022-11-05 08:40 UTC, Rohith-JN approved these changes
Looks good

2022-11-05 09:27 UTC, eddiejaoude approved these changes
LGTM 👍

2022-11-05 09:34 UTC, merged