update Akshay-bendadi
EddieHubCommunity/LinkFree pull request #2119
Opened 2022-11-04 17:52 UTC by Akshay-bendadi

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-11-04 21:28 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/2119/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](http://discord.eddiehub.org). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

2022-11-05 04:38 UTC, CBID2 requested changes

2022-11-05 04:38 UTC, CBID2 commented on public/data/Akshay-bendadi.json
> +  "bio": "Open Source Enthusiast!",
Hi @Akshay-bendadi! Since you mentioned being a Computer student in your profile, consider mentioning it here too! :)

2022-11-05 04:38 UTC, CBID2 commented on public/data/Akshay-bendadi.json
> +}
Consider adding some milestones if applicable.

2022-11-05 04:54 UTC, closed without merging