Added profile amittri1025
EddieHubCommunity/LinkFree pull request #213
Opened 2021-09-16 13:12 UTC by amittri1025

Add my profile in public/data with my username as its name 

## Proposed Changes

  -Change Name
  -Change Designation
  -Change Avatar

## Screenshots
![Screenshot of added Image](https://user-images.githubusercontent.com/74503582/133617870-32e3ca99-9c69-4ab6-acad-f95f5aa85e83.png)

2021-09-16 13:21 UTC, schmelto requested changes

2021-09-16 13:21 UTC, schmelto commented on public/data/amittri1025.json
> +    "avatar": "https://avatars.githubusercontent.com/u/74503582?s=400&u=8afb30d41fd8098e800296c5e9c5646a6de6085d&v=4",
```suggestion
    "avatar": "https://github.com/amittri1025.png",
```

2021-09-16 13:21 UTC, schmelto commented on public/data/amittri1025.json
> +
```suggestion
```

2021-09-17 09:38 UTC, rohan-kulkarni-25 approved these changes

2021-09-17 09:58 UTC, FayasNoushad approved these changes

2021-09-17 12:29 UTC, MukulKolpe approved these changes

2021-09-18 19:19 UTC, CodingSpecies commented
@amittri1025 , please can you resolve the conflicts in `src/index.css` thank you.

2021-09-22 12:08 UTC, closed without merging