Created soumdatta81.json
EddieHubCommunity/LinkFree pull request #2144
Opened 2022-11-06 07:01 UTC by soumdatta81

2022-11-06 16:09 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-11-06 16:26 UTC, accodes21 approved these changes
Looks great

2022-11-06 19:30 UTC, eddiejaoude commented on data/soumdatta81.json
> +      "description": "Started freelancing",
Trailing comma is invalid

```suggestion
      "description": "Started freelancing"
```

2022-11-06 19:31 UTC, eddiejaoude requested changes
Invalid json, comment left inline

2022-11-07 10:07 UTC, eddiejaoude approved these changes
LGTM 👍

2022-11-07 10:07 UTC, merged