Added an accordion to the project
EddieHubCommunity/LinkFree pull request #2150
Opened 2022-11-06 10:04 UTC by Noibisjunior

## Changes proposed

I added an accordion to the projects to help visitors understand the projects

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![accordion](https://user-images.githubusercontent.com/104741218/200164739-daa4811f-ef1f-4c25-ab11-acd3b1ea045a.png)
![accordion2](https://user-images.githubusercontent.com/104741218/200164758-a13aa18d-a9e8-4d9d-8ff1-e8b812545c27.png)

## Note to reviewers

2022-11-21 08:54 UTC, Vyvy-vi requested changes
Thanks for opening this PR and showing interest in LinkFree!
I've left a few comments requesting changes. While this is a great feature, adding Bootstrap as an additional dependency might cause issues later on and make the project less maintainable.

We really appreciate that you took out some of your time to work on LinkFree. If you'd like to refactor this and use primereact's Accordian element, feel free to push additional changes to this PR (that would be highly appreciated, if not, then we could refactor this and merge it in).

2022-11-21 08:54 UTC, Vyvy-vi commented on public/data/Noibisjunior.json
> +  "name": "Abdulsalaam Noibi",
it would be better if this profile is added in a separate PR.

2022-11-21 08:54 UTC, Vyvy-vi commented on src/App.js
> +      <head>
Linkfree is currently using primereact components with tailwindcss for styling. Adding bootstrap would create some redundancy. Perhaps you could implement the same with the Accordion component provided by primereact: https://www.primefaces.org/primereact/accordion/ ?

2022-11-22 14:19 UTC, Noibisjunior commented
Thanks for the feedback,i would be extremely grateful if my pull request
can merged,I would try my possible best to refactor the code and  push the
additional changes to the PR.

On Mon, 21 Nov 2022 at 09:54, Vyom Jain ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for opening this PR and showing interest in LinkFree!
> I've left a few comments requesting changes. While this is a great
> feature, adding Bootstrap as an additional dependency might cause issues
> later on and make the project less maintainable.
>
> We really appreciate that you took out some of your time to work on
> LinkFree. If you'd like to refactor this and use primereact's Accordian
> element, feel free to push additional changes to this PR (that would be
> highly appreciated, if not, then we could refactor this and merge it in).
> ------------------------------
>
> In public/data/Noibisjunior.json
> <https://github.com/EddieHubCommunity/LinkFree/pull/2150#discussion_r1027716587>
> :
>
> > @@ -0,0 +1,35 @@
> +{
> +  "name": "Abdulsalaam Noibi",
>
> it would be better if this profile is added in a separate PR.
> ------------------------------
>
> In src/App.js
> <https://github.com/EddieHubCommunity/LinkFree/pull/2150#discussion_r1027726627>
> :
>
> > @@ -25,6 +25,16 @@ function App() {
>
>    return (
>      <Router>
> +      <head>
>
> Linkfree is currently using primereact components with tailwindcss for
> styling. Adding bootstrap would create some redundancy. Perhaps you could
> implement the same with the Accordion component provided by primereact:
> https://www.primefaces.org/primereact/accordion/ ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EddieHubCommunity/LinkFree/pull/2150#pullrequestreview-1187777342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY7DSYTJJBVOQ56LN6VSSUTWJM2FXANCNFSM6AAAAAARYLHPPA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-22 16:57 UTC, Noibisjunior commented
Please check it out,i have refactor the code base by adding prime react
accordion feature.
https://github.com/Noibisjunior/LinkFree/tree/Accord
please merge

On Tue, 22 Nov 2022 at 15:19, NOIBI ABDULSALAAM ***@***.***>
wrote:

> Thanks for the feedback,i would be extremely grateful if my pull request
> can merged,I would try my possible best to refactor the code and  push the
> additional changes to the PR.
>
> On Mon, 21 Nov 2022 at 09:54, Vyom Jain ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Thanks for opening this PR and showing interest in LinkFree!
>> I've left a few comments requesting changes. While this is a great
>> feature, adding Bootstrap as an additional dependency might cause issues
>> later on and make the project less maintainable.
>>
>> We really appreciate that you took out some of your time to work on
>> LinkFree. If you'd like to refactor this and use primereact's Accordian
>> element, feel free to push additional changes to this PR (that would be
>> highly appreciated, if not, then we could refactor this and merge it in).
>> ------------------------------
>>
>> In public/data/Noibisjunior.json
>> <https://github.com/EddieHubCommunity/LinkFree/pull/2150#discussion_r1027716587>
>> :
>>
>> > @@ -0,0 +1,35 @@
>> +{
>> +  "name": "Abdulsalaam Noibi",
>>
>> it would be better if this profile is added in a separate PR.
>> ------------------------------
>>
>> In src/App.js
>> <https://github.com/EddieHubCommunity/LinkFree/pull/2150#discussion_r1027726627>
>> :
>>
>> > @@ -25,6 +25,16 @@ function App() {
>>
>>    return (
>>      <Router>
>> +      <head>
>>
>> Linkfree is currently using primereact components with tailwindcss for
>> styling. Adding bootstrap would create some redundancy. Perhaps you could
>> implement the same with the Accordion component provided by primereact:
>> https://www.primefaces.org/primereact/accordion/ ?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/EddieHubCommunity/LinkFree/pull/2150#pullrequestreview-1187777342>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AY7DSYTJJBVOQ56LN6VSSUTWJM2FXANCNFSM6AAAAAARYLHPPA>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-11-26 15:39 UTC, EmmaDawsonDev commented
Hi @Noibisjunior thank you so much for your contribution to LinkFree. Unfortunately we just migrated away from React + PrimeReact to NextJS and Tailwind instead.

2022-12-10 05:22 UTC, eddiejaoude commented
As we are no longer using PrimeReact, I will close this PR. Thank you for your contribution and sorry it could not be merged this time.

2022-12-10 05:22 UTC, closed without merging