[README] Outdated Gitpod Removed
EddieHubCommunity/LinkFree pull request #2256
Opened 2022-11-21 11:47 UTC by ShorunTech

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot (260)](https://user-images.githubusercontent.com/61280687/203043416-151e0333-b360-4d8f-b433-8740c60a1245.jpg)

## Note to reviewers

2022-11-21 12:05 UTC, Pradumnasaraf requested changes
Thank you for PR. Please remove the extra line.

2022-11-21 12:05 UTC, Pradumnasaraf commented on README.md
```suggestion
```

2022-11-21 12:12 UTC, ShorunTech commented
okay

2022-11-21 13:35 UTC, schmelto commented on docs/contributing/CONTRIBUTING.md
> +
```suggestion
```

2022-12-09 18:21 UTC, Pradumnasaraf commented
If you need any help, do let's know @ShorunTech

2022-12-17 22:35 UTC, eddiejaoude commented
Thank you for the contribution and collaboration. I will close this PR as the docs have moved forward and now have conflicts. 

Feel free to create a new pull request from the latest docs.

2022-12-17 22:35 UTC, closed without merging