Created my Profile Ansh-Rathod
EddieHubCommunity/LinkFree pull request #2297
Opened 2022-11-30 09:51 UTC by Ansh-Rathod

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-11-30 10:33 UTC, schmelto commented on data/Ansh-Rathod.json
> +
```suggestion
```

2022-11-30 10:33 UTC, schmelto commented on data/Ansh-Rathod.json
> +  "tags": ["flutter","nodejs","dart","javascript", "typescript"],
```suggestion
  "tags": ["flutter", "nodejs", "dart", "javascript", "typescript"],
```

2022-11-30 10:43 UTC, Pradumnasaraf requested changes
Hey, an ending line is required, otherwise looks to me

Comments: Fix the failing action

2022-11-30 10:43 UTC, Pradumnasaraf commented on data/Ansh-Rathod.json
> +}
```suggestion
}

```

2022-11-30 10:57 UTC, Ansh-Rathod commented
> Hey, an ending line is required, otherwise looks to me
> 
> Comments: Fix the failing action

cool, thanks!

2022-11-30 11:47 UTC, kumarsonsoff3 approved these changes
Amazing collaboration! 🎉
Looks Good to me! 👍

2022-11-30 19:35 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-02 20:36 UTC, stevenovak123 approved these changes

2022-12-02 20:36 UTC, stevenovak123 approved these changes

2022-12-04 04:53 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-04 04:54 UTC, merged