i make new profile  mohit.json to maahi.json
EddieHubCommunity/LinkFree pull request #2304
Opened 2022-12-01 06:38 UTC by singhmohit14072002

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-12-05 15:21 UTC, srkds requested changes
Hi @singhmohit14072002 

Thanks for contributing 🎉

Some changes and you're good to go.
- [ ] Format the file, proper indentation
- [ ] Rename the file to your GitHub username for uniqueness

Refer 👉[add your profile guide](https://github.com/EddieHubCommunity/LinkFree#-to-add-your-profile)

2022-12-10 05:29 UTC, eddiejaoude commented on data/maahi.json
> +    }
The formatting is not quite right here, please fix and let's get this merged 👍

2022-12-17 22:46 UTC, eddiejaoude commented
Json is valid, so I will merge

2022-12-17 22:47 UTC, eddiejaoude requested changes
File name does not match GitHub username

2022-12-17 22:47 UTC, eddiejaoude commented
I will close this PR as the file name does not match the username

2022-12-17 22:47 UTC, closed without merging