added json for profile at LinkFree
EddieHubCommunity/LinkFree pull request #2348
Opened 2022-12-09 13:29 UTC by diva-21

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-12-09 13:36 UTC, diva-21 commented
Can i know whats the error in the pull request? @EddieHubCommunity/ambassadors

2022-12-09 17:25 UTC, Pradumnasaraf requested changes
Hey, just an ending line is required

2022-12-09 17:25 UTC, Pradumnasaraf commented on data/diva-21.json
> +}
```suggestion
}

```

2022-12-10 11:15 UTC, diva-21 commented
> Hey, just an ending line is required

thank you, @Pradumnasaraf, I didn't check the minute part

2022-12-10 15:49 UTC, kumarsonsoff3 approved these changes
Looks Good to me! 👍

2022-12-12 02:24 UTC, diva-21 commented
are these changes enough ?

2022-12-12 05:04 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-12 05:04 UTC, merged

2022-12-12 05:43 UTC, diva-21 commented
> Looks good to merge. Thank you for your contribution! 🎉

Thank you, @Pradumnasaraf