added shivanshyadav.json
EddieHubCommunity/LinkFree pull request #235
Opened 2021-09-18 14:32 UTC by Shivansh-yadav13

## Proposed Changes
  - added shivanshyadav.json

2021-09-18 15:44 UTC, qwe123coder approved these changes
hey, nice work 🚀 keep making pr like this :)
Congratulations on making your first pull request to our project.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled help wanted for additional opportunities to contribute.
LGTM

2021-09-18 21:27 UTC, voidz7 approved these changes

2021-09-19 05:43 UTC, rohan-kulkarni-25 approved these changes
LGTM 💥

2021-09-20 23:17 UTC, Panquesito7 requested changes

2021-09-20 23:17 UTC, Panquesito7 commented on public/data/shivanshyadav.json
> +  }
Missing an endline.
```suggestion
}

```

2021-09-20 23:17 UTC, Panquesito7 commented on public/data/shivanshyadav.json
> +        "url": "http://twitter.com/_shivansh_13",
```suggestion
        "url": "https://twitter.com/_shivansh_13",
``
`

2021-09-20 23:17 UTC, Panquesito7 commented on public/data/shivanshyadav.json
> +        "url": "http://github.com/Shivansh-yadav13",
```suggestion
        "url": "https://github.com/Shivansh-yadav13",
```

2021-09-21 13:38 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-09-21 13:42 UTC, merged