Added my profile
EddieHubCommunity/LinkFree pull request #2398
Opened 2022-12-14 18:28 UTC by rkshaw20

## Check List (Check all the applicable boxes) 

- [x]  My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-12-14 19:00 UTC, Pradumnasaraf requested changes
Action is failing due to styling. Please fix that.

2022-12-14 19:00 UTC, Pradumnasaraf commented on data/rkshaw20.json
> +    }
```suggestion
    {
      "name": "Open Source Blog",
      "url": "https://hashnode.com/@rajkishorshaw",
      "icon": "hashnode"
    }
```

2022-12-15 00:16 UTC, eddiejaoude approved these changes
Looks good after reformatting the files 👍

2022-12-15 00:16 UTC, merged

2022-12-15 01:31 UTC, rkshaw20 commented
Thanks @eddiejaoude and @Pradumnasaraf for helping me, you guys are awesome 😃!