Create SamuelIgwesi.json
EddieHubCommunity/LinkFree pull request #2427
Opened 2022-12-18 03:46 UTC by SamuelIgwesi

## Check List 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

2022-12-18 09:07 UTC, eddiejaoude approved these changes
Look good 👍

2022-12-18 09:08 UTC, eddiejaoude commented on data/SamuelIgwesi.json
> +      "description": "Started freelancing"
Invalid json, missing `,` here

2022-12-18 09:08 UTC, eddiejaoude requested changes
Looks good, but has a missing `,`

2022-12-19 13:32 UTC, schmelto approved these changes

2022-12-21 02:38 UTC, Panquesito7 requested changes

2022-12-21 02:38 UTC, Panquesito7 commented on data/SamuelIgwesi.json
> +    { "platform": "github", "url": "https://github.com/Samuel_Igwesi" },
The GitHub link seems to be wrong here.
```suggestion
    { "platform": "github", "url": "https://github.com/SamuelIgwesi" },
```

2022-12-21 09:58 UTC, schmelto commented on data/SamuelIgwesi.json
> +    { "platform": "github", "url": "https://github.com/Samuel_Igwesi" },
```suggestion
    { "platform": "github", "url": "https://github.com/SamuelIgwesi" },
```

2022-12-21 20:15 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2022-12-21 20:51 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-22 10:12 UTC, merged