+souhaib
EddieHubCommunity/LinkFree pull request #2448
Opened 2022-12-21 17:21 UTC by souhaibsfaxi

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-12-21 20:47 UTC, Panquesito7 requested changes

2022-12-21 20:47 UTC, Panquesito7 commented on data/souhaibsfaxi.json
> +  "name": "YOUR NAME",
You have to place your name here.

2022-12-21 20:47 UTC, Panquesito7 commented on data/souhaibsfaxi.json
> +      "url": "https://www.eddiejaoude.io/"
I think you should update this link as well.

2022-12-21 20:47 UTC, Panquesito7 commented on data/souhaibsfaxi.json
> +      "url": "https://github.com/YOUR_GITHUB_USERNAME",
Your GitHub username must be specified here.
```suggestion
      "url": "https://github.com/souhaibsfaxi",
```

2023-01-14 21:41 UTC, EmmaDawsonDev commented
How are you doing with the changes requested @souhaibsfaxi ? Let us know if you need any help

2023-01-23 17:42 UTC, Panquesito7 requested changes

2023-01-23 17:42 UTC, Panquesito7 commented on data/souhaibsfaxi.json
> +    { "platform": "github", "url": "https://github.com/souhaibsfaxi" }
Should be `icon`, AFAIK.
```suggestion
    { "icon": "github", "url": "https://github.com/souhaibsfaxi" }
```

2023-01-24 18:54 UTC, EmmaDawsonDev requested changes
You just have a few icon names that need updating

2023-01-24 18:54 UTC, EmmaDawsonDev commented on data/souhaibsfaxi.json
> +    { "platform": "github", "url": "https://github.com/souhaibsfaxi" }
```suggestion
    { "icon": "FaGithub", "url": "https://github.com/souhaibsfaxi" }
```

2023-01-24 18:54 UTC, EmmaDawsonDev commented on data/souhaibsfaxi.json
> +      "icon": "github"
```suggestion
      "icon": "FaGithub"
```

2023-01-24 18:54 UTC, EmmaDawsonDev commented on data/souhaibsfaxi.json
> +      "icon": "dollar",
```suggestion
      "icon": "FaDollarSign",
```

2023-01-31 06:16 UTC, eddiejaoude commented on data/souhaibsfaxi.json
> +  "avatar": "https://github.com/souhaibsfaxi.png",
This is no longer required
```suggestion

```

2023-01-31 06:18 UTC, SaraJaoude approved these changes
looks good

2023-01-31 06:22 UTC, merged