Profile addition
EddieHubCommunity/LinkFree pull request #245
Opened 2021-09-19 06:46 UTC by AbhijithGanesh

Adds my profile to linktree.

2021-09-19 09:58 UTC, rohan-kulkarni-25 requested changes

2021-09-19 09:58 UTC, rohan-kulkarni-25 commented on public/data/AbhijithGanesh.json
> +            "name":"Check my website out",
you can write " Check Out my website " That will look more proper ( just a suggestion )

2021-09-19 09:58 UTC, rohan-kulkarni-25 commented on src/Components/Links.js
> +    tiktok: '#010101',
I think than including all Socials a few will be proper which everyone is using

2021-09-19 09:58 UTC, rohan-kulkarni-25 commented on public/index.html
>      <meta name="theme-color" content="#000000" />
Please check Index.html file once it seems you deleted few lines

2021-09-27 21:54 UTC, eddiejaoude commented on public/index.html
> -      content="Web site created using create-react-app"
We should probably update this rather than delete it

2021-09-27 22:22 UTC, Panquesito7 requested changes
Please see the comments above.
You may also want to re-make this PR as it's outdated and the branch is deleted.

2021-10-02 04:34 UTC, eddiejaoude commented
Looks like this is a duplicate, I will close https://github.com/EddieHubCommunity/LinkFree/blob/main/public/data/AbhijithGanesh.json

2021-10-02 04:34 UTC, closed without merging