Add doni
EddieHubCommunity/LinkFree pull request #246
Opened 2021-09-19 07:06 UTC by doniwirawan

2021-09-19 09:55 UTC, rohan-kulkarni-25 requested changes

2021-09-19 09:55 UTC, rohan-kulkarni-25 commented on public/data/doniwirawan.json
> +
- Please remove this space

2021-09-19 09:55 UTC, rohan-kulkarni-25 commented on public/data/doniwirawan.json
> +
- Please delete the last line ( Empty Space )

2021-09-19 13:53 UTC, aayush89890 approved these changes
Hi @doniwirawan Welcome to the community.

2021-09-20 01:40 UTC, doniwirawan commented
> Hi @doniwirawan Welcome to the community.

thanks brother

2021-09-20 15:33 UTC, Panquesito7 requested changes

2021-09-20 15:33 UTC, Panquesito7 commented on public/data/doniwirawan.json
> +
```suggestion
```

2021-09-20 23:18 UTC, Panquesito7 requested changes

2021-09-20 23:18 UTC, Panquesito7 commented on public/data/doniwirawan.json
> +  }
```suggestion
}
```

2021-09-21 14:02 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-09-21 14:04 UTC, merged

2021-09-22 00:45 UTC, doniwirawan commented
> LGTM 🚀 Thank you for your contribution! 😄👍

thanks