Arshdeep added link
EddieHubCommunity/LinkFree pull request #248
Opened 2021-09-19 12:42 UTC by Arshdeep-0509

profile added using json

2021-09-19 13:40 UTC, aayush89890 requested changes
Hi @Arshdeep-0509 welcome to the community, but we don't make changes in ```package-lock.json``` & ```package.json``` files, please undo those changes and update your PR.

2021-09-20 19:24 UTC, Arshdeep-0509 commented
I have not made  any changes in  package-lock.json .

2021-09-20 19:34 UTC, CodingSpecies commented
> Hi @Arshdeep-0509 welcome to the community, your json file is good but we don't make changes in `package-lock.json` & `package.json` files, please undo those changes and update your PR.

This seems to happen in other prs too @aayush89890 i think every time someone adds something it updates the version in the package lock.json. Thanks

2021-09-20 20:12 UTC, Panquesito7 requested changes

2021-09-20 20:12 UTC, Panquesito7 commented on public/data/Arshdeep-0509.json
> +        "url": "http://github.com/Arshdeep-0509",
```suggestion
        "url": "https://github.com/Arshdeep-0509",
```

2021-09-20 20:12 UTC, Panquesito7 commented on public/data/Arshdeep-0509.json
> +
```suggestion


```

2021-09-21 07:26 UTC, aayush89890 commented
> This seems to happen in other prs too @aayush89890 i think every time someone adds something it updates the version in the package lock.json. Thanks

That's correct @CodingSpecies but one should not commit those changes right?

2021-09-21 14:15 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/248/conflicts). If you need any help with that, let us know in the [**Discord server**](http://discord.eddiehub.org).

2021-09-21 15:12 UTC, CodingSpecies commented
> > This seems to happen in other prs too @aayush89890 i think every time someone adds something it updates the version in the package lock.json. Thanks
> 
> That's correct @CodingSpecies but one should not commit those changes right?

I think when they git add, they should only `git add profilename.json` instead of git add -A. thanks.

2021-09-21 15:41 UTC, aayush89890 commented
> I think when they git add, they should only git add profilename.json instead of git add -A. thanks.

yes that's correct @CodingSpecies

2021-09-27 21:56 UTC, eddiejaoude commented
I will close this PR and manually add your profile data, feel free to update

2021-09-27 21:56 UTC, closed without merging