Kartik khode
EddieHubCommunity/LinkFree pull request #2499
Opened 2022-12-26 13:13 UTC by Kartiklk

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-12-26 13:57 UTC, eddiejaoude approved these changes
Looks good 👍

2022-12-26 14:01 UTC, eddiejaoude commented on data/kartiklk.json
> +      { "icon": "FaLinkedin", "url": "https://www.linkedin.com/in/kartik-khode-32a7a325a/" }
I think you are missing a command (`,`) at the end of this line

```suggestion
      { "icon": "FaLinkedin", "url": "https://www.linkedin.com/in/kartik-khode-32a7a325a/" },
```

2022-12-26 14:02 UTC, eddiejaoude requested changes
Missing comma

2022-12-27 07:48 UTC, Panquesito7 approved these changes
Thanks! 🎉

2022-12-27 09:47 UTC, eddiejaoude approved these changes
Looks good 👍

2022-12-27 09:48 UTC, merged