Profile Addition
EddieHubCommunity/LinkFree pull request #2532
Opened 2022-12-29 07:03 UTC by mohit1607

Addition of new profile mohit1607.

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-12-29 15:08 UTC, senali-d reviewed
Looks great.

2022-12-29 16:27 UTC, eddiejaoude commented on data/mohit1607.json
> +    { "icon": "github", "url": "https://github.com/mohit1607" }
These are not icons, please use icons available https://linkfree.eddiehub.io/icons

2022-12-29 16:28 UTC, eddiejaoude requested changes
Icons need updating, inline comment added

2022-12-30 06:46 UTC, mohit1607 commented
Hi Eddie thanks for reviewing my profile and Now I look forward to solve more issues.

2022-12-30 07:40 UTC, Pradumnasaraf approved these changes

2022-12-30 07:40 UTC, Pradumnasaraf reviewed
Looks good to merge. Thank you for your contribution! :tada:

2022-12-30 08:30 UTC, eddiejaoude approved these changes
Looks good 👍

2022-12-30 08:32 UTC, merged