feat: milestones (#252)
EddieHubCommunity/LinkFree pull request #254
Opened 2021-09-20 01:24 UTC by eddiejaoude

Fixes #252 

<img width="1016" alt="Screenshot 2021-09-20 at 02 22 07" src="https://user-images.githubusercontent.com/624760/133949721-bc84b60f-16c6-429f-a36b-dcfe9f9813b2.png">

2021-09-20 06:01 UTC, schmelto commented
Mobile view is looking not so good. 

![Screenshot_20210920_080019_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/133961931-ac64660d-64e5-45cb-9ce6-fa5b7ac84f8f.jpg)

2021-09-20 06:09 UTC, voidz7 commented
![video](https://user-images.githubusercontent.com/62803658/133962388-86420874-cad1-40d6-a6a7-cb509d2821a5.gif)

Looks good to me ⚡ . We may need to add more docs about adding ur data for milestones ....

2021-09-20 06:10 UTC, Cahllagerfeld commented
I feel like we should sort the milestones descending to the date? What do you think about that?😅

2021-09-20 06:14 UTC, voidz7 commented
> I feel like we should sort the milestones descending to the date (So the newest is on top, and the oldest on the bottom)? What do you think about that?sweat_smile

ig the person who is making their own milestone has the ability to format it descending or ascending  . Right ?

2021-09-20 06:20 UTC, Cahllagerfeld commented
In my opinion we should write a function which sorts the milestones. Imagine the following scenario:
Someone who initally added 5 milestons wants to add another one. When sorting them manually, he has to maybe restructure all milestones so the one that should be inserted fits chronologically.

When adding a function everyone can just add one as the last entry and everything gets done automatically afterwards.
But thats just my opinion, I'm keen on hearing other opinions :D

2021-09-20 06:25 UTC, CodingSpecies commented
I am not sure, but couldn't it be stored in like a data type, array, or object, and then it auto generates the format, into the milestone?

2021-09-20 07:09 UTC, voidz7 commented
> In my opinion we should write a function which sorts the milestones. Imagine the following scenario:
> Someone who initally added 5 milestons wants to add another one. When sorting them manually, they have to maybe restructure all milestones so the one that should be inserted fits chronologically.
> 
> When adding a function everyone can just add one as the last entry and everything gets done automatically afterwards.
> But thats just my opinion, I'm keen on hearing other opinions :D

oo this would be cool then rather worrying about the order u can keep adding your milestones in the json with date and we just have a function which keeps sorting them ! vouch for this .

2021-09-20 08:49 UTC, eddiejaoude commented
Great feedback everyone!!

- mobile: oh we need to fix that
- sorting: I think this is less of an issue, because I am keen to move the data to the API where it the order can be sorted there

2021-09-21 08:34 UTC, eddiejaoude commented
Now it is responsive 🎉 

Larger screens...

<img width="1680" alt="Screenshot 2021-09-21 at 09 33 06" src="https://user-images.githubusercontent.com/624760/134138917-a3879240-66c5-46f6-908c-b408e714edc4.png">


Smaller screens ...

<img width="1680" alt="Screenshot 2021-09-21 at 09 33 14" src="https://user-images.githubusercontent.com/624760/134138946-79ab8bbf-d193-48c1-88a2-6cd86aa81d98.png">

2021-09-21 08:39 UTC, schmelto requested changes
also the links are not working for me

2021-09-21 08:39 UTC, schmelto commented on src/Components/Milestones.js
> +              'https://user-images.githubusercontent.com/624760/114314273-eaae0100-9af1-11eb-955a-4039657fe85a.png')
```suggestion
              'https://github.com/EddieHubCommunity.png')
```

2021-09-26 10:08 UTC, eddiejaoude commented
Going to merge if no more comments 🤓

2021-09-26 10:08 UTC, merged