Link to CLI profile generator added
EddieHubCommunity/LinkFree pull request #2572
Opened 2023-01-01 17:54 UTC by krupalitrivedi

## Fixes Issue

closes #2206 

## Changes proposed

The link to Pradumna's CLI profile generator for Linkfree has been added.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/99717469/210180286-536d5fd1-4bdb-4b6b-85f1-6edc2c91036c.png)

2023-01-01 19:07 UTC, eddiejaoude commented on README.md
> +> **Note** **CLI Profile Generator**: To generate the code for your profile using CLI, visit [Pradumna's Linkfree-CLI profile generator](https://github.com/Pradumnasaraf/LinkFree-CLI)
I think @Pradumnasaraf's project is included in LinkFree, maybe we could also have steps to how to use it and link for further information.

2023-01-01 19:07 UTC, eddiejaoude requested changes
The Changelog and package files I don't think are needed in this PR (check your branch is up to date)

2023-01-01 19:16 UTC, krupalitrivedi commented
Sure, Eddie, let me work on the further changes and make a pull request, feel free to close this one. (I did update my branch before making changes but there seems to be some problem)

2023-01-01 19:20 UTC, eddiejaoude commented
It is up to you if you want to close it and open a new one - you should be able to close it if you wish

2023-01-03 18:55 UTC, krupalitrivedi commented
Closing this PR - will open another one keeping the discussion here in mind.

2023-01-03 18:55 UTC, closed without merging