Suraj added his json file
EddieHubCommunity/LinkFree pull request #259
Opened 2021-09-20 11:09 UTC by suraj-001

## Proposed Changes

  -Added my json file .

2021-09-20 11:28 UTC, schmelto requested changes

2021-09-20 11:28 UTC, schmelto commented on public/data/SurajkAGarwal.json
> +            "url": "https://github.com/suraj-001/LinkFree",
```suggestion
            "url": "https://github.com/suraj-001",
```

2021-09-20 15:38 UTC, Panquesito7 requested changes

2021-09-20 15:38 UTC, Panquesito7 commented on public/data/SurajkAGarwal.json
> +            "name": "Subscribe to my youtube channel",
```suggestion
            "name": "Subscribe to my YouTube channel",
```

2021-09-20 15:38 UTC, Panquesito7 commented on public/data/SurajkAGarwal.json
> +}
Missing an endline.
```suggestion
}

```

2021-09-20 15:38 UTC, Panquesito7 commented on public/data/SurajkAGarwal.json
> +            "url": "https://github.com/suraj-001/LinkFree",
```suggestion
            "url": "https://github.com/suraj-001",
```

2021-09-21 04:59 UTC, rohan-kulkarni-25 reviewed
Please don't commit Package-lock.json

2021-09-21 13:39 UTC, Panquesito7 commented
> Please don't commit Package-lock.json

That's something automatically done by `npm`.

2021-09-21 13:41 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/259/conflicts).

2021-09-21 16:57 UTC, suraj-001 commented on public/data/SurajkAGarwal.json
> +            "name": "Subscribe to my youtube channel",
ok sure

2021-09-21 17:28 UTC, Panquesito7 commented on public/data/SurajkAGarwal.json
> +    "bio": "Coder | PG Student | YT Conten creator|Student of (MCA)NIT Bhopal INDIA,",
```suggestion
    "bio": "Coder | PG Student | YT Conten creator | Student of (MCA)NIT Bhopal INDIA",
```

2021-09-22 14:35 UTC, Panquesito7 requested changes

2021-09-22 14:35 UTC, Panquesito7 commented on public/data/SurajkAGarwal.json
> +    "bio": "Coder | PG Student | YT Conten creator | Student of (MCA)NIT Bhopal INDIA",
```suggestion
    "bio": "Coder | PG Student | YT Content creator | Student of (MCA)NIT Bhopal INDIA",
```

2021-09-22 15:36 UTC, rohan-kulkarni-25 requested changes
- Please don't commit  Package lock json

2021-09-22 15:55 UTC, suraj-001 commented on public/data/SurajkAGarwal.json
> +    "bio": "Coder | PG Student | YT Conten creator | Student of (MCA)NIT Bhopal INDIA",
updated please check

2021-09-22 19:40 UTC, Panquesito7 commented
> * Please don't commit  Package lock json

That's something done by `npm` automatically.

2021-09-22 19:52 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-09-22 19:58 UTC, merged

2021-09-23 02:03 UTC, suraj-001 commented
Hey  after merge my profilr is not reflecting in site there  i tried 
http://linkfree.eddiehub.org/SurajkAGarwal not working plz check and let me know here or on discord server suraj-001

2021-09-24 15:10 UTC, Panquesito7 commented
> Hey after merge my profilr is not reflecting in site there i tried
> http://linkfree.eddiehub.org/SurajkAGarwal not working plz check and let me know here or on discord server suraj-001

I can see it. For me, there are no problems. 🤔