feat: add personal, community and event
EddieHubCommunity/LinkFree pull request #2597
Opened 2023-01-02 17:40 UTC by davideimola

Hi folks,
I would like to add my personal profile, my community profile and the open source event we are organizing

2023-01-02 18:11 UTC, Pradumnasaraf requested changes
Hey, please rename the org JSON file name the same as the one on the GitHub Org name.

```diff
- data/SchrodingerHat.json
+ data/Schrodinger-Hat.json
```

2023-01-02 19:11 UTC, eddiejaoude commented on data/davideimola.json
> +  "name": "Davide Imola",
Ideally yes, but I think it is ok to have them both here in this case, but the downside is one with mismatch GitHub username will block the other

2023-01-02 19:33 UTC, eddiejaoude approved these changes
Looks good 👍

2023-01-02 19:35 UTC, merged

2023-01-06 06:59 UTC, Pradumnasaraf commented
Event looks @davideimola amzing. I will submit a CFP for that :)