created ashishtom.json
EddieHubCommunity/LinkFree pull request #260
Opened 2021-09-20 11:57 UTC by alceil

Fixes #

## Proposed Changes

  -
  -
  -

## Screenshots

2021-09-20 12:21 UTC, schmelto commented on public/data/ashishtom.json
> +
```suggestion
```

2021-09-20 12:22 UTC, schmelto commented on public/data/ashishtom.json
> +        "url": "http://github.com/alceil",
```suggestion
        "url": "https://github.com/alceil",
```

2021-09-20 13:18 UTC, alceil commented on public/data/ashishtom.json
> +        "url": "http://github.com/alceil",
done

2021-09-20 15:02 UTC, aayush89890 approved these changes
Looks Good.

2021-09-20 15:31 UTC, Panquesito7 requested changes

2021-09-20 15:31 UTC, Panquesito7 commented on public/data/ashishtom.json
> +  }
Missing an endline.
```suggestion
}

```

2021-09-20 15:50 UTC, alceil commented on public/data/ashishtom.json
> +  }
done

2021-09-20 16:03 UTC, Panquesito7 requested changes

2021-09-20 16:03 UTC, Panquesito7 commented on public/data/ashishtom.json
> +}
Still missing an endline.
```suggestion
}

```

2021-09-21 02:40 UTC, alceil commented on public/data/ashishtom.json
> +}
done

2021-09-21 02:46 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-09-21 02:47 UTC, merged