create new profile rinshin jalal
EddieHubCommunity/LinkFree pull request #2718
Opened 2023-01-05 18:15 UTC by Rinshin-Jalal

Added a new profile!!

2023-01-05 20:02 UTC, Pradumnasaraf submitted a review, later dismissed
Hey,

Please fix your JSON profile naming. It should be `{your GitHub username}.json` -> `
Rinshin-Jalal.json`

If you need any help feel free to ask.

2023-01-06 20:25 UTC, senali-d commented on data/rinshin.json
> +  "avatar": "https://avatars.githubusercontent.com/u/88965873?v=4",
Use short image link.
```suggestion
  "avatar": "https://github.com/Rinshin-Jalal.png",
```

2023-01-09 15:47 UTC, senali-d requested changes
@Rinshin-Jalal Revert the changes in `package.json` and `package.lock.json` files

2023-01-10 06:59 UTC, eddiejaoude commented
It looks like you have used `npm install` instead of `npm ci` from the docs, this causes the generated files to be updated but these should not be committed without specific changes to them.
https://linkfree.eddiehub.io/docs/environments/local-development

Please remove these changes with:

- `git checkout main -- package.json`
- `git checkout main -- package-lock.json`

It is always best to check file changed with `git status -s` before doing a commit and never use `.` in your git commands as this will include files you may not want.

Any questions come and ask in the EddieHub Discord http://discord.eddiehub.org

2023-01-14 21:44 UTC, EmmaDawsonDev commented
Do you need any help with the requested changes @Rinshin-Jalal ?

2023-01-31 06:50 UTC, eddiejaoude commented
I will fix in a temporary branch

2023-01-31 06:53 UTC, merged