data:theselaw
EddieHubCommunity/LinkFree pull request #2724
Opened 2023-01-05 19:08 UTC by theselaw

added my username.json file

2023-01-05 19:50 UTC, Pradumnasaraf requested changes
Hey,

Please remove the extra comma `,`

2023-01-05 19:50 UTC, Pradumnasaraf commented on data/theselaw.json
> +    },
```suggestion
    }
```

2023-01-07 12:36 UTC, Pradumnasaraf requested changes
Hey,

please revert the changes in `package-lock.json` and `package.json` we don't need them in profile addition

2023-01-08 08:25 UTC, eddiejaoude commented
If you have any questions, you can come and ask in the EddieHub Discord http://discord.eddiehub.org

2023-01-14 21:45 UTC, EmmaDawsonDev commented
Do you need any help with the requested changes @theselaw ?

2023-01-31 11:48 UTC, SaraJaoude approved these changes
looks good with fix in temporary branch

2023-01-31 11:49 UTC, merged