'data: JoshuaEdo'
EddieHubCommunity/LinkFree pull request #2726
Opened 2023-01-05 19:26 UTC by joshuaedo

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-05 19:35 UTC, Pradumnasaraf reviewed
Hey, 
Are you sure you don't want to add any links?

In case you want to add them, here is the docs - https://linkfree.eddiehub.io/docs/how-to-guides/links

2023-01-05 19:37 UTC, Pradumnasaraf submitted a review, later dismissed
Also, please fix your JSON profile naming. The casing is wrong, It should be `joshuaedo.json`. 

If you need any help feel free to ask.

2023-01-05 19:40 UTC, dan-mba requested changes
The case of the filename should match the case of your GitHub user id.

2023-01-05 19:40 UTC, dan-mba commented on data/JoshuaEdo.json
> +  "avatar": "https://github.com/joshuaedo.png",
Remove the comma at the end of the line

2023-01-14 21:46 UTC, EmmaDawsonDev commented
Do you need any help with the requested changes @joshuaedo ?

2023-01-15 11:48 UTC, joshuaedo commented
## Overview of comments & changes requested ##
- [x] [Addition of links](https://github.com/EddieHubCommunity/LinkFree/pull/2726#pullrequestreview-1237939471)
- [x]  [Fixing the JSON profile naming](https://github.com/EddieHubCommunity/LinkFree/pull/2726#pullrequestreview-1237942394)
- [x]  [Removal of comma](https://github.com/EddieHubCommunity/LinkFree/pull/2726#discussion_r1062830805)
- [x]  [Help with changes](https://github.com/EddieHubCommunity/LinkFree/pull/2726#issuecomment-1382929229)

## Breakdown of changes addressed ##
### 1. Addition of links (Line 8 - 24) @Pradumnasaraf  ###
```diff
+ "links": [
+    {
+       "name": "Follow me on Twitter",
+       "url": "https://twitter.com/Thegr8Joshua",
+       "icon": "FaTwitter"
+     },
+     {
+       "name": "Follow me on LinkedIn",
+       "url": "https://www.linkedin.com/in/joshuaedo",
+       "icon": "FaLinkedIn"
+     },
+      {
+       "name": "Follow me on GitHub",
+       "url": "https://github.com/joshuaedo",
+       "icon": "FaGitHub"
+     }
+   ]
```
### 2. Fixing the JSON profile naming @Pradumnasaraf  & @dan-mba ###
```diff
- JoshuaEdo.json
+ joshuaedo.json
```
### 3. Removal of comma (Line 6) @dan-mba   ###
```diff
- "avatar": "https://github.com/joshuaedo.png",
+ "avatar": "https://github.com/joshuaedo.png"
```
### 4. Help with changes @EmmaDawsonDev   ###
Thanks for offering but I've already addressed the changes. If you find anything else that you think requires improvement, I'd appreciate it if you requested it to be changed.

#### Sorry for taking so long to reply, I was busy with school exams.

2023-01-15 12:17 UTC, dan-mba requested changes
To fix the failing JSON check you need to:
1. Add a `,` at the end of line 6
2. Move the `}` on line 7 to after the links section ends on line 24

2023-01-15 13:55 UTC, dan-mba approved these changes
Looks good to me

2023-01-15 14:53 UTC, EmmaDawsonDev approved these changes
Looks good! Thanks for contributing!

2023-01-15 14:59 UTC, merged