Create KiranJungGurung.json
EddieHubCommunity/LinkFree pull request #2746
Opened 2023-01-06 05:58 UTC by KiranJungGurung

2023-01-06 06:04 UTC, KiranJungGurung commented
Thank you Eddie!!!

2023-01-06 06:15 UTC, fidelmak commented
Thank you. I will also love to contribute more

2023-01-06 21:44 UTC, eddiejaoude commented
@KiranJungGurung did you mean to close this Pull Request?

I think it looked ok, you just need to remove the `'` at the beginning of your file

From `'data/KiranJungGurung.json` to this `data/KiranJungGurung.json`

2023-01-07 03:52 UTC, KiranJungGurung commented
Done Eddie. Thank you so much.

2023-01-07 03:54 UTC, KiranJungGurung commented
Hello Eddie, I want to learn more about open source, how can I contribute more? I am ready to invest my time on this. Thank you.

2023-01-07 19:41 UTC, Njong392 submitted a review, later dismissed
Looks amazing :confetti_ball: Thank you for contributing!

2023-01-07 19:46 UTC, Njong392 commented
> Hello Eddie, I want to learn more about open source, how can I contribute more? I am ready to invest my time on this. Thank you.

Hello there! You can check out EddieHub's official page [here](https://www.eddiehub.org/) (and also the main page of this github organization) for info about our open-source community, and a link to our super discord community. This organization also has many projects with different tech stacks that you can check out if you want to get started with contributing! The awesome people in our discord server would love to hear any questions :+1:

2023-01-08 08:59 UTC, eddiejaoude commented
Great collaboration everyone 🎉  Yes come and geek out with us on open source in the EddieHub community (thanks @Njong392 )

2023-01-08 09:00 UTC, eddiejaoude commented on data/KiranJungGurung.json
> +      "icon": "FaLinkedIn",
This trailing comma `,` is not required

2023-01-08 09:00 UTC, eddiejaoude commented on data/KiranJungGurung.json
> +      "icon": "FaTwitter",
This trailing comma `,` is not required

2023-01-09 11:42 UTC, KiranJungGurung commented
> here

Thanks. I will definitely check out.

2023-01-15 18:09 UTC, EmmaDawsonDev commented
Hi @KiranJungGurung do you need any help removing the trailing commas?

2023-01-17 02:13 UTC, KiranJungGurung commented
Yes. I do @EmmaDawsonDev

2023-01-19 11:16 UTC, kumarsonsoff3 requested changes
You just need to hit <kbd>Commit suggestion</kbd> button in the below 2 comments to make the changes or you can remove these extra commas from line no `11` & `17`.

Hope this help :)

2023-01-20 01:27 UTC, KiranJungGurung commented
Thank you @kumarsonsoff3

2023-01-20 04:03 UTC, Panquesito7 requested changes

2023-01-20 04:03 UTC, Panquesito7 commented on data/KiranJungGurung.json
> +
There are some unneeded extra lines here.
```suggestion
```

2023-01-20 04:49 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-20 05:35 UTC, kumarsonsoff3 approved these changes
Looks good to merge. Great collaboration Everyone! 🎉

<p align="center"> <img src="https://user-images.githubusercontent.com/88786642/213432145-81fb3e2f-8033-4233-9dd7-52e8b4f29629.png" /></p>

2023-01-20 05:35 UTC, merged