data:srijoy-paul
EddieHubCommunity/LinkFree pull request #2769
Opened 2023-01-06 13:13 UTC by srijoy-paul

## Changes proposed

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/77974192/211019023-7f734578-5b5b-44d5-8d3e-3393c16391ea.png)

2023-01-06 13:46 UTC, dan-mba requested changes
Please add commas between each object in the links section

2023-01-06 15:53 UTC, dan-mba submitted a review, later dismissed
Looks good to me

2023-01-06 17:01 UTC, kumarsonsoff3 requested changes

2023-01-06 17:01 UTC, kumarsonsoff3 commented on data/srijoy-paul.json
> +      "url": "https://www.youtube.com/decentcodder4814",
Please fix the broken URL as suggested. Since it shows `Error: 404`🛠

```suggestion
      "url": "https://www.youtube.com/@decentcodder4814",
```

2023-01-10 12:56 UTC, srijoy-paul commented
@kumarsonsoff3 Updated

2023-01-10 14:23 UTC, kumarsonsoff3 approved these changes
Looks Good, Thanks! 👍

2023-01-10 14:24 UTC, merged