Data : KrishChopra22 ✅
EddieHubCommunity/LinkFree pull request #2780
Opened 2023-01-06 18:41 UTC by KrishChopra22

One more contribution to EddieHub Community! 🥳
Created linkfree profile - the open source project ✔

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-01-06 18:48 UTC, dan-mba requested changes
Remove the commas on lines 11, 53, & 79

2023-01-06 18:54 UTC, dan-mba approved these changes
Looks good to me

2023-01-06 18:56 UTC, KrishChopra22 commented
Thanks for reviewing 😊

2023-01-06 22:06 UTC, Panquesito7 requested changes

2023-01-06 22:06 UTC, Panquesito7 commented on data/KrishChopra22.json
> +  "avatar": "https://user-images.githubusercontent.com/77012237/211071479-62ce9139-97e3-4314-844e-605575f69fb8.png",
It's best to use this link as it's shorter and updates automatically.
```suggestion
  "avatar": "https://github.com/KrishChopra22.png",
```

2023-01-07 12:27 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-01-07 12:28 UTC, merged

2023-01-07 15:49 UTC, KrishChopra22 commented
I updated my github profile pic recently, but this didn't reflect to my LinkFree.
How can it be updated dynamically?

2023-01-07 16:00 UTC, dan-mba commented
> I updated my github profile pic recently, but this didn't reflect to my LinkFree. How can it be updated dynamically?

LinkFree caches avatar images for 24 hours. Check back in a day & if it still hasn't changed, open an issue or ask for help on EddieHub discord.