data: BruceWangyq
EddieHubCommunity/LinkFree pull request #2793
Opened 2023-01-07 00:35 UTC by BruceWangyq

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-07 02:46 UTC, Panquesito7 requested changes

2023-01-07 02:46 UTC, Panquesito7 commented on data/BruceWangyq.json
> +      "url": "http://eddiejaoude.io",
You might want to update this link.

2023-01-07 03:50 UTC, BruceWangyq commented
This should be fixed! Thank you for pointing that out!

2023-01-07 13:09 UTC, md-abid-hussain approved these changes
Looks good to me

2023-01-07 17:35 UTC, kumarsonsoff3 approved these changes
Looks good to me! 👍

2023-01-08 08:37 UTC, eddiejaoude commented
Great collaboration 👍

2023-01-08 08:37 UTC, merged

2023-01-08 20:47 UTC, BruceWangyq commented
Thank you so much for your work, guys~ It looks awesome!

2023-01-08 21:02 UTC, eddiejaoude commented
Don't forget you can also add more information to your profile like
- events
- testimonials
- milestones 
with more features coming soon