Add Arsheel Sheikh
EddieHubCommunity/LinkFree pull request #285
Opened 2021-09-21 22:23 UTC by arsheelsheikh

2021-09-21 23:22 UTC, Panquesito7 requested changes

2021-09-21 23:22 UTC, Panquesito7 commented on public/data/arsheelsheikh.json
> +    "bio": "Currently pursing Bachelor of Engineering in CSE from SVPCET, I am tech and open source enthusiast",
```suggestion
    "bio": "Currently pursuing Bachelor of Engineering in CSE from SVPCET || Tech and open source enthusiast",
```

2021-09-21 23:22 UTC, Panquesito7 commented on public/data/arsheelsheikh.json
> +  }
Missing an endline.
```suggestion
}

```

2021-09-22 01:11 UTC, arsheelsheikh commented
Thanks for the review @Panquesito7

2021-09-22 02:41 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-09-22 02:50 UTC, merged