Create new profile
EddieHubCommunity/LinkFree pull request #2853
Opened 2023-01-08 10:22 UTC by david-kariuki

Create a new profile for David Kariuki [David Kariuki - Github](https://www.github.com/david-kariuki)

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [X ] My change requires changes to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

2023-01-08 10:34 UTC, Njong392 approved these changes
Looks great! Thank you for contributing :tada:

2023-01-08 13:06 UTC, Njong392 requested changes

2023-01-08 13:06 UTC, Njong392 commented on data/david-kariuki.json
> +   "tags":[
You could move the `tags` section here up directly before the `links` part.

2023-01-09 12:08 UTC, eddiejaoude approved these changes
Looks good 👍 

Great collaboration 💯

2023-01-09 12:08 UTC, merged

2023-01-10 07:52 UTC, david-kariuki commented
Thank you