data:shivaabhishek07
EddieHubCommunity/LinkFree pull request #2860
Opened 2023-01-08 11:22 UTC by shivaabhishek07

## Changes proposed
- I have created my own linkfree profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-01-08 11:26 UTC, Aadarsh805 requested changes
missing commas after every link object

2023-01-08 11:27 UTC, Aadarsh805 commented on data/shivaabhishek07.json
> +    }
```
{
  "name": "Shiva Abhishek",
  "displayStatsPublic": true,
  "type": "personal",
  "bio": "Intrested in DevOps | Open Source",
  "avatar": "https://github.com/shivaabhishek07.png",
  "links": [
    {
      "name": "Twitter",
      "url": "https://twitter.com/shivaabhishek71",
      "icon": "FaTwitter"
    },
    {
      "name": "Github",
      "url": "https://github.com/shivaabhishek07",
      "icon": "FaGithub"
    },
    {
      "name": "LinkedIn",
      "url": "www.linkedin.com/in/shivaabhishek71",
      "icon": "FaLinkedin"
    },
    {
      "name": "Blogs",
      "url": "https://shiva71.hashnode.dev/",
      "icon": "SiHashnode"
    }
  ]
}
```
Should be like this

2023-01-08 11:29 UTC, Aadarsh805 commented
@shivaabhishek07 and your LinkedIn profile link is wrong, it should be `https://www.linkedin.com/in/shivaabhishek71/`

2023-01-08 11:30 UTC, Aadarsh805 commented on data/shivaabhishek07.json
> +      "url": "www.linkedin.com/in/shivaabhishek71",
LinkedIn URL should be `https://www.linkedin.com/in/shivaabhishek71`

2023-01-08 11:36 UTC, Aadarsh805 approved these changes
All good  👍

2023-01-08 14:33 UTC, Aadarsh805 commented on data/shivaabhishek07.json
>      }
another comma missing here

2023-01-08 14:33 UTC, Aadarsh805 requested changes

2023-01-08 14:33 UTC, Aadarsh805 commented on data/shivaabhishek07.json
> +    },
and this comma must be removed

2023-01-09 08:31 UTC, Aadarsh805 approved these changes
All good here 👍

2023-01-09 15:19 UTC, eddiejaoude approved these changes
Looks good 👍

2023-01-09 15:20 UTC, merged