data:arpitghura
EddieHubCommunity/LinkFree pull request #2882
Opened 2023-01-08 16:39 UTC by arpitghura

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-08 22:24 UTC, amandamartin-dev requested changes

2023-01-08 22:24 UTC, amandamartin-dev commented on data/arpitghura.json
> +  "events": [
Events live in a slightly different location per the documentation here https://linkfree.eddiehub.io/docs/how-to-guides/events

Take a look and move the events portion into a separate file and you should be good here. Let us know if anything does not make sense

2023-01-09 13:53 UTC, arpitghura commented
I have done the required changes @amandamartin-dev

2023-01-09 20:40 UTC, Panquesito7 requested changes

2023-01-09 20:40 UTC, Panquesito7 commented on data/arpitghura/events/2022-12-18-devfest.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-01-10 13:05 UTC, amandamartin-dev approved these changes

2023-01-10 13:05 UTC, amandamartin-dev commented
checked my request, thanks for moving events to the new file.  Looks good!

2023-01-10 16:08 UTC, Panquesito7 approved these changes

2023-01-11 21:36 UTC, eddiejaoude approved these changes
Great collaboration 👍

2023-01-11 21:36 UTC, merged