data:atanda0x
EddieHubCommunity/LinkFree pull request #2910
Opened 2023-01-09 04:09 UTC by atanda0x

2023-01-09 05:31 UTC, Njong392 approved these changes
Looks great! :100: Thank you for contributing!

2023-01-15 18:40 UTC, EmmaDawsonDev reviewed
Hi @atanda0x this PR is almost ready to merge. Let us know if you need any help making the requested changes.

2023-02-04 06:24 UTC, priyankarpal approved these changes

2023-02-04 06:24 UTC, priyankarpal commented on data/atanda0x.json
> +      "icon": "FaLinkedIn"
change the icon to `FaLinkedin`

2023-02-04 06:24 UTC, priyankarpal commented on data/atanda0x.json
> +    },
Delete the ","

2023-02-04 06:25 UTC, priyankarpal requested changes
Change these

2023-02-07 07:45 UTC, SaraJaoude commented
> Change these

@priyankarpal please try to be more friendly with your comments, it will scare people away from open source and our project

2023-02-07 07:46 UTC, SaraJaoude commented
I will fix via a temporary branch and then merge into `main`

2023-02-07 07:46 UTC, merged