Create KrishJaiswal.json
EddieHubCommunity/LinkFree pull request #2926
Opened 2023-01-09 10:16 UTC by KrishJ4856

Add Krish's LinkFree Profile

2023-01-09 10:39 UTC, Aadarsh805 requested changes

2023-01-09 10:39 UTC, Aadarsh805 commented on KrishJaiswal.json
> +      "icon": "FaGitHub"
change icon use this `FaGithub`

2023-01-09 10:39 UTC, Aadarsh805 commented on KrishJaiswal.json
> +      "icon": "FaHashnode"
change this to `SiHashnode`

2023-01-09 10:41 UTC, Aadarsh805 commented
@KrishJ4856 Please fix the file name. It should be {your GitHub username}.json -> KrishJ4856.json

2023-01-09 11:19 UTC, dan-mba requested changes
Please move your profile to the data directory

2023-01-09 12:25 UTC, KrishJ4856 commented
@Aadarsh805 @dan-mba I did the changes as told. Is it ok now?

2023-01-09 12:32 UTC, dan-mba requested changes
Please change your avatar to `https://github.com/KrishJ4856.png`.
This will redirect to the URL you have, but will continue working if you change your profile url

2023-01-09 12:53 UTC, KrishJ4856 commented
Done

2023-01-09 12:54 UTC, dan-mba approved these changes
Looks good to me

2023-01-09 12:56 UTC, KrishJ4856 commented
Thanks for your time!

2023-01-09 20:00 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-10 07:42 UTC, eddiejaoude approved these changes
Looks good 👍 

Great collaboration 💪 

You can also join us in the EddieHub Discord http://discord.eddiehub.org

2023-01-10 07:43 UTC, merged