Feat: Added my json data file
EddieHubCommunity/LinkFree pull request #2928
Opened 2023-01-09 11:42 UTC by ScottDeev

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-09 12:02 UTC, dan-mba requested changes
Please change your filename to match the case of your GitHub ID.
`data/ScottDeev.json`

2023-01-09 12:10 UTC, dan-mba submitted a review, later dismissed
Looks good to me

2023-01-09 12:10 UTC, ScottDeev commented
> Please change your filename to match the case of your GitHub ID. `data/ScottDeev.json`

Done

2023-01-09 19:10 UTC, Panquesito7 commented on data/ScottDeev.json
> +      "url": "https://github.com/scottDeev" ,
There's an extra space here (not sure if it'll get fixed automatically).
```suggestion
      "url": "https://github.com/scottDeev",
```

2023-01-10 07:40 UTC, eddiejaoude approved these changes
Looks good 👍 

Great collaboration 💪 

You can also join us in the EddieHub Discord http://discord.eddiehub.org

2023-01-10 07:41 UTC, merged

2023-01-10 09:17 UTC, ScottDeev commented
> Looks good 👍
> 
> Great collaboration 💪
> 
> You can also join us in the EddieHub Discord http://discord.eddiehub.org

Thanks @eddiejaoude. 

Will be joining the Discord right away!