Created Rajeshds.json
EddieHubCommunity/LinkFree pull request #2934
Opened 2023-01-09 14:16 UTC by Rajeshds20

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/104376917/211328632-151588d0-84be-4b0b-a117-94a5a9433c42.png)
![image](https://user-images.githubusercontent.com/104376917/211328668-885ec37e-fb0b-4b5e-b5b4-bc9de7bd72b7.png)

## Note to reviewers

2023-01-09 14:29 UTC, Aadarsh805 commented on data/Rajeshds.json
> +  "avatar": "https://avatars.githubusercontent.com/u/104376917?s=400&u=932affed6d49d8afa5a12ebf2cf9b723f3db51eb&v=4",
use this for the avatar link `https://github.com/Rajeshds20.png`

2023-01-09 14:29 UTC, Aadarsh805 commented on data/Rajeshds.json
> +    }
missing commas everywhere where each link object

2023-01-09 14:29 UTC, Aadarsh805 commented on data/Rajeshds.json
> +      "icon": "faLinkedin"
this icon has a typo it should be `FaLinkedin`

2023-01-09 14:30 UTC, Aadarsh805 commented on data/Rajeshds.json
> +      "url": "https://www.instagram.com/dsrajesh20",
this link is also wrong

2023-01-09 15:59 UTC, Aadarsh805 requested changes

2023-01-09 15:59 UTC, Aadarsh805 commented on data/Rajeshds.json
> +  "avatar": "https://www.github.com/rajeshds20.png",
the avatar link is still wrong it should be `https://github.com/rajeshds20.png` without the `www`

2023-01-09 15:59 UTC, Aadarsh805 commented on data/Rajeshds.json
> +      "icon": "FaHashnode"
This Hashnode icon doesn't work use this instead `SiHashnode`

2023-01-09 15:59 UTC, Aadarsh805 commented on data/Rajeshds.json
>        "url": "dsrajesh71@gmail.com",
for email use this `FaEnvelope`

2023-01-09 15:59 UTC, Aadarsh805 commented on data/Rajeshds.json
>        "icon": "FaCodechef"
for codechef use this `SiCodechef`

2023-01-09 16:26 UTC, Aadarsh805 requested changes

2023-01-09 16:26 UTC, Aadarsh805 commented on data/Rajeshds.json
> +      "url": "dsrajesh71@gmail.com",
one more thing, This should be a `mailto` link here
change this URL to `mailto:dsrajesh71@gmail.com`

2023-01-09 16:49 UTC, Aadarsh805 approved these changes
Alright, everything seems good now
Great Job 👍

2023-01-09 22:01 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-10 07:52 UTC, eddiejaoude commented
Looks good 👍 

Great collaboration 💪 

You can also join us in the EddieHub Discord http://discord.eddiehub.org

2023-01-10 07:52 UTC, merged