data: nitishkumar07
EddieHubCommunity/LinkFree pull request #2937
Opened 2023-01-09 14:34 UTC by nitishkumar07

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
![screenshot1](https://user-images.githubusercontent.com/70712427/211332600-3a54a406-3098-446e-bcff-ba83d94aba43.png)

## Note to reviewers

2023-01-09 20:15 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-10 07:46 UTC, eddiejaoude commented on data/nitishkumar07.json
> +      "icon": "faLinkedin"
The icon needs to be `FaLinkedin`, you can check available icons here https://linkfree.eddiehub.io/icons in the docs

2023-01-10 07:46 UTC, eddiejaoude requested changes
Icon used is not valid

2023-01-10 08:10 UTC, nitishkumar07 commented
I have done the requested changes @eddiejaoude

2023-01-10 15:20 UTC, Panquesito7 approved these changes

2023-01-11 20:56 UTC, eddiejaoude approved these changes

2023-01-11 20:56 UTC, merged