Imhimansu28 patch 1
EddieHubCommunity/LinkFree pull request #3019
Opened 2023-01-10 07:47 UTC by imhimansu28

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-10 08:05 UTC, ChinmayMhatre requested changes
Please rename the json file in the data directory to your github username. Remove the one that is not in the data folder

2023-01-10 08:05 UTC, ChinmayMhatre commented on himanshu.json
> +  "type": "personal",
Please remove this file from the PR.

2023-01-10 08:28 UTC, imhimansu28 commented on himanshu.json
> +  "type": "personal",
ok Done

2023-01-10 09:55 UTC, ChinmayMhatre approved these changes
left some comments

2023-01-10 09:55 UTC, ChinmayMhatre commented on data/himanshu.json
> +      "url": "https://github.com/imhimansu28/",
Rename the file to imhimansu28.json

2023-01-10 11:44 UTC, ChinmayMhatre approved these changes
LGTM!

2023-01-10 14:14 UTC, swagataroy30 commented on data/imhimansu28.json
> +  ],
Remove the comma on line 23.

2023-01-11 05:07 UTC, closed without merging

2023-01-11 06:00 UTC, ChinmayMhatre commented
Has this been merged in some other PR? @imhimansu28

2023-01-11 07:37 UTC, imhimansu28 commented
Under review