added adityatheoctocatdev to the list
EddieHubCommunity/LinkFree pull request #311
Opened 2021-09-25 16:30 UTC by adityatheoctocatdev

2021-09-25 16:54 UTC, rohan-kulkarni-25 requested changes

2021-09-25 16:54 UTC, rohan-kulkarni-25 commented on public/data/adityatheoctocatdev.json
> +      "url": "http://github.com/adityatheoctocatdev",
- Please make `https` to  Github URL

2021-09-25 16:54 UTC, rohan-kulkarni-25 commented on public/data/adityatheoctocatdev.json
> +      "url": "http://twitter.com/adptheoctcatdev",
- Please make `https` to twitter URL

2021-09-26 02:14 UTC, Panquesito7 requested changes

2021-09-26 02:14 UTC, Panquesito7 commented on public/data/adityatheoctocatdev.json
> +      "url": "http://github.com/adityatheoctocatdev",
```suggestion
      "url": "https://github.com/adityatheoctocatdev",
```

2021-09-26 02:14 UTC, Panquesito7 commented on public/data/adityatheoctocatdev.json
> +  "bio": "DevRel at @thesemicolondevs 🥑·",
```suggestion
  "bio": "DevRel at @thesemicolondevs 🥑",
```

2021-09-26 02:14 UTC, Panquesito7 commented on public/data/adityatheoctocatdev.json
> +      "url": "http://twitter.com/adptheoctcatdev",
```suggestion
      "url": "https://twitter.com/adptheoctcatdev",
```

2021-09-26 05:00 UTC, niteshseram approved these changes
LGTM

2021-09-26 14:49 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍 
Thanks for reviewing this pull request, folks! 🙂

2021-09-26 14:51 UTC, merged