Added filter to show free and paid events
EddieHubCommunity/LinkFree pull request #3110
Opened 2023-01-10 15:53 UTC by shyam0705

## Fixes Issue
Closes #2901 

## Changes proposed 

1)Added filter to show all free and paid events.
2)Modified documentation to suggest adding the `startingFrom` field in events 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

UI:-
![UI](https://user-images.githubusercontent.com/72148710/211597110-72383073-2cf9-4318-a277-c551b3428230.jpg)
Modified events for testing purpose:-
![e1](https://user-images.githubusercontent.com/72148710/211597918-5a0a65a9-a4c6-458b-a302-52aad5446f77.jpg)
![e2](https://user-images.githubusercontent.com/72148710/211597952-8a15949d-9b70-497c-921f-91d0f4a3c8b7.jpg)

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/3110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-01-11 21:19 UTC, eddiejaoude commented on pages/docs/how-to-guides/events.mdx
> +3. This `json` file will contain one object for the event and must have seven fields, `startingFrom`,`isVirtual`and/or`isInPerson`, `color`, `name`, `description`, `date`and`url`, which will look lik
```suggestion
3. This `json` file will contain one object for the event and must have seven fields, `startingFrom`, `isVirtual` and/or `isInPerson`, `color`, `name`, `description`, `date`and`url`, which will look like this:
```

2023-01-11 21:19 UTC, eddiejaoude commented on pages/docs/how-to-guides/events.mdx
> +  "startingFrom":0,
```suggestion
  "startingFrom": 0,
```

2023-01-11 21:20 UTC, eddiejaoude requested changes
Looks good, I think the field should be more descriptive, something like ...

```js
price: {
   startingFrom: 0
}
```

2023-01-12 02:51 UTC, shyam0705 commented
> Looks good, I think the field should be more descriptive, something like ...
> 
> ```js
> price: {
>    startingFrom: 0
> }
> ```

Thanks @eddiejaoude, I will make changes soon.

2023-01-12 10:35 UTC, eddiejaoude commented
Thanks for making the changes 👍  During testing, I got this error on the user profile page...

<img width="1019" alt="Screenshot 2023-01-12 at 10 35 15" src="https://user-images.githubusercontent.com/624760/212044470-1cc6cecb-159d-4c9c-a6b9-c91b620745b9.png">

2023-01-12 10:36 UTC, eddiejaoude commented
Also please update `main` into this branch to reduce any future conflicts

2023-01-17 10:18 UTC, eddiejaoude commented
> Can you check now? I'm sorry; I completely missed adding free and paid categories in the user event tab.

no problem, these things happen to everyone

These changes are going to have challenges with another PR https://github.com/EddieHubCommunity/LinkFree/pull/3125

I think the extra filter is a good idea, but not sure how to display it so it doesn't take up too much space on the page 🤔

2023-01-17 14:54 UTC, shyam0705 commented
> > Can you check now? I'm sorry; I completely missed adding free and paid categories in the user event tab.
> 
> no problem, these things happen to everyone
> 
> These changes are going to have challenges with another PR #3125
> 
> I think the extra filter is a good idea, but not sure how to display it, so it doesn't take up too much space on the page 🤔

I guess we can modify @Aadarsh805  design to include the following and previous icons. We can have a design like pagination.

2023-02-05 06:17 UTC, shyam0705 commented
> @eddiejaoude and @shyam0705, I noticed this has stalled, can we pick it back up? I saw the comment about the filters but we could break that part out into a separate issue. wdyt?

@amandamartin-dev  sorry, I was busy due to some personal reasons last week. will pick this back. I am thinking about creating a separate issue to display filters as we add more filters in future.

2023-02-12 16:09 UTC, closed without merging