data:ShyamTawli
EddieHubCommunity/LinkFree pull request #3122
Opened 2023-01-10 16:42 UTC by shyamtawli

2023-01-10 16:48 UTC, Panquesito7 requested changes
Your filename is missing `.json` at the end. Without this, your profile won't be added properly.

2023-01-10 17:02 UTC, shyamtawli commented
@Panquesito7  how can i update on current branch ?

2023-01-10 19:00 UTC, Aadarsh805 commented
@shyamtawli your username must match the file name, make it `shyamtawli.json`

2023-01-11 15:04 UTC, Panquesito7 requested changes

2023-01-11 15:04 UTC, Panquesito7 commented on data/shyamtawli.json
> +    }
Missing comma.
```suggestion
    },
```

2023-01-11 15:04 UTC, Panquesito7 commented on data/shyamtawli.json
> +    }
```suggestion
    },
```

2023-01-11 15:04 UTC, Panquesito7 commented on data/shyamtawli.json
> +    }
```suggestion
    },
```

2023-01-12 00:48 UTC, eddiejaoude approved these changes
Looks good 👍  Great collaboration 💪

2023-01-12 00:49 UTC, merged