data: ShivaRapolu01
EddieHubCommunity/LinkFree pull request #3132
Opened 2023-01-10 19:31 UTC by ShivaRapolu01

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-10 19:38 UTC, Njong392 requested changes
Thank you for contributing to LinkFree! :tada: Please take a look at the suggested changes I've made.

2023-01-10 19:38 UTC, Njong392 commented on data/ShivaRapolu01.json
> +  ],
Whoops. Looks like there is a trailing comma here 
```suggestion
  ]
```

2023-01-10 19:38 UTC, Njong392 commented on data/ShivaRapolu01.json
> +      "icon": "DiOpensource",
Unfortunately, I cannot find the icon `DiOpensource` in the docs. There is a section there that lists available icons.

2023-01-11 04:45 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2023-01-11 21:56 UTC, merged