data:olatocode
EddieHubCommunity/LinkFree pull request #3143
Opened 2023-01-11 08:16 UTC by olatocode

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-11 09:58 UTC, Rohith-JN requested changes
Missing a `d` in `https://github.com/olatocoe.png`

2023-01-11 13:04 UTC, Rohith-JN requested changes
[olatocoed](https://github.com/olatocoed.png) doesn't exist, change it to `https://github.com/olatocode.png`

2023-01-15 18:52 UTC, EmmaDawsonDev requested changes
There's just a small typo to fix in your avatar link, then this is good to merge.

2023-01-15 18:52 UTC, EmmaDawsonDev commented on data/olatocode.json
> +  "avatar": "https://github.com/olatocoed.png",
```suggestion
  "avatar": "https://github.com/olatocode.png",
```

2023-02-09 04:30 UTC, merged