data:Deathqsd
EddieHubCommunity/LinkFree pull request #3174
Opened 2023-01-11 17:07 UTC by Deathqsd

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-11 17:35 UTC, kumarsonsoff3 requested changes

2023-01-11 17:35 UTC, kumarsonsoff3 commented on Deathqsd.json
> +      "url": "https://twitter.com/SaraJaoude",
Please update it with your Twitter profile link. You might forget to update it! 🛠

```suggestion
      "url": "https://twitter.com/deathqsd",
```

2023-01-11 17:36 UTC, dan-mba requested changes
Please move your profile to the data directory

2023-01-12 23:27 UTC, closed without merging

2023-01-12 23:34 UTC, Deathqsd commented
please delete my pull request