data:Bharath-V26
EddieHubCommunity/LinkFree pull request #3177
Opened 2023-01-11 17:19 UTC by Bharath-V26

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-11 17:24 UTC, Bharath-V26 commented
This is the first file I'm creating

2023-01-11 17:27 UTC, Aadarsh805 requested changes

2023-01-11 17:27 UTC, Aadarsh805 commented on data/Bharath-V26.json
> +  "avatar": "https://github.com/Bharath_V26.png",
the avatar URL should be `https://github.com/Bharath-V26.png`

2023-01-15 18:54 UTC, EmmaDawsonDev submitted a review, later dismissed
This is almost ready to go, just need to correct your avatar link. Let us know if you need any help.

2023-01-19 23:06 UTC, eddiejaoude commented on data/Bharath-V26.json
> +  "avatar": "https://github.com/Bharath_V26.png",
```suggestion
  "avatar": "https://github.com/Bharath-V26.png",
```

2023-01-19 23:07 UTC, SaraJaoude approved these changes
looks good

2023-01-20 03:54 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-20 10:42 UTC, merged