Added prgayake Profile
EddieHubCommunity/LinkFree pull request #321
Opened 2021-09-26 19:18 UTC by prgayake

2021-09-26 22:19 UTC, Panquesito7 requested changes

2021-09-26 22:19 UTC, Panquesito7 commented on public/data/prgayake.json
> +
```suggestion
```

2021-09-26 22:19 UTC, Panquesito7 commented on public/data/prgayake.json
> +  "bio": "Web Developer 🖥 | Passionate about coding ",
```suggestion
  "bio": "Web Developer 💻 | Passionate about coding",
```

2021-09-26 22:19 UTC, Panquesito7 commented on public/data/prgayake.json
> +
```suggestion
```

2021-09-27 04:23 UTC, prgayake commented
Hey There, 
Done all the Requested changes and Waiting for your response.

2021-09-27 04:35 UTC, rohan-kulkarni-25 approved these changes

2021-09-27 18:09 UTC, merged