data:Jonte
EddieHubCommunity/LinkFree pull request #3250
Opened 2023-01-12 06:42 UTC by jontstaz

## Changes proposed

- Add my profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-12 10:50 UTC, eddiejaoude requested changes
File name does not match username

2023-01-15 19:00 UTC, EmmaDawsonDev requested changes
Hi Jonte! The way linkfree is set up the name of your file needs to match your github username (case-sensitive). Once you've updated the name then this is good to merge.

2023-01-31 07:12 UTC, jontstaz commented
Hi @eddiejaoude @EmmaDawsonDev - Sorry for the late reply but I've renamed the file to match my github username now and I've merged latest changes so its up-to-date w/ master. Should be all good to go now. Thx!

2023-01-31 18:24 UTC, Panquesito7 requested changes

2023-01-31 18:24 UTC, Panquesito7 commented on data/jontstaz.json
> +  "avatar": "http://github.com/jontstaz.png",
The avatar field is no longer required as of a new update.
```suggestion
```

2023-02-01 07:12 UTC, jontstaz commented
@Panquesito7 - Ok thanks for the info. I removed it as suggested now.

2023-02-01 20:30 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2023-02-02 09:43 UTC, jontstaz commented
@eddiejaoude - Mind approving the PR when you can so it can be merged?

2023-02-03 02:20 UTC, eddiejaoude approved these changes
Great collaboration everyone 👍

2023-02-03 02:21 UTC, merged