data:Himanshuch8055
EddieHubCommunity/LinkFree pull request #3323
Opened 2023-01-12 19:42 UTC by Himanshuch8055

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-12 19:48 UTC, Njong392 submitted a review, later dismissed
Looks awesome! Thank you for contributing to LinkFree :tada:

2023-01-12 19:53 UTC, Himanshuch8055 commented
I'm also thankful. @Njong392 @

2023-01-12 20:13 UTC, Panquesito7 requested changes

2023-01-12 20:13 UTC, Panquesito7 commented on data/Himanshuch8055.json
> +    { "icon": "FaDiscord", "url": "https://discord.gg/https://discord.gg/deYQcTGk" },
Wrong link here.
```suggestion
    { "icon": "FaDiscord", "url": "https://discord.gg/deYQcTGk" },
```

2023-01-12 20:29 UTC, Njong392 commented on data/Himanshuch8055.json
> +    { "icon": "FaDiscord", "url": "https://discord.gg/https://discord.gg/deYQcTGk" },
> Wrong link here.
> ```suggestion
>     { "icon": "FaDiscord", "url": "https://discord.gg/deYQcTGk" },
> ```
> 

Must've missed that! Thanks 🙌

2023-01-13 10:29 UTC, closed without merging

2023-01-13 10:37 UTC, Njong392 commented
Hello @Himanshuch8055 Is there any particular reason for closing this before it's merged? I see that you made changes as per the reviewer.

2023-01-13 11:28 UTC, Himanshuch8055 commented
@Njong392 Actually I'm create new pull request.