data: Dimple-Choudhary
EddieHubCommunity/LinkFree pull request #3332
Opened 2023-01-13 03:03 UTC by Dimple-Choudhary

* Added my profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-01-13 03:13 UTC, ChinmayMhatre submitted a review, later dismissed
Looks good!

2023-01-13 07:07 UTC, Pradumnasaraf requested changes
Hey,

There is an extra **Curly brackets** `}` in the file. Please fix that. If you need any help feel free to reach out.

2023-01-13 07:07 UTC, Pradumnasaraf commented on data/Dimple-Choudhary.json
> +}"links": [
```suggestion
 "links": [
```

2023-01-15 17:58 UTC, kumarsonsoff3 approved these changes
Looks Good, Thanks! 🎉

2023-01-15 19:05 UTC, EmmaDawsonDev approved these changes

2023-01-15 19:06 UTC, merged