Add kulkarnigaurav38 profile
EddieHubCommunity/LinkFree pull request #334
Opened 2021-09-27 15:23 UTC by kulkarnigaurav38

# Please Merge my Profile file !
## Just getting started here with open-source contributions!

2021-09-27 15:31 UTC, niteshseram approved these changes
LGTM

2021-09-27 16:03 UTC, CodingSpecies approved these changes

2021-09-27 17:18 UTC, aayush89890 reviewed
Looks good, Welcome to the community @kulkarnigaurav38 .

2021-09-27 17:31 UTC, Panquesito7 requested changes

2021-09-27 17:31 UTC, Panquesito7 commented on public/data/kulkarnigaurav38.json
> +      "name": "Checkout my GitHub profile",
```suggestion
      "name": "Check out my GitHub profile",
```

2021-10-02 04:49 UTC, eddiejaoude approved these changes
Thanks

2021-10-02 04:52 UTC, merged