[data]: [manthanank]
EddieHubCommunity/LinkFree pull request #3396
Opened 2023-01-13 18:43 UTC by manthanank

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-13 20:51 UTC, Panquesito7 commented on data/manthanank.json
> +    "testimonials": []
You can remove these fields if you're not going to use them for now.
```suggestion
```

2023-01-13 20:51 UTC, Panquesito7 commented on data/manthanank.json
> +
There's an extra line here.
```suggestion
}
```

2023-01-15 06:17 UTC, Panquesito7 requested changes

2023-01-15 06:17 UTC, Panquesito7 commented on data/manthanank.json
> +    "avatar": "https://github.com/manthaank.png",
Wrong username.
```suggestion
    "avatar": "https://github.com/manthanank.png",
```

2023-01-15 06:17 UTC, Panquesito7 commented on data/manthanank.json
> +        "url": "https://github.com/manthaank",
Same here.
```suggestion
        "url": "https://github.com/manthanank",
```

2023-01-15 06:22 UTC, manthanank commented
updated

2023-01-15 06:25 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-15 18:02 UTC, kumarsonsoff3 approved these changes
Looks Good, Great Collaboration Everyone! 🎉

2023-01-15 18:02 UTC, merged

2023-01-15 18:04 UTC, manthanank commented
Finally, on LinkFree after so many conflicts✌️😂, Thanks