eddie-pp
EddieHubCommunity/LinkFree pull request #3404
Opened 2023-01-13 20:30 UTC by ravi0900

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-13 20:51 UTC, Aadarsh805 requested changes
Your filename must match your GitHub username, make it `ravi0900.json`

2023-01-13 20:54 UTC, Aadarsh805 requested changes

2023-01-13 20:54 UTC, Aadarsh805 commented on data/ravirajkushwaha.json
> +  "avatar": "https://raw.githubusercontent.com/ravi0900/AboutMe/main/images/image.png",
use this link for avatar `https://github.com/ravi0900.png`

2023-01-13 20:54 UTC, Aadarsh805 commented on data/ravirajkushwaha.json
> +  "Links": [
this `L` in `Links` should be `l` (small L)

2023-01-13 20:56 UTC, Aadarsh805 commented
@ravi0900 now your file is out of `data` directory, for this change your name to `data/ravi0900.json`

2023-01-13 21:05 UTC, ravi0900 commented
> @ravi0900 now your file is out of `data` directory, for this change your name to `data/ravi0900.json`

now everything fixed ? right ?

2023-01-13 21:11 UTC, Aadarsh805 approved these changes
Yep all good 👍

2023-01-14 06:05 UTC, ChinmayMhatre approved these changes

2023-01-14 21:49 UTC, EmmaDawsonDev approved these changes
Looks good!

2023-01-14 21:50 UTC, merged