data: AkshayAwate
EddieHubCommunity/LinkFree pull request #3419
Opened 2023-01-14 07:38 UTC by AkshayAwate

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-14 13:04 UTC, Aadarsh805 reviewed
I think you must have the `links` field for it to work
I'm not really sure, can someone have a look

2023-01-21 14:55 UTC, amandamartin-dev requested changes

2023-01-21 14:55 UTC, amandamartin-dev commented on data/AkshayAwate.json
>    ]
Hey @AkshayAwate! This looks good so far, but you have not added any links to your linkfree! The "socials" section shows up just below the avatar as clickable icons.  To complete your profile, you will want to add your links section as well.  To see what I mean, take a look at the docs https://linkfree.eddiehub.io/docs/quickstart and Eddie's profile https://github.com/EddieHubCommunity/LinkFree/blob/main/data/eddiejaoude.json

Let us know if you need any help!

2023-02-09 06:59 UTC, SaraJaoude commented
I am going to close as this Profile already exists: https://github.com/EddieHubCommunity/LinkFree/blob/main/data/AkshayAwate.json

@AkshayAwate if you would like to make any updates/edits to your profile, you may want to have a look at the Docs: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-02-09 06:59 UTC, closed without merging