data:OGEmanuel
EddieHubCommunity/LinkFree pull request #3427
Opened 2023-01-14 11:36 UTC by OGEmanuel

2023-01-14 12:53 UTC, Aadarsh805 requested changes

2023-01-14 12:53 UTC, Aadarsh805 commented on data/OGEmanuel.json
> +    }
missing commas after each link

2023-01-14 12:54 UTC, Aadarsh805 requested changes

2023-01-14 12:54 UTC, Aadarsh805 commented on data/OGEmanuel.json
> +      "url": "emanuolumide@gmail.com",
make it a mail to link like this `mailto:emanuolumide@gmail.com`

2023-01-14 12:54 UTC, Aadarsh805 commented on data/OGEmanuel.json
> +      "url": "emanuolumide@gmail.com",
also use `FaEnvelope` this for the email icon

2023-01-15 18:13 UTC, kumarsonsoff3 commented
Closing this one because it seems to be a duplicate to PR #3481

2023-01-15 18:13 UTC, closed without merging