added Data
EddieHubCommunity/LinkFree pull request #344
Opened 2021-09-28 10:39 UTC by StarTrooper08

2021-09-28 14:08 UTC, Panquesito7 requested changes

2021-09-28 14:08 UTC, Panquesito7 commented on public/data/StarTrooper08.json
> +    },
```suggestion
    }
```

2021-09-28 14:08 UTC, Panquesito7 commented on src/Components/Links.js
> +
Please revert the changes in this file.
```suggestion
```

2021-09-29 09:15 UTC, StarTrooper08 commented on src/Components/Links.js
> +
ok

2021-09-30 07:11 UTC, StarTrooper08 commented
Did the suggested changes

2021-10-02 04:50 UTC, eddiejaoude approved these changes
Thanks

2021-10-02 04:51 UTC, merged