data:vidhimakani74
EddieHubCommunity/LinkFree pull request #3447
Opened 2023-01-14 16:05 UTC by vidhimakani74

2023-01-14 17:02 UTC, kumarsonsoff3 requested changes
Hi @vidhimakani74, Please replace the icons below with the respective icons for the links, else it will look something like this! 😄

![image](https://user-images.githubusercontent.com/88786642/212485443-bac700dd-2e66-41e9-91cc-9e2bbda70407.png)

2023-01-15 04:01 UTC, vidhimakani74 commented on data/vidhimakani74.json
> +      "icon": "FaInstagram"
i forgot to change icons, thanks for suggestions

2023-01-15 06:29 UTC, Panquesito7 submitted a review, later dismissed
Overall, it looks good. Thanks! 🎉

2023-01-15 06:29 UTC, Panquesito7 commented on data/vidhimakani74.json
> +  "tags": ["Open Source", "Web Development", "Fronted" ],
Non-blocking: minor spelling error here.
```suggestion
  "tags": ["Open Source", "Web Development", "Frontend" ],
```

2023-01-15 16:56 UTC, kumarsonsoff3 approved these changes
Looks good to merge. Thanks for your contribution! 🎉

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/212554676-9b334376-a645-4392-b135-4246f7fc4993.png" /></p>

2023-01-15 16:57 UTC, merged