data:akhil3shh
EddieHubCommunity/LinkFree pull request #3450
Opened 2023-01-14 18:29 UTC by akhil3shh

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-14 19:18 UTC, Pradumnasaraf approved these changes

2023-01-14 19:21 UTC, Pradumnasaraf requested changes
Hey,

There is an extra `,` in the JSON file.Please remove that

2023-01-14 19:21 UTC, Pradumnasaraf commented on data/akhil3shh.json
> +    },
```suggestion
    }
```

2023-01-15 06:26 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-15 19:19 UTC, EmmaDawsonDev approved these changes
Looks good 👍

2023-01-15 19:22 UTC, merged