data:jainamshah3638
EddieHubCommunity/LinkFree pull request #3466
Opened 2023-01-15 06:47 UTC by jainamshah3638

Jainam shah Profile added

2023-01-15 19:36 UTC, EmmaDawsonDev requested changes
Just a couple of links to update then this should be good to merge.

2023-01-15 19:36 UTC, EmmaDawsonDev commented on data/jainamshah3638.json
> +      "url": "https://twitter.com/EddieAndSaraExplore",
Please update to your own account

2023-01-15 19:36 UTC, EmmaDawsonDev commented on data/jainamshah3638.json
> +      "url": "https://twitter.com/SaraJaoude",
Please update this link too

2023-01-16 03:24 UTC, jainamshah3638 commented on data/jainamshah3638.json
> +      "url": "https://twitter.com/EddieAndSaraExplore",
Changes done as you told 
Q

2023-01-16 20:15 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-16 21:12 UTC, EmmaDawsonDev approved these changes

2023-01-16 21:12 UTC, merged