Create abishek.json
EddieHubCommunity/LinkFree pull request #3472
Opened 2023-01-15 09:11 UTC by abishekgit

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-15 13:54 UTC, Aadarsh805 requested changes
Your file name must match your GitHub username, make it `data/abishekgit.json`

2023-01-15 13:58 UTC, Aadarsh805 requested changes
and your Hashnode link return 404

2023-01-15 13:58 UTC, Aadarsh805 commented on data/abishek.json
> +    }
you are missing commas after each link object, fix those

2023-01-15 13:58 UTC, Aadarsh805 commented on data/abishek.json
> +      "icon": "FaHashnode"
use this icon for Hashnode `SiHashnode`

2023-01-15 13:58 UTC, Aadarsh805 commented on data/abishek.json
> +      "icon": "FaLinkedIn"
this should be `FaLinkedin`

2023-01-15 13:58 UTC, Aadarsh805 commented on data/abishek.json
> +      "icon": "FaGitHub"
and GitHub should be `FaGithub`

2023-01-15 16:58 UTC, Tejender1521 requested changes
Validate JSON using any online Json validator

2023-01-26 00:59 UTC, rahulpandey70 commented
Hey @abishekgit, It should be {your GitHub username}.json -> abishekgit.json

2023-02-12 03:36 UTC, SaraJaoude commented
@abishekgit we are looking forward to having your Profile on LinkFree, but as it has been some time since you created this Pull Request and the suggested changes to have this merged have not been done, I will be closing it.  

I hope you will submit a new PR and you may wish to have a look at the QuickStart Guide in our docs which will cover those points made in the comments: https://linkfree.eddiehub.io/docs/quickstart

2023-02-12 03:36 UTC, closed without merging