Adding maharshi-sinha.json
EddieHubCommunity/LinkFree pull request #3493
Opened 2023-01-15 15:36 UTC by maharshi-sinha

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-15 16:42 UTC, Aadarsh805 requested changes
hey you should remove all the files except  `maharshi-sinha.json`  from the commit

2023-01-15 16:44 UTC, Aadarsh805 requested changes
All the icons are wrong, search icons `https://linkfree.eddiehub.io/icons` here

2023-01-15 16:44 UTC, Aadarsh805 commented on public/data/maharshi-sinha.json
> +  ]
and there is a missing comma at the end fo line 33

2023-01-15 16:52 UTC, Tejender1521 requested changes
You have to remove all the files except maharashi-sinha.json

2023-01-17 16:21 UTC, Aadarsh805 reviewed
I see that you have 5 files in the commit, you should remove them except `maharshi-sinha.json`

2023-01-17 16:22 UTC, Aadarsh805 requested changes
Also your file is in wrong directory it should be `data/maharshi-sinha.json`

2023-01-17 16:24 UTC, Aadarsh805 commented
If you need help with the deleting task, feel free to ask okay

2023-01-17 17:17 UTC, closed without merging