Add ssbarnea
EddieHubCommunity/LinkFree pull request #3497
Opened 2023-01-15 16:30 UTC by ssbarnea

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-15 17:11 UTC, Bereky commented
Looks good!

2023-01-15 19:59 UTC, EmmaDawsonDev requested changes
Please add `displayStatsPublic` with a value of true or false then this will be good to go.

2023-01-16 18:48 UTC, Pradumnasaraf submitted a review, later dismissed
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/212091929-1fcc2fb2-b3b4-48cf-9ec4-5c827bfe47dc.png"></p>

2023-01-16 18:52 UTC, Pradumnasaraf commented
> Please add `displayStatsPublic` with a value of true or false then this will be good to go.

Hey, Emma. It's by default `false`. So, I don't think it's necessary to add that.

2023-01-17 06:26 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-17 09:45 UTC, ssbarnea commented
@EmmaDawsonDev With lack of json json schema is quite hard to guess which fields are available.

2023-01-17 12:14 UTC, kumarsonsoff3 requested changes
Last few changes required, then it should be good to goo! 🛠

2023-01-17 12:14 UTC, kumarsonsoff3 commented on data/ssbarnea.json
> +        "url": "https://www.youtube.com/ssbarnea",
Please fix this invalid URL, there is a missing `@`.
```suggestion
        "url": "https://www.youtube.com/@ssbarnea",
```

2023-01-17 12:14 UTC, kumarsonsoff3 commented on data/ssbarnea.json
> +      },
Please remove the trailing comma `,` here to validate the `json` check.

```suggestion
      }
```

2023-01-17 18:49 UTC, Pradumnasaraf approved these changes
Looks good to merge.

2023-01-17 18:50 UTC, merged