swapnil patle
EddieHubCommunity/LinkFree pull request #3499
Opened 2023-01-15 16:48 UTC by SwapnilPatle

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-15 16:49 UTC, Aadarsh805 requested changes
Change the file name to `data/SwapnilPatle.json`

2023-01-15 16:50 UTC, Aadarsh805 commented
and now that you have opened a new pr, you should close the previous one #3494

2023-01-15 16:54 UTC, Aadarsh805 requested changes

2023-01-15 16:54 UTC, Aadarsh805 commented on Swapnil Patle
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
You also need to change the bio here, seems like you have used the one described in the `Quickstart` guide

2023-01-15 17:19 UTC, yashdev9274 approved these changes
This profile is ready to merge , before that just make sure to manage the sengmentation of "link" section and your profile is set to go live

And don't forget to close prev PR

2023-01-15 20:01 UTC, EmmaDawsonDev requested changes
Your file needs to be called SwapnilPatle.json and it needs to be inside the data folder. Once these changes are made then this should be good to merge.

2023-01-16 03:10 UTC, closed without merging

2023-01-16 09:40 UTC, Aadarsh805 commented
Hey @SwapnilPatle, if you would like some help feel free to ask