data: harshasingamshetty1
EddieHubCommunity/LinkFree pull request #3508
Opened 2023-01-15 19:37 UTC by harshasingamshetty1

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-15 20:09 UTC, EmmaDawsonDev requested changes
There's a missing comma on line 25, otherwise this looks good.

2023-01-15 20:09 UTC, EmmaDawsonDev commented on data/harshasingamshetty1.json
> +  ]
```suggestion
  ],
```

2023-01-16 13:18 UTC, Tejender1521 requested changes
Validate JSON file and put "," after links array

2023-01-16 18:56 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/212091929-1fcc2fb2-b3b4-48cf-9ec4-5c827bfe47dc.png"></p>

2023-01-16 18:57 UTC, merged