Added Amit Khatri profile
EddieHubCommunity/LinkFree pull request #355
Opened 2021-09-29 16:14 UTC by aamita96

New aamita96.json file added to this repo.

2021-09-29 18:01 UTC, voidz7 requested changes

2021-09-30 04:23 UTC, aamita96 commented on public/data/aamita96.json
> +  }
You mean aligning the parenthesis right? If that is the case I have done it, If not then please specify. Thanks.

2021-09-30 06:08 UTC, voidz7 commented on public/data/aamita96.json
> +  }
yep .

2021-09-30 06:09 UTC, voidz7 approved these changes

2021-09-30 10:52 UTC, eddiejaoude requested changes
GitHub is highlighting the file ending is not correct

2021-09-30 11:58 UTC, aamita96 commented
> GitHub is highlighting the file ending is not correct

@eddiejaoude would be great if you can specify what I am missing like it was whitespace or new-line. I have tried to keep the file like your provided JSON and tried to compare other JSON files as well didn't find any major diferrence.

2021-09-30 17:26 UTC, Kunal0007 approved these changes
LGTM

2021-09-30 17:52 UTC, MukulKolpe approved these changes

2021-10-01 03:45 UTC, rohan-kulkarni-25 approved these changes
LGTM 💥

2021-10-02 05:44 UTC, eddiejaoude approved these changes
Looks good now 👍

2021-10-02 06:00 UTC, merged