Data:Greenchapeljohn
EddieHubCommunity/LinkFree pull request #3566
Opened 2023-01-16 21:00 UTC by greenchapeljohn

## Changes proposed
Adding JohnGreenDev Linkfree Data file

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-01-17 06:29 UTC, Panquesito7 requested changes
Please keep your profile changes only and revert the other changes.
I think this can be fixed by updating your branch. Any help, let us know. 🙂

2023-01-17 07:48 UTC, greenchapeljohn commented
My commit only contains the one file change. 
The other change has been done by the github action ( I assume setup in the project ?)

2023-01-17 16:17 UTC, greenchapeljohn commented
The above has been succeeded  with main

2023-01-17 16:17 UTC, greenchapeljohn commented
Think the above has now been succeeded  with main

2023-01-18 08:17 UTC, kumarsonsoff3 requested changes
Please rename your file to `username.json`, else some features may not work for you. 

It should be `greenchapeljohn.json`. 🛠

2023-01-18 08:37 UTC, greenchapeljohn commented
File Is now renamed

2023-01-18 18:20 UTC, Panquesito7 commented on data/greenchapeljohn.json
> +  ]
I think it's best to remove this field if you're not going to use it, IMO.
```suggestion
  ]
```

2023-01-18 21:26 UTC, greenchapeljohn commented
Sure, I updated that, did plan to add them later but I can stick the object back in once I have some milestones written to go in it.

2023-01-19 08:56 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-01-19 21:40 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-19 22:11 UTC, SaraJaoude approved these changes
looks good

2023-01-19 22:12 UTC, merged

2023-01-19 22:14 UTC, eddiejaoude commented
> My commit only contains the one file change.
> The other change has been done by the github action ( I assume setup in the project ?)

@greenchapeljohn thanks for fixing 👍 it looks like the GitHub Actions are running on your fork, these should not be running on the fork (they should be off by default on a fork)

2023-01-19 22:44 UTC, greenchapeljohn commented
Will take a look and see why they are switched on. I did have an old fork from a while back when I did some doc additions, probably had it enabled from then.

2023-01-19 22:46 UTC, eddiejaoude commented
@greenchapeljohn ah maybe, let us know how it goes or if we can help with anything 👍