add ashwin to the list
EddieHubCommunity/LinkFree pull request #357
Opened 2021-09-29 19:39 UTC by Ashwin-exe

2021-09-30 04:21 UTC, FayasNoushad approved these changes

2021-09-30 10:51 UTC, eddiejaoude requested changes
GitHub is highlighting the file ending is not correct

2021-10-01 03:43 UTC, rohan-kulkarni-25 requested changes

2021-10-01 03:43 UTC, rohan-kulkarni-25 commented on public/data/ashwin.json
> +
- Please delete this empty line No 18

2021-10-01 13:44 UTC, Ashwin-exe reviewed
removed the spaces and last line

2021-10-02 05:59 UTC, eddiejaoude approved these changes
Thanks 👍

2021-10-02 06:00 UTC, merged