data: theVatsal3802
EddieHubCommunity/LinkFree pull request #3572
Opened 2023-01-17 04:48 UTC by theVatsal3802

2023-01-17 04:57 UTC, Tejender1521 commented on data/theVatsal3802.json
> +    },
}

2023-01-17 04:58 UTC, Tejender1521 requested changes
Remove , at line # 27

2023-01-17 04:58 UTC, Tejender1521 commented on data/theVatsal3802.json
> +    },
Remove , at the end to validate JSON

2023-01-17 05:02 UTC, theVatsal3802 commented on data/theVatsal3802.json
> +    },
Done

2023-01-17 06:11 UTC, iamthecloverly submitted a review, later dismissed

2023-01-17 06:33 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-01-17 06:38 UTC, kumarsonsoff3 reviewed
I recommend updating the **invalid icons** as suggested, else the default globe icon will be implemented for both the links. 

Rest looks good to me! 👍

2023-01-17 06:38 UTC, kumarsonsoff3 commented on data/theVatsal3802.json
> +      "icon": "FaGitHub"
```suggestion
      "icon": "FaGithub"
```

2023-01-17 06:38 UTC, kumarsonsoff3 commented on data/theVatsal3802.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-01-18 04:45 UTC, theVatsal3802 commented on data/theVatsal3802.json
> +      "icon": "FaLinkedIn"
Done

2023-01-18 04:45 UTC, theVatsal3802 commented on data/theVatsal3802.json
> +      "icon": "FaGitHub"
Done

2023-01-18 05:44 UTC, Tejender1521 approved these changes
Now everything looks good and ready to be merged

2023-01-18 07:20 UTC, kumarsonsoff3 approved these changes
Looks good to merge, Thanks for your Contribution! 🎉 

<p align="center"> <img src="https://user-images.githubusercontent.com/88786642/212844246-70e18f2b-58df-4dbb-834d-adf2c12d0def.png" /></p>

2023-01-18 07:21 UTC, merged