data:lilmubby
EddieHubCommunity/LinkFree pull request #3588
Opened 2023-01-17 16:12 UTC by lilmubby

## Fixes Issue
added my data linkfree

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-17 19:26 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-17 19:51 UTC, Pradumnasaraf requested changes
Hey,

`i` in Linkedin should be lowercase
<img width="307" alt="Screenshot 2023-01-18 at 1 19 50 AM" src="https://user-images.githubusercontent.com/51878265/212997946-02a0cbbb-1e55-4079-a073-276db6ad4cb4.png">

2023-01-17 19:51 UTC, Pradumnasaraf commented on data/lilmubby.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-01-19 22:06 UTC, SaraJaoude approved these changes
looks good

2023-01-19 22:08 UTC, merged