data: krishnanunnijs
EddieHubCommunity/LinkFree pull request #3607
Opened 2023-01-18 11:48 UTC by krishnanunnijs

## Changes proposed

Added new profie link

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2023-01-18 23:35 UTC, SaraJaoude commented on data/krishnanunnijs.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
Please update your bio with your information

2023-01-19 16:19 UTC, Tejender1521 requested changes
Please update bio with your information and use your github avatar url link.

2023-01-19 17:54 UTC, krishnanunnijs reviewed
updated bio

2023-01-19 22:14 UTC, SaraJaoude approved these changes
looks good

2023-01-19 22:14 UTC, merged