data:Madhavi210
EddieHubCommunity/LinkFree pull request #3623
Opened 2023-01-18 13:44 UTC by Madhavi210

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-18 14:21 UTC, senali-d requested changes

2023-01-18 14:21 UTC, senali-d commented on data/Madhavi210.json
> +      "icon": "FaLinkedIn"
Linkedin icon name should be `FaLinkedin`

```suggestion
      "icon": "FaLinkedin"
```

2023-01-18 14:26 UTC, ChinmayMhatre requested changes
Please add the commas as suggested

2023-01-18 14:26 UTC, ChinmayMhatre commented on data/Madhavi210.json
> +    }
```suggestion
    },
```
missing comma

2023-01-18 14:26 UTC, ChinmayMhatre commented on data/Madhavi210.json
> +    }
```suggestion
    },
```
Missing comma

2023-01-18 14:26 UTC, senali-d requested changes

2023-01-18 14:26 UTC, senali-d commented on data/Madhavi210.json
> +    }
Missing `,`

2023-01-18 14:26 UTC, senali-d commented on data/Madhavi210.json
> +    }
Missing `,`
```suggestion
    },
```

2023-01-19 07:09 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/212091929-1fcc2fb2-b3b4-48cf-9ec4-5c827bfe47dc.png"></p>

2023-01-19 07:09 UTC, merged