data:RishabhDhawad
EddieHubCommunity/LinkFree pull request #3633
Opened 2023-01-18 18:00 UTC by RishabhDhawad

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-18 18:10 UTC, RishabhDhawad reviewed
I have updated my initial commit and it's now according to the JSON format

2023-01-19 09:23 UTC, ChinmayMhatre requested changes
I have suggested some changes as to why your PR might be failing

2023-01-19 09:23 UTC, ChinmayMhatre commented on data/RishabhDhawad.json
> +    },
```suggestion
    }
```
Please remove this comma

2023-01-19 09:23 UTC, ChinmayMhatre commented on data/RishabhDhawad.json
> +  ],
```suggestion
  ]
```
Please remove this comma

2023-01-19 16:34 UTC, RishabhDhawad commented
Thank you so much for pointing it out, Chinmay. Also, I have updated the JSON file.

2023-01-19 21:53 UTC, SaraJaoude approved these changes
looks good

2023-01-19 21:53 UTC, merged