data:vidhimakani74
EddieHubCommunity/LinkFree pull request #3649
Opened 2023-01-19 04:32 UTC by vidhimakani74

portfolio website and milestone section added

2023-01-19 10:24 UTC, Pradumnasaraf requested changes
Hey, 

The `icon"` value is not supported. I have suggested the fix. If you still want to add something different, please check the available icons docs - https://linkfree.eddiehub.io/icons

2023-01-19 10:24 UTC, Pradumnasaraf commented on data/vidhimakani74.json
> +      "icon": "code",
```suggestion
      "icon": "FaCode",
```

2023-01-19 10:24 UTC, Pradumnasaraf commented on data/vidhimakani74.json
> +      "icon": "globe"
```suggestion
      "icon": "FaGlobe"
```

2023-01-19 10:30 UTC, vidhimakani74 commented
> Hey,
> 
> The `"icon"` value provided by you is not supported. I have suggested the fix. If you still want to add something different, please check the available icons docs - https://linkfree.eddiehub.io/icons

How to see preview of our changes?

2023-01-19 11:53 UTC, kumarsonsoff3 approved these changes
Looks Good, Thanks! 🎉

2023-01-19 11:56 UTC, kumarsonsoff3 commented
> > Hey,
> > The `"icon"` value provided by you is not supported. I have suggested the fix. If you still want to add something different, please check the available icons docs - https://linkfree.eddiehub.io/icons
> 
> How to see preview of our changes?

You'll see the preview of these changes once the PR will be merged, & deployed.

2023-01-19 21:11 UTC, SaraJaoude approved these changes
looks good

2023-01-19 21:12 UTC, merged

2023-01-21 11:23 UTC, vidhimakani74 commented
> 

Thanks ✨  thank you for merging