data: mehmetsaidozsoy
EddieHubCommunity/LinkFree pull request #3653
Opened 2023-01-19 07:13 UTC by mehmetsaidozsoy

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-19 09:45 UTC, ChinmayMhatre requested changes
Changes to a few icons

2023-01-19 09:45 UTC, ChinmayMhatre commented on mehmetsaidozsoy.json
> +      "icon": "FaInstagram"
```suggestion
      "icon": "FaGithub"
```
You could use the GitHub icon for your GitHub profile

2023-01-19 09:45 UTC, ChinmayMhatre commented on mehmetsaidozsoy.json
> +      "icon": "FaInstagram"
```suggestion
      "icon": "FaLinkedin"
```
There is a linked in icon aswell

2023-01-19 09:45 UTC, ChinmayMhatre commented on mehmetsaidozsoy.json
> +      "icon": "FaInstagram"
```suggestion
      "icon": "FaYoutube"
```
Here is this YouTube icon

2023-01-19 09:50 UTC, ChinmayMhatre commented
@mehmetsaidozsoy Please move you json file to the data folder

2023-01-19 09:52 UTC, ChinmayMhatre requested changes

2023-01-19 09:52 UTC, ChinmayMhatre commented on mehmetsaidozsoy.json
> +    },
```suggestion
    }
    ]
```
There is a missing closing bracket for the link

2023-01-19 09:55 UTC, ChinmayMhatre requested changes

2023-01-19 09:55 UTC, ChinmayMhatre commented on mehmetsaidozsoy.json
> +  "avatar": "https://avatars.githubusercontent.com/u/6255955?s=40&v=4",
```suggestion
  "avatar": "https://github.com/mehmetsaidozsoy.png",
```
Please use this icon

2023-01-20 03:25 UTC, Panquesito7 requested changes
Your file must be inside the `data` directory.
Please move it there. Any help, let us know. 🙂

2023-01-27 18:06 UTC, devvsakib approved these changes

2023-02-13 03:19 UTC, SaraJaoude commented
@mehmetsaidozsoy you seem to have created another Pull Request for your profile in https://github.com/EddieHubCommunity/LinkFree/pull/4649 which supersedes this one.  

I will be closing this Pull Request. In future it would be helpful if you could close your own Pull Request if they are no longer required, as this helps maintainers manage the project.

2023-02-13 03:19 UTC, closed without merging