Social icons
EddieHubCommunity/LinkFree pull request #366
Opened 2021-10-01 00:44 UTC by mohammad4kh

Adding different social media icons to the site

For example

 - Facebook
 - Instagram
 - Linkedin
 - Vimeo
 - Discord

and others 

![Screenshot from 2021-10-01 02-33-57](https://user-images.githubusercontent.com/6501582/135548858-7dc2ee92-8693-4091-a1d0-c6798c87cc3f.png)

2021-10-02 06:12 UTC, eddiejaoude commented
Looks great 👍 Thank you!

Could you resolve the conflict please

2021-10-02 06:25 UTC, AbhijithGanesh approved these changes

2021-10-03 00:56 UTC, mohammad4kh commented
@eddiejaoude thank you
the conflict is now resolved.

2021-10-03 09:01 UTC, eddiejaoude commented on src/index.css
> +.p-button:hover {
please can you check for existing/duplicate styles https://github.com/EddieHubCommunity/LinkFree/blob/main/src/Components/Links.css#L5

2021-11-14 05:30 UTC, krishguptadev requested changes
## Merge Conflict

Thank you for your contribution. Your pull request currently has conflicting changes with our `main` branch. In order to review this pull request, we will need those conflicts to be resolved.

We recommend doing this with the `git rebase` command. If you are unsure of how to fix this, let us know and we would be happy to assist you.

2021-11-14 05:30 UTC, krishguptadev requested changes
Please take a look at the old requested changes.

2021-11-24 18:03 UTC, shreyaansjain06 requested changes
Please see comments above

2021-11-24 19:04 UTC, Panquesito7 requested changes
Please see the comments above.

2021-11-25 03:20 UTC, krishguptadev commented
Hey there! Just checking in 👋 Do you need any help?

2021-12-06 15:11 UTC, emmalearnscode commented
As there are conflicts and this PR hasn't been worked on for a long time I will close it for now. Please feel free to open it if you get the time to fix the conflicts and make the requested updates. Thanks for contributing and please feel free to come back and help out again in the future!

2021-12-06 15:11 UTC, closed without merging