data:obaidashfaq20
EddieHubCommunity/LinkFree pull request #3691
Opened 2023-01-19 22:30 UTC by obaidashfaq20

2023-01-19 22:39 UTC, dan-mba submitted a review, later dismissed
To fix the JSON error, add a comma at the end of line 6.

2023-01-21 05:59 UTC, AbbeyIT requested changes

2023-01-21 05:59 UTC, AbbeyIT commented on data/obaidashfaq20.json
> +  "avatar": "https://github.com/obaidashfaq20.png"
Hi, please put a comma at the end of the line. So it won't have a syntax error in the json format.

2023-01-27 18:05 UTC, devvsakib requested changes

2023-01-27 18:05 UTC, devvsakib commented on data/obaidashfaq20.json
> +  "avatar": "https://github.com/obaidashfaq20.png"
you can add tags here, and add a comma to line 6

2023-02-13 04:24 UTC, SaraJaoude commented on data/obaidashfaq20.json
> +  "avatar": "https://github.com/obaidashfaq20.png"
The avatar is no longer needed 

```suggestion
```

2023-02-13 04:25 UTC, SaraJaoude commented on data/obaidashfaq20.json
> +  "displayStatsPublic": true,
Following a recent improvement this is no longer needed
```suggestion
```

2023-02-13 04:44 UTC, merged