Create braxas.json
EddieHubCommunity/LinkFree pull request #3695
Opened 2023-01-20 04:34 UTC by braxas

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-20 06:38 UTC, kumarsonsoff3 requested changes

2023-01-20 06:38 UTC, kumarsonsoff3 commented on data/braxas.json
> +  "avatar": "https://xn--tnediefreudemachen-d3b.de/wp-content/uploads/2021/11/fav.jpg"
Please add a missing comma `,` here to validate your json! 

```suggestion
  "avatar": "https://xn--tnediefreudemachen-d3b.de/wp-content/uploads/2021/11/fav.jpg",
```

2023-01-20 14:30 UTC, SaraJaoude commented on data/braxas.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
Please update the bio with **your** information

2023-02-13 04:59 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.eddiehub.io/docs/quickstart

Editing your Profile: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-02-13 04:59 UTC, closed without merging