data:Amrendra_Singh.json
EddieHubCommunity/LinkFree pull request #3699
Opened 2023-01-20 09:29 UTC by i-am-amrendra

2023-01-20 09:58 UTC, ChinmayMhatre requested changes
Please rename the json file to your GitHub username

2023-01-20 09:58 UTC, ChinmayMhatre commented on data/Amrendra_Singh.json
> +  "name": "Amrendra Snigh",
```suggestion
  "name": "Amrendra Singh",
```
Maybe name was misspelled

2023-01-20 09:58 UTC, ChinmayMhatre commented on data/Amrendra_Singh.json
> +  "avatar": "https://github.com/account",
```suggestion
  "avatar": "https://github.com/i-am-amrendra.png",
```
please use this url

2023-01-20 09:58 UTC, ChinmayMhatre commented on data/Amrendra_Singh.json
> +      "icon": "FaStackoverflow"
```suggestion
      "icon": "FaStackOverflow"
```
Icon spelling error

2023-01-20 11:43 UTC, ChinmayMhatre approved these changes

2023-01-20 11:45 UTC, ChinmayMhatre requested changes
looks good only a few missing commas

2023-01-20 11:45 UTC, ChinmayMhatre commented on data/i-am-amrendra.json
> +       "url": "https://medium.com/@Amrendra_Singh/"
```suggestion
       "url": "https://medium.com/@Amrendra_Singh/",
```
missing comma

2023-01-20 11:45 UTC, ChinmayMhatre commented on data/i-am-amrendra.json
> +      "name": "StackOverflow"
missing comma
```suggestion
      "name": "StackOverflow",
```

2023-01-20 11:45 UTC, ChinmayMhatre commented on data/i-am-amrendra.json
> +      "url": "https://stackoverflow.com/users/20550455/amrendra-singh"
```suggestion
      "url": "https://stackoverflow.com/users/20550455/amrendra-singh",
```
missing comma

2023-01-20 15:03 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/212091929-1fcc2fb2-b3b4-48cf-9ec4-5c827bfe47dc.png"></p>

2023-01-20 15:03 UTC, merged

2023-01-20 18:14 UTC, ChinmayMhatre commented
@Pradumnasaraf  I think one of the commits had a failed build before you merged it 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/51131670/213775753-e8682a10-14b6-4ebd-a137-0ac8c730e0fa.png">

2023-01-20 18:53 UTC, Pradumnasaraf commented
> @Pradumnasaraf  I think one of the commits had a failed action before you merged it 
> <img width="929" alt="image" src="https://user-images.githubusercontent.com/51131670/213775753-e8682a10-14b6-4ebd-a137-0ac8c730e0fa.png">
> 

Yep, I did that mistake 🙁. That caused the action to fail on other PRs. No worries, everything is sorted out now.

2023-01-21 05:54 UTC, i-am-amrendra commented
Thank u very much @eddiejaoude @ChinmayMhatre @Pradumnasaraf  for helping me out.🫡