Baibhav tiwari patch 3
EddieHubCommunity/LinkFree pull request #3718
Opened 2023-01-20 16:02 UTC by baibhav-tiwari

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-20 16:06 UTC, baibhav-tiwari commented
@Aadarsh805 Can you please tell what i have done wrong here

2023-01-20 17:39 UTC, Tejender1521 submitted a review, later dismissed
Everything looks good and ready to be merged.

2023-01-20 17:40 UTC, Aadarsh805 commented
> Everything looks good and ready to be merged.

JSON check failed though

2023-01-20 18:34 UTC, Pradumnasaraf requested changes
Hey, 

Please remove the extra `,`

2023-01-20 18:34 UTC, Pradumnasaraf commented on data/baibhav-tiwari.json
> +      "description": "Firstly i thought Twitter is boring but as i started using it more i started loving it.",
```suggestion
      "description": "Firstly i thought Twitter is boring but as i started using it more i started loving it."
```

2023-01-21 05:11 UTC, baibhav-tiwari commented on data/baibhav-tiwari.json
> +      "description": "Firstly i thought Twitter is boring but as i started using it more i started loving it.",
done , thanks

2023-01-21 06:22 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-01-21 06:24 UTC, merged