data:Labhk
EddieHubCommunity/LinkFree pull request #3740
Opened 2023-01-21 09:27 UTC by Labhk

2023-01-21 11:34 UTC, Aadarsh805 requested changes

2023-01-21 11:34 UTC, Aadarsh805 commented on data/Labhk.json
> +  "avatar": "https://i.ibb.co/XyWdRrF/Me.jpg",
Change avatar link to `https://github.com/Labhk.png`

2023-01-21 11:34 UTC, Aadarsh805 commented on data/Labhk.json
> +      "icon": "FaLinkedIn"
change this LinkedIn icon, use `FaLinkedin`

2023-01-22 03:16 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-22 09:41 UTC, kumarsonsoff3 approved these changes
Looks good! 👍

2023-01-22 09:41 UTC, merged