Create EternalCoderss.json
EddieHubCommunity/LinkFree pull request #3741
Opened 2023-01-21 09:30 UTC by EternalCoderss

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-21 11:30 UTC, Aadarsh805 requested changes
change the file name to `data/EternalCoderss.json` so that it's in the correct directory

2023-01-21 11:32 UTC, Aadarsh805 requested changes

2023-01-21 11:32 UTC, Aadarsh805 commented on EternalCoderss.json
> +      "url": "hhttps://hashnode.com/@shivi",
Typo in the Hashnode URL, change it to `https://hashnode.com/@shivi`

2023-01-21 12:49 UTC, Aadarsh805 requested changes

2023-01-21 12:49 UTC, Aadarsh805 commented on data/EternalCoderss.json
> +      "url": "hhttps://hashnode.com/shivi",
there's still a extra `h` in the https

it should be `https://hashnode.com/@shivi`

2023-01-21 12:49 UTC, Aadarsh805 commented on data/EternalCoderss.json
> +      "url": "hhttps://hashnode.com/shivi",
keep the `@`

2023-01-22 08:41 UTC, EternalCoderss commented
Everything is Good

2023-01-22 08:41 UTC, closed without merging