data: prajapati55
EddieHubCommunity/LinkFree pull request #3752
Opened 2023-01-21 13:20 UTC by prajapati55

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-21 16:14 UTC, Hrishi5111998 commented
hey, your testimonials is empty please add some  into it or remove it. thank you!

2023-01-22 03:40 UTC, Panquesito7 requested changes

2023-01-22 03:40 UTC, Panquesito7 commented on data/prajapati55.json
> +  "testimonials": [],
Best to remove this field if it's not used, IMO.
```suggestion
```

2023-01-22 06:56 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-22 09:43 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 👍

2023-01-22 09:43 UTC, merged