Updated my profile
EddieHubCommunity/LinkFree pull request #3756
Opened 2023-01-21 14:13 UTC by omk-coder

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-21 16:51 UTC, lewisushindi approved these changes

2023-01-22 03:47 UTC, Panquesito7 requested changes

2023-01-22 03:47 UTC, Panquesito7 commented on data/omk-coder.json
> +      "icons":"SiHashnode",
Wrong field name.
```suggestion
      "icon":"SiHashnode",
```

2023-01-22 03:47 UTC, Panquesito7 commented on data/omk-coder.json
> +      {"icons":"SiHashnode", "url":"https://hashnode.com/@Omkar009"}
Should be `icon` here as well.
```suggestion
    {"icon":"FaGithub", "url":"https://github.com/omk-coder"},
      {"icon":"FaLinkedin", "url":"https://www.linkedin.com/in/omkar-ramishte-9ba784207/"},
      {"icon":"FaTwitter", "url":"https://twitter.com/ORamishte"},
      {"icon":"SiHashnode", "url":"https://hashnode.com/@Omkar009"}
```

2023-01-22 09:36 UTC, closed without merging