Piyush link free profile
EddieHubCommunity/LinkFree pull request #3759
Opened 2023-01-21 14:34 UTC by Piyush142

## Changes proposed

Added new json file.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-21 14:58 UTC, ChinmayMhatre requested changes
Please Rename the json file to `Piyush142.json`

2023-01-21 15:37 UTC, Piyush142 commented
> Please Rename the json file to `Piyush142.json`

Hi Chinmay, I have updated the file name.

2023-01-21 16:28 UTC, schmelto submitted a review, later dismissed

2023-01-22 03:41 UTC, Panquesito7 requested changes

2023-01-22 03:41 UTC, Panquesito7 commented on data/Piyush142.json
> +      "url": "https://www.eddiejaoude.io/"
I think you should update this link.

2023-01-22 03:41 UTC, Panquesito7 commented on data/Piyush142.json
> +      "url": "https://www.eddiejaoude.io/"
Same here.

2023-01-22 09:38 UTC, Piyush142 commented on data/Piyush142.json
> +      "url": "https://www.eddiejaoude.io/"
I have done the suggested changes.

2023-01-22 09:39 UTC, Piyush142 commented on data/Piyush142.json
> +      "url": "https://www.eddiejaoude.io/"
Done suggested changes.

2023-01-22 10:00 UTC, kumarsonsoff3 approved these changes
Looks good to me! 🎉

2023-01-22 10:05 UTC, Piyush142 commented
> Looks good to me! 🎉
Thank You!
Could you please provide review for requested changes. 🙏

2023-01-22 11:58 UTC, SaraJaoude approved these changes
looks good

2023-01-22 21:41 UTC, merged