Added the LinkFree account creation content
EddieHubCommunity/LinkFree pull request #3763
Opened 2023-01-21 15:04 UTC by ibilalkayy

## Changes proposed

Added two resources to create an account in LinkFree

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Thank you, for letting me contribute to the non-code!

2023-01-21 18:15 UTC, Pradumnasaraf requested changes
Hey, Bilala.

There are some blank lines and also some markdown issues. I have requested the changes. Please fix them. IF you need some help feel free to ask.

2023-01-21 18:15 UTC, Pradumnasaraf commented on NOCODE-CHANGELOG.md
> +
```suggestion
```

2023-01-21 18:15 UTC, Pradumnasaraf commented on NOCODE-CHANGELOG.md
> +| [Bilal Khan](https://github.com/ibilalkayy) | YouTube | 2023/01/18 | [Submitting My First PR with Dean | LinkFree Account Creation for Beginners](https://www.youtube.com/watch?v=I8wNateK3hM) |
```suggestion
| [Bilal Khan](https://github.com/ibilalkayy) | YouTube | 2023/01/18 | Submitting My First PR with Dean | [LinkFree Account Creation for Beginners](https://www.youtube.com/watch?v=I8wNateK3hM) |
```

2023-01-21 18:15 UTC, Pradumnasaraf commented on NOCODE-CHANGELOG.md
> +
```suggestion
```

2023-01-22 03:43 UTC, ibilalkayy commented
I have sent another PR with updates. You can check it out.

2023-01-23 10:41 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-01-23 10:42 UTC, merged

2023-01-23 11:21 UTC, ibilalkayy commented
Thank you, for merging my request!