data:parveshsaini
EddieHubCommunity/LinkFree pull request #3764
Opened 2023-01-21 15:21 UTC by parveshsaini

2023-01-21 16:50 UTC, lewisushindi approved these changes

2023-01-21 16:56 UTC, senali-d requested changes
Looks good, but do the suggested change.

2023-01-21 16:56 UTC, senali-d commented on data/parveshsaini
> +  ]
`,` is missing
```suggestion
  ],
```

2023-01-21 18:35 UTC, dan-mba requested changes
please add `.json` to the end of your filename.

2023-01-24 20:02 UTC, Pradumnasaraf requested changes
Hey, 

Dan means adding `.json` to your file which you added in the data folder. YOu can see in the screenshot the file name without extension.

<img width="351" alt="Screenshot 2023-01-25 at 1 31 25 AM" src="https://user-images.githubusercontent.com/51878265/214396533-dfdf4c99-41ec-49ed-bce1-a950f54d1f49.png">

2023-01-27 17:59 UTC, devvsakib approved these changes
LGTM

2023-01-27 18:00 UTC, devvsakib requested changes
change your file name to `parveshsaini.json`

2023-01-28 09:58 UTC, closed without merging