data:darvesh29
EddieHubCommunity/LinkFree pull request #3768
Opened 2023-01-21 17:34 UTC by darvesh29

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-21 18:17 UTC, Pradumnasaraf requested changes
Hey,

Add your name to the `data` folder and also fix the JSON syntax suggested. If you need help, feel free to ask.

2023-01-21 18:17 UTC, Pradumnasaraf commented on darvesh29.json
> +  "bio": 21 | Begginner in Open Source | Learning DevOps | Learning Web-Development | Java | DSA",
```suggestion
  "bio": "21 | Begginner in Open Source | Learning DevOps | Learning Web-Development | Java | DSA",
```

2023-01-21 18:17 UTC, Pradumnasaraf commented on darvesh29.json
> +      "url": https://www.linkedin.com/in/darveshchauhan/",
```suggestion
      "url": "https://www.linkedin.com/in/darveshchauhan",
```

2023-01-21 18:17 UTC, Pradumnasaraf commented on darvesh29.json
> +      "icon": "FaInstagram
```suggestion
      "icon": "FaInstagram"
```

2023-01-21 19:52 UTC, darvesh29 commented
> Hey,
> 
> Add your name to the `data` folder and also fix the JSON syntax suggested. If you need help, feel free to ask.

Hii Pradumansaraf , thanks for correcting me 
Where is the data folder?

2023-01-22 14:59 UTC, Pradumnasaraf commented
> > Hey,
> > Add your name to the `data` folder and also fix the JSON syntax suggested. If you need help, feel free to ask.
> 
> Hii Pradumansaraf , thanks for correcting me Where is the data folder?

In the root directory - https://github.com/EddieHubCommunity/LinkFree/tree/main/data

2023-01-23 06:23 UTC, darvesh29 commented
> > > Hey,
> > > Add your name to the `data` folder and also fix the JSON syntax suggested. If you need help, feel free to ask.
> > 
> > 
> > Hii Pradumansaraf , thanks for correcting me Where is the data folder?
> 
> In the root directory - https://github.com/EddieHubCommunity/LinkFree/tree/main/data

i did it brother
when will this get merge now

2023-01-23 15:50 UTC, darvesh29 commented
> It is still at the root of the project not in the `data`. Please fix that.
> 
> if you need help feel free to ask

i am not understanding you
can you please provide me the steps to do this

2023-01-23 16:38 UTC, kumarsonsoff3 requested changes
To move your file into data folder, you just need to go to (https://github.com/darvesh29/LinkFree/edit/main/darvesh29.json). 
- And rename your file as `data/darvesh29.json`.
- Commit the changes, & it should be good to go then. 

Hope this helps. Feel free to ask if still confusion persists. :)

![image](https://user-images.githubusercontent.com/88786642/214096403-8af8841b-3f84-4bed-852a-0c0464768219.png)

2023-01-23 17:14 UTC, darvesh29 commented
> To move your file into data folder, you just need to go to (https://github.com/darvesh29/LinkFree/edit/main/darvesh29.json).
> 
> * And rename your file as `data/darvesh29.json`.
> * Commit the changes, & it should be good to go then.
> 
> Hope this helps. Feel free to ask if still confusion persists. :)
> 
> ![image](https://user-images.githubusercontent.com/88786642/214096403-8af8841b-3f84-4bed-852a-0c0464768219.png)

hey !!!!Thank you
did it , is it good to go now?

2023-01-24 16:36 UTC, closed without merging