data:RajeshAnthari.json
EddieHubCommunity/LinkFree pull request #3810
Opened 2023-01-22 17:14 UTC by antharir

New entry in data

2023-01-22 17:56 UTC, Aadarsh805 requested changes
Change file name to `data/antharir.json`

2023-01-22 17:56 UTC, Aadarsh805 commented on data/RajeshAnthari.json
> +      "icon": "FaLinkedIn"
Change this icon to `FaLinkedin`

2023-01-23 04:13 UTC, antharir commented on data/RajeshAnthari.json
> +      "icon": "FaLinkedIn"
updated.
Thanks,

2023-01-23 13:13 UTC, amandamartin-dev submitted a review, later dismissed
Looks good, just need to make sure your json file name exactly matches your github profile as @Aadarsh805 noted

2023-01-23 16:40 UTC, antharir commented
> Looks good, just need to make sure your json file name exactly matches your github profile as @Aadarsh805 noted

Thanks, Amanda. Updated the file name.

2023-01-23 16:48 UTC, antharir commented
> Change file name to `data/antharir.json`

Done @Aadarsh805

2023-01-23 17:01 UTC, antharir reviewed
Completed change requests.

2023-01-23 18:58 UTC, SaraJaoude approved these changes
looks good

2023-01-23 18:59 UTC, merged