Create sambhavrana27.json'
EddieHubCommunity/LinkFree pull request #3838
Opened 2023-01-23 13:03 UTC by sambhavrana27

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-23 13:55 UTC, Tejender1521 approved these changes
Everything looks good to me

2023-01-23 16:25 UTC, sambhavrana27 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->Thanks, Mr. Upadhyay !!!  Means a lot .From: TEJENDER UPADHYAYSent: 23 January 2023 07:25 PMTo: EddieHubCommunity/LinkFreeCc: Sambhav Rana; MentionSubject: Re: [EddieHubCommunity/LinkFree] Create sambhavrana27.json' (PR ***@***.*** approved this pull request.Everything looks good to me—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 

2023-01-23 17:17 UTC, kumarsonsoff3 submitted a review, later dismissed
Please move your file to data directory. 

Change the filename from `'data/sambhavrana27.json'`  - >  `data/sambhavrana27.json`

2023-01-27 17:56 UTC, devvsakib requested changes
you can add tags like this:
![image](https://user-images.githubusercontent.com/88339569/215159835-582f22dc-61fc-46ac-8a5a-6b3132875293.png)

2023-01-28 05:02 UTC, devvsakib requested changes

2023-01-28 05:02 UTC, devvsakib commented on 'data/sambhavrana27.json'
> +      "icon": "FaLinkedIn"
icon name: FaLinkedin

2023-02-13 08:58 UTC, merged