data:cybergeekgyan
EddieHubCommunity/LinkFree pull request #3865
Opened 2023-01-23 21:01 UTC by cybergeekgyan

2023-01-23 22:53 UTC, Panquesito7 requested changes
Wrong icon names and missing commas.

2023-01-23 22:53 UTC, Panquesito7 commented on data/cybergeekgyan.json
> +    }
```suggestion
    },
```

2023-01-23 22:53 UTC, Panquesito7 commented on data/cybergeekgyan.json
> +{
```suggestion
    },
    {
```

2023-01-23 22:53 UTC, Panquesito7 commented on data/cybergeekgyan.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-01-23 22:53 UTC, Panquesito7 commented on data/cybergeekgyan.json
> +      "icon": "FaGitHub"
```suggestion
      "icon": "FaGithub"
```

2023-01-24 15:30 UTC, SaraJaoude approved these changes
looks good

2023-01-24 15:31 UTC, merged