Update jmgrd98.json
EddieHubCommunity/LinkFree pull request #3979
Opened 2023-01-25 17:53 UTC by jmgrd98

## Changes proposed

Just editing my profile!

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-25 18:03 UTC, dan-mba requested changes
Remove the `,` on line 23 to fix the JSON check

2023-01-25 18:40 UTC, ChinmayMhatre requested changes

2023-01-25 18:40 UTC, ChinmayMhatre commented on data/jmgrd98.json
> +    },
```suggestion
    }
```
Please remove this comma

2023-01-27 10:55 UTC, SaraJaoude approved these changes
looks good

2023-01-27 10:55 UTC, merged