data: mhdamaan79
EddieHubCommunity/LinkFree pull request #4010
Opened 2023-01-26 09:23 UTC by mhdamaan79

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-26 09:40 UTC, stevenovak123 commented on data/mhdamaan79.json
> +  "avatar": "https://github.com/mhdamaan79.png"
a comma is required after avatar `,`

2023-01-26 09:43 UTC, stevenovak123 requested changes

2023-01-26 09:43 UTC, stevenovak123 commented on data/mhdamaan79.json
> +  "avatar": "https://github.com/mhdamaan79.png"
Comma required at the end of line

2023-01-26 09:55 UTC, mhdamaan79 commented
@stevenovak123 thanks, I've just corrected it.

2023-01-26 10:00 UTC, stevenovak123 requested changes

2023-01-26 10:00 UTC, stevenovak123 commented on data/mhdamaan79.json
> +      "icon": "FaTwitter",
here a comma is not required as its the end. Please correct. 
`  "icon": "FaTwitter"`

2023-01-26 10:02 UTC, stevenovak123 approved these changes
LGTM, Thank you for your contribution

2023-01-26 10:20 UTC, money8203 approved these changes

2023-01-26 12:15 UTC, mhdamaan79 commented
@stevenovak123 and @money8203 any update?
I mean what's next, is there anything left to be changed...

2023-01-26 14:43 UTC, stevenovak123 commented
Wait till a maintainer merges your request. thats it

2023-01-26 19:17 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-27 08:50 UTC, SaraJaoude approved these changes
looks good

2023-01-27 08:51 UTC, merged