Create Harman97.json
EddieHubCommunity/LinkFree pull request #4032
Opened 2023-01-26 14:33 UTC by Hrmn97

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-26 14:38 UTC, AbbeyIT requested changes
Hi kindly rename your file accordingly with your GitHub username which is `Hrmn97`.

2023-01-26 19:17 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-27 05:24 UTC, Sindhuinti approved these changes

2023-01-27 08:36 UTC, SaraJaoude commented on data/Hrmn97.json
> +        "name": "COnnect with me on GitHub",
Not a blocker but you may want to fix this in a future PR

```suggestion
        "name": "Connect with me on GitHub",
```

2023-01-27 08:36 UTC, SaraJaoude approved these changes
looks good

2023-01-27 08:37 UTC, merged