Lakshay Vardhan's json file was added to LinkFree
EddieHubCommunity/LinkFree pull request #405
Opened 2021-10-01 18:04 UTC by iwantamaste

2021-10-01 18:11 UTC, CodingSpecies requested changes

2021-10-01 18:11 UTC, CodingSpecies commented on public/data/LakshayVardhan.json
> +    },
@iwantamaste please can you remove the comma after the bracket.

2021-10-01 18:11 UTC, CodingSpecies commented on public/data/LakshayVardhan.json
> +  ],
Please remove the bracket.

2021-10-01 18:11 UTC, CodingSpecies commented on public/data/LakshayVardhan.json
> +    },
Please swap line 15 and 16.

2021-10-01 19:22 UTC, CodingSpecies approved these changes
Thank you @iwantamaste

2021-10-02 08:08 UTC, eddiejaoude commented on public/data/LakshayVardhan.json
> +
GitHub is highlighting that this needs an extra blank line - we can merge and this can be fixed later

2021-10-02 08:08 UTC, merged