Shreeyash garde patch 1
EddieHubCommunity/LinkFree pull request #4053
Opened 2023-01-26 17:08 UTC by ShreeyashGarde

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-26 19:22 UTC, Panquesito7 requested changes

2023-01-26 19:22 UTC, Panquesito7 commented on data/ShreeyashGarde.json
>        "url": "https://github.com/settings/profile",
Duplicate link.
```suggestion
```

2023-01-27 03:27 UTC, ShreeyashGarde commented
Changes done

2023-01-27 03:32 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-27 08:33 UTC, SaraJaoude approved these changes
looks good

2023-01-27 08:33 UTC, merged

2023-01-27 08:41 UTC, ShreeyashGarde commented
Thanks