Adding member JSON data
EddieHubCommunity/LinkFree pull request #410
Opened 2021-10-01 19:59 UTC by bamblebam

2021-10-01 20:07 UTC, CodingSpecies approved these changes
LGTM, thank you for contributing @bamblebam

2021-10-02 06:25 UTC, Kunal0007 requested changes

2021-10-02 06:25 UTC, Kunal0007 commented on public/data/bamblebam.json
> +
Please delete the last empty line

2021-10-02 08:24 UTC, rohan-kulkarni-25 commented on package.json
> +}
- Please don't commit package.json

2021-10-03 01:20 UTC, Panquesito7 requested changes

2021-10-03 01:20 UTC, Panquesito7 commented on public/data/bamblebam.json
> +}
```suggestion
}

```

2021-10-03 01:20 UTC, Panquesito7 commented on public/data/bamblebam.json
> +  "bio": "Web Developer, Machine Learning Engineer, ML-OPS, Web3, FreeLancer",
```suggestion
  "bio": "Web Developer, Machine Learning Engineer, ML-OPS, Web3, and Freelancer",
```

2021-10-04 04:05 UTC, krishguptadev approved these changes
LGTM

2021-10-04 16:07 UTC, merged