I have added my json file, please check
EddieHubCommunity/LinkFree pull request #4133
Opened 2023-01-27 18:34 UTC by Its-Aman-Yadav

## Changes proposed
I have added my json file, as suggested in the documentation

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

2023-01-28 13:17 UTC, amandamartin-dev commented
This looks great as far as format goes, but was curious if you meant to only add your twitter (and not also github or other links you may have)

You totally don't have to add anything else, just checking before I merge! lmk

2023-01-28 13:18 UTC, amandamartin-dev requested changes

2023-01-28 13:18 UTC, amandamartin-dev commented on data/Its-Aman-Yadav.json
> +  "bio": "Undergrad at KCCITM, just exploring this world :)",
you are missing your avatar.  See docs here step 9 https://linkfree.eddiehub.io/docs/quickstart

2023-01-29 10:55 UTC, Its-Aman-Yadav commented
@amandamartin-dev done ma'am, please have a look now :)

2023-01-29 18:43 UTC, closed without merging