create samarth8765.json
EddieHubCommunity/LinkFree pull request #4136
Opened 2023-01-27 19:38 UTC by samarth8765

2023-01-27 19:50 UTC, Pradumnasaraf reviewed
Hey, 

Add your profile to the `data` folder. which is on root of the project

2023-01-27 20:08 UTC, samarth8765 commented
Hey, @Pradumnasaraf thanks for helping.
I have added my profile to the data folder

2023-01-28 04:59 UTC, Sindhuinti submitted a review, later dismissed
Looks good 👍🏻

2023-01-28 17:56 UTC, kumarsonsoff3 requested changes

2023-01-28 17:56 UTC, kumarsonsoff3 commented on data/samarth8765.json
> +      "url": "https://twitter.com/samarthdhawan2911",
Please update it with your LinkedIn URL! 🛠

2023-01-28 18:15 UTC, samarth8765 commented
@kumarsonsoff3 Thanks for the update....I have updated the linkedIn url

2023-01-28 18:44 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-01-28 18:45 UTC, merged