Update shubhsharma19.json
EddieHubCommunity/LinkFree pull request #4153
Opened 2023-01-28 06:39 UTC by shubhsharma19

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers
:) have a great weekend

2023-01-28 06:51 UTC, shubhsharma19 commented
Yipee Fixed the conflict issue myself :)

2023-01-28 14:50 UTC, rahulpandey70 submitted a review, later dismissed
LGTM

2023-01-28 18:16 UTC, kumarsonsoff3 requested changes
Please remove all the duplicate fields from the file, like you've used the `name` twice for your links , `description`, `title` keys multiple times for same milestone.

Let us know if you need any help with this!

2023-01-28 18:16 UTC, kumarsonsoff3 commented on data/shubhsharma19.json
> +    { "icon": "FaInstagram", "url": "https://instagram.com/code.shubh/" },
Seems like you've added same Instagram link twice. Please remove one of them. 

```suggestion
```

2023-01-28 18:16 UTC, kumarsonsoff3 commented on data/shubhsharma19.json
> +  "bio": "BCA Graduate | **Open Source** Advocate | Fullstack Web Development | Designer and Content Creator | Technical Writer | Music Producer",
You've added same bio twice. Please remove one of them. 

```suggestion
```

2023-01-29 07:31 UTC, shubhsharma19 commented
Fixed it

2023-01-30 04:35 UTC, Panquesito7 requested changes
Looks like there are duplicated fields in the links. You might want to remove one of those.

2023-01-30 11:46 UTC, shubhsharma19 commented
Fixed :)

2023-01-30 16:38 UTC, merged