data kingDOM2227
EddieHubCommunity/LinkFree pull request #4159
Opened 2023-01-28 07:52 UTC by kingDOM2227

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-28 11:22 UTC, swagataroy30 reviewed
Can you please remove the comma from line 12. Thanks you!

2023-01-28 11:22 UTC, swagataroy30 commented on data/kingDOM2227.json
> +    "Javascript",
```suggestion
    "Javascript"
```

2023-01-29 17:11 UTC, Pradumnasaraf requested changes
Hey,

In the recent update, we don't need to add `avatar:` anymore, it will auto-pick your GitHub profile picture. So, please remove that. If you need any help feel free to ask.

Updated docs: https://linkfree.eddiehub.io/docs/quickstart

2023-01-29 17:11 UTC, Pradumnasaraf commented on data/kingDOM2227.json
> +  "avatar": "https://github.com/kingDOM2227.png",
```suggestion
```

2023-02-13 05:14 UTC, SaraJaoude commented on data/kingDOM2227.json
> +  "displayStatsPublic": true,
Following an improvement, this is no longer needed
```suggestion
```

2023-02-13 05:35 UTC, merged