data:ayush-3150
EddieHubCommunity/LinkFree pull request #4210
Opened 2023-01-29 11:18 UTC by ayush-3150

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-29 13:02 UTC, Sindhuinti approved these changes
Looks good 👍🏻

2023-01-29 13:09 UTC, Aadarsh805 requested changes

2023-01-29 13:09 UTC, Aadarsh805 commented on data/ayush-3150.json
> +      "icon": "FaYouTube"
All good, just fix this youtube icon, use `FaYoutube`

2023-01-29 16:46 UTC, Pradumnasaraf requested changes
Hey,

In the recent update, we don't need to add `avatar:` anymore, it will auto-pick your GitHub profile picture. So, please remove that.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart

2023-01-29 16:46 UTC, Pradumnasaraf commented on data/ayush-3150.json
> +  "avatar":"https://avatars.githubusercontent.com/u/60433144?s=400&u=1945de7a9bb08a5ed799907763f2367285e77e80&v=4",
```suggestion
```

2023-02-01 04:56 UTC, ayush-3150 commented
First of all, Thank you for the time to review my pull request and for giving me comments. I have removed Avatar and fixed the youtube icon typo.

2023-02-01 08:54 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-01 18:27 UTC, merged