Devanshukoli patch 1
EddieHubCommunity/LinkFree pull request #4216
Opened 2023-01-29 13:52 UTC by Devanshukoli

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

2023-01-29 17:13 UTC, kumarsonsoff3 requested changes
Hey @Devanshukoli, Please make the below changes as suggested to validate your json + revert the changes from the `CHANGELOG.md` file. Let us know if you need any help with this. 

This video https://youtu.be/YUHS5Ana7Jw will help you with revert the changes.

2023-01-29 17:13 UTC, kumarsonsoff3 commented on data/Devanshukoli.json
> +  "bio": "A Recent Front-End Software Intern and Open-source contributor as well. Here to meet with nice people."
There is a missing comma `,` here. 
```suggestion
  "bio": "A Recent Front-End Software Intern and Open-source contributor as well. Here to meet with nice people.",
```

2023-01-29 17:13 UTC, kumarsonsoff3 commented on data/Devanshukoli.json
> +   {
Please add the missing links key here to validate your json. 

```suggestion
   "links": [ {
```

2023-01-30 06:27 UTC, Devanshukoli commented
@kumarsonsoff3 I have done as told. I guess. so please kindly view this if any further changes are required please say so!

2023-01-30 06:32 UTC, kumarsonsoff3 requested changes
Still you need to revert the changes from the `CHANGELOG.md`. You can refer this video https://youtu.be/YUHS5Ana7Jw will help you with this. 

Feel free to ask if you need any help.

2023-01-30 11:28 UTC, Devanshukoli commented
@kumarsonsoff3 hey, I actually tried to do as from the eddie's video. but Still am stuck. so could you help me?

2023-01-30 16:34 UTC, kumarsonsoff3 commented
> -So, i tried first, directly copying files from the main file(eddihub/linkfree) and that won't work? right?

@Devanshukoli, It also works because the one in your branch & base branch (EddieHubCommunity/linkfree) should be the same, then it will not be included in the PR. 

Don't worry, here you just need to add the last 2 lines as Panquesito7 suggested above. Should be good to go!

2023-01-31 00:56 UTC, Devanshukoli commented
Hey @Panquesito7 
![git](https://user-images.githubusercontent.com/99028806/215631088-8eaa622d-3e2c-4e09-8712-84c499ee8729.png)
I am doing as you have told but in bash it said **fatal error**

2023-01-31 04:23 UTC, Panquesito7 commented
> Hey @Panquesito7 ![git](https://user-images.githubusercontent.com/99028806/215631088-8eaa622d-3e2c-4e09-8712-84c499ee8729.png) I am doing as you have told but in bash it said **fatal error** -As earlier you told i just added missing lines, then in git bash commited and then tried to push origin test-doc but get above message...

You must clone and push to your fork instead, not the original repository.

2023-02-02 15:56 UTC, kumarsonsoff3 approved these changes
Fixed the CHANGELOG file for you. You can refer [these docs](https://linkfree.eddiehub.io/docs/how-to-guides/editing) if you need to make any other changes in your profile later. 🚀

2023-02-02 15:57 UTC, merged

2023-02-03 14:45 UTC, Devanshukoli commented
Yeeey! My PR is finally merged. Thanks for guiding me this through. @kumarsonsoff3 @Panquesito7