data:Malavi-Pande
EddieHubCommunity/LinkFree pull request #4227
Opened 2023-01-29 16:05 UTC by Malavi1

2023-01-29 16:36 UTC, Pradumnasaraf requested changes
Hey,

Please add your profile in `data` which is at the root of the project. 

Also, fix your JSON profile file naming. It should be `{your GitHub username}.json` ->  `Malavi1.json`. Otherwise, some features will not be functional in the future.

If you need any help feel free to ask.

2023-01-30 05:23 UTC, Panquesito7 requested changes

2023-01-30 05:23 UTC, Panquesito7 commented on data/Malavi1.json
> +      "description": "It helping me to document my Journey comprehensively through blogs,I am one of the top 10 participants of #Devretro2022"
Missing comma
```suggestion
      "description": "It helping me to document my Journey comprehensively through blogs,I am one of the top 10 participants of #Devretro2022",
```

2023-01-30 05:23 UTC, Panquesito7 commented on data/Malavi1.json
> +      "description": "I feel fortunate that I get to know about the open source and started contributing"
Same here.
```suggestion
      "description": "I feel fortunate that I get to know about the open source and started contributing",
```

2023-01-30 16:08 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-30 16:54 UTC, kumarsonsoff3 approved these changes
Looks good to merge. Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/215344023-67219781-455d-48b2-a6a0-504150ef7df9.png" /></p>

2023-01-30 16:56 UTC, merged