First Contribution
EddieHubCommunity/LinkFree pull request #4231
Opened 2023-01-29 16:48 UTC by SakshiShah29

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-29 16:50 UTC, Pradumnasaraf requested changes
Hey,

In the recent update, we don't need to add `avatar:` anymore, it will auto-pick your GitHub profile picture. So, please remove that.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart

Also, fix your JSON profile file naming. It should be `{your GitHub username}.json` ->  `SakshiShah29.json`. Otherwise, some features will not be functional in the future.

If you need any help feel free to ask.

2023-01-29 16:50 UTC, Pradumnasaraf commented on data/Sakshi.json
> +    "avatar":"https://github.com/SakshiShah29.png",
```suggestion
```

2023-01-29 16:55 UTC, SakshiShah29 commented on data/Sakshi.json
> +    "avatar":"https://github.com/SakshiShah29.png",
Changes made

2023-01-29 16:58 UTC, kumarsonsoff3 submitted a review, later dismissed

2023-01-29 16:58 UTC, kumarsonsoff3 commented on data/SakshiShah29.json
> +            "url":"https://www.eddiejaoude.io/"
Please update it with your URL instead, or else you can remove this field!

2023-01-30 04:46 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

<p align="center"><img src="https://user-images.githubusercontent.com/51878265/212091929-1fcc2fb2-b3b4-48cf-9ec4-5c827bfe47dc.png"></p>

2023-01-30 04:47 UTC, merged