Zuber8040 patch 1
EddieHubCommunity/LinkFree pull request #4254
Opened 2023-01-30 11:51 UTC by Zuber8040

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-30 16:20 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-30 18:16 UTC, kumarsonsoff3 requested changes

2023-01-30 18:16 UTC, kumarsonsoff3 commented on data/Zuber8040.json
> +			"url": "https://www.instagram.com/eddieandsaraexplore/",
Please update it with your LinkedIn URL. 🛠

2023-01-31 04:16 UTC, Zuber8040 reviewed
I have added the linkdln link

2023-01-31 04:30 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-01-31 06:54 UTC, SaraJaoude approved these changes
looks good

2023-01-31 06:54 UTC, merged