Update sidharthviz.json
EddieHubCommunity/LinkFree pull request #4298
Opened 2023-01-31 10:17 UTC by sidharthviz

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-31 10:43 UTC, iamthecloverly submitted a review, later dismissed

2023-01-31 18:48 UTC, Panquesito7 requested changes

2023-01-31 18:48 UTC, Panquesito7 commented on data/sidharthviz.json
> +	"Links": [{
This should be lowercase, I guess.
```suggestion
	"links": [{
```

2023-01-31 21:53 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-01 15:57 UTC, amandamartin-dev approved these changes

2023-02-01 15:58 UTC, merged