Create freedompraise.json
EddieHubCommunity/LinkFree pull request #4324
Opened 2023-01-31 20:16 UTC by freedompraise

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-01-31 22:25 UTC, Aadarsh805 requested changes
Hey @freedompraise I see that you have commited three other files along with your `.json` file, you need to remove the other from the commit

2023-01-31 22:30 UTC, Aadarsh805 requested changes
Also, your file name is incorrect, you need to change it to `data/freedompraise.json` without the `public`

2023-01-31 22:30 UTC, Aadarsh805 commented on public/data/freedompraise.json
> +  "avatar":
you can remove this avatar field from here, and you must have links field in your profile for it to work

2023-01-31 22:30 UTC, Aadarsh805 commented
Feel free to ask for help, if you're stuck somewhere

2023-02-01 10:40 UTC, freedompraise commented
> Feel free to ask for help, if you're stuck somewhere

Thank you so much. I am relatively new and trying to find my way around in this space.

2023-02-01 10:49 UTC, closed without merging