created freedompraise.json
EddieHubCommunity/LinkFree pull request #4339
Opened 2023-02-01 10:58 UTC by freedompraise

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-01 16:50 UTC, senali-d requested changes
@freedompraise Please revert the changes in the files other than the `data/freedompraise.json` file.

2023-02-01 16:50 UTC, senali-d commented on data/freedompraise.json
> +    },
Remove `,`
```suggestion
    }
```

2023-02-01 17:06 UTC, kumarsonsoff3 requested changes
Please resolve merge conflicts [here](https://github.com/EddieHubCommunity/LinkFree/pull/4339/conflicts). Let us know if you need any help with this. :)

2023-02-08 19:19 UTC, kumarsonsoff3 commented
Hey @freedompraise, do you need any help in making the requested changes? Feel free to let us know. :)

You can use the command line to resolve merge conflicts following these steps. 
- Step 1: From your project repository, check out a new branch and test the changes.

```
git checkout -b freedompraise-main main
git pull https://github.com/freedompraise/LinkFree.git main
```

- Step 2: Merge the changes and update on GitHub.
```
git checkout main
git merge --no-ff freedompraise-main
git push origin main
```

2023-02-13 08:28 UTC, eddiejaoude commented
It looks like GitHub Actions are running in your fork, please disable these to avoid these generated files.

Also it is better to make changes in a branch, so I will close pull request, you can follow our quickstart guide here and create a new pull request https://linkfree.eddiehub.io/docs/quickstart

2023-02-13 08:28 UTC, closed without merging