data: vishalrathore8oct
EddieHubCommunity/LinkFree pull request #4349
Opened 2023-02-01 15:51 UTC by vishalrathore8oct

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-01 16:07 UTC, swagataroy30 reviewed
Can you please remove the comma from line 31. Thank You!

2023-02-01 16:07 UTC, swagataroy30 commented on data/vishalrathore8oct.json
> +    },
```suggestion
    }
```

2023-02-01 17:41 UTC, Krishnapro requested changes
please remove `,` after `}` from line 31.

2023-02-02 18:20 UTC, rupali-codes commented on data/vishalrathore8oct.json
> +      "name": "Follow me on Showcase",
It should be `Showwcase`

2023-02-02 18:24 UTC, rupali-codes commented on data/vishalrathore8oct.json
> +      "name": "Follow me on Showcase",
```suggestion
      "name": "Follow me on Showwcase",
```

2023-02-13 04:28 UTC, merged