data:Kordedekehine
EddieHubCommunity/LinkFree pull request #4352
Opened 2023-02-01 17:39 UTC by Kordedekehine

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-01 17:52 UTC, ChinmayMhatre requested changes
Hey @Kordedekehine , Profile looks great. A few minor changes.

-  Please add the suggestions in the json file.
- Please move the json file to the `data` directory.


Thank you!

2023-02-01 17:52 UTC, ChinmayMhatre commented on Kordedekehine.json
> +    }
```suggestion
    },
```

2023-02-01 17:52 UTC, ChinmayMhatre commented on Kordedekehine.json
> +    }
```suggestion
    },
```

2023-02-01 17:52 UTC, ChinmayMhatre commented on Kordedekehine.json
> +    }
```suggestion
    },
```

2023-02-02 15:19 UTC, Hrishi5111998 reviewed
hey @Kordedekehine, please update **icon** value to **FaLinkedin** rather than FaLinkedIn. thank you!

2023-02-02 15:37 UTC, Kordedekehine commented
> 

I have made the changes now. Thank you.

2023-02-02 15:38 UTC, kumarsonsoff3 requested changes
Please move your file to `data` directory. You need to rename your [file here](https://github.com/Kordedekehine/LinkFree/edit/Kordedekehine-patch-1/Kordedekehine.json) to exact `data/Kordedekehine.json`.

- Change `Kordedekehine.json` to `data/Kordedekehine.json` here. 

Let us know if you need any help with this! :)

![image](https://user-images.githubusercontent.com/88786642/216369811-3c37e1f2-ad99-4105-ba30-2c770df479f6.png)

2023-02-02 18:27 UTC, rupali-codes reviewed
lgtm

2023-02-03 08:04 UTC, Kordedekehine commented
> Please move your file to `data` directory. You need to rename your [file here](https://github.com/Kordedekehine/LinkFree/edit/Kordedekehine-patch-1/Kordedekehine.json) to exact `data/Kordedekehine.json`.
> 
> * Change `Kordedekehine.json` to `data/Kordedekehine.json` here.
> 
> Let us know if you need any help with this! :)
> 
> ![image](https://user-images.githubusercontent.com/88786642/216369811-3c37e1f2-ad99-4105-ba30-2c770df479f6.png)

Fixed now

2023-02-03 12:40 UTC, kumarsonsoff3 commented
It seems to be a Duplicate of #4388, which is being merged recently. So closing this one. 

--------------------------
You can access your profile here https://linkfree.eddiehub.io/Kordedekehine. 
For any changes you need to make in your profile, you can follow this guide - https://linkfree.eddiehub.io/docs/how-to-guides/editing :)

2023-02-03 12:40 UTC, closed without merging