data: add ams0.json
EddieHubCommunity/LinkFree pull request #4386
Opened 2023-02-02 14:55 UTC by ams0

## Changes proposed

Add [ams0](https://github.com/ams0) to EddieHub' LinkFree!

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

Thank you!

2023-02-02 15:08 UTC, kumarsonsoff3 requested changes

2023-02-02 15:08 UTC, kumarsonsoff3 commented on data/ams0.json
> +  "avatar": "https://github.com/ams0.png",
As of our latest update, we no longer need the `avatar` key. So please remove this from your file. 🛠

```suggestion
```

2023-02-02 15:41 UTC, kumarsonsoff3 submitted a review, later dismissed
Looks good, Thanks! 🎉

2023-02-02 18:29 UTC, rupali-codes reviewed
lgtm :)

2023-02-03 07:12 UTC, Panquesito7 requested changes

2023-02-03 07:12 UTC, Panquesito7 commented on data/ams0.json
> +    { "icon": "FaLinkedIn", "url": "https://www.linkedin.com/in/alessandrovozza/" }
Wrong icon name.
```suggestion
    { "icon": "FaLinkedin", "url": "https://www.linkedin.com/in/alessandrovozza/" }
```

2023-02-03 09:36 UTC, priyankarpal submitted a review, later dismissed
LGTM 👍🏻

2023-02-03 18:47 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-04 16:10 UTC, merged