data : priyanshu-11000
EddieHubCommunity/LinkFree pull request #4450
Opened 2023-02-03 20:06 UTC by priyanshu-11000

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-03 20:17 UTC, Panquesito7 requested changes

2023-02-03 20:17 UTC, Panquesito7 commented on data/priyanshu-11000.json
> +    "avatar": "https://bit.ly/3JDlnoa",
The `avatar` field is no longer required as of a new update.
```suggestion
```

2023-02-03 23:11 UTC, schmelto approved these changes

2023-02-04 00:08 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-02-04 03:50 UTC, priyankarpal requested changes

2023-02-04 03:50 UTC, priyankarpal commented on data/priyanshu-11000.json
> +      "HTML/CSS"
You can add separate Tags such as "HTML", "CSS"

2023-02-04 08:37 UTC, priyanshu-11000 reviewed
Added some more tags in the file.

2023-02-04 09:33 UTC, priyankarpal approved these changes
LGTM 👍🏻

2023-02-05 01:49 UTC, amandamartin-dev approved these changes

2023-02-05 09:34 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 


<p align="center"><img src="https://user-images.githubusercontent.com/88786642/216811557-7e40cee4-1318-426e-9852-b75ec24e25f6.png" /></p>

2023-02-05 09:35 UTC, merged