data:rahul152-ai
EddieHubCommunity/LinkFree pull request #4454
Opened 2023-02-04 04:23 UTC by rahul152-ai

2023-02-04 06:13 UTC, priyankarpal approved these changes
LGTM 👍🏻 Thanks for your contribution

2023-02-04 10:37 UTC, himanshu1221 requested changes
Hey your linkedin link doesnt seems like to be working 

`"url": "https://www.linkedin.com/in/ahul-kumar-0674bb214/"`

2023-02-04 10:50 UTC, rahul152-ai commented
> Hey your linkedin link doesnt seems like to be working
> 
> `"url": "https://www.linkedin.com/in/ahul-kumar-0674bb214/"`
Thank you for noticing that. I will update that

2023-02-04 12:21 UTC, priyankarpal approved these changes
LGTM 👍🏻

2023-02-04 14:09 UTC, priyankarpal submitted a review, later dismissed
LGTM

2023-02-05 09:41 UTC, kumarsonsoff3 reviewed
Rest looks good to me! 👍

2023-02-05 09:41 UTC, kumarsonsoff3 commented on data/rahul152-ai.json
> +  "bio": "New in opens source",
Did you mean `open source`.
```suggestion
  "bio": "New to open source",
```

2023-02-05 11:27 UTC, himanshu1221 approved these changes
LGTM :+1:  
Thanks for contributing 😃

2023-02-05 12:22 UTC, rahul152-ai commented
> LGTM 👍 Thanks for contributing 😃

Who will merges this pull request into [EddieHubCommunity: main]?

2023-02-05 12:29 UTC, himanshu1221 commented
> > LGTM 👍 Thanks for contributing 😃
> 
> Who will merges this pull request into [EddieHubCommunity: main]?
> 

Maintainer will merge it

2023-02-05 12:35 UTC, rahul152-ai commented
@himanshu1221 should I close this pull request or wait to merge it?

2023-02-05 12:37 UTC, himanshu1221 commented
> @himanshu1221 should I close this pull request or wait to merge it?

You should wait for getting it merge

2023-02-05 14:54 UTC, kumarsonsoff3 approved these changes
Looks good, Thank you for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/216811557-7e40cee4-1318-426e-9852-b75ec24e25f6.png" /></p>

2023-02-05 14:55 UTC, merged

2023-02-05 15:14 UTC, rahul152-ai commented
Hey, @kumarsonsoff3  While setting up this project I got the following error Do I need to install the next-auth/react? 
![e5e052f1-1dff-49d1-9ccc-0704a151b205](https://user-images.githubusercontent.com/77874363/216827452-d4305730-6286-44e2-9d6b-2d26b8e56cc9.jpg)