Rename and update the username
EddieHubCommunity/LinkFree pull request #4460
Opened 2023-02-04 10:17 UTC by YashkShrivas4491

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-04 10:20 UTC, priyankarpal approved these changes
LGTM 👍🏻 Thankas for your contribution.

2023-02-04 10:21 UTC, YashkShrivas4491 commented
> LGTM 👍🏻 Thankas for your contribution.

Thanks 🤩🚀

2023-02-04 14:19 UTC, Hrishi5111998 reviewed
hey @YashkShrivas4491 you have mistakenly added wrong link to your **github** profile, please remove **.png** extension from your link. thank you!

2023-02-04 14:21 UTC, priyankarpal requested changes

2023-02-04 14:21 UTC, priyankarpal commented on data/YashkShrivas4491.json
> +      "url": "https://github.com/YashkShrivas4491.png",
change the URL

2023-02-04 14:22 UTC, YashkShrivas4491 commented on data/YashkShrivas4491.json
> +      "url": "https://github.com/YashkShrivas4491.png",
ok

2023-02-04 14:26 UTC, YashkShrivas4491 commented
> hey @YashkShrivas4491 you have mistakenly added wrong link to your **github** profile, please remove **.png** extension from your link. thank you!

Dove☑️

2023-02-04 14:27 UTC, YashkShrivas4491 commented on data/YashkShrivas4491.json
> +      "url": "https://github.com/YashkShrivas4491.png",
Done

2023-02-04 14:29 UTC, priyankarpal approved these changes
LGTM

2023-02-04 15:14 UTC, Hrishi5111998 submitted a review, later dismissed
LGTM

2023-02-06 21:24 UTC, Panquesito7 requested changes
Please revert the changes in the other files and keep your profile changes only.
Let us know if you need any help doing that. 🙂

2023-02-07 11:34 UTC, priyankarpal requested changes
hey, @YashkShrivas4491 here is a conflict error please solve it.

2023-02-07 15:10 UTC, YashkShrivas4491 commented
> Please revert the changes in the other files and keep your profile changes only. Let us know if you need any help doing that. 🙂

I deleted conflicting files , that's all i can do from my side . if any improvement needed , guide me

2023-02-07 17:12 UTC, priyankarpal requested changes
hey @YashkShrivas4491 here is a conflicts error you need to solve it. If you don't know you can check this official doc https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github
You can ask here if you're facing any problems. ✌️

2023-02-07 17:39 UTC, YashkShrivas4491 commented
> hey @YashkShrivas4491 here is a conflicts error you need to solve it. If you don't know you can check this official doc https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github You can ask here if you're facing any problems. ✌️

Can you tell me why this conflicts are occurring

2023-02-08 12:43 UTC, priyankarpal commented
> > hey @YashkShrivas4491 here is a conflicts error you need to solve it. If you don't know you can check this official doc https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github You can ask here if you're facing any problems. v
> 
> Can you tell me why this conflicts are occurring

Conflicts in GitHub can occur when two or more users make separate changes to the same line or block of code in a shared repository, and Git is unable to automatically merge these changes. This can lead to a conflict that needs to be resolved manually. Other factors that can contribute to conflicts include conflicting changes made to the same file, different branches being merged, or changes to files being pushed simultaneously. It's important to regularly pull updates from the repository and communicate with other contributors to prevent conflicts from occurring.

2023-02-09 13:44 UTC, YashkShrivas4491 commented
> > > hey @YashkShrivas4491 here is a conflicts error you need to solve it. If you don't know you can check this official doc https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github You can ask here if you're facing any problems. v
> > 
> > 
> > Can you tell me why this conflicts are occurring
> 
> Conflicts in GitHub can occur when two or more users make separate changes to the same line or block of code in a shared repository, and Git is unable to automatically merge these changes. This can lead to a conflict that needs to be resolved manually. Other factors that can contribute to conflicts include conflicting changes made to the same file, different branches being merged, or changes to files being pushed simultaneously. It's important to regularly pull updates from the repository and communicate with other contributors to prevent conflicts from occurring.

sure ☑️

2023-02-15 06:14 UTC, eddiejaoude commented
Wow a lot of collaboration going on here which is great 👍 

But unfortunately, deleting the files is not correct as these files are needed, you should remove the changes from your pull request not delete the files as these are still changes

I think it is best, if I close this pull request and you follow the quickstart guide and create a new pull request https://linkfree.eddiehub.io/docs/quickstart

2023-02-15 06:14 UTC, closed without merging

2023-02-15 08:44 UTC, YashkShrivas4491 commented
> Wow a lot of collaboration going on here which is great 👍
> 
> But unfortunately, deleting the files is not correct as these files are needed, you should remove the changes from your pull request not delete the files as these are still changes
> 
> I think it is best, if I close this pull request and you follow the quickstart guide and create a new pull request https://linkfree.eddiehub.io/docs/quickstart

yup Sure I will do it