Added Milestones and minor changes.
EddieHubCommunity/LinkFree pull request #4465
Opened 2023-02-04 12:27 UTC by bhattabhi013

## Changes proposed

Added new milestones to my profile. 
Added bifurcation/ groups to the links section.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

I've added milestones to my profile.

2023-02-04 12:28 UTC, priyankarpal requested changes
Hey, there is a conflict please resolve it.

2023-02-04 12:36 UTC, priyankarpal approved these changes
LGTM ⚡

2023-02-04 12:36 UTC, bhattabhi013 commented
> Hey, there is a conflict please resolve it.

Thanks for responding. Conflicts resolved.

2023-02-05 05:25 UTC, stevenovak123 requested changes

2023-02-05 05:25 UTC, stevenovak123 commented on data/bhattabhi013.json
> +    "avatar": "https://github.com/bhattabhi013.png",
Avatar can be removed as it is automatically pickedup from GitHub

2023-02-05 09:36 UTC, priyankarpal requested changes
Fix these problems

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "github"
AAd this GitHub icon
``` suggestion
        "icon": "SiGithub"
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "twitter"
Add this Twitter icon
``` suggestion
        "icon": "SiTwitter"
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "linkedin"
Add this LinkedIn icon
``` suggestion
        "icon": "SiLinkedin"
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "FaAndroid"
``` suggestion
        "icon": "FaGooglePlay"
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "globe",
```suggestion
        "icon": "FaGlobe",
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "globe",
```suggestion
        "icon": "FaGlobe",
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "globe",
```suggestion
        "icon": "FaMedapps",
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "globe",
```suggestion
        "icon": "FaGlobe",
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "github",
```suggestion
        "icon": "SiGithub",
```

2023-02-05 09:36 UTC, priyankarpal commented on data/bhattabhi013.json
> +        "icon": "android",
```suggestion
        "icon": "FaGooglePlay",
```

2023-02-05 12:22 UTC, bhattabhi013 commented
> Fix these problems

Hi, Issue resolved

2023-02-05 12:40 UTC, priyankarpal submitted a review, later dismissed
LGTM 👍🏻

2023-02-05 12:40 UTC, priyankarpal commented
> Hi, Issue resolved

Done

2023-02-06 21:31 UTC, Panquesito7 requested changes

2023-02-06 21:31 UTC, Panquesito7 commented on data/bhattabhi013.json
> +      { "platform": "instagram", "url": "https://www.instagram.com/bwith_abhi" }
Should be `icon`. Not sure `platform` is valid?
```suggestion
      { "platform": "FaTwitter", "url": "https://twitter.com/AbhishekBtwt" },
      { "platform": "FaGithub", "url": "https://github.com/bhattabhi013" },
      { "platform": "FaInstagram", "url": "https://www.instagram.com/bwith_abhi" }
```

2023-02-06 21:50 UTC, Panquesito7 requested changes

2023-02-06 21:50 UTC, Panquesito7 commented on data/bhattabhi013.json
> +      { "platform": "FaInstagram", "url": "https://www.instagram.com/bwith_abhi" }
```suggestion
      { "icon": "FaTwitter", "url": "https://twitter.com/AbhishekBtwt" },
      { "icon": "FaGithub", "url": "https://github.com/bhattabhi013" },
      { "icon": "FaInstagram", "url": "https://www.instagram.com/bwith_abhi" }
```

2023-02-07 03:05 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-07 18:25 UTC, stevenovak123 approved these changes

2023-02-09 05:05 UTC, SaraJaoude approved these changes
looks good

2023-02-09 05:06 UTC, merged