update my bio and links
EddieHubCommunity/LinkFree pull request #4483
Opened 2023-02-05 03:22 UTC by shivam-sharma7

update my bio and links

 
  

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-05 03:24 UTC, shivam-sharma7 commented
review/ @Pradumnasaraf

2023-02-05 03:46 UTC, priyankarpal commented on data/shivam-sharma7.json
>        "name": "Blog's",
``` suggestion
      "name": "Blog",
```

2023-02-05 03:47 UTC, priyankarpal requested changes
fix this spelling

2023-02-05 09:27 UTC, priyankarpal requested changes

2023-02-05 09:27 UTC, priyankarpal commented on data/shivam-sharma7.json
>        "icon": "FaLink"
Add Hashnode icon
``` suggestion
      "icon": "SiHashnode"
```

2023-02-05 12:41 UTC, priyankarpal approved these changes
LGTM 👍🏻

2023-02-06 14:18 UTC, Pradumnasaraf commented
> review/ @Pradumnasaraf

Hey, you need to ping any specific maintainers. Anyone can review and merge

2023-02-06 14:18 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-06 14:19 UTC, merged