data: anthonrodgrs01
EddieHubCommunity/LinkFree pull request #4501
Opened 2023-02-05 08:19 UTC by anthonrodgrs01

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [yes ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ yes] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-05 08:35 UTC, AbbeyIT approved these changes
LGTM! Thank you for your contribution.

2023-02-05 08:57 UTC, kumarsonsoff3 requested changes

2023-02-05 08:57 UTC, kumarsonsoff3 commented on data/anthonrodgrs01.json
> +  "avatar": "https://github.com/anthonrodgrs01.png",
In our recent update, we no longer need the `avatar` key. So please remove this from your json file. 
```suggestion
```

2023-02-05 11:23 UTC, himanshu1221 approved these changes
LGTM:+1:

2023-02-05 14:59 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/216811557-7e40cee4-1318-426e-9852-b75ec24e25f6.png" /></p>

2023-02-05 15:46 UTC, Hrishi5111998 approved these changes

2023-02-05 15:51 UTC, anthonrodgrs01 commented
I am really new to open source even after all the checks it was showing the option for updating the branch so I clicked it, I am sorry if the maintainer had to go over again for me... I am really new to this.. I dont know if my pull request is merged or not

2023-02-06 05:13 UTC, anthonrodgrs01 commented
Can anyone merge my pull request

2023-02-06 14:05 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-06 14:05 UTC, merged