Updated my profile
EddieHubCommunity/LinkFree pull request #4507
Opened 2023-02-05 11:33 UTC by Jaideep25-tech

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-05 12:05 UTC, priyankarpal approved these changes
LGTM 👍🏻

2023-02-06 12:40 UTC, priyankarpal requested changes
There is a conflict error please resolve it.

2023-02-09 19:27 UTC, lewisushindi approved these changes

2023-02-13 09:49 UTC, SaraJaoude commented on data/priyanshu-11000.json
> +  "displayStatsPublic": true,
Further to an improvement this is no longer necessary:
```suggestion
```

2023-02-13 10:46 UTC, closed without merging