data:Taheer10
EddieHubCommunity/LinkFree pull request #4508
Opened 2023-02-05 11:37 UTC by Taheer10

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-05 12:00 UTC, priyankarpal requested changes
you created your json file in the leading directory. You need to make it into `data` directory `data/your-GitHub-user-name.json`

Just follow this video guide https://www.youtube.com/watch?v=05HEeCQSKRE&t=2s

2023-02-05 12:07 UTC, Taheer10 commented on Taheer10.json
> +  "avatar":"https://github.com/Taheer10.png"
How do i update  bio and change directory. The video does not show anything regarding update.

2023-02-05 12:18 UTC, priyankarpal requested changes

2023-02-05 12:18 UTC, priyankarpal commented on data/Taheer10.json
> +  "bio": "I am a frontend Developerand Love to Learn New technologies",
``` suggestion
  "bio": "I am a frontend Developer and Love to Learn New technologies",
```

2023-02-05 12:23 UTC, Taheer10 reviewed
Reviwed.

2023-02-05 12:39 UTC, priyankarpal commented
> Reviwed.

Just fix this small problem

2023-02-05 12:55 UTC, Taheer10 reviewed
Done

2023-02-05 12:57 UTC, Taheer10 commented
What do i do now ?

2023-02-05 13:37 UTC, priyankarpal approved these changes
LGTM 👍🏻

2023-02-05 13:37 UTC, priyankarpal commented
> What do i do now ?

Just wait It will merge soon by the maintainer.

2023-02-05 14:57 UTC, Sindhuinti approved these changes
LGTM 👍🏻

2023-02-05 15:39 UTC, Hrishi5111998 approved these changes

2023-02-06 21:35 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-07 02:39 UTC, SaraJaoude approved these changes
looks good

2023-02-07 02:39 UTC, merged