data:Vikkybliz
EddieHubCommunity/LinkFree pull request #4519
Opened 2023-02-05 17:50 UTC by Vikkybliz

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Opened my personal linkfree account

2023-02-05 17:58 UTC, priyankarpal requested changes

2023-02-05 17:58 UTC, priyankarpal commented on data/Vikkybliz.json
> +			"icon": "SiHashnode"
You added a wrong Icon. Change it to a YouTube icon.
``` suggestion
			"icon": "SiYoutube"
```

2023-02-06 12:36 UTC, priyankarpal approved these changes
LGTM 👍🏻

2023-02-06 21:45 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-07 02:43 UTC, SaraJaoude approved these changes
looks good

2023-02-07 02:43 UTC, merged