docs: Added Motasim's data
EddieHubCommunity/LinkFree pull request #456
Opened 2021-10-04 20:30 UTC by motasimmakki

2021-10-04 20:42 UTC, Panquesito7 requested changes

2021-10-04 20:42 UTC, Panquesito7 commented on public/data/motasimmakki.json
> +
```suggestion
```

2021-10-04 20:45 UTC, Panquesito7 requested changes

2021-10-04 20:45 UTC, Panquesito7 commented on public/data/motasimmakki.json
> +  }
```suggestion
}

```

2021-10-04 22:16 UTC, eddiejaoude approved these changes
Great collaboration 👍

2021-10-04 22:20 UTC, merged

2021-10-05 09:50 UTC, motasimmakki commented
@eddiejaoude Kindly invite me to join the org. ✨

2021-10-05 10:35 UTC, krishguptadev commented
Open a issue on our support repo to get invited: https://github.com/EddieHubCommunity/support/issues/new/choose