update oyenolaphilipinc.json
EddieHubCommunity/LinkFree pull request #4585
Opened 2023-02-07 13:06 UTC by oyenolaphilipinc

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-07 13:13 UTC, priyankarpal requested changes

2023-02-07 13:13 UTC, priyankarpal commented on data/oyenolaphilipinc.json
>    ]
Please add a `,` after bracket
``` suggestion
  ],
```

2023-02-07 13:14 UTC, oyenolaphilipinc commented on data/oyenolaphilipinc.json
>    ]
already added it and fixed it

2023-02-07 13:16 UTC, priyankarpal approved these changes
Yeah! 😎 Looks great.

2023-02-07 15:56 UTC, Hrishi5111998 approved these changes

2023-02-07 20:44 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-08 17:02 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-02-08 17:02 UTC, merged