Abhinav 6 patch 1
EddieHubCommunity/LinkFree pull request #4601
Opened 2023-02-08 06:14 UTC by Abhinav-6

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-08 06:53 UTC, rahulpandey70 requested changes
Hey, @Abhinav-6 please rename your json file name to data/Abhinav-6.json.

2023-02-08 06:54 UTC, Abhinav-6 commented
What's wrong with this. I have done everything according to the guide. Am I missing something.

2023-02-08 07:05 UTC, rahulpandey70 commented
> What's wrong with this. I have done everything according to the guide. Am I missing something.

Your file name should match to your github username.
like this :- ```data/Abhinav6.json to data/Abhinav-6.json```

2023-02-08 07:27 UTC, swagataroy30 reviewed
In the recent update, we don't need to add avatar: anymore, it will auto-pick your GitHub profile picture. So, please remove that.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart
Thank You!

2023-02-08 07:27 UTC, swagataroy30 commented on data/Abhinav6.json
> +  "avatar": "https://github.com/Abhinav-6.png",
```suggestion
```

2023-02-08 07:37 UTC, maharshi-sinha requested changes
There's no need of avatar! It'll automatically pick up your github profile pic.

2023-02-08 10:04 UTC, Hrishi5111998 requested changes
hey @Abhinav-6 please remove comma.
![2023-02-08](https://user-images.githubusercontent.com/115489262/217498707-af12053f-84e4-402c-a213-f022d1ad18b9.png)

2023-02-08 12:10 UTC, Abhinav-6 commented
I've edited the filename and remooved the avatar field. Now i think it is ready to merge.

2023-02-08 12:54 UTC, priyankarpal submitted a review, later dismissed
LGTM 👍🏻

2023-02-08 16:45 UTC, Panquesito7 requested changes

2023-02-08 16:45 UTC, Panquesito7 commented on data/Abhinav-6.json
> +    { "icon": "FaGithub", "url": "https://github.com/Abhinav-6" },
Extra comma in here (if I'm not wrong).
```suggestion
    { "icon": "FaGithub", "url": "https://github.com/Abhinav-6" }
```

2023-02-09 00:53 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-09 03:23 UTC, priyankarpal approved these changes
Awesome 🎉 let's get this merge.

2023-02-09 03:46 UTC, SaraJaoude approved these changes
looks good

2023-02-09 03:46 UTC, merged