add my profile anassbouchfar
EddieHubCommunity/LinkFree pull request #461
Opened 2021-10-05 20:14 UTC by anassbouchfar

2021-10-05 21:52 UTC, Panquesito7 requested changes

2021-10-05 21:52 UTC, Panquesito7 commented on public/data/anassbouchfar.json
> +
```suggestion
}
```

2021-10-05 21:52 UTC, Panquesito7 commented on public/data/anassbouchfar.json
> +        "icon": ""
```suggestion
        "icon": "website"
```

2021-10-05 21:52 UTC, Panquesito7 commented on public/data/anassbouchfar.json
> +    "bio": "Web Developer , BI & Analytics Engineer Student",
```suggestion
    "bio": "Web Developer, BI & Analytics Engineer Student",
```

2021-10-06 03:54 UTC, rohan-kulkarni-25 requested changes

2021-10-06 03:54 UTC, rohan-kulkarni-25 commented on public/data/anassbouchfar.json
> +
- Please delete these empty line

2021-10-06 03:57 UTC, krishguptadev requested changes

2021-10-06 03:57 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +
```suggestion
```

2021-10-06 03:57 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +}
```suggestion
}

```

2021-10-06 03:57 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +
```suggestion
```

2021-10-06 03:57 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +    ]
```suggestion
  ]
```

2021-10-06 04:05 UTC, krishguptadev requested changes

2021-10-06 04:05 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +        "icon": ""
Please add a icon here
```suggestion
        "icon": "book"
```

2021-10-06 04:05 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +        "name": "GitHub",
```suggestion
        "name": "Checkout my GitHub",
```

2021-10-06 04:05 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +        "name": "Twitter",
```suggestion
        "name": "Follow me on Twitter",
```

2021-10-06 04:05 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +        "name": "Blog",
```suggestion
        "name": "Read my Blog",
```

2021-10-06 04:05 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +        "name": "Portfolio",
```suggestion
        "name": "Visit my Website",
```

2021-10-06 04:05 UTC, krishguptadev commented on public/data/anassbouchfar.json
> +        "name": "E-mail",
```suggestion
        "name": "Contact me via E-mail",
```

2021-10-06 04:15 UTC, krishguptadev approved these changes

2021-10-06 13:24 UTC, schmelto approved these changes

2021-10-07 00:45 UTC, merged