data: Danypooh
EddieHubCommunity/LinkFree pull request #4619
Opened 2023-02-08 19:25 UTC by Danypooh

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-08 19:51 UTC, priyankarpal requested changes

2023-02-08 19:51 UTC, priyankarpal commented on data/Danypooh.json
> +  "avatar": "https://github.com/Danypooh.png"
Thanks for your first contribution. 🎉  Currently, you can delete this code. You don't need to add `avatar` code. 
``` suggestion
 
```

2023-02-11 01:28 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-12 03:18 UTC, SaraJaoude approved these changes
looks good

2023-02-12 03:18 UTC, merged