data: EndGaurav
EddieHubCommunity/LinkFree pull request #4630
Opened 2023-02-09 07:02 UTC by EndGaurav

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-09 07:10 UTC, ChinmayMhatre commented
Hey @EndGaurav , move the json file to the data directory

2023-02-09 07:26 UTC, EndGaurav commented
Hey @ChinmayMhatre please can you tell me how can i move that file to the data directory ?

2023-02-09 07:32 UTC, ChinmayMhatre commented
Have you setup Linkfree locally? Or did you do it on github?

2023-02-09 07:45 UTC, priyankarpal requested changes
hey, @EndGaurav you mistakenly created `json` file in the main folder. You have to change it to `data/EndGaurav.json` To change this check the [official doc ](https://linkfree.eddiehub.io/docs/quickstart). If you're facing any doubts you can ask. ✌️

2023-02-09 09:57 UTC, Hrishi5111998 requested changes
hey @EndGaurav there is typo in your bio newbier should be **newbie**

2023-02-09 13:49 UTC, EndGaurav commented
Hey @ChinmayMhatre i have done it on github. locally i can do that locally by forking. so please tell me will i have to create a new pull request for putting into data directory ?

2023-02-09 14:36 UTC, EndGaurav commented
@Hrishi5111998 there is no typo in my bio bro. where have you seen that ?

2023-02-11 05:36 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-02-11 05:40 UTC, EndGaurav commented
Hey @kumarsonsoff3 i have moved that file in data directory.

2023-02-11 13:32 UTC, kumarsonsoff3 requested changes

2023-02-11 13:32 UTC, kumarsonsoff3 commented on data/EndGaurav.json
> +  "displayStatsPublic": true,
This `displayStatsPublic` key is no longer needed as of our latest update, so please update it accordingly. 
```suggestion
```

2023-02-11 14:58 UTC, EndGaurav reviewed
have you deleted that "displayStatsPublic" : true ? or will i have to do thar. sorry i am little bit unable to understand that what exactly happening. can you tell me ?

2023-02-11 16:56 UTC, kumarsonsoff3 commented
> have you deleted that "displayStatsPublic" : true ? or will i have to do thar. sorry i am little bit unable to understand that what exactly happening. can you tell me ?

No worries, it does happen, I asked you to delete that field because we no longer need that. Hence you did the same. Now it's good to go! 🚀

2023-02-11 16:56 UTC, kumarsonsoff3 approved these changes

2023-02-11 16:57 UTC, merged

2023-02-12 14:02 UTC, EndGaurav commented
very  very thanks all of you guyss for helping me in this. can you help me how from here how can i get more involve in open source?

2023-02-17 13:22 UTC, kumarsonsoff3 commented
> very very thanks all of you guyss for helping me in this. can you help me how from here how can i get more involve in open source?

Hey Gaurav, you can check out other good first issues you can work on, in LinkFree. Also, there are tonnes of projects out there you can contribute to. You can use https://github.com/search/advanced to find projects that fits you more effectively. 

Any questions, we can chat on EddieHub Discord: http://discord.eddiehub.org/

2023-02-18 14:11 UTC, EndGaurav commented
okay, thanks @kumarsonsoff3 .