Update KrishnaTheCoder756.json
EddieHubCommunity/LinkFree pull request #4632
Opened 2023-02-09 09:10 UTC by KrishnaTheCoder756

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-09 09:49 UTC, Hrishi5111998 submitted a review, later dismissed

2023-02-09 09:57 UTC, priyankarpal requested changes
There is a conflict error. please resolve it. you can check this [official doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to solve this error. If you're facing any problem you can ask.

2023-02-09 15:19 UTC, kumarsonsoff3 commented
There are merge conflicts probably because you had an outdated branch. Updating your fork may resolve the conflicts or you can try suggestions by @priyankarpal.  🛠

2023-02-11 13:01 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-02-11 13:02 UTC, merged