data: RockingSNP
EddieHubCommunity/LinkFree pull request #4639
Opened 2023-02-09 15:26 UTC by RockingSNP

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-09 15:30 UTC, RockingSNP commented
Cannot pass the last check

2023-02-09 15:41 UTC, Sindhuinti requested changes

2023-02-09 15:41 UTC, Sindhuinti commented on data/RockingSNP.json
> +      "icon": "FaLinkedIn"
also change the `FaLinkedIn` to `Falinkedin`

2023-02-09 17:41 UTC, Krishnapro requested changes

2023-02-09 17:41 UTC, Krishnapro commented on data/RockingSNP.json
> +      "icon": "Fagithub"
```diff
-"icon": "Fagithub"
+"icon": "FaGithub"
```

please fix the typo in Github icon

2023-02-10 07:05 UTC, RockingSNP commented on data/RockingSNP.json
> +  "bio": "Full Stack Web Developer **Digital Nomad**. Explporer & Karma -te Prastut"
Thnx

2023-02-10 07:12 UTC, RockingSNP commented
`FaLinkedIn` changed to `FalikedIn`
`Fagithub` changed to `FaGithub`
Comma added

2023-02-10 15:57 UTC, kumarsonsoff3 requested changes

2023-02-10 15:57 UTC, kumarsonsoff3 commented on data/RockingSNP.json
> +  "displayStatsPublic": true,
As of our latest update, we no longer need the `displayStatsPublic` key. So please remove this field from your json. 

```suggestion
```

2023-02-10 15:59 UTC, kumarsonsoff3 requested changes

2023-02-10 15:59 UTC, kumarsonsoff3 commented on data/RockingSNP.json
> +    },
Also remove this extra comma `,` from here. 

```suggestion
    }
```

2023-02-11 10:16 UTC, RockingSNP commented
Is it good now?

2023-02-11 12:45 UTC, RockingSNP commented
Merge this please

2023-02-11 12:55 UTC, kumarsonsoff3 submitted a review, later dismissed

2023-02-11 12:55 UTC, kumarsonsoff3 commented on data/RockingSNP.json
> +      "icon": "FalinkedIn"
Looks good to me. 

>**Note**: You're using an `invalid` Linkedin icon here. It should be `FaLinkedin`, else the fallback icon FaGlobe will be used by default on your page. 
```suggestion
      "icon": "FaLinkedin"
```

2023-02-11 13:49 UTC, kumarsonsoff3 approved these changes

2023-02-11 13:50 UTC, merged