Add my profile merouanezouaid.json
EddieHubCommunity/LinkFree pull request #464
Opened 2021-10-06 15:07 UTC by merouanezouaid

2021-10-06 15:17 UTC, merouanezouaid commented on public/data/merouanezouaid.json
> +  }
done!

2021-10-06 15:26 UTC, krishguptadev requested changes

2021-10-06 15:26 UTC, krishguptadev commented on public/data/merouanezouaid.json
> +      "name": "Contact me",
```suggestion
      "name": "Contact me via E-Mail",
```

2021-10-06 15:28 UTC, krishguptadev approved these changes

2021-10-06 18:54 UTC, Panquesito7 approved these changes

2021-10-07 00:35 UTC, eddiejaoude commented
Great collaboration everyone

2021-10-07 00:42 UTC, merged