data: sheriffOladimeji
EddieHubCommunity/LinkFree pull request #4640
Opened 2023-02-09 15:58 UTC by sheriffOladimeji

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-09 16:18 UTC, priyankarpal requested changes

2023-02-09 16:18 UTC, priyankarpal commented on data/sheriffOladimeji.json
> +  "bio": "Frontend web developer, CS student"
hey, @sheriffOladimeji just add a comma.
``` suggestion
  "bio": "Frontend web developer, CS student",
```

2023-02-09 16:27 UTC, priyankarpal submitted a review, later dismissed
Looks good

2023-02-09 16:38 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-02-10 15:51 UTC, kumarsonsoff3 requested changes

2023-02-10 15:51 UTC, kumarsonsoff3 commented on data/sheriffOladimeji.json
> +  "displayStatsPublic": true,
We no longer need the `displayStatsPublic` key. So please remove this field from your json.

```suggestion
```

2023-02-11 01:35 UTC, Panquesito7 approved these changes

2023-02-11 12:59 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/218258654-0b081c88-8ed3-40ae-8887-84290310e2f9.png" /></p>

2023-02-11 12:59 UTC, merged