data:NikhilRaikwar
EddieHubCommunity/LinkFree pull request #4643
Opened 2023-02-09 18:18 UTC by NikhilRaikwar

## Fixes Issue

Adding my profile to LinkFree

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-02-09 18:31 UTC, priyankarpal requested changes

2023-02-09 18:31 UTC, priyankarpal commented on data/NikhilRaikwar.json
> +  "avatar": "https://github.com/NikhilRaikwar.png",
Currently, you don't need to add an avatar code. You have to delete it.
``` suggestion

```

2023-02-09 18:37 UTC, priyankarpal approved these changes
Looks good 🎉

2023-02-09 21:06 UTC, Panquesito7 requested changes

2023-02-09 21:06 UTC, Panquesito7 commented on data/NikhilRaikwar.json
> +      "icon": "FaLinkedIn"
Wrong icon name.
```suggestion
      "icon": "FaLinkedin"
```

2023-02-10 05:12 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-02-10 13:20 UTC, NikhilRaikwar commented
Hey anyone can give me details when my profile is available on LinkFree

2023-02-10 15:49 UTC, kumarsonsoff3 requested changes

2023-02-10 15:49 UTC, kumarsonsoff3 commented on data/NikhilRaikwar.json
> +  "displayStatsPublic": true,
As of the latest update, we no longer need `displayStatsPublic` property. So please remove this field from your json. 

```suggestion
```

2023-02-10 18:46 UTC, Panquesito7 approved these changes

2023-02-11 06:59 UTC, closed without merging

2023-02-11 13:06 UTC, kumarsonsoff3 commented
Hey @NikhilRaikwar, not sure why did you close the PR when it was about to merge!?

2023-02-11 13:33 UTC, NikhilRaikwar commented
Sorry for saying but I close this pr and Create a new pr and that pr is finally merge.

Thankyou for  your help.