data: kumarankit999
EddieHubCommunity/LinkFree pull request #4644
Opened 2023-02-09 18:40 UTC by kumarankit999

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-09 19:06 UTC, priyankarpal requested changes
Lastly, you mistakenly added your `kumarankit999.json` into the main folder. You have to create it to `data/kumarankit999.json`. So, kindly update it. 

If you're facing any problems don't forget to check the [official doc](https://linkfree.eddiehub.io/docs/quickstart) ✌️

2023-02-09 19:06 UTC, priyankarpal commented on kumarankit999.json
> +    },
Delete the last comma.
``` suggestion
    }
```

2023-02-09 19:06 UTC, priyankarpal commented on kumarankit999.json
> +  "avatar": "https://github.com/kumarankit999.png"
Currently, you don't need to add an avatar. You can delete it. It will automatically fetch from your GitHub ID.
``` suggestion
 
```

2023-02-10 03:37 UTC, kumarankit999 commented
thanks for veryfying

2023-02-10 05:21 UTC, Panquesito7 submitted a review, later dismissed
Please add your file under the `data` directory.
Let us know if you need any help with that. 🙂

2023-02-10 15:42 UTC, kumarsonsoff3 requested changes

2023-02-10 15:42 UTC, kumarsonsoff3 commented on kumarankit999.json
> +  "displayStatsPublic": true,
Also, remove the `displayStatsPublic` property as we no longer need this. 

```suggestion
```

2023-02-13 10:06 UTC, merged