data: SageKyle
EddieHubCommunity/LinkFree pull request #4646
Opened 2023-02-09 19:55 UTC by SageKyle

2023-02-09 22:45 UTC, Panquesito7 requested changes

2023-02-09 22:45 UTC, Panquesito7 commented on data/SageKyle.json
> +      "icon": "FaHashnode",
Wrong icon name.
```suggestion
      "icon": "SiHashnode",
```

2023-02-10 15:35 UTC, kumarsonsoff3 requested changes

2023-02-10 15:35 UTC, kumarsonsoff3 commented on data/SageKyle.json
> +  "displayStatsPublic": true,
We recently have removed the public stats feature. So `displayStatsPublic` property is no longer needed. 
Please remove this from your json. 

```suggestion
```

2023-02-10 18:37 UTC, Panquesito7 commented on data/SageKyle.json
> +       "color": "blue",
Wrong indentation.
```suggestion
      "color": "blue",
```

2023-02-10 19:58 UTC, SageKyle commented
I used a JSON formatter to update the format of the entire file.

2023-02-10 20:08 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-11 13:39 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-02-11 13:39 UTC, merged