data: chiragjh7
EddieHubCommunity/LinkFree pull request #4654
Opened 2023-02-10 04:48 UTC by chiragjh7

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-10 05:26 UTC, Panquesito7 requested changes

2023-02-10 05:26 UTC, Panquesito7 commented on data/chiragjh7.json
> +  "avatar": "https://github.com/chiragjh7.png",
The `avatar` field is no longer required as of a new update.
```suggestion
```

2023-02-10 05:31 UTC, chiragjh7 reviewed
Thanks for the suggestions!

2023-02-10 05:44 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-02-10 15:28 UTC, kumarsonsoff3 requested changes

2023-02-10 15:28 UTC, kumarsonsoff3 commented on data/chiragjh7.json
> +  "displayStatsPublic": true,
We've recently removed the public stats feature, so `displayStatsPublic` property is no longer needed. 
Please remove this from your json. 

```suggestion
```

2023-02-11 13:42 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/218258654-0b081c88-8ed3-40ae-8887-84290310e2f9.png" /></p>

2023-02-11 13:43 UTC, merged