Profile Created
EddieHubCommunity/LinkFree pull request #4662
Opened 2023-02-10 10:59 UTC by kshitij9896

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-10 11:24 UTC, stevenovak123 approved these changes

2023-02-10 11:26 UTC, stevenovak123 requested changes

2023-02-10 11:26 UTC, stevenovak123 commented on data/kshitij9896.json
> +
add `}` a the end

2023-02-10 14:44 UTC, kumarsonsoff3 requested changes

2023-02-10 14:44 UTC, kumarsonsoff3 commented on data/kshitij9896.json
> +  ],
There is an extra comma `,` which should be removed. 
```suggestion
  ]
```

2023-02-10 14:55 UTC, kumarsonsoff3 requested changes
Unfortunately you've removed the closing bracket from the end. Please add a `}` in the end as Steven suggested.

2023-02-11 13:10 UTC, kumarsonsoff3 approved these changes
Looks good to me. 🎉 

But not sure why did you delete your other sections & links from the file. When you ever wanted to add them again, you can follow [these docs for editing](https://linkfree.eddiehub.io/docs/how-to-guides/editing)

2023-02-11 13:11 UTC, merged