data:swapnul
EddieHubCommunity/LinkFree pull request #4677
Opened 2023-02-10 19:13 UTC by swapnul

## Changes proposed
Add  https://github.com/swapnul profile to  LinkFree

##Check List (Check all the applicable boxes)
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

NA

## Note to reviewers

NA

2023-02-10 19:14 UTC, Panquesito7 requested changes
Please move your file to the `data` directory.
Let us know if you need any help with that. 🙂

2023-02-10 19:27 UTC, Panquesito7 commented on data/swapnul.json
> +      "icon": "FaTwitter"
You might want to use the GitHub icon here.
```suggestion
      "icon": "FaGithub"
```

2023-02-10 20:08 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-11 04:05 UTC, priyankarpal approved these changes
Looks great 🎉

2023-02-11 04:50 UTC, Sindhuinti approved these changes
LGTM 🎉

2023-02-12 03:13 UTC, SaraJaoude approved these changes
looks good

2023-02-12 03:13 UTC, merged