Fixed data not to have stats property
EddieHubCommunity/LinkFree pull request #4682
Opened 2023-02-11 03:12 UTC by I-MirzaBaig

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-11 04:02 UTC, priyankarpal requested changes

2023-02-11 04:02 UTC, priyankarpal commented on data/I-MirzaBaig.json
> +< main
Delete this line.
```suggestion

```

2023-02-11 04:02 UTC, priyankarpal commented on data/I-MirzaBaig.json
> +    "avatar": "https://github.com/I-MirzaBaig.png",
Currently, you don't need to add an avatar code. 
```suggestion
   
```

2023-02-11 04:28 UTC, swagataroy30 reviewed
There is a typo and also `FaHashnode` is not available. can you please change it to `SiHashnode`. Thank you!

2023-02-11 04:28 UTC, swagataroy30 commented on data/I-MirzaBaig.json
> +        "icon": "FaHasnode"
```suggestion
        "icon": "SiHashnode"
```

2023-02-13 09:57 UTC, SaraJaoude approved these changes
looks good

2023-02-13 09:58 UTC, merged