data: Deepakktripathy
EddieHubCommunity/LinkFree pull request #4701
Opened 2023-02-11 15:29 UTC by Deepakktripathy

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers
You all are doing amazing! Would love to have my linkfree profile created!

2023-02-11 15:41 UTC, priyankarpal requested changes

2023-02-11 15:41 UTC, priyankarpal commented on data/Deepakktripathy.json
> +  "displayStatsPublic" : true,
Currently, you don't need to add the `"displayStatsPublic" : true,` code. you can delete it.
Check the updated doc https://linkfree.eddiehub.io/docs/quickstart

2023-02-11 15:47 UTC, priyankarpal approved these changes
LGTM 🎉

2023-02-11 15:48 UTC, Deepakktripathy reviewed
Removed displayStatsPublic

2023-02-11 15:58 UTC, Hrishi5111998 approved these changes

2023-02-11 17:15 UTC, Deepakktripathy commented
Hey, I am unable to view my linkfree profile. It still shows "user not found"

2023-02-11 17:37 UTC, priyankarpal commented
> Hey, I am unable to view my linkfree profile. It still shows "user not found"

Wait Maintainer will merge it soon & after merging it will automatically live.

2023-02-12 02:59 UTC, SaraJaoude approved these changes
looks good

2023-02-12 02:59 UTC, merged