Create Jonnie-Dev.json
EddieHubCommunity/LinkFree pull request #4707
Opened 2023-02-11 16:22 UTC by Jonnie-Dev

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-11 17:57 UTC, stevenovak123 requested changes
Please refer to https://linkfree.eddiehub.io/docs/full-profile-example and correct the changes. Thanks

2023-02-11 17:57 UTC, stevenovak123 commented on data/Jonnie-Dev.json
> +  "avatar": "https://github.com/Jonnie-Dev.png",
`avatar` is not a required property. GH actions auto pick it from your profile. Linking you a complete JSON file https://linkfree.eddiehub.io/docs/full-profile-example

2023-02-11 17:57 UTC, stevenovak123 commented on data/Jonnie-Dev.json
> +  "displayStatsPublic": true,
This is now not required!

2023-02-11 17:57 UTC, stevenovak123 commented on data/Jonnie-Dev.json
> +      "platform": "twitter",
`socials` follow a new system now.  pasting an example here but please refer to the link mentioned above 
`"socials": [
    { "icon": "FaTwitter", "url": "https://twitter.com/eddiejaoude" },
    { "icon": "FaGithub", "url": "https://github.com/eddiejaoude" },
    { "icon": "FaYoutube", "url": "https://youtube.com/eddiejaoude" }
  ],`

2023-02-11 17:57 UTC, stevenovak123 commented on data/Jonnie-Dev.json
> +      "icon": "twitter"
`icon` follows as `"icon": "FaTwitter"`

2023-02-11 17:57 UTC, stevenovak123 commented on data/Jonnie-Dev.json
> +      "icon": "linkedin"
`icon` follows as `"icon": "FaLinkedin"`

2023-02-11 17:57 UTC, stevenovak123 commented on data/Jonnie-Dev.json
> +      "icon": "github"
`icon` follows as `"icon": "FaGithub"`

2023-02-11 19:08 UTC, Jonnie-Dev commented
all suggestions taken and corrected

2023-02-13 03:36 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-13 04:14 UTC, SaraJaoude approved these changes
looks good

2023-02-13 04:14 UTC, merged