data : Aditya Dafe
EddieHubCommunity/LinkFree pull request #4709
Opened 2023-02-11 17:03 UTC by KaKashi1210

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-11 18:00 UTC, Saadat-B requested changes
Hey Aditya, please rename the `.json` file name and add your GitHub username exactly as it appears after `data/`. 
Please replace `AdityaDafe` with `KaKashi1210`
Please let us know if you need any help with it 🙂

2023-02-11 18:55 UTC, priyankarpal requested changes
Rename your name from `data/AdityaDafe.json` to your GitHub username such as `data/KaKashi1210.json`.

2023-02-11 18:55 UTC, priyankarpal commented on data/AdityaDafe.json
> +    }
Add a comma 
``` suggestion
    },
```

2023-02-11 18:55 UTC, priyankarpal commented on data/AdityaDafe.json
> +      "icon":"FaLinkedIn"
Change the icon to `SiLinkedin`
```suggestion
      "icon":"SiLinkedin"
```

2023-02-12 06:00 UTC, KaKashi1210 commented
ok guys thanks for the help imma fix it asap

2023-02-12 07:16 UTC, priyankarpal approved these changes
LGTM 🎉

2023-02-12 08:54 UTC, KaKashi1210 reviewed
Thanks for the help !!

2023-02-12 09:15 UTC, krshkun approved these changes

2023-02-12 09:15 UTC, krshkun commented on data/KaKashi1210.json
> +
Looks great! Empty line will be fixed by github actions

2023-02-13 04:12 UTC, merged