data: nidhi333-9
EddieHubCommunity/LinkFree pull request #4713
Opened 2023-02-11 18:56 UTC by nidhi333-9

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-11 19:01 UTC, swagataroy30 reviewed
In the recent update, we don't need to add avatar: anymore, it will auto-pick your GitHub profile picture. So, please remove that.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart
Thank You!

2023-02-11 19:01 UTC, swagataroy30 commented on data/nidhi333-9.json
> +  "avatar": "https://github.com/nidhi333-9.png",
```suggestion
```

2023-02-12 04:26 UTC, Hrishi5111998 approved these changes

2023-02-12 06:18 UTC, Sindhuinti requested changes
Avatar will auto import from github profile. no need to include it.

2023-02-13 04:28 UTC, merged