Junesh k patch 1
EddieHubCommunity/LinkFree pull request #4742
Opened 2023-02-12 09:56 UTC by JuneshK

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-12 10:02 UTC, krshkun requested changes
Please delete the extra file

2023-02-12 10:03 UTC, krshkun commented on data/JuneshK.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-02-12 18:09 UTC, JuneshK commented on data/JuneshK.json
> +      "icon": "FaLinkedIn"
Noted.

2023-02-13 04:01 UTC, SaraJaoude commented on data/JuneshK.json
> +    }
```suggestion
    },
```

2023-02-13 04:02 UTC, SaraJaoude commented on data/JuneshK.json
> +    }
```suggestion
    },
```

2023-02-13 04:02 UTC, SaraJaoude commented on data/JuneshK.json
> +    }
```suggestion
    },
```

2023-02-13 04:02 UTC, SaraJaoude commented on data/JuneshK.json
> +    }
```suggestion
    },
```

2023-02-15 06:24 UTC, merged