data:Gawade15
EddieHubCommunity/LinkFree pull request #4753
Opened 2023-02-12 15:00 UTC by Gawade15

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-12 15:03 UTC, krshkun requested changes
The directory name should be lowercase, and the file extension should be json. Otherwise it's awesome

2023-02-12 15:16 UTC, priyankarpal requested changes
hey please rename from `Data/Gawade15` to `Data/Gawade15.json`.

2023-02-12 15:16 UTC, priyankarpal commented on Data/Gawade15
> +  "displayStatsPublic": true,
Currently you don't need to add this code 
```suggestion
```

2023-02-12 15:16 UTC, priyankarpal commented on Data/Gawade15
> +  "avatar":"https://github.com/Gawade15.png",
in a recent update, you don't need to add an avatar code.
```suggestion
  
```

2023-02-12 15:20 UTC, swagataroy30 reviewed
In the recent update, we don't need to add avatar, it will auto-pick your GitHub profile picture and also we don't need to add `"displayStatsPublic": true`: anymore. So, please remove that.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart
Thank You!

2023-02-12 15:20 UTC, swagataroy30 commented on Data/Gawade15
> +  "displayStatsPublic": true,
```suggestion
```

2023-02-12 15:20 UTC, swagataroy30 commented on Data/Gawade15
> +  "avatar":"https://github.com/Gawade15.png",
```suggestion
```

2023-02-12 15:27 UTC, kumarsonsoff3 requested changes
A few changes are required as **priyankarpal** suggested
Your file should be in data directory, to do so, you need to rename your [file here](https://github.com/Gawade15/LinkFree/edit/Gawade15-patch-1/Data/Gawade15) to `data/Gawade15.json`. 

- Change `Data/Gawade15`  - >  `data/Gawade15.json` here. 
- Remove the `avatar` & `displayStatsPublic` properties from your json, as these fields are no longer required.

Let us know if you'd any confusion. 

![image](https://user-images.githubusercontent.com/88786642/218320037-20cbd835-f268-4a49-a6e2-17fd17cff424.png)

2023-02-12 15:27 UTC, kumarsonsoff3 commented on Data/Gawade15
> +  "displayStatsPublic": true,
As of our latest update, we no longer need the `displayStatsPublic` property. 

```suggestion
```

2023-02-12 15:27 UTC, kumarsonsoff3 commented on Data/Gawade15
> +  "avatar":"https://github.com/Gawade15.png",
Also `avatar` key is no longer needed, it will auto-pick from your GitHub profile.

```suggestion
```

2023-02-14 16:28 UTC, kumarsonsoff3 requested changes
Still it's not in the right directory. It should be exact `data/Gawade15.json`, `D` in data should be a small letter `d`. Follow the exact steps suggested above by me. 

Let us know if you need any help! :)

2023-02-16 03:43 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-16 06:31 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-02-16 06:32 UTC, merged