Accessibility: Remove bounce effect on QR codes
EddieHubCommunity/LinkFree pull request #4835
Opened 2023-02-15 10:05 UTC by SavvasStephanides

## Closes #4792

This change updates the Profile page so that the QR code no longer has a bouncing effect, which can be distracting for certain individuals.

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

<details>
  <summary>Video description</summary>
  <div>The video shows a LinkFree Profile page showing the QR code no longer having a bounce effect. Clicking the QR code expands the QR code.</div>

</details>

[](https://user-images.githubusercontent.com/478770/218995971-eaa26730-6eb1-4457-b104-77f51d3feeba.mov)

## Note to reviewers

2023-02-18 01:58 UTC, eddiejaoude requested changes
I think the badges don't look quite right now?

Events page 
<img width="582" alt="Screenshot 2023-02-18 at 08 56 51" src="https://user-images.githubusercontent.com/624760/219825696-b5e8ff04-14ca-4e08-aa7c-f1f278347242.png">

Search page
<img width="403" alt="Screenshot 2023-02-18 at 08 56 58" src="https://user-images.githubusercontent.com/624760/219825698-896d2916-990b-4587-bb8c-bf1ba8025a61.png">

2023-02-18 17:08 UTC, SavvasStephanides commented
Thanks for testing, @eddiejaoude. I didn’t realise. I’ll send a fix for it soon.

2023-02-18 18:51 UTC, SavvasStephanides commented
Updated to bring back translate styles to:

Search.

<img width="1052" alt="" src="https://user-images.githubusercontent.com/478770/219883161-2493bcc4-cab5-4962-a0c9-60435f5ccad7.png">

and events

<img width="1052" alt="" src="https://user-images.githubusercontent.com/478770/219883177-501be47a-7d0b-4b0b-a9df-7c9df898a9da.png">

2023-02-19 01:02 UTC, eddiejaoude approved these changes
Looks good 👍

2023-02-19 01:02 UTC, merged