data: ankitk26
EddieHubCommunity/LinkFree pull request #4848
Opened 2023-02-15 17:55 UTC by ankitk26

2023-02-15 18:08 UTC, priyankarpal requested changes

2023-02-15 18:08 UTC, priyankarpal commented on data/ankitk26.json
> +    },
Hey, @ankitk26 kindly delete this comma. 
``` suggestion
    }
```

2023-02-15 18:23 UTC, priyankarpal requested changes

2023-02-15 18:23 UTC, priyankarpal commented on data/ankitk26.json
> +	"avatar": "https://github.com/ankitk26.png",
After the update, you don't need to add an `avatar` code. Just delete the line.
``` suggestion

```

2023-02-15 18:39 UTC, priyankarpal approved these changes
LGTM 🎉

2023-02-15 20:53 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-16 03:45 UTC, SaraJaoude approved these changes
looks good

2023-02-16 03:45 UTC, merged