data: GitWiz01
EddieHubCommunity/LinkFree pull request #4857
Opened 2023-02-16 02:17 UTC by GitWiz01

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 03:16 UTC, Panquesito7 requested changes

2023-02-16 03:16 UTC, Panquesito7 commented on data/GitWiz01.json
> +  "avatar": "https://github.com/GitWiz01.png"
The `avatar` field is no longer required as of a new update.
```suggestion
```

2023-02-16 03:16 UTC, Panquesito7 commented on data/GitWiz01.json
> +  "bio": "A Web Dev Enthusiast who love open source "
Missing comma.
```suggestion
  "bio": "A Web Dev Enthusiast who love open source",
```

2023-02-16 23:51 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 01:12 UTC, GitWiz01 commented
@Panquesito7 please merge this pr

2023-02-17 01:49 UTC, Panquesito7 commented
> @Panquesito7 please merge this pr

We'll merge it once another maintainer approves it. 🙂

2023-02-17 03:19 UTC, SaraJaoude commented on data/GitWiz01.json
> +      "icon": "FaGithub"
You have a twitter url here (which leads to an account that does not exist) but a GitHub icon.  This is not a blocker so I will merge your PR.  Should you wish to make changes please open a new Pull Request.  You may wish to refer to the Editing guide in our Docs: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-02-17 03:19 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:20 UTC, merged