data: siddarth2810
EddieHubCommunity/LinkFree pull request #4861
Opened 2023-02-16 05:50 UTC by siddarth2810

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 06:27 UTC, iamthecloverly requested changes

2023-02-16 06:27 UTC, iamthecloverly commented on data/siddarth2810.jso
> +
Please remove these blank lines.

2023-02-16 07:46 UTC, imbeshat requested changes
the file extension should be .json

2023-02-16 07:46 UTC, imbeshat commented on data/siddarth2810.jso
> +  "avatar": "https://github.com/siddarth2810.png",
```suggestion
  
```
It is not required now.

2023-02-16 16:39 UTC, siddarth2810 reviewed
made the changes

2023-02-16 18:57 UTC, imbeshat approved these changes
LGTM

2023-02-17 01:05 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 02:15 UTC, siddarth2810 commented
Thank youuu

2023-02-17 03:15 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:15 UTC, merged