data: samMintah
EddieHubCommunity/LinkFree pull request #4864
Opened 2023-02-16 06:45 UTC by SamMintah

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 07:32 UTC, imbeshat requested changes

2023-02-16 07:32 UTC, imbeshat commented on data/samMintah.json
> +  "avatar": "https://github.com/SamMintah.png",
```suggestion
  
```
It is not needed now

2023-02-16 08:24 UTC, imbeshat commented on data/samMintah.json
> +  "bio": "Software Engineer, Tech junkie, early adopter, and futurist. #AI #ML #gadgetlove #innovation",
If #AI #ML ... are tags that you want to add then you can add them separately.
See this, https://linkfree.eddiehub.io/docs/how-to-guides/tags
If it's part of the bio then it looks good.

2023-02-16 08:59 UTC, imbeshat requested changes

2023-02-16 08:59 UTC, imbeshat commented on data/samMintah.json
> +   "Rect","full-stack developer"]
```suggestion
   "React", "Full-Stack Developer"],
```

2023-02-16 09:39 UTC, imbeshat submitted a review, later dismissed

2023-02-17 01:42 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 03:21 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:21 UTC, merged