data: ashutoshkandpal
EddieHubCommunity/LinkFree pull request #4867
Opened 2023-02-16 08:32 UTC by ashutoshkandpal

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 09:47 UTC, imbeshat requested changes

2023-02-16 09:47 UTC, imbeshat commented on data/ashutoshkandpal.json
> +			"url": "https://www.linkedin.com/in/ashutoshkandpal/",
Should be your github url.

2023-02-16 10:04 UTC, ashutoshkandpal reviewed
updated link of github

2023-02-16 10:12 UTC, imbeshat requested changes
Please, update these links also

2023-02-16 10:12 UTC, imbeshat commented on data/ashutoshkandpal.json
> +			"url": "https://twitter.com/SaraJaoude",
Your Twitter link

2023-02-16 10:12 UTC, imbeshat commented on data/ashutoshkandpal.json
> +			"url": "https://www.instagram.com/eddieandsaraexplore/",
Your Instagram link

2023-02-16 12:32 UTC, imbeshat approved these changes

2023-02-16 19:56 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 03:28 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:29 UTC, merged