data: gawadeatul
EddieHubCommunity/LinkFree pull request #4870
Opened 2023-02-16 09:08 UTC by gawadeatul

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 09:23 UTC, md-abid-hussain approved these changes
LGTM

2023-02-16 09:51 UTC, imbeshat requested changes

2023-02-16 09:51 UTC, imbeshat commented on data/gawadeatul.json
> +	"displayStatsPublic": "true",
```suggestion
	
```

2023-02-16 09:51 UTC, imbeshat commented on data/gawadeatul.json
> +	"avatar": "https://github.com/gawadeatul.png",
```suggestion
	
```

2023-02-16 12:28 UTC, imbeshat approved these changes

2023-02-16 19:39 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 03:32 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:32 UTC, merged