data: Langi10
EddieHubCommunity/LinkFree pull request #4875
Opened 2023-02-16 10:55 UTC by Langi10

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 12:45 UTC, imbeshat requested changes
`avatar` is no longer required

2023-02-16 12:45 UTC, imbeshat commented on data/Langi10.json
> +  "avatar": "https://github.com/Langi10.png",
```suggestion
```

2023-02-16 14:54 UTC, Hrishi5111998 submitted a review, later dismissed

2023-02-16 16:11 UTC, himanshu1221 requested changes
`avatar` has been depriciated please remove it other than that LGTM:+1:

2023-02-17 03:35 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:49 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 03:58 UTC, merged