data:Muyixone
EddieHubCommunity/LinkFree pull request #4876
Opened 2023-02-16 12:50 UTC by Muyixone

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-16 13:56 UTC, priyankarpal submitted a review, later dismissed
LGTM 🎉

2023-02-16 14:53 UTC, Hrishi5111998 approved these changes

2023-02-16 18:35 UTC, sansarmaske submitted a review, later dismissed

2023-02-16 19:04 UTC, imbeshat requested changes

2023-02-16 19:04 UTC, imbeshat commented on data/Muyixone.json
> +  "tags": ["Programming, Open Source", "Technical Writing", "Blogging"],
```suggestion
  "tags": ["Programming", "Open Source", "Technical Writing", "Blogging"],
```

2023-02-17 03:37 UTC, SaraJaoude approved these changes
looks good

2023-02-17 03:40 UTC, merged