Update social and links
EddieHubCommunity/LinkFree pull request #4885
Opened 2023-02-16 20:28 UTC by Yushi5058

## Changes proposed

- Add a link to my portfolio website
-  Remove codewars social link
-  Add protonmail social link

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-17 01:28 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/EddieHubCommunity/LinkFree/pull/4885/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](http://discord.eddiehub.org). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

2023-02-17 13:18 UTC, priyankarpal approved these changes
LGTM  🎉

2023-02-17 14:59 UTC, iamthecloverly submitted a review, later dismissed

2023-02-17 18:18 UTC, Panquesito7 submitted a review, later dismissed

2023-02-17 18:18 UTC, Panquesito7 commented on data/Yushi5058.json
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2023-02-18 07:28 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-02-18 10:25 UTC, merged