updated json file and link
EddieHubCommunity/LinkFree pull request #4914
Opened 2023-02-17 14:22 UTC by Chamberezigbo

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/4914"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-02-17 14:29 UTC, kumarsonsoff3 requested changes
Awesome, it looks better than the last one. 

But your filename should be exact same as your username. So please update it to `Chamberezigbo.json`

Let us know if you need any help with this! :)

2023-02-17 14:29 UTC, kumarsonsoff3 commented on data/chamberezigbo.json
> +  "avatar": "https://github.com/chamberezigbo.png",
As of our latest update, we no longer need the `avatar` key, so please remove this one. 

```suggestion
```

2023-02-20 12:42 UTC, devvsakib requested changes
please rename your file as your GitHub username, C must be uppercase as your username

2023-02-21 11:06 UTC, Chamberezigbo reviewed
Change the json file name from c to C

2023-02-21 17:26 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-02-21 17:27 UTC, merged