Rob jack tech patch 1
EddieHubCommunity/LinkFree pull request #4924
Opened 2023-02-17 19:19 UTC by RobJackTech

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

Thank you for taking the time to review my pull request!

2023-02-17 19:44 UTC, Panquesito7 requested changes

2023-02-17 19:44 UTC, Panquesito7 commented on data/RobJackTech.json
> +	"avatar": "https://github.com/RobJackTech.png",
The `avatar` field is no longer required as of a recent update.
```suggestion
```

2023-02-17 20:14 UTC, RobJackTech commented
Thanks for taking the time to review my pull request. I have made the changes and deleted the avatar field, as recommended.

2023-02-17 20:28 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-17 20:57 UTC, RobJackTech commented
👍 Thanks!

2023-02-18 05:37 UTC, swagataroy30 reviewed
In the recent update, we also don't need to add `"displayStatsPublic": true` anymore. So, please remove that.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart
Thank You!

2023-02-18 05:37 UTC, swagataroy30 commented on data/RobJackTech.json
> +	"displayStatsPublic": true,
```suggestion
```

2023-02-19 15:58 UTC, himanshu1221 commented
> In the recent update, we also don't need to add `"displayStatsPublic": true` anymore. So, please remove that. Updated docs: https://linkfree.eddiehub.io/docs/quickstart Thank You!

agree on this +1

2023-02-20 06:58 UTC, SaraJaoude approved these changes
looks good

2023-02-20 06:59 UTC, merged

2023-02-20 20:04 UTC, RobJackTech commented
Thank you very much SaraJaoude and everyone who assisted me!