data: PriyanshShrivasatava
EddieHubCommunity/LinkFree pull request #4931
Opened 2023-02-18 08:53 UTC by PriyanshShrivastava

docs: adding my (Priyansh Shrivastava) data in LinkFree repo.

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-18 09:58 UTC, sansarmaske requested changes

2023-02-18 09:58 UTC, sansarmaske commented on data/PriyanshShrivastava.json
> +	"avatar": "https://github.com/PriyanshShrivastava.png",
```suggestion
```
`avatar` is no longer needed. Picture will be fetched automatically from your GitHub account

2023-02-18 09:58 UTC, sansarmaske commented on data/PriyanshShrivastava.json
> +	}],
```suggestion
"links": [
    {
      "name": "like humour? Follow me on Twitter",
      "url": "https://twitter.com/shadow_priyansh",
      "icon": "FaTwitter"
    },
    {
      "name": "Let's collaborate on some amazing project",
      "url": "https://github.com/PriyanshShrivastava",
      "icon": "FaGithub"
    },
    {
      "name": "Follow me on LinkedIn for some achievement bragging!",
      "url": "https://www.linkedin.com/in/priyansh-shrivastava-184355145/",
      "icon": "FaLinkedin"
    },
    {
      "name": "Read my blogs on Hashnode",
      "url": "https://priyanshshrivastava.hashnode.dev/",
      "icon": "SiHashnode"
    },
    {
      "name": "Some animated stuff here",
      "url": "https://codepen.io/PriyanshShrivastava",
      "icon": "SiCodepen"
    },
    {
      "name": "Some basic Blockchain content ",
      "url": "https://youtube.com/@inyour20s46",
      "icon": "FaYoutube"
    }
  ],	
```

2023-02-18 11:17 UTC, imbeshat commented on data/PriyanshShrivastava.json
> +	"displayStatsPublic": true,
```suggestion
```

2023-02-18 11:18 UTC, imbeshat requested changes
Please, remove this also as it is not required.

2023-02-18 11:18 UTC, imbeshat commented on data/PriyanshShrivastava.json
> +	"displayStatsPublic": true,
```suggestion
```

2023-02-18 14:30 UTC, Hrishi5111998 approved these changes

2023-02-18 18:27 UTC, lewisushindi approved these changes

2023-02-19 05:55 UTC, stevenovak123 approved these changes

2023-02-19 13:04 UTC, Pradumnasaraf approved these changes
Looks good to merge. Welcome to LinkFree 🎉

2023-02-19 13:04 UTC, merged