data: imaaquibali
EddieHubCommunity/LinkFree pull request #4961
Opened 2023-02-19 20:19 UTC by imaaquibali

## Changes proposed

Added profile 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

Add this profile as soon as possible

2023-02-20 03:10 UTC, himanshu1221 requested changes
Hey @imaaquibali please put your file in `data` folder

2023-02-20 10:32 UTC, imaaquibali commented
> Hey @imaaquibali please put your file in `data` folder

Done. Can you please check it know.

2023-02-20 10:35 UTC, himanshu1221 approved these changes
**LGTM :+1:**

2023-02-20 12:39 UTC, devvsakib approved these changes
Amazing

2023-02-20 16:52 UTC, Pradumnasaraf submitted a review, later dismissed
Hey,

There is a missing `,` comma. Fix that

2023-02-20 16:52 UTC, Pradumnasaraf commented on data/imaaquibali.json
> +    "Content Creator"
```suggestion
    "Content Creator",
```

2023-02-26 03:23 UTC, SaraJaoude commented
looks good

2023-02-26 03:24 UTC, merged