Raj210 kumari patch 2
EddieHubCommunity/LinkFree pull request #4971
Opened 2023-02-20 09:48 UTC by Raj210Kumari

2023-02-20 10:13 UTC, senali-d requested changes

2023-02-20 10:13 UTC, senali-d commented on data/Raj210Kumari.json
> +      "icon": "FaWeb"
`FaWeb` is not a valid icon. You can find any relevant icon from here.
https://linkfree.eddiehub.io/icons

2023-02-20 12:35 UTC, devvsakib requested changes
line14, icon name not valid. please update your file

2023-02-20 16:49 UTC, kumarsonsoff3 requested changes

2023-02-20 16:49 UTC, kumarsonsoff3 commented on data/Raj210Kumari.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
Please update it with your info/bio. 🛠

2023-02-23 17:36 UTC, Panquesito7 commented on data/Raj210Kumari.json
> +      "icon": "FaWeb"
You could use `FaGlobe` for this, as `FaWeb` is not a valid icon as @senali-d said.
```suggestion
      "icon": "FaGlobe"
```

2023-03-02 05:30 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-02 15:59 UTC, merged