Tusharjagi patch 2
EddieHubCommunity/LinkFree pull request #4974
Opened 2023-02-20 10:28 UTC by Tusharjagi

2023-02-20 12:34 UTC, devvsakib submitted a review, later dismissed

2023-02-20 12:42 UTC, priyankarpal requested changes

2023-02-20 12:42 UTC, shubhsharma19 commented on data/Tusharjagi.json
> +  "displayStatsPublic": true,
Yes

2023-02-21 04:40 UTC, priyankarpal requested changes

2023-02-21 04:40 UTC, priyankarpal commented on data/Tusharjagi.json
> +      "icon": "FaMedium"
One suggestion please remove the `FaMedium` icon and add the `SiMedium` icon. You can check the changelog of the medium logo from [this blog](https://medium.com/blogging-guide/mediums-new-logo-2020-unfinished-ellipses-logomark-e24c059871e7).
``` suggestion
      "icon": "SiMedium"
```

2023-02-21 04:44 UTC, priyankarpal approved these changes
Now it's looking great 🎉

2023-02-21 08:10 UTC, shubhsharma19 approved these changes
Looks good 👍

2023-02-22 06:10 UTC, mahfuztbt approved these changes

2023-02-22 09:33 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉
Great collaboration everyone! 👍

2023-02-22 09:35 UTC, merged