Create ndzhwr.json
EddieHubCommunity/LinkFree pull request #5001
Opened 2023-02-21 16:45 UTC by ndzhwr

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

I just added my profile in `/data` directory -> `/data/ndzhwr.json`

2023-02-21 17:00 UTC, mahfuztbt commented on data/ndzhwr.json
> +      "icon": "FaGithub"
delete `,` from line 20. only use `}`

2023-02-21 17:33 UTC, shubhsharma19 approved these changes
Looks good 🎉, however you can fix the indentation on line 11 and 16. :D

2023-02-21 17:52 UTC, Krishnapro commented on data/ndzhwr.json
> +    },
Remove `,` after `}` in line 20
```diff
- },
+ }

2023-02-21 17:53 UTC, Krishnapro requested changes
Remove `,` after `}` in line 20

2023-02-21 17:55 UTC, shubhsharma19 commented on data/ndzhwr.json
> +    },
Thanks for the mention 🎉

2023-02-21 18:04 UTC, ndzhwr commented
I've removed the `,` @Krishnapro

2023-02-21 18:11 UTC, shubhsharma19 approved these changes
LGTM 🎉

2023-02-21 18:37 UTC, samyabrata-maji approved these changes

2023-02-22 01:22 UTC, himanshu1221 approved these changes
**LGTM :+1:**

2023-02-22 06:07 UTC, mahfuztbt approved these changes
it's  okay now

2023-02-23 02:02 UTC, SaraJaoude approved these changes
looks good

2023-02-23 02:06 UTC, merged