data: pacifiquem.json added
EddieHubCommunity/LinkFree pull request #5026
Opened 2023-02-23 07:49 UTC by pacifiquem

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-23 08:08 UTC, imbeshat requested changes
Please, update these.

2023-02-23 08:08 UTC, imbeshat commented on data/pacifiquem.json
> +  "avatar":"https://github.com/pacifiquem.png",
```suggestion
```

2023-02-23 08:08 UTC, imbeshat commented on data/pacifiquem.json
> +      "name": "Linked",
```suggestion
      "name": "LinkedIn",
```

2023-02-24 07:29 UTC, pacifiquem commented
@imbeshat I've finished all suggested changes .

2023-02-24 08:22 UTC, imbeshat approved these changes

2023-02-25 07:11 UTC, SaraJaoude approved these changes
looks good

2023-02-25 07:11 UTC, merged