data: DaduDev
EddieHubCommunity/LinkFree pull request #5035
Opened 2023-02-23 16:46 UTC by DaduDev

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5035"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-02-23 17:08 UTC, Ananya2001-an requested changes
You have to create this file inside the data folder. Also remove the `avatar` and `displayPublicStats` keys from the JSON object since according to new upgrades we don't need them anymore.

2023-02-24 04:50 UTC, DaduDev commented
> You have to create this file inside the data folder. Also remove the `avatar` and `displayPublicStats` keys from the JSON object since according to new upgrades we don't need them anymore.

Thank you

2023-02-24 04:55 UTC, Panquesito7 commented on data/DaduDev.json
> +      "icon": "FaTwitter"
You might want to use the Instagram icon here instead.
```suggestion
      "icon": "FaInstagram"
```

2023-02-24 18:41 UTC, SurajPratap10 approved these changes

2023-02-25 04:26 UTC, SaraJaoude approved these changes
looks good

2023-02-25 04:26 UTC, merged