data: akashrajakku
EddieHubCommunity/LinkFree pull request #5040
Opened 2023-02-24 01:23 UTC by akashrajakku

2023-02-24 02:36 UTC, Panquesito7 requested changes
Your filename must match your GitHub username.
In this case, it should be `akashrajakku`. Please update accordingly.

If you need any help, let us know. 🙂

2023-02-24 02:36 UTC, Panquesito7 commented on data/akashraj.json
> +  "avatar":"https://github.com/akashrajakku.png",
The `avatar` field is no longer required as of a recent update.
```suggestion
```

2023-02-24 03:19 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-24 08:44 UTC, SurajPratap10 approved these changes
Good

2023-02-25 04:24 UTC, SaraJaoude approved these changes
looks good

2023-02-25 04:24 UTC, merged

2023-02-25 09:38 UTC, akashrajakku commented
Thanks for having me