data:Chetax
EddieHubCommunity/LinkFree pull request #5055
Opened 2023-02-25 04:55 UTC by Chetax

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-25 10:12 UTC, priyankarpal requested changes
Please move `Chetax.json` to `data/Chetax.json`

![Screenshot from 2023-02-25 15-40-40](https://user-images.githubusercontent.com/88102392/221351434-057ef698-30d8-497b-aab1-debc37d6813c.png)

2023-02-25 10:12 UTC, priyankarpal commented on Chetax.json
> +  "avatar":"https://github.com/Chetax.png",
please remove the `avatar` code. Now it's no longer needed. 
```suggestion
```

2023-02-25 10:12 UTC, priyankarpal commented on Chetax.json
> +  "diplayStatsPublic": true,
Also, remove `  "diplayStatsPublic": true,`
```suggestion
```

2023-02-26 03:05 UTC, SaraJaoude approved these changes
looks good

2023-02-26 03:05 UTC, merged

2023-02-26 13:09 UTC, swagataroy30 commented
Hey but the `json` file is not in the `data` folder.

2023-02-26 13:47 UTC, priyankarpal commented
hi @SaraJaoude please check json file is not in the data folder

2023-02-26 15:58 UTC, eddiejaoude commented
Good spot 👍  we will fix

2023-02-26 16:00 UTC, eddiejaoude commented
Fixed here https://github.com/EddieHubCommunity/LinkFree/pull/5105