data: preshpi
EddieHubCommunity/LinkFree pull request #5063
Opened 2023-02-25 09:47 UTC by preshpi

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-25 10:05 UTC, priyankarpal requested changes

2023-02-25 10:05 UTC, priyankarpal commented on data/preshpi.json
> +  "avatar": "https://github.com/preshpi.png",
hey after the current update `avatar` is no longer needed. You can delete this line.
 ```suggestion
  
```

2023-02-25 10:05 UTC, priyankarpal commented on data/preshpi.json
> +    },
Delete the last comma.
```suggestion
    }
```

2023-02-26 03:10 UTC, SaraJaoude approved these changes
looks good

2023-02-26 03:11 UTC, merged