data:Hishammpsnhn
EddieHubCommunity/LinkFree pull request #5159
Opened 2023-02-28 18:12 UTC by Hishammpsnhn

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-02-28 18:16 UTC, Krishnapro approved these changes
LGTM 🚀 Add more links

2023-02-28 18:54 UTC, imbeshat requested changes
Also, move your file to the ```data``` folder.

2023-03-01 03:37 UTC, SaraJaoude requested changes
Please move the json file to the `data` folder

2023-03-01 10:17 UTC, iamthecloverly approved these changes

2023-03-01 17:59 UTC, closed without merging