data:Brownei
EddieHubCommunity/LinkFree pull request #5205
Opened 2023-03-02 11:41 UTC by Brownei

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-02 13:09 UTC, SurajPratap10 commented on data/Brownei.json
> +"type" : "personal",
What's wrong with this and it's too big, brief in 1-2 lines.

2023-03-02 13:10 UTC, SurajPratap10 commented
What's wrong with the bio part it's too long, brief in 1-2 lines.

2023-03-02 15:07 UTC, Sindhuinti requested changes

2023-03-02 15:07 UTC, Sindhuinti commented on data/Brownei.json
> +"bio" :  "Frontend Web Developer who just started his career less than a year ago. I have always been fascinated with the power of the internet and how websites are built. I started learning HTML, CS
Please make your bio to single link and place a comma `,` at the end.

2023-03-03 08:34 UTC, SaraJaoude commented
> What's wrong with the bio part it's too long, brief in 1-2 lines.

@SurajPratap10 whilst there are advantages to having a short bio this is not a requirement and we encourage people to write the bios they want (and these can always be updated). Clearly there is nothing wrong with this bio -  please do not write such rude and unsupportive messages in the future, this is not collaborative or welcoming.

2023-03-03 08:43 UTC, SurajPratap10 commented
> > What's wrong with the bio part it's too long, brief in 1-2 lines.
> 
> @SurajPratap10 whilst there are advantages to having a short bio this is not a requirement and we encourage people to write the bios they want (and these can always be updated). Clearly there is nothing wrong with this bio - please do not write such rude and unsupportive messages in the future, this is not collaborative or welcoming.

It was too long that's why I told him to write a shorter bio as it gives greater engagement from a reader's POV. Sorry, if it looked rude will take care of it in the future,

2023-03-03 09:05 UTC, Brownei commented
Thank you very much for the assistance

2023-03-04 07:43 UTC, devvsakib requested changes
Your bio is way too long, you can make it simple, in 1/2 line. add a comma here
![image](https://user-images.githubusercontent.com/88339569/222883542-5202eb97-8256-4143-b643-308e4e5671b8.png)

2023-03-04 09:42 UTC, SurajPratap10 commented
> Your bio is way too long, you can make it simple, in 1/2 line. add a comma here
> ![image](https://user-images.githubusercontent.com/88339569/222883542-5202eb97-8256-4143-b643-308e4e5671b8.png)
> 

Ya, and as per your wish if you want to keep this bio then no worries but add the comma @Brownei  as this PR is opened from a long time.

2023-03-08 22:40 UTC, eddiejaoude commented
@devvsakib please do not comment on people's bio's, it is **their** bio - also if you look further up the Pull request timeline you can see this has already been discussed

2023-03-17 01:57 UTC, SaraJaoude commented on data/Brownei.json
> +          I is constantly seeking new challenges and opportunities to improve my skills and knowledge."
```suggestion
"bio" :  "Frontend Web Developer who just started his career less than a year ago. I have always been fascinated with the power of the internet and how websites are built. I started learning HTML, CSS, and JavaScript on my own and quickly discovered my undying passion for frontend development. I am well-versed in a frontend framework which is React and I do hope to always stays up-to-date with the latest web technologies. Despite my short experience, I has already completed several projects, ranging from small static websites to large e-commerce platforms. I understand the importance of creating user-friendly and visually appealing interfaces and I do hope will strive to exceed the clients' expectations. I is a team player and enjoys working collaboratively with other developers, designers, and project managers. I am always willing to share my knowledge and learn from my colleagues. I is constantly seeking new challenges and opportunities to improve my skills and knowledge."
```

2023-03-17 01:59 UTC, SaraJaoude commented on data/Brownei.json
> +"bio" :  "Frontend Web Developer who just started his career less than a year ago. I have always been fascinated with the power of the internet and how websites are built. I started learning HTML, CS
```suggestion
"bio" :  "Frontend Web Developer who just started his career less than a year ago. I have always been fascinated with the power of the internet and how websites are built. I started learning HTML, CSS, and JavaScript on my own and quickly discovered my undying passion for frontend development. I am well-versed in a frontend framework which is React and I do hope to always stays up-to-date with the latest web technologies. Despite my short experience, I has already completed several projects, ranging from small static websites to large e-commerce platforms. I understand the importance of creating user-friendly and visually appealing interfaces and I do hope will strive to exceed the clients' expectations. I is a team player and enjoys working collaboratively with other developers, designers, and project managers. I am always willing to share my knowledge and learn from my colleagues. I is constantly seeking new challenges and opportunities to improve my skills and knowledge.",
```

2023-03-17 02:01 UTC, SaraJaoude commented
Hi @Brownei I have fixed the json without changing any content from your bio (json does not accept line breaks/paragraphs) so I will now be merging your Profile

2023-03-17 02:02 UTC, merged