Update CONTRIBUTING.md
EddieHubCommunity/LinkFree pull request #5206
Opened 2023-03-02 13:40 UTC by priyankarpal

Added new styles
fixed wrong spellings

2023-03-02 16:27 UTC, SurajPratap10 approved these changes
lgtm

2023-03-03 03:04 UTC, eddiejaoude commented on CONTRIBUTING.md
> -
This blank line is recommended to be kept

2023-03-03 03:04 UTC, eddiejaoude commented on CONTRIBUTING.md
>  - only request to be assigned an issue if you know how to work on it
Probably best to have the whole block in the same formatting

```suggestion
> Notes:
> - any issues that have no activity after 2 weeks will be unassigned and re-assigned to someone else
> - only request to be assigned an issue if you know how to work on it
```

2023-03-03 03:05 UTC, eddiejaoude requested changes
Thank you 👍 

I added some inline comments

2023-03-03 07:41 UTC, eddiejaoude commented on CONTRIBUTING.md
> +
Single blank line is recommended between Markdown sections

```suggestion

```

2023-03-03 08:00 UTC, eddiejaoude approved these changes
Thank you 👍

2023-03-03 08:01 UTC, merged