data: devPhantom
EddieHubCommunity/LinkFree pull request #5207
Opened 2023-03-02 14:04 UTC by dev-phantom

2023-03-02 14:39 UTC, priyankarpal commented on data/devPhantom.json
> +      "url": "https://www.linkedin.com/in/elimihele-god-s-favour-09341822b/"
Add a comma

 ```suggestion
      "url": "https://www.linkedin.com/in/elimihele-god-s-favour-09341822b/",
```

2023-03-02 14:42 UTC, priyankarpal requested changes
hi, @dev-phantom JSON file looks great, but you need to add your exact same GitHub username to the json file such as `data/dev-phantom.json` Please fix it. 

![Screenshot from 2023-03-02 20-09-38](https://user-images.githubusercontent.com/88102392/222460136-008c8906-2c5f-44fa-80f8-1b15508dbf56.png)

2023-03-02 19:46 UTC, dev-phantom commented
@priyankarpal I've fixed this

2023-03-03 03:42 UTC, priyankarpal commented
> @priyankarpal I've fixed this

You just added a new title. You need to change the json file name from `devPhantom.json` to `dev-phantom.json`. If you're facing any trouble you can check this official doc. https://docs.github.com/en/repositories/working-with-files/managing-files/renaming-a-file. Or ask to LinkFree discord https://discord.com/invite/jZQs6Wu

> Make sure that your file into the `data` folder.

2023-03-03 23:28 UTC, dev-phantom commented
@priyankarpal I've fixed this

2023-03-04 00:24 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-04 07:41 UTC, devvsakib approved these changes

2023-03-04 16:35 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-03-04 16:35 UTC, merged