data:KishanGupta
EddieHubCommunity/LinkFree pull request #5221
Opened 2023-03-03 07:40 UTC by KishanGupta114

2023-03-03 07:44 UTC, SurajPratap10 commented on data/KishanGupta.json
> +    }
```suggestion
  "links": [
    {
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/i_kishan_",
      "icon": "FaTwitter"
    },
    {
      "name": "Follow me on LinkedIn",
      "url": "https://www.linkedin.com/in/i-kishan",
      "icon": "FaLinkedIn"
    },
```

2023-03-03 07:44 UTC, SurajPratap10 commented on data/KishanGupta.json
> +    }
`,`

2023-03-03 07:51 UTC, priyankarpal requested changes

2023-03-03 07:51 UTC, priyankarpal commented on data/KishanGupta.json
> +      "icon": "FaLinkedIn"
change the icon to `SiLinkedin`
```suggestion
      "icon": "SiLinkedin"
```

2023-03-03 07:51 UTC, priyankarpal commented on data/KishanGupta.json
> +    }
Add comma 
```suggestion
    },
```

2023-03-03 07:51 UTC, priyankarpal commented on data/KishanGupta.json
> +    }
also here 
```suggestion
    },
```

2023-03-03 08:06 UTC, SurajPratap10 commented on data/KishanGupta.json
> +    },
```suggestion
    }
```

2023-03-03 08:08 UTC, SurajPratap10 commented on data/KishanGupta.json
> +    },
You don't need to put  `,` here.

2023-03-03 08:10 UTC, KishanGupta114 commented on data/KishanGupta.json
> +    },
Okay, Bro.. let me correct it.

2023-03-03 08:13 UTC, KishanGupta114 commented on data/KishanGupta.json
> +    },
Bro Check it again

2023-03-03 08:14 UTC, SurajPratap10 approved these changes
LGTM

2023-03-03 08:47 UTC, priyankarpal approved these changes
Looks good to me 🎉

2023-03-03 15:17 UTC, Panquesito7 requested changes
The filename must match your GitHub username.
In this case, `KishanGupta114`. Please update accordingly.

If you need any help, let us know. 🙂

2023-03-03 16:19 UTC, md-abid-hussain requested changes
instead of data:KishanGupta filename should be data:KishanGupta114

2023-03-03 19:42 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-04 04:16 UTC, SaraJaoude approved these changes
looks good

2023-03-04 04:16 UTC, merged