data: hamidayb
EddieHubCommunity/LinkFree pull request #5224
Opened 2023-03-03 12:19 UTC by hamidayb

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-03 12:36 UTC, Aadarsh805 requested changes

2023-03-03 12:36 UTC, Aadarsh805 commented on data/hamidayb.json
> +  "name": "Sara Jaoude",
Hey @hamidayb, you have forgotten to change the name and bio

2023-03-03 12:36 UTC, Aadarsh805 commented on data/hamidayb.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado"
and there is a comma missing at the end of line 4

2023-03-03 12:48 UTC, sidharthviz requested changes

2023-03-03 12:48 UTC, sidharthviz commented on data/hamidayb.json
> +  "avatar": "https://github.com/hamidayb.png",
@hamidayb You can remove the avatar.
Updated docs: https://linkfree.eddiehub.io/docs/quickstart
Thank You.

2023-03-09 17:37 UTC, TRohit20 reviewed
Have a look at the Updated Docs Here: Updated docs: https://linkfree.eddiehub.io/docs/quickstart to make necessary changes. 
Thank you.

2023-03-09 18:05 UTC, rohitverse reviewed
Have a look at the Updated Docs Here: Updated docs: https://linkfree.eddiehub.io/docs/quickstart to make necessary changes.
Thank you.

2023-03-11 03:02 UTC, SaraJaoude commented
@TRohit20 and @rohitverse please can you avoid making a duplicate comment as this does not add value to the conversation and can confuse the author of the Pull Request. 

@hamidayb please let us know if you need any help with this.  You do need to update your name and bio as you have actually used mine and not your details.

2023-03-17 01:47 UTC, SaraJaoude commented
Due to the lack of activity and given the changes have not been made, I will be closing this Pull Request. 

Feel free to create a new Pull Request and as suggested above, you may wish to take a look at our Quick Start Guide when doing this.

2023-03-17 01:47 UTC, closed without merging