data DEEPRAJKUSHWAHA
EddieHubCommunity/LinkFree pull request #5238
Opened 2023-03-04 06:45 UTC by DEEPRAJKUSHWAHA

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-04 07:36 UTC, devvsakib approved these changes
LGTM

2023-03-04 12:01 UTC, SurajPratap10 approved these changes
LGTM 

`suggestion:` you can add more links and some sections like tags if you like to.

2023-03-04 16:30 UTC, kumarsonsoff3 requested changes
Your file should be in data directory, to move it using GitHub UI, rename your [file here](https://github.com/DEEPRAJKUSHWAHA/LinkFree/edit/DEEPRAJKUSHWAHA-patch-1/DEEPRAJKUSHWAHA.json) to `data/DEEPRAJKUSHWAHA.json`. 

Change `DEEPRAJKUSHWAHA.json`  - >  `data/DEEPRAJKUSHWAHA.json`

Let us know if you need any help with this. 🛠

![image](https://user-images.githubusercontent.com/88786642/222917482-685228f2-6ff1-495b-a66d-da3dfb90dfd3.png)

2023-03-04 16:30 UTC, kumarsonsoff3 commented on DEEPRAJKUSHWAHA.json
> +  "bio": "I am a android and full stack developer"
There is a missing comma which is leading json check fail. 

```suggestion
  "bio": "I am a android and full stack developer",
```

2023-03-04 21:04 UTC, samyabrata-maji approved these changes

2023-03-04 21:24 UTC, SurajPratap10 commented
@DEEPRAJKUSHWAHA  
Put `DEEPRAJKUSHWAHA.json` file inside the `data` folder, like this -->  `data/DEEPRAJKUSHWAHA.json`

2023-03-05 19:00 UTC, Pradumnasaraf commented
> @DEEPRAJKUSHWAHA Put `DEEPRAJKUSHWAHA.json` file inside the `data` folder, like this --> `data/DEEPRAJKUSHWAHA.json`

Hey, 

Please refrain from requesting for same changes if someone has already requested that. It creates an extra notification for everyone. Thank you for understanding.

2023-03-07 15:05 UTC, TRohit20 approved these changes

2023-03-09 15:51 UTC, vedprakashnautiyal approved these changes

2023-03-17 01:52 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.eddiehub.io/docs/quickstart

Editing your Profile: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-03-17 01:52 UTC, closed without merging