More Sites Updates
EddieHubCommunity/LinkFree pull request #5263
Opened 2023-03-05 11:19 UTC by kshitij9896

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-05 11:26 UTC, priyankarpal commented on data/kshitij9896.json
> +      "icon": "SiGmail",
Remove last comma 
```suggestion
      "icon": "SiGmail"
```

2023-03-05 11:26 UTC, priyankarpal commented on data/kshitij9896.json
> +      "icon": "FaGlobe",
same here remove last comma  
```suggestion
      "icon": "FaGlobe"
```

2023-03-05 11:28 UTC, priyankarpal requested changes
One Suggestion...
- when you create a PR please add some description & screenshots it helps us to understand the changes quickly.

2023-03-05 15:48 UTC, kumarsonsoff3 commented
Merged the one with latest changes in the same file #5264

2023-03-05 15:48 UTC, closed without merging

2023-03-06 06:50 UTC, kshitij9896 commented
> Merged the one with latest changes in the same file #5264

Thank You