data: Gautam-666
EddieHubCommunity/LinkFree pull request #5277
Opened 2023-03-06 09:19 UTC by Gautam-666

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-06 09:31 UTC, Gautam-666 commented
added tags and social icons ..

2023-03-06 13:09 UTC, priyankarpal requested changes

2023-03-06 13:09 UTC, priyankarpal commented on data/Gautam-666.json
> +	"bio": "A aspiring full stack webdeveloper. Guitarist and Travel enthusiast",
Add a space between Web Developer.
``` suggestion
	"bio": "An aspiring full stack web developer. Guitarist and Travel enthusiast",
```

2023-03-06 13:16 UTC, priyankarpal approved these changes
LGTM 🎉

2023-03-06 13:16 UTC, Gautam-666 commented
Commited the changes

2023-03-06 14:24 UTC, TRohit20 approved these changes

2023-03-06 14:26 UTC, SurajPratap10 approved these changes

2023-03-06 14:40 UTC, Gautam-666 commented
I am guessing all the changes are committed. If anything has to be changed just let me know

2023-03-06 14:50 UTC, Atharv181 approved these changes
LGTM

2023-03-07 01:50 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-07 12:06 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-03-07 12:07 UTC, merged