data:AFB-M
EddieHubCommunity/LinkFree pull request #5298
Opened 2023-03-07 17:37 UTC by AFB-M

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-07 19:08 UTC, imbeshat reviewed
filename should be ```YourGithubUsername.json```. And please, move your file into ```data``` folder

2023-03-07 19:11 UTC, imbeshat requested changes

2023-03-07 19:11 UTC, imbeshat commented on AM
> +      "icon": "FaHashnode"
```suggestion
      "icon": "SiHashnode"
```

2023-03-07 22:22 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-08 00:04 UTC, SurajPratap10 approved these changes
LGTM

2023-03-08 10:07 UTC, himanshu1221 approved these changes
LGTM :+1:

2023-03-08 15:03 UTC, mahfuztbt approved these changes
ready to merge

2023-03-08 15:15 UTC, Sindhuinti approved these changes
Thanks 🎉

2023-03-08 15:59 UTC, iamthecloverly approved these changes

2023-03-08 16:04 UTC, merged