data: analizzi
EddieHubCommunity/LinkFree pull request #5317
Opened 2023-03-10 01:00 UTC by analizzi

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-10 02:09 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-03-10 12:37 UTC, SurajPratap10 submitted a review, later dismissed

2023-03-10 14:48 UTC, amandamartin-dev requested changes
missing a comma

2023-03-10 14:48 UTC, amandamartin-dev commented on data/analizzi.json
> +  "bio": "Civil engineer by day, **coder** by night. Travel enthusiast Yoga & Peloton aficionado"
```suggestion
  "bio": "Civil engineer by day, **coder** by night. Travel enthusiast Yoga & Peloton aficionado",
```

2023-03-10 23:40 UTC, eddiejaoude commented
Duplicate of https://github.com/EddieHubCommunity/LinkFree/pull/5319

2023-03-15 23:27 UTC, eddiejaoude approved these changes
Looks great 👍 

Great collaboration everyone 🎉

2023-03-15 23:28 UTC, merged