data: fatemaker254
EddieHubCommunity/LinkFree pull request #5320
Opened 2023-03-10 04:01 UTC by fatemaker254

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-10 09:55 UTC, imbeshat requested changes

2023-03-10 09:55 UTC, imbeshat commented on data/fatemaker254.json
> +      "url": "www.linkedin.com/in/soham-das07",
```suggestion
      "url": "https://www.linkedin.com/in/soham-das07",
```

2023-03-10 09:55 UTC, imbeshat commented on data/fatemaker254.json
> +    },
```suggestion
    }
```

2023-03-11 03:07 UTC, SaraJaoude approved these changes
looks good

2023-03-11 03:07 UTC, merged

2023-03-12 02:37 UTC, fatemaker254 commented
Thanks a lot everyone for your effort