data: JohnOkari
EddieHubCommunity/LinkFree pull request #5333
Opened 2023-03-10 14:39 UTC by JohnOkari

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5333"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-03-10 15:24 UTC, imbeshat commented on data/JohnOkari.json
> +  "avatar": "https://media.licdn.com/dms/image/C4D03AQFQ-TQCaXGhGQ/profile-displayphoto-shrink_800_800/0/1611950036081?e=1683763200&v=beta&t=a1RvqcN7e55SjEZSfQNTe2BKXPhAqKxjIs8rnrSbc58",
```suggestion
```

2023-03-10 15:28 UTC, imbeshat requested changes

2023-03-10 15:28 UTC, imbeshat commented on data/JohnOkari.json
> +      "url": "linkedin.com/in/johnnokari-001",
```suggestion
      "url": "https://www.linkedin.com/in/johnnokari-001",
```

2023-03-11 03:16 UTC, SaraJaoude approved these changes
looks good

2023-03-11 03:17 UTC, merged