data:coder-chahal
EddieHubCommunity/LinkFree pull request #5336
Opened 2023-03-10 17:21 UTC by coder-chahal

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5336"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-03-10 18:21 UTC, ChinmayMhatre requested changes
Mentioned some changes for things that you might have missed . overall, looks good! Thank you!

2023-03-10 18:21 UTC, ChinmayMhatre commented on data/coder-chahal.json
> +  "name": "Sara Jaoude",
I believe you missed this, update this with your name

2023-03-10 18:21 UTC, ChinmayMhatre commented on data/coder-chahal.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
Please update the bio with your own

2023-03-10 18:24 UTC, priyankarpal requested changes

2023-03-10 18:24 UTC, priyankarpal commented on data/coder-chahal.json
> +  "name": "Sara Jaoude",
hi @coder-chahal please remove `Sara Jaoude` and add your name. 
``` suggestion
  "name": "coder-chahal",
```

2023-03-10 18:24 UTC, priyankarpal commented on data/coder-chahal.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
Also please add your bio.

2023-03-11 10:01 UTC, coder-chahal commented on data/coder-chahal.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
@ChinmayMhatre Updated Successfully.

2023-03-11 12:24 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-03-11 17:31 UTC, kumarsonsoff3 approved these changes
Looks good, Welcome to LinkFree. 🎉

2023-03-11 17:31 UTC, merged