data: jyotir07
EddieHubCommunity/LinkFree pull request #5362
Opened 2023-03-11 17:24 UTC by jyotir07

## Changes proposed

My first contribution to opensource

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-11 19:25 UTC, Pradumnasaraf requested changes
Hey,

There are some missing elements in the JSON file please update them to make the PR ready for merge

2023-03-11 19:25 UTC, Pradumnasaraf commented on data/jyotir07.json
> +      "icon": "FaTwitter"
Add your Twitter GitHub usernames, if not, remove the section.

```suggestion
      "name": "Twitter: Follow me",
      "url": "https://twitter.com/<Your Twitter Username>",
      "icon": "FaTwitter"
```

2023-03-11 19:25 UTC, Pradumnasaraf commented on data/jyotir07.json
> +      "url": "Your Linkedin Profile URL",
Add your LinkedIn URL here. If you don't have to remove this block
```suggestion
      "url": "Your Linkedin Profile URL",
```

2023-03-11 19:25 UTC, Pradumnasaraf commented on data/jyotir07.json
> +  ],
Add your Twitter, GitHub and LinkedIn usernames, if not, remove the section and also remove the comments (`//for mini icons`)


```suggestion
  "socials": [
    { "icon": "FaTwitter", "url": "https://twitter.com/<Your Twitter Username>" },
    { "icon": "FaGithub", "url": "https://github.com/<Your GitHub Username>" }, //for mini icons
    {
      "icon": "FaLinkedin",
      "url": "Your Linkedin Profile URL"
    }
  ],
```

2023-03-11 19:25 UTC, Pradumnasaraf commented on data/jyotir07.json
> +  "bio": "**Your Bio**",
Add a bio

```suggestion
  "bio": "**Your Bio**",
```

2023-03-23 08:40 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.eddiehub.io/docs/quickstart

Editing your Profile: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-03-23 08:40 UTC, closed without merging