data: prathamkandari
EddieHubCommunity/LinkFree pull request #5363
Opened 2023-03-11 17:24 UTC by prathamkandari

## Changes proposed

Contributing to OpenSource 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-11 18:37 UTC, SurajPratap10 approved these changes
LGTM

2023-03-11 19:35 UTC, Pradumnasaraf requested changes
Hey,

There are some missing elements in the JSON file please update them to make the PR ready for merge

2023-03-11 19:35 UTC, Pradumnasaraf commented on data/prathamkandari.json
> +    { "icon": "FaTwitter", "url": "https://twitter.com/<Your Twitter Username>" },
Add your Twitter usernames, if not, remove the section.

2023-03-11 19:35 UTC, Pradumnasaraf commented on data/prathamkandari.json
> +    },
Add your Twitter usernames, if not, remove the section.

```suggestion
    {
      "name": "Twitter: Follow me",
      "url": "https://twitter.com/<Your Twitter Username>",
      "icon": "FaTwitter"
    },
```

2023-03-23 08:49 UTC, SaraJaoude commented
@prathamkandari the changes that have been proposed by the maintainer above would enhance your LinkFree profile.  However as there has been a lack of activity from you to make these changes I will be merging your Pull Request.

Should you wish to make changes please raise a new Pull Request.  You may wish to look at our Editing Guide in Docs when you do so:https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-03-23 08:50 UTC, merged