data: akshatshukla13
EddieHubCommunity/LinkFree pull request #5403
Opened 2023-03-13 13:08 UTC by akshatshukla13

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-13 15:14 UTC, Sindhuinti requested changes

2023-03-13 15:14 UTC, Sindhuinti commented on akshatshukla13.json
> +  "avatar": "https://media.licdn.com/dms/image/D5603AQFA-E-9DFGSUA/profile-displayphoto-shrink_800_800/0/1668493033974?e=1684368000&v=beta&t=RRQZUtcrRu3hXT6yIZoGZ65ydkLUFVakMK4C43lWbPE",
No need to add your avatar here. It will be auto imported from github.

2023-03-13 17:09 UTC, kumarsonsoff3 requested changes

2023-03-13 17:09 UTC, kumarsonsoff3 commented on akshatshukla13.json
> +  "avatar": "https://media.licdn.com/dms/image/D5603AQFA-E-9DFGSUA/profile-displayphoto-shrink_800_800/0/1668493033974?e=1684368000&v=beta&t=RRQZUtcrRu3hXT6yIZoGZ65ydkLUFVakMK4C43lWbPE",
As of our recent update, we no longer need the `displayStatsPublic` & `avatar` keys. So please remove these fields from your json. 

```suggestion
  "type": "personal",
  "bio": "As An enthusiastic tech aficionado, I am constantly fueled by my passion to explore and discover",
```

2023-03-13 17:12 UTC, kumarsonsoff3 requested changes
Also add your file to data directory. To do so, you need to [rename your file here](https://github.com/akshatshukla13/LinkFree/edit/akshatshukla13-patch-1/akshatshukla13.json) to `data/akshatshukla13.json`. 

Change `akshatshukla13.json`  - >  `data/akshatshukla13.json`

2023-03-18 01:39 UTC, SaraJaoude commented on data/akshatshukla13.json
> +  "avatar": "https://media.licdn.com/dms/image/D5603AQFA-E-9DFGSUA/profile-displayphoto-shrink_800_800/0/1668493033974?e=1684368000&v=beta&t=RRQZUtcrRu3hXT6yIZoGZ65ydkLUFVakMK4C43lWbPE",
```suggestion
```

2023-03-18 01:40 UTC, SaraJaoude commented on data/akshatshukla13.json
> +  "displayStatsPublic": true,
```suggestion
```

2023-03-18 01:40 UTC, SaraJaoude approved these changes
looks good

2023-03-18 01:41 UTC, merged