data: TanmayBhosale
EddieHubCommunity/LinkFree pull request #5410
Opened 2023-03-13 16:30 UTC by TanmayBhosale

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5410"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-03-13 16:51 UTC, Ananya2001-an commented on data/TanmayBhosale.json
> +  "displayStatsPublic" : true,
We don't need this prop anymore due to latest updates.
```suggestion

```

2023-03-13 16:53 UTC, Ananya2001-an requested changes
Just some minor changes. Rest looks good!

2023-03-15 12:53 UTC, TanmayBhosale commented
Made the changes! Thank you for the input!

2023-03-15 12:53 UTC, Ananya2001-an approved these changes
Looks good! Thanks for contributing 😊

2023-03-15 22:07 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-16 01:11 UTC, SaraJaoude approved these changes
looks good

2023-03-16 01:11 UTC, merged