Testimonials & Milestones added
EddieHubCommunity/LinkFree pull request #5415
Opened 2023-03-13 18:04 UTC by RockingSNP

## Fixes Issue

## Changes proposed
Update Profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers
Review this and help me to update this to my profile

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-03-13 18:23 UTC, TRohit20 approved these changes

2023-03-14 11:46 UTC, MahirMahdi requested changes

2023-03-14 11:46 UTC, MahirMahdi commented on data/RockingSNP/testimonials/RockingSNP.json
> +
I think this addition made JSON check fail. Try removing it.

2023-03-14 13:54 UTC, RockingSNP commented
`Let it be merged`

2023-03-16 01:50 UTC, SaraJaoude commented
> Let it be merged

@RockingSNP writing this is not necessary. All maintainers receive notifications - please do not forget that maintainers are in different timezones and have other commitments. 

I will merge your Pull Request but the point of Testimonials is not to give one to yourself, but to give one to other members of the community.  You may want to take a look at our Testimonials docs here: https://linkfree.eddiehub.io/docs/how-to-guides/testimonials

2023-03-16 01:51 UTC, merged

2023-03-16 03:28 UTC, RockingSNP commented
> > Let it be merged
> 
> @RockingSNP writing this is not necessary. All maintainers receive notifications - please do not forget that maintainers are in different timezones and have other commitments. 
> 
> I will merge your Pull Request but the point of Testimonials is not to give one to yourself, but to give one to other members of the community.  You may want to take a look at our Testimonials docs here: https://linkfree.eddiehub.io/docs/how-to-guides/testimonials

Yes, next time I'll keep that in mind. & Thank You!