data: Chintu1509
EddieHubCommunity/LinkFree pull request #5466
Opened 2023-03-15 16:12 UTC by Chintu1509

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-15 16:17 UTC, vedprakashnautiyal requested changes

2023-03-15 16:17 UTC, vedprakashnautiyal commented on data/Chintu1509.json
> +    }.
this should be ,

2023-03-15 16:19 UTC, vedprakashnautiyal requested changes

2023-03-15 16:19 UTC, vedprakashnautiyal commented on data/Chintu1509.json
> +  "avatar":"https://github.com/Chintu1509",
remove it from the JSON

2023-03-15 18:36 UTC, imbeshat commented on data/Chintu1509.json
> +  "displayStatusPublic":true,
```suggestion
```

2023-03-15 18:37 UTC, imbeshat commented on data/Chintu1509.json
> +  "displayStatusPublic":true,
```displayStatusPublic``` is also not required.

2023-03-18 02:32 UTC, SaraJaoude commented
You have conflicts in your file, please resolve. This is usually because your fork is not up to date.  

You may wish to have a look at the following Docs and video: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-03-18 08:22 UTC, Chintu1509 commented
Thanks for your suggestion, I have updated my fork.

2023-03-18 17:18 UTC, kumarsonsoff3 commented
Duplicate of #5531 

--
Closing this one, as your latest PR with the same changes has been merged recently.

2023-03-18 17:18 UTC, closed without merging