data: saifrahmn
EddieHubCommunity/LinkFree pull request #5474
Opened 2023-03-16 03:34 UTC by saifrahmn

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-16 03:54 UTC, schmelto commented on public/data/saifrahmn.json
> +
```suggestion
```

2023-03-16 06:10 UTC, himanshu1221 requested changes
Hey @saifrahmn please move your file from `public/data` to `data` folder

2023-03-16 08:37 UTC, eddiejaoude requested changes
As previously requested, please allow the docs on updating your fork and your profile. We have a step by step guide and a video https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-03-16 09:53 UTC, eddiejaoude commented on data/saifrahmn.json
> +    "avatar": "https://github.com/saifrahmn.png",
Avatar is not required, please read the docs for the fields https://linkfree.eddiehub.io/docs/quickstart

2023-03-16 09:53 UTC, eddiejaoude commented on data/saifrahmn.json
> +        "icon": "github"
these are not validate icons, please read the docs https://linkfree.eddiehub.io/docs/quickstart

2023-03-16 12:13 UTC, khushalarora requested changes
Hey @saifrahmn, you have not used your own name and Bio. Please correct them. :+1:

2023-03-16 12:13 UTC, khushalarora commented on data/saifrahmn.json
> +  "name": "Sara Jaoude",
Please replace this with your own name "Saif Rahman"

2023-03-16 12:13 UTC, khushalarora commented on data/saifrahmn.json
> +  "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado",
Replace this with your own bio

2023-03-16 13:52 UTC, khushalarora requested changes

2023-03-16 13:52 UTC, khushalarora commented on data/saifrahmn.json
> +  "bio": "Student - Engineer - Snthusiast",
hey @saifrahmn, Spelling of **'Enthusiast'** is not correct here :+1:

2023-03-18 01:27 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🎉

2023-03-18 01:56 UTC, eddiejaoude requested changes
Please remove your duplicate profile with the incorrect username

2023-03-18 03:52 UTC, eddiejaoude commented
> I can not find my files in the repository, even when a search in saifrahmn:patch-1
> [these is the folder i am searching in](https://github.com/saifrahmn/LinkFree/tree/patch-1/data)

I share a link for you already in my review https://github.com/EddieHubCommunity/LinkFree/pull/5474#pullrequestreview-1343299189

2023-03-18 23:50 UTC, eddiejaoude approved these changes
Looks good 👍

2023-03-18 23:50 UTC, eddiejaoude commented
After I merge this please update anywhere you use your LinkFree url, as now it is using your correct GitHub username, your LinkFree url will change

2023-03-18 23:51 UTC, merged

2023-03-19 04:12 UTC, saifrahmn commented
Thanks @eddiejaoude