Create ErArvindk.json
EddieHubCommunity/LinkFree pull request #5485
Opened 2023-03-16 18:17 UTC by ErArvindk

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-16 18:31 UTC, SurajPratap10 submitted a review, later dismissed

2023-03-16 21:07 UTC, khushalarora requested changes

2023-03-16 21:07 UTC, khushalarora commented on data/ErArvindk.json
> +    "wev dev"
Hi @ErArvindk, there is a minor typo in the spelling of **'web'**. Please correct it :+1:

2023-03-17 15:56 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-03-17 15:57 UTC, merged