data:Kgkunal
EddieHubCommunity/LinkFree pull request #5495
Opened 2023-03-17 04:56 UTC by Kgkunal

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-17 07:56 UTC, vedprakashnautiyal commented on data/Kgkunal.json
> +  "avatar":"https://github.com/Kgkunal.png",
```suggestion

```

2023-03-17 07:56 UTC, vedprakashnautiyal requested changes

2023-03-17 07:56 UTC, vedprakashnautiyal commented on data/Kgkunal.json
> +  "avatar":"https://github.com/Kgkunal.png",
You don't have to use avatar....

2023-03-18 01:43 UTC, SaraJaoude approved these changes
looks good

2023-03-18 01:45 UTC, merged

2023-03-18 17:59 UTC, Kgkunal commented
> looks good

Thanks alot  🤗