data: high-prog
EddieHubCommunity/LinkFree pull request #5502
Opened 2023-03-17 13:07 UTC by high-prog

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-17 14:02 UTC, priyankarpal requested changes
you mistakenly added the filename to the root folder please add it into the `data` folder & remember to add your exact github username. `sarthkdobriyal`

- `data/sarthkdobriyal.json` 

- you can see the official docs https://linkfree.io/docs/quickstart

2023-03-17 14:23 UTC, priyankarpal requested changes
- add `.json` next to your username. `data/sarthkdobriyal.json`

2023-03-17 14:44 UTC, priyankarpal requested changes

2023-03-17 18:59 UTC, priyankarpal requested changes

2023-03-17 18:59 UTC, priyankarpal commented on data/sarthkdobriyal.json
> +      "icon": "FaHashnode"
`FaHashnode` is not available. Change to `SiHashnode`

2023-03-18 01:31 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-18 02:04 UTC, priyankarpal approved these changes
Awesome Looks Great 🎉

2023-03-18 02:21 UTC, merged