data: qadatta
EddieHubCommunity/LinkFree pull request #5546
Opened 2023-03-18 19:11 UTC by qadatta

2023-03-18 19:50 UTC, khushalarora requested changes
Hi @qadatta, thank you for contributing  :tada: 
Please rename your file and add  **' data/ '** at the beginning :+1: 
It will look like  `data/qadatta.json`

2023-03-18 19:50 UTC, khushalarora commented on qadatta.json
> +      "icon": "FaLinkedIn"
Please replace it with the value  **' FaLinkedin '**  :+1: 
```suggestion
      "icon": "FaLinkedin"
```

2023-03-19 16:54 UTC, qadatta commented
> 

Updated file path to data/qadatta.json

2023-03-19 23:07 UTC, khushalarora approved these changes
Thank you  :tada:

2023-03-22 12:07 UTC, kumarsonsoff3 approved these changes
Looks awesome. Great collaboration everyone. 👍

2023-03-22 12:08 UTC, merged