data: rohit190183107010
EddieHubCommunity/LinkFree pull request #5547
Opened 2023-03-18 19:25 UTC by rohit190183107010

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-18 20:11 UTC, khushalarora requested changes

2023-03-18 20:11 UTC, khushalarora commented on data/rohit190183107010.json
> +  "avatar": "https://github.com/rohit190183107010.png",
Hi @rohit190183107010, thank you for contributing  :tada: 
You can delete this line, it is not required anymore :+1: 
```suggestion
```

2023-03-18 20:11 UTC, khushalarora commented on data/rohit190183107010.json
> +    },
Please remove the  **'Comma'** after the 'closing brace **}**' :+1: 
```suggestion
    }
```

2023-03-19 02:29 UTC, SaraJaoude approved these changes
looks good

2023-03-19 02:30 UTC, merged