data:B2prakash
EddieHubCommunity/LinkFree pull request #5563
Opened 2023-03-19 20:15 UTC by B2prakash

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

you'll are doing a great job . i would like my linkfree profile to be updated

2023-03-21 04:55 UTC, Krishnapro approved these changes
Look good to merge

2023-03-21 10:06 UTC, khushalarora submitted a review, later dismissed
Thank you for contributing  :tada:

2023-03-22 13:50 UTC, kumarsonsoff3 requested changes

2023-03-22 13:50 UTC, kumarsonsoff3 commented on data/B2prakash.json
> +      "url": "https://linkedin.com/in/ved prakash",
There is a broken URL, Please update it with your LinkedIn url.

2023-03-22 13:50 UTC, kumarsonsoff3 commented on data/B2prakash.json
> +      "url": "https://youtube.com/@ved prakash",
Please fix this one too, as it takes me to `404` 🛠

2023-03-22 13:50 UTC, kumarsonsoff3 commented on data/B2prakash.json
> +      "url": "https://github.com/sponsors/eddiejaoude",
You might want to update it with your Sponsor URL. If you don't have a sponsor page. Then you can remove this section.

2023-03-22 14:23 UTC, B2prakash commented on data/B2prakash.json
> +      "url": "https://youtube.com/@ved prakash",
```suggestion
      "url": "https://youtube.com/@vedprakash2431",
```

2023-03-22 14:23 UTC, B2prakash commented on data/B2prakash.json
> +      "url": "https://linkedin.com/in/ved prakash",
```suggestion
      "url": "https://linkedin.com/in/vedprakash",
```

2023-03-22 14:23 UTC, B2prakash commented on data/B2prakash.json
> +    }
```suggestion
   
```

2023-03-23 13:55 UTC, B2prakash commented on data/B2prakash.json
> +    },
```suggestion
    }
```

2023-03-24 15:46 UTC, closed without merging

2023-03-24 16:24 UTC, eddiejaoude commented
Did you mean to close this @B2prakash ?