data: JonVojtush
EddieHubCommunity/LinkFree pull request #5566
Opened 2023-03-20 03:59 UTC by JonVojtush

- Added initial data file for JonVojtush (me)
- Added testimonials for me from LinkedIn (x2)
- Moved data file for tanitoluwam.json as it appears to be in the wrong directory

2023-03-20 06:35 UTC, ChinmayMhatre requested changes
Added a few comments.

2023-03-20 06:35 UTC, ChinmayMhatre commented on data/JonVojtush.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-03-20 06:35 UTC, ChinmayMhatre commented on data/JonVojtush.json
> +      "icon": "FaLinkedIn",
```suggestion
      "icon": "FaLinkedin",
```

2023-03-20 06:35 UTC, ChinmayMhatre commented on data/JonVojtush.json
Check the icon names from the docs

2023-03-20 06:35 UTC, ChinmayMhatre commented on data/tanitoluwam.json
Please create an issue incase any bugs found before creating a PR. uncommit this file from this PR. This change can come in a separate one. Hope you understand. Thanks!

2023-03-20 13:33 UTC, JonVojtush commented on data/JonVojtush.json
Thank you for identifying the LinkedIn typos. Is there a better place to find the potential icons other than /confic/icons.json? I took the following icons from /data/eddiejaoude.json yet they are not listed in icons.json.

102 "icon": "FaRegMoneyBillAlt"
109 "icon": "FaDollarSign",

Thanks

2023-03-20 13:42 UTC, JonVojtush commented on data/tanitoluwam.json
I created #5571.

Is there a suggested method to revert this specific commit or do i need to move the file back to its original place in my branch as a new commit?

Thank you

2023-03-20 14:17 UTC, eddiejaoude commented
Good spot and great collaboration. I have moved the profile that is in the root of the project here https://github.com/EddieHubCommunity/LinkFree/pull/5573

Please have your PR focused on only your profile changes.

2023-03-21 17:30 UTC, JonVojtush commented on data/JonVojtush.json
I overlooked the site documentation, thank you for sharing.

2023-03-21 17:32 UTC, JonVojtush commented
- [ ] Bookmark & analyse https://linkfree.io/icons

2023-03-31 03:05 UTC, SaraJaoude commented
Please resolve the conflicts in this Pull Request so that we can get this merged

2023-04-03 05:03 UTC, eddiejaoude commented on data/tanitoluwam.json
>        "icon": "FaYoutube"
Please do not modify anyone else's profiles, you can remove these changes from your PR as it will block your PR from getting merged

2023-04-03 05:04 UTC, eddiejaoude requested changes
Please do not make changes to other people's profiles, this will block your PR

2023-04-03 05:19 UTC, closed without merging

2023-04-03 05:22 UTC, eddiejaoude commented
Not sure if you meant to close this PR @JonVojtush ? 

You can revert your changes to that other profile file with the command `git checkout main -- <FILE-NAME>`

But if easier feel free to create a new Pull Request