data: Mohiit70
EddieHubCommunity/LinkFree pull request #5568
Opened 2023-03-20 12:50 UTC by Mohiit70

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers
Hi Eddie,

Thank you for taking the time to review my pull request. This is my first contribution to an open-source project, and I'm excited to be a part of this community.

Please let me know if there's anything that needs to be fixed or improved. I'm open to feedback and eager to learn.

Thank you again for your time and guidance.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5568"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-03-20 13:13 UTC, iamthecloverly approved these changes

2023-03-20 13:13 UTC, Ananya2001-an commented on data/Mohiit70.json
> +  "followMe": [
It has to be links key.
```suggestion
  "links": [
```

2023-03-20 13:15 UTC, Ananya2001-an commented on data/Mohiit70.json
> +      "icon": "FaGitHub"
same here..
```suggestion
      "icon": "FaGithub"
```

2023-03-20 13:17 UTC, Ananya2001-an commented on data/Mohiit70.json
> +      "icon": "Fahashnode"
Not sure but I guess this should also be something like this.
```suggestion
      "icon": "FaHashnode"
```

2023-03-21 10:36 UTC, Ananya2001-an submitted a review, later dismissed
Looks great! Thanks for making the changes 👍🏼

2023-03-21 11:05 UTC, khushalarora requested changes

2023-03-21 11:05 UTC, khushalarora commented on data/Mohiit70.json
> +      "icon": "FaHashnode"
Hi @Mohiit70, thank you for contributing  :tada: 
Please replace this with  **' SiHashnode '** 
You can checkout [ICONS](https://linkfree.eddiehub.io/icons) to search icons.  :+1:

2023-03-21 13:48 UTC, khushalarora approved these changes
Looks good, thanks  :tada:

2023-03-23 09:32 UTC, merged