data:Pushpa-Mali
EddieHubCommunity/LinkFree pull request #5577
Opened 2023-03-20 18:05 UTC by Pushpa-Mali

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-20 18:36 UTC, khushalarora requested changes

2023-03-20 18:36 UTC, khushalarora commented on data/Pushpa-Mali.json
> +      "icon": "FaLinkedIn"
Hi @Pushpa-Mali, thank you for contributing  :tada:
Please replace its value with **' FaLinkedin '**.
```Suggestion
      "icon": "FaLinkedin"
```

2023-03-21 13:55 UTC, khushalarora approved these changes
Looks good, thanks  :tada:

2023-03-23 09:30 UTC, SaraJaoude approved these changes
looks good

2023-03-23 09:31 UTC, merged