data: Engeniusam
EddieHubCommunity/LinkFree pull request #5585
Opened 2023-03-21 11:15 UTC by Engeniusam

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-21 12:13 UTC, khushalarora requested changes

2023-03-21 12:13 UTC, khushalarora commented on data/Engeniusam.json
> +  "avatar": "https://twitter.com/engeniusam/photo",
Hi @Engeniusam, thank you for contributing  :tada: 
Please delete this line, it is not required anymore :+1: 
```Suggestion
```

2023-03-21 12:13 UTC, khushalarora commented on data/Engeniusam.json
> +    ,{
Also remove this extra  **' Comma '** before the **' opening brace  { '**
```Suggestion
    {
```

2023-03-21 12:13 UTC, khushalarora commented on data/Engeniusam.json
> +    },
Also remove this  ' Comma ' after the ' closing brace } '
```Suggestion
    }
```

2023-03-21 19:34 UTC, Engeniusam reviewed
avatar line removed and the extra commas.

2023-03-21 20:15 UTC, khushalarora approved these changes
Looks good, thanks  :tada:

2023-03-22 12:05 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></p>

2023-03-22 12:05 UTC, merged