Patch 1
EddieHubCommunity/LinkFree pull request #5590
Opened 2023-03-21 18:29 UTC by taimoorahmadta

## Fixes Issue

## Changes proposed
I corrected some grammatical errors I readme

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-21 20:08 UTC, devvsakib requested changes

2023-03-21 20:08 UTC, devvsakib commented on README.md
> +
Please change it to `https://linkfree.io/docs` . This is he LinkFree URL now

2023-03-22 00:14 UTC, eddiejaoude requested changes
Please only have a PR focused on a single change.

- your profile should be in its own PR
- any doc changes should be in a separate PR

I suggest removing the doc changes and having this PR as your profile

2023-03-22 00:59 UTC, closed without merging

2023-03-22 01:09 UTC, eddiejaoude commented
You don't need to close it, you can add/remove changes from your open PR. But if creating a new PR is easier for you, that is ok 👍