data: SGsubhash77
EddieHubCommunity/LinkFree pull request #5599
Opened 2023-03-22 10:18 UTC by SGsubhash77

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-22 12:46 UTC, khushalarora requested changes
Hi @SGsubhash77, thank you for contributing  :tada: 
Please rename your file and add  **.json**  at the end.
It will look like  `data/SGsubhash77.json`

2023-03-22 12:46 UTC, khushalarora commented on data/SGsubhash77
> +     },
Remove this **Comma** after the **' closing brace  }'**  :+1: 
```Suggestion
     }
```

2023-03-22 12:46 UTC, khushalarora commented on data/SGsubhash77
> +   ],
Remove this **' Comma '** also  :+1:

2023-03-23 03:58 UTC, SGsubhash77 commented on data/SGsubhash77
> +     { "icon": "FaLinkedin", "url": "https://www.linkedin.com/in/subhash-gandhi/" },
ok sure, I will resolve it.

2023-03-23 04:16 UTC, SGsubhash77 reviewed
I have made the changes you have told @khushalarora

2023-03-23 09:42 UTC, SaraJaoude approved these changes
looks good

2023-03-23 09:42 UTC, merged

2023-03-23 18:30 UTC, SGsubhash77 commented
Thankyou for your comment making my first contribution