data: utkarshkrishna2004
EddieHubCommunity/LinkFree pull request #5642
Opened 2023-03-24 21:13 UTC by utkarshkrishna2004

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-24 21:31 UTC, Panquesito7 requested changes

2023-03-24 21:31 UTC, Panquesito7 commented on data/utkarshkrishna2004.json
> +  "avatar": "https://github.com/utkarshkrishna2004.png",
Your avatar is automatically fetched from your GitHub profile.
```suggestion
```

2023-03-24 22:24 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-03-24 22:59 UTC, khushalarora approved these changes
Looks good :tada:

2023-03-25 01:28 UTC, SaraJaoude approved these changes
looks good

2023-03-25 01:28 UTC, merged

2023-03-25 07:10 UTC, utkarshkrishna2004 commented
Hey people, so I have a question, if I do some changes(say, I want to add my Instagram profile too), do I again have to create a PR for those changes to reflect in my LinkFree page?