data: geeky-sambhav
EddieHubCommunity/LinkFree pull request #5656
Opened 2023-03-25 20:52 UTC by geeky-sambhav

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

You are doing a great job. I would like my Linkfree profile to be updated

2023-03-25 21:25 UTC, khushalarora requested changes
Hi @geeky-sambhav, thank you for contributing  :tada: 
Please rename your file and Add **`data/`** at the beginning :+1: 
It will look like **`data/geeky-sambhav.json`**

2023-03-25 21:25 UTC, khushalarora commented on geeky-sambhav.json
> +			"url": "https://github.com/geeky_sambhav"
This URL is broken, you can correct it :+1:

2023-03-25 21:25 UTC, khushalarora commented on geeky-sambhav.json
> +			"url": "https://github.com/sambhav-gandhi"
I think you want to use your LinkedIn url here :+1:

2023-03-25 21:25 UTC, khushalarora commented on geeky-sambhav.json
> +			"url": "https://github.com/geky-sambhav",
Also, this URL is broken, you can correct it :+1:

2023-03-25 21:25 UTC, khushalarora commented on geeky-sambhav.json
> +			"url": "https://www.linkedin.com/in/sambhav-gandhi",
This URL is also broken :+1:

2023-03-26 14:08 UTC, khushalarora approved these changes
Looks good, thanks  :tada:

2023-03-27 20:58 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></p>

2023-03-27 20:59 UTC, merged