data: ShubhamMore6688
EddieHubCommunity/LinkFree pull request #5662
Opened 2023-03-26 16:32 UTC by ShubhamMore6688

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-26 20:45 UTC, imbeshat requested changes
```avatar``` is not required.

2023-03-26 20:45 UTC, imbeshat commented on data/ShubhamMore6688.json
> +  "avatar": "https://github.com/ShubhamMore6688.png",
```suggestion
```

2023-03-27 11:07 UTC, khushalarora approved these changes
Looks good, thanks :tada:

2023-03-27 12:07 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></p>

2023-03-27 12:07 UTC, merged