data: tarunclub
EddieHubCommunity/LinkFree pull request #5663
Opened 2023-03-26 17:31 UTC by tarunclub

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-26 18:19 UTC, vedprakashnautiyal commented on data/tarunclub.json
> +	"displayStatsPublic": true,
```suggestion
```

2023-03-26 18:19 UTC, vedprakashnautiyal requested changes

2023-03-26 18:19 UTC, vedprakashnautiyal commented on data/tarunclub.json
> +	"displayStatsPublic": true,
This is not required .

2023-03-26 20:31 UTC, khushalarora approved these changes
Thank you for contributing  :tada:

2023-03-27 00:29 UTC, mahfuztbt approved these changes

2023-03-27 12:05 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></p>

2023-03-27 12:05 UTC, merged