data:Junnygram
EddieHubCommunity/LinkFree pull request #5680
Opened 2023-03-28 07:18 UTC by Junnygram

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-03-28 09:49 UTC, ChinmayMhatre requested changes
Looks awesome! Left a comment for a change. Could you tell me what resource you followed to create the json file? someone's profile or documentation? Just asking as feedback.

2023-03-28 09:49 UTC, ChinmayMhatre commented on data/Junnygram.json
> +"avatar" : "https://avatars.githubusercontent.com/u/90139191?v=4",
```suggestion
```

2023-03-28 09:49 UTC, ChinmayMhatre commented on data/Junnygram.json
> +"avatar" : "https://avatars.githubusercontent.com/u/90139191?v=4",
You can remove this field as it isn't required anymore.

2023-03-29 02:40 UTC, Junnygram commented
> Looks awesome! Left a comment for a change. Could you tell me what resource you followed to create the json file? someone's profile or documentation? Just asking as feedback.

well its all in the starter guide, i just followed the template, did i do something wrong?

2023-03-29 04:00 UTC, closed without merging

2023-03-29 05:40 UTC, ChinmayMhatre commented
> > Looks awesome! Left a comment for a change. Could you tell me what resource you followed to create the json file? someone's profile or documentation? Just asking as feedback.
> 
> well its all in the starter guide, i just followed the template, did i do something wrong? 
> 

Not at all! I was wondering which guide had the avatar property. So that we could remove it from the documentation.

Please reopen this PR, the PR needs to be merged by the maintainer so that you can see your profile.