data: roberanegussie
EddieHubCommunity/LinkFree pull request #5689
Opened 2023-03-28 18:55 UTC by roberanegussie

## Fixes Issue

## Changes proposed
Adding my profile

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-28 19:32 UTC, khushalarora requested changes
Hi @roberanegussie, thank you for contributing :tada:

2023-03-28 19:32 UTC, khushalarora commented on data/roberanegussie.json
> +      "icon": "FaLinkedIn"
Please replace it with **' FaLinkedin '**  :+1: 
You can also checkout [ICONS](https://linkfree.eddiehub.io/icons) for valid icons.
```Suggestion
      "icon": "FaLinkedin"
```

2023-03-28 19:32 UTC, khushalarora commented on data/roberanegussie.json
> +      "icon": "FaGitHub"
Please replace it with **' FaGithub '**  :+1: 
```Suggestion
      "icon": "FaGithub"
```

2023-03-29 06:40 UTC, roberanegussie commented
@khushalarora  I have made the changes kindly review.

2023-03-30 06:36 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></p>

2023-03-30 06:36 UTC, merged