data: BenceDv
EddieHubCommunity/LinkFree pull request #5691
Opened 2023-03-28 21:48 UTC by BenceDv

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-28 22:18 UTC, khushalarora requested changes
Hi @BenceDv, thank you for contributing :tada:

2023-03-28 22:18 UTC, khushalarora commented on data/BenceDv.json
> +    },
Please add a  square bracket &nbsp; **' ] '** &nbsp;&nbsp; between &nbsp; " } " &nbsp; and  &nbsp; " , "
```Suggestion
    }],
```

2023-03-28 22:18 UTC, khushalarora commented on data/BenceDv.json
> +]
Delete this **' square bracket  ] '** :+1: 
```Suggestion
```

2023-03-31 02:51 UTC, SaraJaoude approved these changes
looks good

2023-03-31 02:51 UTC, merged