data: dineshlalam15
EddieHubCommunity/LinkFree pull request #5706
Opened 2023-03-29 14:51 UTC by dineshlalam15

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-29 15:59 UTC, kumarsonsoff3 requested changes

2023-03-29 15:59 UTC, kumarsonsoff3 commented on data/dineshlalam15.json
> +    }
Please add a missing comma `,` here.

```suggestion
    },
```

2023-03-29 20:00 UTC, khushalarora commented on data/dineshlalam15.json
>        "icon": "FaLinkedIn"
Hi @dineshlalam15, thank you for contributing  :tada:
Please replace it with &nbsp; **' FaLinkedin '** &nbsp; :+1: 
```Suggestion
      "icon": "FaLinkedin"
```

2023-03-30 05:55 UTC, kumarsonsoff3 requested changes

2023-03-30 05:55 UTC, kumarsonsoff3 commented on data/dineshlalam15.json
>      }
There is another missing comma `,`

```suggestion
    },
```

2023-03-30 06:06 UTC, kumarsonsoff3 commented on data/dineshlalam15.json
> +      "icon": "FaHashnode"
You probably be using an invalid icon here, it should be `SiHashnode`.

```suggestion
      "icon": "SiHashnode"
```

2023-03-30 06:27 UTC, merged