Modified user tabs on a mobile viewport when user has only 1 tab
EddieHubCommunity/LinkFree pull request #5711
Opened 2023-03-29 21:50 UTC by KaveriRai

Closes #3080 

## Changes proposed

In UserTabs.js:
1. Modified the sm:hidden class div to remove the dropdown on mobile view if number of tabs for a user is less than 2
2. Created a functional component MultipleTabsDisplay to avoid code duplication as it renders the regular tabs display on a computer viewport 
3. MultipleTabsDisplay is conditionally called in sm:hidden and always called in hidden:sm 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

Original dropdown:
<img width="277" alt="Screen Shot 2023-03-29 at 5 46 32 PM" src="https://user-images.githubusercontent.com/66638197/228675015-2789550e-f61e-4ed3-bf57-fd8c01d1d31c.png">

Modified version with dropdown removed for tabs with less than 2 tabs:
<img width="350" alt="Screen Shot 2023-03-29 at 5 47 36 PM" src="https://user-images.githubusercontent.com/66638197/228675196-e1e5c076-efb1-400d-bce7-7c74a9cb1108.png">
People with more than 2 tabs still have the dropdown: 
<img width="449" alt="Screen Shot 2023-03-29 at 5 48 46 PM" src="https://user-images.githubusercontent.com/66638197/228675386-c4f2bd71-4fba-492d-9f2c-b6def72203eb.png">

## Note to reviewers

2023-03-30 03:43 UTC, eddiejaoude commented on components/user/UserTabs.js
> -      <div className="sm:hidden">
I think it would be cleaner to have less changes by wrapping this `div` in ...

```js
{ tabs.length > 1 && <div className="sm:hidden">}
```

2023-03-30 03:43 UTC, eddiejaoude requested changes
Added inline comment

2023-03-31 19:08 UTC, KaveriRai commented
Just made the requested changes

2023-04-02 01:27 UTC, eddiejaoude commented
It seems like there are no long any changes in this pull request?

2023-04-03 03:11 UTC, eddiejaoude commented
This PR still has no changes, so I will close. Please create a new PR.

<img width="1664" alt="Screenshot 2023-04-03 at 10 10 26" src="https://user-images.githubusercontent.com/624760/229402859-4146381a-96f7-4ec8-b6dd-99997206dc82.png">

2023-04-03 03:11 UTC, closed without merging