data:shubham185y
EddieHubCommunity/LinkFree pull request #5723
Opened 2023-03-30 16:09 UTC by Shubham185y

2023-03-30 16:25 UTC, accodes21 requested changes
Change your filename to that of your github username i.e ```Shubham185y.json```

2023-03-30 17:04 UTC, vedprakashnautiyal commented on Shubham185y.json
> +      "url": "https://twitter.com/Shubham185y",
This account doesn't exist.......!!??

2023-03-30 17:06 UTC, vedprakashnautiyal commented
Also your json file should be in the data folder......

2023-03-30 17:25 UTC, Shubham185y commented on Shubham185y.json
> +      "url": "https://twitter.com/Shubham185y",
thank you i miss placed y in the username a bit confusing from github and twitter

2023-03-31 03:14 UTC, SaraJaoude commented
> > Also your json file should be in the data folder......
> 
> how to add it to data folder

Please take a look at the QuickStart guide in Docs as this should help you: https://linkfree.eddiehub.io/docs/quickstart

2023-04-04 09:58 UTC, khushalarora approved these changes
Thank you for contributing  :tada:

2023-04-05 10:39 UTC, kumarsonsoff3 approved these changes
Looks awesome. Great collaboration everyone. 👍

2023-04-05 10:39 UTC, merged