data: prasunkundu.json
EddieHubCommunity/LinkFree pull request #5725
Opened 2023-03-30 18:13 UTC by PrasunKundu

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-03-30 18:48 UTC, priyankarpal requested changes
mistake

2023-03-30 18:51 UTC, priyankarpal requested changes

2023-03-30 18:51 UTC, priyankarpal commented on data/prasunkundu.json
> +  "bio": "Electrical engineering grad who have a deep passion in **Cs and Softwares**. Learning new tech stacks by contributing in OpenSource"
add `,` after the line.
``` suggestion
  "bio": "Electrical engineering grad who has a deep passion in **Cs and Softwares**. Learning new tech stacks by contributing to OpenSource",
```

2023-03-30 18:53 UTC, priyankarpal requested changes

2023-03-30 18:53 UTC, priyankarpal commented on data/prasunkundu.json
> +  "icon": "FaInstagram",
delete `,` after the line.
``` suggestion
  "icon": "FaInstagram"
}
```

2023-03-30 18:53 UTC, priyankarpal commented on data/prasunkundu.json
> +  "icon": "FaGithub",
also remove `,` from here.
```suggestion
  "icon": "FaGithub"
```

2023-03-31 02:55 UTC, priyankarpal requested changes
Also rename to `PrasunKundu.json`

2023-03-31 03:21 UTC, SaraJaoude commented on data/prasunkundu.json
> +}
missing a comma
```suggestion
},
```

2023-03-31 18:28 UTC, PrasunKundu commented on data/prasunkundu.json
> +  "icon": "FaInstagram"
ok

2023-03-31 18:31 UTC, PrasunKundu commented on data/prasunkundu.json
> +]
,

2023-03-31 19:12 UTC, PrasunKundu commented
hey eddie i am waiting for your approval. :)

2023-03-31 19:12 UTC, closed without merging