added changelog.js file in user
EddieHubCommunity/LinkFree pull request #5727
Opened 2023-03-30 20:08 UTC by ApurvaBasule

added changelog file to user to track profile progress

2023-03-30 20:56 UTC, ApurvaBasule commented
closes #5727

2023-03-30 20:57 UTC, ApurvaBasule commented
#5727 closes

2023-03-31 00:56 UTC, eddiejaoude commented on .env.example
> +NEXTAUTH_SECRET="afsfdsafadsf"
You should not commit your secrets here, please remove these changes and reset your GitHub OAuth secrets

2023-03-31 00:57 UTC, eddiejaoude commented on pages/changelog.js
> +import { CalendarIcon } from "@heroicons/react/20/solid";
The file already exists, you only need to add a new object entry here 
https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/changelog.js#L12

2023-03-31 00:58 UTC, eddiejaoude requested changes
Thank you for your contribution, I have added some inline comments

Also please do not commit the `package-lock.json` file if you have not made changes to the `package.json` file

2023-03-31 06:44 UTC, bharat5604 requested changes
Remove secret tokens

2023-03-31 06:57 UTC, eddiejaoude commented
> Remove secret tokens

@bharat5604 thank you for reviewing, please read existing comments first as this has already been mentioned here https://github.com/EddieHubCommunity/LinkFree/pull/5727#pullrequestreview-1366114316 , repeating the same comments does not help, can scare off contributors and also creates more notifications for everyone

2023-03-31 09:55 UTC, closed without merging