data: PrasunKundu
EddieHubCommunity/LinkFree pull request #5760
Opened 2023-03-31 19:54 UTC by PrasunKundu

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-01 01:10 UTC, imbeshat requested changes

2023-04-01 01:10 UTC, imbeshat commented on data/PrasunKundu.json
> +{ "name": Prasun Kundu",
```suggestion
{ "name":  "Prasun Kundu",
```

2023-04-01 01:10 UTC, imbeshat commented on data/PrasunKundu.json
> + "displayStatsPublic": true,
```suggestion
```

2023-04-01 01:10 UTC, imbeshat commented on data/PrasunKundu.json
> + "displayStatsPublic": true,
not required.

2023-04-01 01:10 UTC, imbeshat commented on data/PrasunKundu.json
> +"avatar": "https://github.com/PrasunKundu",
```suggestion
```

2023-04-01 01:10 UTC, imbeshat commented on data/PrasunKundu.json
> +"avatar": "https://github.com/PrasunKundu",
not required

2023-04-01 01:10 UTC, imbeshat commented on data/PrasunKundu.json
> +    },
```suggestion
    }
```

2023-04-01 07:08 UTC, PrasunKundu commented on data/PrasunKundu.json
> +    },
+ ]
+}

2023-04-01 07:08 UTC, PrasunKundu commented on data/PrasunKundu.json
> +{ "name": Prasun Kundu",
{ "name": "Prasun Kundu",

2023-04-01 08:23 UTC, Pradumnasaraf requested changes
Hey,

There is a missing `"`. Fix that to make the Pull Request ready for merge

2023-04-01 08:23 UTC, Pradumnasaraf commented on data/PrasunKundu.json
> +{ "name": Prasun Kundu",
```suggestion
{ "name": "Prasun Kundu",
```

2023-04-01 08:49 UTC, PrasunKundu commented on data/PrasunKundu.json
> +{ "name": Prasun Kundu",
Hey , i have made tha changes kindly check

2023-04-01 16:06 UTC, vedprakashnautiyal approved these changes
LGTM 🌱

2023-04-01 16:51 UTC, Pradumnasaraf approved these changes
Looks good to merge. Thank you for your contribution! :tada:

2023-04-01 16:54 UTC, Pradumnasaraf submitted a review, later dismissed
There is still a chnage need to be done, removing the extra `,` suggested by https://github.com/EddieHubCommunity/LinkFree/pull/5760/files#r1155069528

2023-04-01 16:54 UTC, Pradumnasaraf commented on data/PrasunKundu.json
> +    },
```suggestion
    }
```

2023-04-02 06:32 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-04-02 09:27 UTC, imbeshat approved these changes

2023-04-09 02:58 UTC, merged