Create akhilesh-w.json
EddieHubCommunity/LinkFree pull request #5763
Opened 2023-03-31 22:18 UTC by akhilesh-w

2023-04-01 01:06 UTC, imbeshat requested changes

2023-04-01 01:06 UTC, imbeshat commented on data/akhilesh-w.json
> +  "bio": "Designer & Developer"
```suggestion
  "bio": "Designer & Developer",
```

2023-04-01 01:06 UTC, imbeshat commented on data/akhilesh-w.json
> +    }
```suggestion
    },
```

2023-04-01 01:06 UTC, imbeshat commented on data/akhilesh-w.json
> +    }
```suggestion
    },
```

2023-04-01 01:06 UTC, imbeshat commented on data/akhilesh-w.json
> +    }
```suggestion
    },
```

2023-04-01 01:06 UTC, imbeshat commented on data/akhilesh-w.json
> +      "url": "https://twitter.com/dichotomyofakhil",
should be Instagram URL.

2023-04-01 10:15 UTC, Amishapopli1 commented on data/akhilesh-w.json
> +    }
"url": "https://instagram.com/dichotomyofakhil".

2023-04-01 10:18 UTC, Amishapopli1 commented on data/akhilesh-w.json
use instagram url

2023-04-01 12:07 UTC, akhilesh-w commented
Thanks for the link review @imbeshat

2023-04-01 13:01 UTC, khushalarora requested changes
Hi @akhilesh-w, thank you for contributing :tada:

2023-04-01 13:01 UTC, khushalarora commented on data/akhilesh-w.json
> +      "icon": "FaGitHub"
Replace it with **' FaGithub '** :+1: 
```Suggestion
      "icon": "FaGithub"
```

2023-04-02 04:01 UTC, SaraJaoude approved these changes
looks good

2023-04-02 04:02 UTC, merged