data: Palakkgoyal
EddieHubCommunity/LinkFree pull request #5814
Opened 2023-04-03 08:56 UTC by Palakkgoyal

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-03 09:37 UTC, khushalarora requested changes

2023-04-03 09:37 UTC, khushalarora commented on data/Palakkgoyal.json
> +    },
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
    }
```

2023-04-03 09:37 UTC, khushalarora commented on data/Palakkgoyal.json
> +  "displayStatsPublic": true,
You can delete this line, it is not required anymore :+1: 
```Suggestion
```

2023-04-03 09:37 UTC, khushalarora commented on data/Palakkgoyal.json
> +  "avatar": "https://github.com/Palakkgoyal.png",
you can delete this line, it is not required anymore :+1: 
```Suggestion
```

2023-04-03 09:39 UTC, khushalarora requested changes
Hi @Palakkgoyal, thank you for contributing :tada:

2023-04-03 10:32 UTC, accodes21 approved these changes

2023-04-03 11:44 UTC, SandeepKrSuman approved these changes
Thanks, @Palakkgoyal 🎉 Looks good to me!

2023-04-03 12:58 UTC, khushalarora approved these changes
Thank you for contributing  :tada:

2023-04-03 20:46 UTC, SurajPratap10 approved these changes
Thanks for contributing 👍

2023-04-04 02:09 UTC, SaraJaoude approved these changes
looks good

2023-04-04 02:09 UTC, merged