updated social links
EddieHubCommunity/LinkFree pull request #5834
Opened 2023-04-04 10:52 UTC by tanitoluwam

## Changes proposed
feat:edited my social links, some of them were not working

2023-04-04 14:19 UTC, kumarsonsoff3 requested changes

2023-04-04 14:19 UTC, kumarsonsoff3 commented on data/tanitoluwam.json
> +      "url": "https://www.youtube.com/@tanisjourney7489"
Please add the missing comma `,` here. 

```suggestion
      "url": "https://www.youtube.com/@tanisjourney7489",
```

2023-04-05 15:17 UTC, AnushaSP07 submitted a review, later dismissed

2023-04-07 05:11 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:11 UTC, merged