data: anekemichael
EddieHubCommunity/LinkFree pull request #5838
Opened 2023-04-04 13:29 UTC by anekemichael

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-04 13:45 UTC, anekemichael commented
Please what is the problem with my file.?

2023-04-04 13:49 UTC, khushalarora requested changes
Hi @anekemichael, thank you for contributing   :tada:

2023-04-04 13:49 UTC, khushalarora commented on data/anekemichael.json
> +    },
Please remove this extra **' Comma '** from this line :+1: 
```Suggestion
    }
```

2023-04-07 05:10 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:19 UTC, merged

2023-04-07 10:48 UTC, anekemichael commented
Thanks so much @SaraJaoude

2023-04-08 16:18 UTC, anekemichael reviewed
Please i would like to add some links in my commit

2023-04-09 02:45 UTC, SaraJaoude commented
> Please i would like to add some links in my commit

If you would like to add links to your Profile, you will need to open a new Pull Request.  I suggest you look at the Editing Guide in Docs and follow the steps: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-04-09 14:10 UTC, anekemichael commented
Alright.. Thanks so much