data:ROUSE_prog
EddieHubCommunity/LinkFree pull request #5861
Opened 2023-04-05 15:28 UTC by ROUSE-prog

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-05 16:15 UTC, amandamartin-dev requested changes

2023-04-05 16:15 UTC, amandamartin-dev commented on data/ROUSE-prog.json
> +  "displayStatsPublic": true,
```suggestion
 
```

2023-04-05 16:15 UTC, amandamartin-dev commented on data/ROUSE-prog.json
> +  "avatar": "https://github.com/ROUSE-prog.png"
```suggestion
 
```

2023-04-05 16:15 UTC, amandamartin-dev commented on data/ROUSE-prog.json
> +  "bio": "Full-stack Developer, Jazz enthusiast, and eating curry where I roam."
```suggestion
  "bio": "Full-stack Developer, Jazz enthusiast, and eating curry where I roam.",
```

2023-04-07 05:20 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:21 UTC, merged