Create jaiswalshash.json
EddieHubCommunity/LinkFree pull request #5863
Opened 2023-04-05 17:11 UTC by jaiswalshash

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/5863"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-04-06 11:10 UTC, khushalarora requested changes
Hi @jaiswalshash, thank you for contributing :tada:

2023-04-06 11:10 UTC, khushalarora commented on data/jaiswalshash.json
> +  "bio": "Existing in a spider-verse where coding and sketching meet"
Please add a **' Comma '** at the end of this line :+1: 
```Suggestion
  "bio": "Existing in a spider-verse where coding and sketching meet",
```

2023-04-06 11:10 UTC, khushalarora commented on data/jaiswalshash.json
> +    },
Please replace the **'Comma'** with a **' Square Bracket **]** '** in this line. Thank you :+1: 
```Suggestion
    }]
```

2023-04-07 05:23 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:30 UTC, merged