data: nfa1
EddieHubCommunity/LinkFree pull request #5873
Opened 2023-04-06 02:38 UTC by nfa1

## Fixes Issue

## Changes proposed

Added my name, bio and 2 social media links (Twitter & GitHub) to this new file.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-06 04:29 UTC, SandeepKrSuman requested changes

2023-04-06 04:29 UTC, SandeepKrSuman commented on data/nfa1.json
> +			"icon": "FaGitHub"
```diff
-  "icon": "FaGitHub"

+ "icon": "FaGithub"
```

2023-04-06 04:29 UTC, SandeepKrSuman commented on data/nfa1.json
> +	"bio": "Software Engineering|Data Science|Python|SQL|R|HTML|CSS|JavaScript",
You may add proper spacing if that will look good.

> "Software Engineering | Data Science | Python | SQL | R | HTML | CSS | JavaScript"

2023-04-06 11:43 UTC, nfa1 commented
Applied changes thanks!

2023-04-06 16:48 UTC, SandeepKrSuman approved these changes
Thanks, @nfa1 🎉 Looks good to me!

2023-04-07 05:25 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:25 UTC, merged