data:StarKnightt
EddieHubCommunity/LinkFree pull request #5874
Opened 2023-04-06 06:00 UTC by StarKnightt

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-06 07:48 UTC, ChinmayMhatre requested changes
Looks awesome! A few changes need to be done for which I have left comments

2023-04-06 07:48 UTC, ChinmayMhatre commented on data/StarKnightt.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-04-06 07:48 UTC, ChinmayMhatre commented on data/StarKnightt.json
> +      "icon": "FaGitHub"
```suggestion
      "icon": "FaGithub"
```

2023-04-06 07:50 UTC, ChinmayMhatre commented
Please check the rest of the icons from the set of available icons at : https://linkfree.io/icons

2023-04-06 09:56 UTC, khushalarora requested changes
Hi @StarKnightt, thank you for contributing :tada:

2023-04-06 09:56 UTC, khushalarora commented on data/StarKnightt.json
> +      "icon": "FaGitHub"
You only need to replace this with **' FaGithub '**, &nbsp;as suggested by @ChinmayMhatre.
Rest everything looks good :+1: 
```Suggestion
      "icon": "FaGithub"
```

2023-04-07 05:27 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:30 UTC, merged

2023-04-07 06:01 UTC, StarKnightt commented
> looks good

Thank YOU