data:EminTalhaArik
EddieHubCommunity/LinkFree pull request #5876
Opened 2023-04-06 10:27 UTC by EminTalhaArik

2023-04-06 10:48 UTC, khushalarora requested changes
Hi @EminTalhaArik, thank you for contributing :tada:

2023-04-06 10:48 UTC, khushalarora commented on data/EminTalhaArik.json
> +    "Django",
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
    "Django"
```

2023-04-06 10:48 UTC, khushalarora commented on data/EminTalhaArik.json
> +      "icon": "FaInstagram",
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
      "icon": "FaInstagram"
```

2023-04-06 10:48 UTC, khushalarora commented on data/EminTalhaArik.json
> +      "icon": "FaTwitter",
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
      "icon": "FaTwitter"
```

2023-04-06 10:48 UTC, khushalarora commented on data/EminTalhaArik.json
> +    },
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
    }
```

2023-04-06 10:48 UTC, khushalarora commented on data/EminTalhaArik.json
> +  ],
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
  ]
```

2023-04-07 05:33 UTC, SaraJaoude approved these changes
looks good

2023-04-07 05:33 UTC, merged