data: OtomuolaAdebayo
EddieHubCommunity/LinkFree pull request #5882
Opened 2023-04-06 13:58 UTC by OtomuolaAdebayo

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-07 05:38 UTC, SaraJaoude commented on data/OtomuolaAdebayo.json
> +  "displayStatsPublic": true
This is no longer required:
```suggestion
```

2023-04-15 08:51 UTC, iamravi1 requested changes

2023-04-15 08:51 UTC, iamravi1 commented on data/OtomuolaAdebayo.json
> +  "displayStatsPublic": true
Add comma `,` at the end of the line or remove it (no longer needed)

2023-04-16 05:00 UTC, SaraJaoude commented
I have committed the change so that the JSON check will pass and I will merge your Pull Request. 

As a suggestion, when you are ready to add links to your Profile, I suggest you have a look at your Editing Guide in Docs: https://linkfree.io/docs/how-to-guides/editing and then raise a new Pull Request.

2023-04-16 05:00 UTC, merged