data: 1js2002
EddieHubCommunity/LinkFree pull request #5894
Opened 2023-04-07 09:00 UTC by 1js2002

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-07 11:35 UTC, khushalarora requested changes
Hi @1js2002, thank you for contributing :tada: 
Please rename your file and add **`data/`** in the beginning :+1: 
It will look like **`data/1js2002.json`**

2023-04-07 12:30 UTC, 1js2002 reviewed
changed the filename from "1js2002.json" to "data/1js2002.json"

2023-04-07 16:38 UTC, kumarsonsoff3 commented on data/1js2002.json
> +      "url": "https://github.com/1js2002",
Did you mean with **GitHub** here!?

```suggestion
      "name": "Follow me on GitHub",
      "url": "https://github.com/1js2002",
```

2023-04-07 19:01 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-04-08 01:12 UTC, kumarsonsoff3 approved these changes
Looks awesome. Great collaboration everyone. 👍

2023-04-08 01:12 UTC, merged