Update Manazsharma.json
EddieHubCommunity/LinkFree pull request #5925
Opened 2023-04-08 10:21 UTC by Manazsharma

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-08 10:32 UTC, khushalarora requested changes
Hi @Manazsharma, thank you for contributing :tada:

2023-04-08 10:32 UTC, khushalarora commented on data/Manazsharma.json
> +  "C++" ]
Please add a **' Comma '** at the end of this line :+1: 
```Suggestion
  "C++" ],
```

2023-04-08 15:40 UTC, vedprakashnautiyal approved these changes

2023-04-09 02:52 UTC, SaraJaoude commented
You have conflicts in your file, please resolve. This is usually because your fork is not up to date.  

You may wish to have a look at the following Docs and video: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-04-10 10:23 UTC, closed without merging