Arranges user milestones in descending order.
EddieHubCommunity/LinkFree pull request #5991
Opened 2023-04-11 11:20 UTC by Vedant-Manjrekar

## Fixes Issue #5945

## Changes proposed

- Arranges user milestones in descending order according to the milestone date.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

### Before:
<img width="790" alt="Screenshot 2023-04-11 at 4 44 47 PM" src="https://user-images.githubusercontent.com/93585735/231144053-6bb5d06b-90df-4a1c-b8b1-27d33af82511.png">

### After:
<img width="789" alt="Screenshot 2023-04-11 at 4 44 21 PM" src="https://user-images.githubusercontent.com/93585735/231144155-ba575528-8e90-422e-9a44-25b1cdb26548.png">

## Note to reviewers

2023-04-12 14:36 UTC, FrozenHearth approved these changes

2023-04-12 21:26 UTC, amandamartin-dev requested changes
This looks good, but can you remove your package lock file from the PR, it's not needed.

2023-04-13 05:49 UTC, eddiejaoude commented
Thank you for your contribution @Vedant-Manjrekar 👍 but I will be closing this Pull Request because the issue is not assigned to you and this creates more work for everyone - for example see how many people have been involved in the Issue and Pull Request discussion already

The other reason is on a technical note, I do not think reversing the data is the solution, because some people actually have the data in descending order themselves and this would create a bug for them. The data should be sorted on the date in descending order, there it would always work even if someone puts items in the collection in random order.

It is great you are keen to contribute to LinkFree, I hope we can continue to collaborate together more efficiently.

2023-04-13 05:49 UTC, closed without merging

2023-04-13 07:35 UTC, Vedant-Manjrekar commented
> Thank you for your contribution @Vedant-Manjrekar 👍 but I will be closing this Pull Request because the issue is not assigned to you and this creates more work for everyone - for example see how many people have been involved in the Issue and Pull Request discussion already
> 
> The other reason is on a technical note, I do not think reversing the data is the solution, because some people actually have the data in descending order themselves and this would create a bug for them. The data should be sorted on the date in descending order, there it would always work even if someone puts items in the collection in random order.
> 
> It is great you are keen to contribute to LinkFree, I hope we can continue to collaborate together more efficiently.

Got it. I will try to be more careful next time onwards while contributing. My sincere apologies to everyone for the inconvenience caused because of me.