data:PushkarRoy
EddieHubCommunity/LinkFree pull request #5996
Opened 2023-04-11 13:56 UTC by roy2pushkar

2023-04-11 14:09 UTC, shyamtawli commented on PushkarRoy.json
> +    }
add `,` after `}`

2023-04-11 16:45 UTC, vedprakashnautiyal requested changes
Also please add your json file in data folder.......

2023-04-11 16:45 UTC, vedprakashnautiyal commented on PushkarRoy.json
> +    }
```suggestion
    },
```

2023-04-11 17:29 UTC, kumarsonsoff3 requested changes
Hey Pushkar, please move your file into data directory and [rename it here](https://github.com/roy2pushkar/LinkFree/edit/roy2pushkar-patch-1/PushkarRoy.json) to exact same as your username. 

Change `PushkarRoy.json`  -->  `data/roy2pushkar.json`

Also, make the changes requested by Shyam and Vedprakash above. 🛠

2023-04-11 18:24 UTC, roy2pushkar commented
please help...why my JSON check failed ??

2023-04-12 04:26 UTC, SaraJaoude commented
I am going to close this Pull Request as this is a duplicate of #5999

2023-04-12 04:26 UTC, closed without merging