Fixed a, blockquote, strong tags in darkmode
EddieHubCommunity/LinkFree pull request #6000
Opened 2023-04-11 18:34 UTC by ChinmayMhatre

## Fixes Issue
closes #5922 closes #5926

2023-04-11 18:41 UTC, ChinmayMhatre commented
A good first issue can be moving the li, table tag to separate components similar to these tags

2023-04-12 01:35 UTC, eddiejaoude commented on components/mdx/BlockQuote.js
> +        <blockquote className='text-primary-medium dark:text-primary-low-medium'>{children}</blockquote>
I think should be double quotes

2023-04-12 01:36 UTC, eddiejaoude commented on components/mdx/ComponentStyle.js
> +import BlockQuote from "@components/mdx/BlockQuote";
Blank link between import and export would be more readable and match other files

2023-04-12 01:36 UTC, eddiejaoude commented on components/mdx/Strong.js
> +    return (
I think indentation might not math our style

2023-04-12 01:37 UTC, eddiejaoude commented on components/mdx/Strong.js
> +        <span className=" font-bold">{children}</span>
I don't think the extra space is needed here

```suggestion
        <span className="font-bold">{children}</span>
```

2023-04-12 01:37 UTC, eddiejaoude commented on components/mdx/Strong.js
> +export default Strong
Ending blank line is recommended by GitHub

2023-04-12 01:38 UTC, eddiejaoude requested changes
@ChinmayMhatre looks great 👍  thank you for making these contributions 

Just some formatting feedback

2023-04-12 01:45 UTC, eddiejaoude approved these changes
These are super important improvements, so I am keen to get them in, I will fix the formatting via a temporary branch (I hope you don't mind)

2023-04-12 01:46 UTC, merged

2023-04-12 01:49 UTC, eddiejaoude commented on components/mdx/BlockQuote.js
> +import React from 'react'
Actually, I don't think this import is used

2023-04-12 03:48 UTC, eddiejaoude commented
no problem Chinmay, you did all the hard work 💪 , I am happy to reformat because that is the easy part

2023-04-12 03:53 UTC, eddiejaoude commented
yes your PR has been merged, reformatted and deployed 👍

2023-04-12 03:59 UTC, ChinmayMhatre commented
> yes your PR has been merged, reformatted and deployed 👍

Oh no I was asking if. Like we have separate components for a, blockquotes, strong can we do it for table, li in the `componentStyle` file?
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/51131670/231345864-a2119d53-d9ae-41c2-b700-0aea783d110b.png">

2023-04-12 04:05 UTC, ChinmayMhatre commented
> Sorry @ChinmayMhatre , I read your previous comment too fast and missed your question 🤦‍♂️
> 
> Yes we should do this, if you like can you create an issue for each one, and maybe those could be `good first issue` for someone else to do

I think we should make it a `good first issue` it can be a good one for first timers 💪🏻. Should I create separate issue for `table` and `li`? Wouldn't it create a conflict? it'd be confusing for beginners? what do you think?

2023-04-12 04:10 UTC, eddiejaoude commented
I think make them separate issues, I can always resolve conflicts if any - although they are different lines so hopefully git figures it out ok - that way 2 people can get started with contributing