data: im-machakata (init)
EddieHubCommunity/LinkFree pull request #6007
Opened 2023-04-12 02:02 UTC by im-machakata

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

Adding new profile data

2023-04-12 15:22 UTC, shyamtawli requested changes

2023-04-12 15:22 UTC, shyamtawli commented on data/EddieHubCommunity/im-machakata.json
> +    "DevOps",
remove `,` from last element that is `"DevOps"`

2023-04-13 15:51 UTC, Sindhuinti requested changes

2023-04-13 15:51 UTC, Sindhuinti commented on data/EddieHubCommunity/im-machakata.json
> +    },
Please remove the comma `,` here

2023-04-14 22:14 UTC, im-machakata commented on data/EddieHubCommunity/im-machakata.json
> +    },
Done, thanks!

2023-04-14 23:42 UTC, Panquesito7 requested changes
Please remove the `im-machakata` folder and keep your filename in the `data` directory only.
Let us know if you need any help updating that. 🙂

2023-04-15 09:12 UTC, im-machakata commented
Sorry for the delay. I had to resort to using my phone. Please let me know if there are any more errors

2023-04-15 09:18 UTC, im-machakata commented
> Please remove the `im-machakata` folder and keep your filename in the `data` directory only. Let us know if you need any help updating that. 🙂

Thanks I had forgotten to push it.

2023-04-15 18:34 UTC, shyamtawli reviewed
LGTM now.

2023-04-16 05:12 UTC, SaraJaoude approved these changes
looks good now

2023-04-16 05:12 UTC, merged