#6012:Move table from ComponentStyles  to a separate component called Table
EddieHubCommunity/LinkFree pull request #6021
Opened 2023-04-12 12:59 UTC by ajaxbo360

## Fixes Issue

 Closes issue : #6012 

## Changes proposed
 - Move table from ComponentStyles  to a separate component called Table

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
   -- creating table component :
<img width="540" alt="Screen Shot 2023-04-12 at 12 28 25" src="https://user-images.githubusercontent.com/57604163/231464499-a24f9e7a-a71f-4d89-bcf5-a841afa0aa7e.png">
 -- exporting  table component into ComponentStyle :
<img width="577" alt="Screen Shot 2023-04-12 at 12 28 46" src="https://user-images.githubusercontent.com/57604163/231464094-42782b87-dac2-4763-809e-0f2f170127d1.png">

## Note to reviewers

2023-04-12 13:57 UTC, ChinmayMhatre requested changes

2023-04-12 15:02 UTC, ajaxbo360 commented on components/mdx/Table.js
> +import React from 'react';
thanks for reviewing my code 👩‍💻

2023-04-13 02:52 UTC, eddiejaoude commented
Please resolve conflicts

2023-04-13 13:06 UTC, eddiejaoude commented on components/mdx/Table.js
> +}
Closing blank line is recommended by GitHub

```suggestion
}

```

2023-04-13 13:22 UTC, ajaxbo360 commented on components/mdx/ComponentStyle.js
> +import Table from "./Table";
Thank you for your support

2023-04-13 13:36 UTC, eddiejaoude approved these changes
Thank you 👍

2023-04-13 13:36 UTC, merged