feature: account hint section #5669
EddieHubCommunity/LinkFree pull request #6037
Opened 2023-04-13 03:27 UTC by Landouda

## Fixes Issue

Closes #5669

## Changes proposed

Implementation of the hint section feature below the progress bar where a code snippet and a brief description is provided for all missing pofile sections.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/119908341/231640515-e67e7124-c77a-41b6-8913-7b167b3181d7.png)

## Note to reviewers

I created mdx files inside the components folder to include code snippets inside the hint component and included them in the statistics page. I have doubts about this implementation and I am open to fix it.

2023-05-04 14:43 UTC, eddiejaoude commented
Thank you for your contribution 👍 sorry for my slow reply, I am working through notifications

The way you did the `mdx` components is interesting, I am thinking of other alternatives of how to achieve this

2023-05-04 14:55 UTC, eddiejaoude commented on pages/account/statistics.js
> +  }
Please check you have VScode Prettier installed, so the formatting automatically matches the projects

2023-05-04 15:04 UTC, eddiejaoude requested changes
Great work on this Pull Request 👍 I left some inline comments

2023-05-21 10:01 UTC, ChinmayMhatre commented
Hey @Landouda, just wanted to check in about progress of the changes, do let us know if you need any help.

2023-05-28 02:57 UTC, SaraJaoude commented
@Landouda thank you for your contribution so far.  Due to lack of activity I will be closing this Pull Request and unassigning the Issue so that it does not remain blocked.

2023-05-28 02:57 UTC, closed without merging