Create 3simransharma
EddieHubCommunity/LinkFree pull request #6052
Opened 2023-04-13 17:01 UTC by 3simransharma

2023-04-13 17:09 UTC, khushalarora requested changes
Hi @3simransharma, thank you for contributing :tada: 
Please rename your file and Add **`.json`** at the end :+1: 
It will look like **`data/3simransharma.json`**

2023-04-13 17:09 UTC, khushalarora commented on data/3simransharma
> +    },
Please remove the extra **' Comma '** from this line :+1: 
```Suggestion
    }
```

2023-04-13 17:53 UTC, 3simransharma commented
> Hi @3simransharma, thank you for contributing 🎉 Please rename your file and Add **`.json`** at the end 👍 It will look like **`data/3simransharma.json`**
Thank you for the review, I have changed the things you said.

2023-04-14 03:06 UTC, SaraJaoude approved these changes
looks good

2023-04-14 03:06 UTC, merged