Create sanskar1306.json
EddieHubCommunity/LinkFree pull request #6073
Opened 2023-04-14 16:58 UTC by sanskar1306

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-14 17:54 UTC, iamthecloverly approved these changes

2023-04-14 18:54 UTC, amandamartin-dev requested changes

2023-04-14 18:54 UTC, amandamartin-dev commented on data/sanskar1306.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

2023-04-15 04:15 UTC, SaraJaoude approved these changes
looks good

2023-04-15 04:16 UTC, merged