data: Rufji
EddieHubCommunity/LinkFree pull request #6078
Opened 2023-04-14 21:12 UTC by Rufji

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-14 21:27 UTC, Panquesito7 requested changes

2023-04-14 21:27 UTC, Panquesito7 commented on data/Rufji.json
> +      "url": "https://inkedin.com/in/rufaimahmud",
Small typo.
```suggestion
      "url": "https://linkedin.com/in/rufaimahmud",
```

2023-04-14 21:36 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-04-15 01:24 UTC, SandeepKrSuman approved these changes

2023-04-15 03:15 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for your Contribution! 🎉 

<p align="center"><a href="https://linkfree.eddiehub.io/docs/how-to-guides/editing"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></a></p>

2023-04-15 03:15 UTC, merged