data:nayanprasad
EddieHubCommunity/LinkFree pull request #6079
Opened 2023-04-14 23:18 UTC by nayanprasad

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-14 23:54 UTC, Panquesito7 requested changes
Please revert the changes in the `package-lock.json` file.
Let us know if you need any help with this. 🙂

2023-04-19 11:24 UTC, harshsingh32 approved these changes

2023-04-26 17:42 UTC, Panquesito7 requested changes

2023-04-26 17:42 UTC, Panquesito7 commented on package-lock.json
> +}
Looks like there's still a modification.
Please remove the endline.

2023-04-29 14:38 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

2023-04-29 14:38 UTC, closed without merging