data:GarimaSaroj
EddieHubCommunity/LinkFree pull request #6091
Opened 2023-04-15 07:50 UTC by AndroGari

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-15 18:45 UTC, shyamtawli requested changes
filename should be your github username like `AndroGari.json`

2023-04-15 18:49 UTC, shyamtawli commented on GarimaSaroj.json
> +    }
```suggestion
    },
```

2023-04-15 18:50 UTC, shyamtawli commented on GarimaSaroj.json
> +    }
```suggestion
    },
```

2023-04-15 18:50 UTC, shyamtawli commented on GarimaSaroj.json
> +    }
```suggestion
    },
```

2023-04-15 18:51 UTC, shyamtawli requested changes
add `,` after every completed object

2023-04-15 18:52 UTC, imbeshat requested changes
Also, move your file to ```data``` folder.

2023-04-15 18:52 UTC, imbeshat commented on GarimaSaroj.json
> +    }
```suggestion
    },
```

2023-04-15 18:52 UTC, imbeshat commented on GarimaSaroj.json
> +    }
```suggestion
    },
```

2023-04-15 18:52 UTC, imbeshat commented on GarimaSaroj.json
> +    }
```suggestion
    },
```

2023-04-16 03:23 UTC, iamravi1 requested changes
JSON file name should be your username and remaining looks good

2023-04-16 04:28 UTC, SaraJaoude commented
> JSON file name should be your username and remaining looks good

@iamravi1  when reviewing, please look at the conversation above before making a comment. This has already been mentioned and adding the same comment again can create confusion for the author.

2023-04-16 05:00 UTC, iamravi1 commented
Ok sure

2023-04-16 14:41 UTC, md-abid-hussain approved these changes
LGTM

2023-04-17 04:47 UTC, iamravi1 approved these changes
LGTM 🎉

2023-04-18 03:45 UTC, SaraJaoude commented
@iamravi1 and @md-abid-hussain 

your comments of LGTM cause confusion to the author and also maintainers because this profile is not ready to be merged - given than the JSON file is not in the correct directory and the file name needs to match the username. Before adding LGTM on a Pull Request, please double check this as much as possible. 


@AndroGari please let us know if you need help with the changes.

2023-04-26 18:35 UTC, amandamartin-dev commented
Hello @AndroGari it has been a few weeks please let us know if you are able to address the changes or if you are having any trouble understanding what is needed to get your profile merged! We are happy to help.  If we do not hear a response, we will close this PR for now but you are welcome to resubmit at any time.

2023-04-29 14:39 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

2023-04-29 14:39 UTC, closed without merging