fix: fade deleted links #5202
EddieHubCommunity/LinkFree pull request #6095
Opened 2023-04-15 09:18 UTC by AJcodes42

## Fixes Issue

Closes #5202 

## Changes proposed

Faded deleted links in statistics page 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

**Before Changes**
Dark mode
<img width="1063" alt="Screenshot 2023-04-15 at 2 43 52 PM" src="https://user-images.githubusercontent.com/29297057/232203612-c5454863-91fd-4faa-b253-ef416331e800.png">

Light mode
<img width="970" alt="Screenshot 2023-04-15 at 2 43 31 PM" src="https://user-images.githubusercontent.com/29297057/232203511-a4aa4e37-152a-49c8-8bca-408213987d53.png">

**After Changes**
Dark mode
<img width="1098" alt="Screenshot 2023-04-15 at 1 21 19 PM" src="https://user-images.githubusercontent.com/29297057/232203156-8545d5fe-d1e7-4c37-b208-6f1dd8bc3768.png">

Light mode
<img width="1098" alt="Screenshot 2023-04-15 at 1 21 19 PM" src="https://user-images.githubusercontent.com/29297057/232203189-2b912aaa-fa90-4974-b644-52c4a2015269.png">
## Note to reviewers

2023-04-15 16:15 UTC, jtejederabit commented on pages/account/statistics.js
> +  data.links.individual.forEach(link => {
Hi, one suggestion, you will save a few lines of code :

```
data.links.individual.forEach(link => {
  link.deleted = !profile.links.some(pLink => pLink.url === link.url);
});

data.links.individual.sort((a, b) => (a.deleted && !b.deleted) ? 1 : ((!a.deleted && b.deleted) ? -1 : 0));
```

2023-04-16 05:08 UTC, eddiejaoude requested changes
I think a filter might be the cleanest way, then you end up with 2 arrays

2023-04-16 07:01 UTC, jonathantejedera commented
> I think a filter might be the cleanest way, then you end up with 2 arrays

Is the goal to show deleted items?

2023-04-16 07:04 UTC, eddiejaoude commented
> > I think a filter might be the cleanest way, then you end up with 2 arrays
> 
> Is the goal to show deleted items?

Yes items that have stats but not in the user's list https://github.com/EddieHubCommunity/LinkFree/issues/5202

But now thinking about it, maybe it is not really needed 🤔 

@AJcodes42 sorry to change my mind, but I still think you should use a filter, but only for the items we want to display and discard the other items

2023-04-16 07:11 UTC, jtejederabit commented
Something like this:

`data.links.individual = data.links.individual.filter(link => {
  return profile.links.some(pLink => pLink.url === link.url);
});
`

2023-04-17 12:37 UTC, AJcodes42 commented
Sure, Will update the code accordingly. Thanks @jtejederabit for your suggestion. It helps.

2023-04-19 05:22 UTC, eddiejaoude approved these changes
Thank you 👍

2023-04-19 05:22 UTC, merged