index imports for models (#5654)
EddieHubCommunity/LinkFree pull request #6147
Opened 2023-04-17 08:25 UTC by Shaikh-Danish

Closes #5654

2023-04-26 19:01 UTC, amandamartin-dev commented
Hello @Shaikh-Danish there are some conflicts to resolve in one file.  Please take a look and let us know if you need any help prior to review

2023-05-02 03:57 UTC, eddiejaoude requested changes
Thank you for your contribution.

There are failing tests. Also when I try to run the code, I get a lot of errors that the models are not working now.

2023-05-02 03:58 UTC, eddiejaoude commented on models/index.js
> +export default {
This should not be `default`, this is what is causing the app to no longer work

2023-05-02 04:06 UTC, eddiejaoude commented
I will fix via a temporary branch

2023-05-02 04:06 UTC, merged

2023-05-02 04:23 UTC, eddiejaoude commented on pages/api/discover/random.js
> +import loadProfiles from "@services/profiles/loadProfiles";
Not sure why this import was added? It is not used in the file, maybe from a bad merge (or git conflict)