Samil web patch 1
EddieHubCommunity/LinkFree pull request #6203
Opened 2023-04-19 02:30 UTC by samil-web

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-19 05:42 UTC, kumarsonsoff3 requested changes

2023-04-19 05:42 UTC, kumarsonsoff3 commented on samil-web.json
This file seems to be a duplicate. Please remove the [file `samil-web.json`](https://github.com/samil-web/LinkFree/delete/samil-web-patch-1/samil-web.json) which is in the root directory.

2023-04-19 05:43 UTC, kumarsonsoff3 requested changes

2023-04-19 05:43 UTC, kumarsonsoff3 commented on data/samil-web.json
> +  "bio": "Engineer turned into Programmer. In a journey to make remarkable things"
Also, add a missing comma `,` here. 

```suggestion
  "bio": "Engineer turned into Programmer. In a journey to make remarkable things",
```

2023-05-03 03:38 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

2023-05-03 03:38 UTC, closed without merging