Create Adityakrpand.json
EddieHubCommunity/LinkFree pull request #6211
Opened 2023-04-19 06:39 UTC by Adityakrpand

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-19 07:15 UTC, ChinmayMhatre requested changes
Looks good, mentioned a few changes.

2023-04-19 07:15 UTC, ChinmayMhatre commented on data/Adityakrpand.json
> +      "url": "https://www.instagram.com/adityakrpandey7777/?igshid=MDM4ZDc5MmU%3D,
```suggestion
      "url": "https://www.instagram.com/adityakrpandey7777",
```
Missing semi colon and refactored url

2023-04-19 07:15 UTC, ChinmayMhatre commented on data/Adityakrpand.json
> +      "url": "https://twitter.com/AimlAditya?t=KgtiJz4Wkm9tcB7i3bitrA&s=09",
```suggestion
      "url": "https://twitter.com/AimlAditya",
```

2023-04-19 17:46 UTC, imbeshat requested changes

2023-04-20 05:10 UTC, Adityakrpand commented
amazing experience

2023-04-20 08:37 UTC, iamravi1 approved these changes
Looks good

2023-04-20 17:31 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-04-20 17:32 UTC, merged