data: Gauthamprasath
EddieHubCommunity/LinkFree pull request #6212
Opened 2023-04-19 06:56 UTC by Gauthamprasath

Profile update

2023-04-19 07:15 UTC, ChinmayMhatre requested changes

2023-04-19 07:15 UTC, ChinmayMhatre commented on data/Gauthamprasath.json
> +            "icon": "FaLinkedinIn"
```suggestion
            "icon": "FaLinkedin"
```

2023-04-19 10:52 UTC, khushalarora approved these changes
Thank you for contributing :tada:

2023-04-19 13:04 UTC, harshsingh32 reviewed
changes reviewd

2023-04-19 14:46 UTC, ChinmayMhatre commented on data/Gauthamprasath.json
> +            "icon": "FaLinkedinIn"
Oh right! My bad👍🏻

2023-04-19 15:43 UTC, sidharthviz approved these changes

2023-04-20 02:11 UTC, SaraJaoude commented
You have conflicts in your file, please resolve. This is usually because your fork is not up to date.  

You may wish to have a look at the following Docs and video: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-04-20 08:35 UTC, iamravi1 approved these changes
Looks quite good

2023-04-20 14:52 UTC, closed without merging