data: Sheriff-Oladimeji
EddieHubCommunity/LinkFree pull request #6219
Opened 2023-04-19 14:55 UTC by Sheriff-Oladimeji

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6219"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-04-19 16:40 UTC, accodes21 submitted a review, later dismissed

2023-04-19 17:37 UTC, imbeshat requested changes

2023-04-19 17:37 UTC, imbeshat commented on data/Sheriff-Oladimeji.json
> +    "Tailwind",
```suggestion
    "Tailwind"
```

2023-04-19 17:37 UTC, imbeshat commented on data/Sheriff-Oladimeji.json
> +    { "icon": "FaGithub", "url": "https://github.com/Sheriff-Oladimeji" },
```suggestion
    { "icon": "FaGithub", "url": "https://github.com/Sheriff-Oladimeji" }
```

2023-04-20 02:22 UTC, SaraJaoude approved these changes
looks like the GitHub username has been renamed, old user no longer exists and twitter remains the same

2023-04-20 02:22 UTC, merged