Add FidalMathew.json
EddieHubCommunity/LinkFree pull request #622
Opened 2021-10-31 05:44 UTC by FidalMathew

2021-10-31 11:26 UTC, Pradumnasaraf commented on public/data/FidalMathew.json
> +  }
```suggestion
    ]  
  }
```
Please Remove that extra line

2021-10-31 11:26 UTC, Pradumnasaraf commented on public/data/FidalMathew.json
> +    "bio": "Frontend Developer | I love exploring and learning new technologies. ",
```suggestion
    "bio": "Frontend Developer | I love exploring and learning new technologies.",
```

2021-10-31 11:29 UTC, Pradumnasaraf commented on public/data/FidalMathew.json
> +    "bio": "Frontend Developer | I love exploring and learning new technologies. ",
**Please remove that extra space, otherwise LGTM.**

Thanks for the contribution :)
Happy Halloween🎃

2021-10-31 13:41 UTC, krishguptadev requested changes

2021-10-31 13:41 UTC, krishguptadev commented on public/data/FidalMathew.json
> +
```suggestion
```

2021-10-31 13:41 UTC, krishguptadev commented on public/data/FidalMathew.json
> +  }
```suggestion
 }
 
```

2021-10-31 13:41 UTC, krishguptadev commented on public/data/FidalMathew.json
> +    "bio": "Frontend Developer | I love exploring and learning new technologies. ",
```suggestion
    "bio": "Frontend Developer | I love exploring and learning new technologies.",
```

2021-10-31 14:36 UTC, Panquesito7 requested changes
Please see the comments above.

2021-10-31 16:22 UTC, FidalMathew commented
Thank you @krishguptadev @Pradumnasaraf @Panquesito7 for the assist :)

2021-10-31 16:39 UTC, Panquesito7 requested changes

2021-10-31 16:39 UTC, Panquesito7 commented on public/data/FidalMathew.json
> +  }
```suggestion
}

```

2021-10-31 16:42 UTC, Panquesito7 commented on public/data/FidalMathew.json
> +    "bio": "Frontend Developer | I love exploring and learning new technologies.",
```suggestion
    "bio": "Front-end Developer | I love exploring and learning new technologies.",
```

2021-10-31 16:43 UTC, Panquesito7 approved these changes

2021-10-31 16:44 UTC, Pradumnasaraf approved these changes
![lgtm_thumb](https://user-images.githubusercontent.com/51878265/139593731-1b866f71-3bf9-4128-be7f-2f0428afaf69.png)

2021-11-01 02:26 UTC, krishguptadev approved these changes
LGTM!

2021-11-01 07:14 UTC, schmelto approved these changes

2021-11-01 13:54 UTC, Panquesito7 approved these changes

2021-11-01 15:27 UTC, shreyaansjain06 approved these changes
LGTM

2021-11-02 00:50 UTC, merged