data: vaibhav-xt
EddieHubCommunity/LinkFree pull request #6264
Opened 2023-04-22 05:43 UTC by vaibhav-xt

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-22 06:37 UTC, shyamtawli commented on data/vaibhav-xt.json
> +  "avatar": "https://github.com/vaibhav-xt.png"
```suggestion
  "avatar": "https://github.com/vaibhav-xt.png",
```

2023-04-22 06:37 UTC, shyamtawli commented on data/vaibhav-xt.json
> +    },
```suggestion
    }
```

2023-04-22 06:39 UTC, shyamtawli requested changes
Welcome to EddieHub @vaibhav-xt, Please make changes as mentioned above.

2023-04-22 06:41 UTC, shyamtawli commented on data/vaibhav-xt.json
> +  ],
```suggestion
  ]
```
remove this also

2023-04-22 06:41 UTC, shyamtawli requested changes
remove this `,` also

2023-04-23 02:37 UTC, SaraJaoude commented on data/vaibhav-xt.json
> +  "displayStatsPublic": true,
this is no longer needed:
```suggestion
```

2023-04-23 02:38 UTC, SaraJaoude approved these changes
look good

2023-04-23 02:39 UTC, merged