Created my JSON
EddieHubCommunity/LinkFree pull request #627
Opened 2021-11-01 12:31 UTC by abhishekY2401

2021-11-01 13:54 UTC, Panquesito7 requested changes

2021-11-01 13:54 UTC, Panquesito7 commented on public/data/abhishekY2401.json
> +}
```suggestion
}

```

2021-11-01 15:26 UTC, shreyaansjain06 requested changes

2021-11-01 15:26 UTC, shreyaansjain06 commented on public/data/abhishekY2401.json
> +            "name": "Follow me on Linkedin",
```suggestion
            "name": "Connect with me on LinkedIn",
```

2021-11-01 16:31 UTC, Panquesito7 approved these changes

2021-11-02 00:51 UTC, merged

2021-11-02 00:52 UTC, schmelto approved these changes