data: omlondhe
EddieHubCommunity/LinkFree pull request #6283
Opened 2023-04-22 09:27 UTC by omlondhe

Added my profile

2023-04-22 10:45 UTC, khushalarora requested changes
Hi @omlondhe, thank you for contributing :tada:

2023-04-22 10:45 UTC, khushalarora commented on data/omlondhe.json
> +    "displayStatsPublic": true,
You can remove this line, it is not required anymore :+1: 
```Suggestion
```

2023-04-22 10:45 UTC, khushalarora commented on data/omlondhe.json
> +    "avatar": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUWFRgWFhYYGBgaHR4cGRwcHRwaHRwcHBoaHB8cHBoeIS4lHB4rIRocJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHxISHz0rJSw0MTQ0NDQ2NDQ0NDE0NDQ0N
You can remove this avatar line, it is not required anymore :+1: 
```Suggestion
```

2023-04-22 10:47 UTC, omlondhe commented
Hey, @khushalarora Thank you for replying, changes are done.

2023-04-22 10:48 UTC, omlondhe commented
By the way, I'm adding a feature to the project. You will receive a pull request in the next 5 minutes, kindly review it.

2023-04-22 11:09 UTC, omlondhe commented
Hey @khushalarora , done with changes for this page.

The feature that I was talking about is also added in PR, take a look.
Along with that, I have also raised an issue in the production code that I have solved locally, will send you a PR once you merge both of these PRs so the issue will be merged separately.

Thank you!

2023-04-23 02:50 UTC, SaraJaoude approved these changes
looks good

2023-04-23 02:50 UTC, merged