data: sabrinalzbh
EddieHubCommunity/LinkFree pull request #6308
Opened 2023-04-23 13:05 UTC by sabrinalzbh

~ Socials Update ( provided Github account twice. Added LinkedIn URL).

2023-04-23 14:40 UTC, Sindhuinti requested changes

2023-04-23 14:40 UTC, Sindhuinti commented on data/sabrinalzbh.json
> +      "icon": "FaLinkedIn"
Please change icon name to `FaLinkedin`

2023-04-23 15:22 UTC, sabrinalzbh commented on data/sabrinalzbh.json
> +      "icon": "FaLinkedIn"
Will do. Thank you. 😌

2023-04-23 15:25 UTC, Sindhuinti approved these changes
Looks good now 🎉

2023-04-23 15:27 UTC, sabrinalzbh commented
> Looks good now 🎉 

~ Yaay!! Thank you!

2023-04-24 07:29 UTC, SaraJaoude commented
Hi @sabrinalzbh! You have conflicts in your file - this is usually because your fork is not up to date.  

Hopefully the following Docs and video help: https://linkfree.eddiehub.io/docs/how-to-guides/editing

2023-04-24 11:54 UTC, sabrinalzbh commented
> Hi @sabrinalzbh! You have conflicts in your file - this is usually because your fork is not up to date.  
> 
> 
> 
> Hopefully the following Docs and video help: https://linkfree.eddiehub.io/docs/how-to-guides/editing

~ Hola @SaraJaoude 😊 I'll give that another shot. Thank you!

2023-04-25 14:59 UTC, closed without merging