data: sejosephmartin
EddieHubCommunity/LinkFree pull request #6351
Opened 2023-04-25 13:50 UTC by sejosephmartin

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6351"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-04-25 15:24 UTC, imbeshat requested changes
Also, move your file to ```data``` folder.

2023-04-25 15:24 UTC, imbeshat commented on sejosephmartin.json
> +  "displayStatsPublic": true,
not required

2023-04-25 15:24 UTC, imbeshat commented on sejosephmartin.json
> +  "avatar": "https://github.com/sejosephmartin.png"
```suggestion
```

2023-04-25 15:24 UTC, imbeshat commented on sejosephmartin.json
> +  "avatar": "https://github.com/sejosephmartin.png"
not required

2023-04-25 15:24 UTC, imbeshat commented on sejosephmartin.json
> +  "bio": "Aspiring Front end developer 🚀 | Self-Taught Developer ✨ | Undergraduate"
```suggestion
  "bio": "Aspiring Front end developer 🚀 | Self-Taught Developer ✨ | Undergraduate",
```

2023-04-26 01:45 UTC, sejosephmartin commented
> Also, move your file to `data` folder

can I move the file like this  **data/sejosephmartin.json.**. I change already some of the unnecessary script. should i create another branch when i commit this?

2023-04-26 09:40 UTC, khushalarora approved these changes
Looks good, thanks :tada:

2023-04-26 10:55 UTC, harshsingh32 reviewed
lgtm

2023-04-26 16:01 UTC, kumarsonsoff3 approved these changes
Looks awesome. Great collaboration everyone. 👍

2023-04-26 16:01 UTC, merged