data: chirag4242
EddieHubCommunity/LinkFree pull request #6417
Opened 2023-04-28 05:30 UTC by chirag4242

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-28 07:24 UTC, Arindam200 submitted a review, later dismissed

2023-04-28 09:39 UTC, imbeshat requested changes

2023-04-28 09:39 UTC, imbeshat commented on data/chirag4242.json
> +  "avatar": "https://github.com/chirag4242.png",
```suggestion
```

2023-04-28 09:39 UTC, imbeshat commented on data/chirag4242.json
> +  "avatar": "https://github.com/chirag4242.png",
not required

2023-04-28 09:39 UTC, imbeshat commented on data/chirag4242.json
> +    "Python"
```suggestion
    "Python",
```

2023-04-28 17:47 UTC, chirag4242 commented on data/chirag4242.json
> +  "avatar": "https://github.com/chirag4242.png",
Just an avatar right? fixed that

2023-04-28 17:48 UTC, chirag4242 commented on data/chirag4242.json
> +    "Python"
fixed that also 👍

2023-04-29 02:17 UTC, SaraJaoude approved these changes
looks good

2023-04-29 02:18 UTC, merged