Create shubhamds24.json
EddieHubCommunity/LinkFree pull request #6445
Opened 2023-04-29 06:39 UTC by shubhamds24

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-29 07:53 UTC, jaydeepkhatri requested changes
Hi @shubhamds24,
Thank you for contributing to Linkfree.

I have found few changes for your PR.
Please update the file name to `data/shubhamds24.json` 

Thanks :)

2023-04-29 07:53 UTC, jaydeepkhatri commented on data/shubhamds24
> +  "boi": "Travelling is good for health"
The please check the spelling for "bio".
Also the JSON is invalid for the same line. It should have a trailing comma.

Here is how it should be 👇
```json
"bio": "Travelling is good for health",
```

2023-04-29 07:53 UTC, jaydeepkhatri commented on data/shubhamds24
> +      "icon": "Fainstagram"
The Correct instagram icon name is "FaInstagram". It is case-sensitive.

2023-04-29 07:53 UTC, jaydeepkhatri commented on data/shubhamds24
> +      "icon": "FaGitHub"
The correct github icon name is "FaGithub". It is case-sensitive.

2023-05-10 07:01 UTC, SaraJaoude commented
Given the length of time this PR has been open I will fix via a temporary branch and merge into main

2023-05-10 07:02 UTC, merged