Create navneet17360.json
EddieHubCommunity/LinkFree pull request #6446
Opened 2023-04-29 06:39 UTC by navneet17360

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-29 08:00 UTC, jaydeepkhatri requested changes
Hi @navneet17360 
Thank you for creating a PR at Linkfree.

I found that the JSON is invalid.
Use this tool to verify the Code.
-> https://linkfree.io/playground

Thanks :)

2023-04-29 08:00 UTC, jaydeepkhatri commented on data/navneet17360.json
> +			"icon:"FaGithub"
The JSON is not properly formatted, 
You missed to close the quotation for "icon".

```json
"icon": "FaGithb"
```

2023-05-10 05:48 UTC, SaraJaoude commented on data/navneet17360.json
> +			"icon:"FaGithub"
needs the following corrections:
```suggestion
			"icon": "FaGithub",
```

2023-05-10 05:51 UTC, SaraJaoude commented on data/navneet17360.json
> +			"icon": "FaGithub",
```suggestion
			"icon": "FaGithub"
```

2023-05-10 05:57 UTC, SaraJaoude approved these changes
looks good

2023-05-10 05:58 UTC, merged