Create vinita.json
EddieHubCommunity/LinkFree pull request #6491
Opened 2023-04-29 06:46 UTC by VinitaMenaria

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-29 08:16 UTC, SaraJaoude commented on vinita.json
> + ]
```suggestion
 "url": "https://instagram.com/vinita_menaria_?igshid=ZDdkNTZiNTM=",
 		"icon": "FaInstagram"
 	}]
 }
```

2023-04-29 08:18 UTC, SaraJaoude requested changes
Please move your file to the `data` folder and make sure that your file name matches your GitHub username exactly. Instead of `vinita.json` it should be `data/VinitaMenaria.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-04-29 11:45 UTC, harshit-paneri commented
> ## Fixes Issue
> ## Changes proposed
> ## Check List (Check all the applicable boxes)
> * [x]  My code follows the code style of this project.
> * [x]  My change requires changes to the documentation.
> * [x]  I have updated the documentation accordingly.
> * [x]  All new and existing tests passed.
> * [x]  This PR does not contain plagiarized content.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ## Screenshots
> ## Note to reviewers
> [![](https://camo.githubusercontent.com/76e60919474807718793857d8eb615e7a50b18b04050577e5a35c19421f260a3/68747470733a2f2f676974706f642e696f2f627574746f6e2f6f70656e2d696e2d676974706f642e737667)](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6491)

Hey @VinitaMenaria , your vinita.json file is not in the data folder, move this file to data folder otherise PR will not accept.

2023-04-29 11:46 UTC, harshit-paneri commented
> > ## Fixes Issue
> > ## Changes proposed
> > ## Check List (Check all the applicable boxes)
> > 
> > * [x]   My code follows the code style of this project.
> > * [ ]  My change requires changes to the documentation.
> > * [ ]  I have updated the documentation accordingly.
> > * [x]   All new and existing tests passed.
> > * [x]   This PR does not contain plagiarized content.
> > * [x]   The title of my pull request is a short description of the requested changes.
> > 
> > ## Screenshots
> > ## Note to reviewers
> > [![](https://camo.githubusercontent.com/76e60919474807718793857d8eb615e7a50b18b04050577e5a35c19421f260a3/68747470733a2f2f676974706f642e696f2f627574746f6e2f6f70656e2d696e2d676974706f642e737667)](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6491)
> 
> Hey @VinitaMenaria , your vinita.json file is not in the data folder, move this file to data folder otherwise PR will not accept.

2023-04-29 14:32 UTC, SaraJaoude commented
> Hey @VinitaMenaria , your vinita.json file is not in the data folder, move this file to data folder otherwise PR will not accept.

@harshit-paneri as mentioned to you previously, please check the history of the PR and avoid duplicating suggestions already made.

2023-05-10 06:44 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

2023-05-10 06:44 UTC, closed without merging