Bhavya Mehta
EddieHubCommunity/LinkFree pull request #6492
Opened 2023-04-29 06:46 UTC by bhavyamehta4439

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-29 08:13 UTC, SaraJaoude submitted a review, later dismissed
Please move your file to the `data` folder. 

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-05-05 21:11 UTC, HassanTanveer requested changes
Please rename PR to:

`data: bhavyamehta4439`

2023-05-05 21:11 UTC, HassanTanveer commented on bhavyamehta4439.json{   "name": "Sara Jaoude",   "type": "personal",   "bio": "Lawyer turned **Digital Nomad**. Travel enthusiast Yoga & Peloton aficionado" }
This file is not necessary.

2023-05-05 21:11 UTC, HassanTanveer commented on bhavyamehta4439.json
Please move this file the the **data** folder.

The [Quick Start](https://linkfree.io/docs/quickstart) guides you exactly how to do that

2023-05-07 05:49 UTC, SaraJaoude commented on bhavyamehta4439.json
Thank you for reviewing @HassanTanveer, but the duplicate feedback is not required and can cause confusion to the author - so I shall mark this comment as `resolved`

2023-05-10 07:20 UTC, SaraJaoude commented on bhavyamehta4439.json
> +    {
corrections are needed for the json to pass:
```suggestion
  "bio": "Pursuing Btech in CSE I am creative and cultural with multiple talents",
	"links": [{
			"name": "Follow me on Linekdin",
			"url": "https://www.linkedin.com/in/bhavya-mehta-b6a824226",
			"icon": "FaLinkedin"
		},
		{
```

2023-05-10 07:23 UTC, merged