createkritipatwa.json
EddieHubCommunity/LinkFree pull request #6494
Opened 2023-04-29 06:48 UTC by Kritipatwa16

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-04-29 08:06 UTC, SaraJaoude requested changes
Your file name must match your GitHub username.  

So instead of data/kritipatwa.json it should be data/Kritipatwa16.json

I would suggest you look at our QuickStart Guide in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request so that we can get it merged.

Your JSON is also failing, check this on: https://jsonlint.com so that you can see how to correct it.

2023-05-03 10:43 UTC, Sindhuinti requested changes

2023-05-03 10:43 UTC, Sindhuinti commented on data/kritipatwa.json
> +  "links": [kriti15038
remove this `kriti15038`

2023-05-04 01:46 UTC, SaraJaoude submitted a review, later dismissed
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/kritipatwa.json`   it should be `data/Kritipatwa16.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-05-10 06:13 UTC, SaraJaoude commented on data/kritipatwa.json
> +  "links": [kriti15038
```suggestion
  "links": [
```

2023-05-10 06:35 UTC, merged