updated profile
EddieHubCommunity/LinkFree pull request #6518
Opened 2023-04-29 22:55 UTC by Shalini469717

added socials, updated bio, added blog link

2023-04-30 01:51 UTC, GauravKanwat requested changes
You can check the code you typed on "jsonlint.com" for any errors. :+1:

2023-04-30 01:51 UTC, GauravKanwat commented on data/Shalini469717.json
>        "name": "Twitter",
Please add a link for twitter and close with proper format.

2023-04-30 02:28 UTC, SaraJaoude requested changes
The package lock file should only be committed if the package.json file has changes. There could be two reasons why the lock file has been updated for you:

1. You used `npm install` instead of `npm ci` or
2. You have GitHub Actions running on your fork. This should be disabled by default, please do not enable.

Please undo any changes to the package lock file. 

Here is a video that will show you how to do it: https://youtu.be/jHkIXYVpMTo

2023-04-30 08:53 UTC, Shalini469717 commented
Thanks for the review, I was using Linkfree cli and used `npm install`.
Hey, maybe we add `npm ci` to Linkfree cli, since I found it confusing what to use while installing dependencies.

2023-05-01 13:23 UTC, eddiejaoude commented
> Thanks for the review, I was using Linkfree cli and used `npm install`.
> Hey, maybe we add `npm ci` to Linkfree cli, since I found it confusing what to use while installing dependencies.

Sorry @Shalini469717 for the confusion, we have [docs](https://linkfree.io/docs/environments/linkfree-cli) on using the CLI but I think we are missing the `npm ci` step and most people do `npm install` which causes this problem. I will add these steps to our docs now

Was the video clear on how to remove the changes to the package lock file? Any questions let us know

2023-05-01 17:41 UTC, Shalini469717 commented
Yeah the video was clear, but the issue I faced was after committing, the package-lock.json file had changed in my local repo's main branch as well. So, it took a bit of time to figure out how to fetch from remote repo and merging it with local repo. 
`$ git checkout EddieLinkFree/main -- package-lock.json`
After that I did everything according to the video and it worked.

2023-05-01 17:59 UTC, Shalini469717 commented
Yeah will start using branches from now on! Learnt new things again. Thanks for the help!

2023-05-01 18:00 UTC, eddiejaoude commented
> Yeah will start using branches from now on! Learnt new things again. Thanks for the help!

we are all always learning, part of the fun of being in tech 🤓

2023-05-02 01:59 UTC, SaraJaoude approved these changes

2023-05-02 01:59 UTC, SaraJaoude commented
looks good

2023-05-02 02:00 UTC, merged