Fixed the double borders on inputs; issue #6310
EddieHubCommunity/LinkFree pull request #6524
Opened 2023-04-30 09:08 UTC by Vee339

**Close #6310** 

## Fixes Issue

The issue was that inputs and textarea were showing double borders when they were focused. 

## Changes proposed

The first issue was that tailwind classes were added both in the components and pages where these components were called. Therefore, I commented the classes in individual pages and they have remained now only in components that are reusable.

Secondly, there were default rings added due to tailwind CSS which I removed now.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-01 00:58 UTC, eddiejaoude commented on pages/search.js
> +            // className="border-2 hover:border-tertiary-medium transition-all dark:bg-primary-high duration-250 ease-linear rounded px-6 py-2 mb-4 block w-full"
If commented out, I think it can be removed?

2023-05-01 00:58 UTC, eddiejaoude commented on pages/playground.js
> +          // className="dark:bg-primary-high dark:text-white rounded border-2 hover:border-tertiary-medium"
If commented out, I think it can be removed?

2023-05-01 08:37 UTC, Vee339 commented
I have made the commit. Please review it.

2023-05-01 17:12 UTC, eddiejaoude requested changes
It is looking better 👍 

Unfortunately for dark mode the text in the input box is not readable

**LIGHT MODE**

<img width="1662" alt="Screenshot 2023-05-02 at 00 10 53" src="https://user-images.githubusercontent.com/624760/235494597-5e171ac1-a6da-42cb-bde0-e566e4f4e6af.png">

**DARK MODE**

<img width="1662" alt="Screenshot 2023-05-02 at 00 10 58" src="https://user-images.githubusercontent.com/624760/235494627-80e4edc4-ea59-46a5-bb3f-aa3813af176c.png">

2023-05-02 02:05 UTC, eddiejaoude approved these changes
Looks great 👍

2023-05-02 02:05 UTC, merged