data NickAzureDevops
EddieHubCommunity/LinkFree pull request #6544
Opened 2023-05-01 16:48 UTC by NickAzureDevops

2023-05-01 20:49 UTC, imbeshat requested changes

2023-05-01 20:49 UTC, imbeshat commented on data/NickAzureDevops.json
> +    "Github",
```suggestion
    "Github"
```

2023-05-01 20:49 UTC, imbeshat commented on data/NickAzureDevops.json
> +    },
```suggestion
    }
```

2023-05-01 20:58 UTC, NickAzureDevops commented
Updated changes @imbeshat

2023-05-02 02:10 UTC, SaraJaoude approved these changes
looks good

2023-05-02 02:10 UTC, merged