data: Eric-Obeng
EddieHubCommunity/LinkFree pull request #6566
Opened 2023-05-02 13:00 UTC by Eric-Obeng

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6566"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-05-02 13:01 UTC, Eric-Obeng commented
My linkfree profile has been edited successfully

2023-05-02 13:09 UTC, Sindhuinti requested changes

2023-05-02 13:09 UTC, Sindhuinti commented on data/Eric-Obeng.json
> +  "avatar": "https://github.com/Eric-Obeng.png",
Hey!! No need to add avatar here. It will be auto imported from your github profile.

2023-05-02 13:13 UTC, Eric-Obeng commented
Okay Thank you.

2023-05-02 13:19 UTC, Eric-Obeng reviewed
Avatar removed

2023-05-02 13:30 UTC, Sindhuinti requested changes

2023-05-02 13:38 UTC, Eric-Obeng commented on data/Eric-Obeng.json
> +  "displayStatsPublic": true,
displayStatusPublic removed

2023-05-02 16:28 UTC, kumarsonsoff3 commented
Duplicate of #6567

2023-05-02 16:30 UTC, kumarsonsoff3 commented
I'll be closing this PR since it seems to be a duplicate of PR #6567. The one with the latest and updated changes has already been merged!!

2023-05-02 16:30 UTC, closed without merging

2023-05-03 01:28 UTC, Eric-Obeng commented
Okay Sir
Thank you