Technicave patch 1
EddieHubCommunity/LinkFree pull request #6571
Opened 2023-05-02 18:10 UTC by technicave

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6571"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-05-02 18:54 UTC, khushalarora requested changes
Hey @technicave, thank you for contributing :tada:

2023-05-02 18:54 UTC, khushalarora commented on data/technicave.json
> +  "avatar": "https://github.com/technicave.png",
You can remove this line, it is not required anymore :+1: 
```suggestion
```

2023-05-02 18:54 UTC, khushalarora commented on data/technicave.json
> +    },
Please remove the extra **' Comma '** from this line :+1: 
```suggestion
    }
```

2023-05-03 03:35 UTC, SaraJaoude approved these changes
looks good

2023-05-03 03:35 UTC, merged