data: Webdevava
EddieHubCommunity/LinkFree pull request #6615
Opened 2023-05-04 18:49 UTC by Webdevava

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-04 20:13 UTC, khushalarora requested changes
Hey @Webdevava, thank you for contributing :tada:

2023-05-04 20:13 UTC, khushalarora commented on data/Webdevava.json
> +  "displayStatsPublic": true,
You can remove this line, it is not required anymore :+1: 
```Suggestion
```

2023-05-04 20:13 UTC, khushalarora commented on data/Webdevava.json
> +  "avatar": "https://github.com/Webdevava.png",
You can remove this line, it is not required anymore.
Thankyou :+1: 
```Suggestion
```

2023-05-05 02:15 UTC, SaraJaoude approved these changes
looks good

2023-05-05 02:17 UTC, merged