ci: update workflow to work with protected branches
EddieHubCommunity/LinkFree pull request #662
Opened 2021-11-13 13:09 UTC by Sfitzg

Update the `releases.yml` workflow to work with protected branches by means of a environment variable being set with a personal access token containing admin rights.

closes #659

2021-11-14 02:02 UTC, Panquesito7 reviewed
Is this a work in progress or done already? 🤔

2021-11-15 07:53 UTC, Sfitzg commented
@Panquesito7 it is complete but as I never received any confirmation on the issue  I just supplied a draft pull request so anyone could look at the changes.

2021-11-15 17:22 UTC, Panquesito7 reviewed
How can we ensure this was tested properly? Was this ran in your fork?

2021-11-16 03:33 UTC, krishguptadev requested changes
Check the latest comment on the issue.

2021-11-16 07:36 UTC, Sfitzg commented
I'm rather going to close this pull request as I don't think this is needed at this time.
The only real difference is that is disables the include admins checkbox and then re enables it after changelog is committed.

2021-11-16 07:36 UTC, closed without merging