data: OmkarBorhade98 LinkFree Profile
EddieHubCommunity/LinkFree pull request #6641
Opened 2023-05-06 08:58 UTC by OmkarBorhade98

## Check List

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers
Added my LinkFree profile

2023-05-06 09:33 UTC, khushalarora requested changes
Hey @OmkarBorhade98, thank you for contributing :tada:

2023-05-06 09:33 UTC, khushalarora commented on data/OmkarBorhade98.json
> +  "bio": "Mechanical Engineer turned into Software Devolaper. Avid Reader"
Please add a **'Comma'** at the end of this line :+1: 
```Suggestion
  "bio": "Mechanical Engineer turned into Software Devolaper. Avid Reader",
```

2023-05-06 09:33 UTC, khushalarora commented on data/OmkarBorhade98.json
> +    }
Please add a **'Comma'** here also :+1: 
```Suggestion
    },
```

2023-05-06 09:33 UTC, khushalarora commented on data/OmkarBorhade98.json
> +    }
Please add a **'Comma'** here also :+1: 
```Suggestion
    },
```

2023-05-07 05:09 UTC, OmkarBorhade98 commented
Thanks @khushalarora I've made the necessary changes

2023-05-07 05:38 UTC, SaraJaoude approved these changes
looks good

2023-05-07 05:39 UTC, merged