Dockerfile: Upgrade Node.js docker image to 20
EddieHubCommunity/LinkFree pull request #6644
Opened 2023-05-06 10:51 UTC by sarthakroy2002

* Node.js 16 (LTS) will go End-of-Life in September 2023
* Node.js 20 will enter long-term support (LTS) in October

2023-05-06 10:54 UTC, eddiejaoude commented
Please create an issue for this first, you can read more in our contributing guide

Also, everything should be kept in sync 
- Gitpod
- nvm
- Docker
... etc

2023-05-06 10:55 UTC, eddiejaoude requested changes
Node versions should be kept in sync

2023-05-06 12:06 UTC, sarthakroy2002 commented
> Please create an issue for this first, you can read more in our contributing guide https://github.com/EddieHubCommunity/LinkFree/blob/main/CONTRIBUTING.md
> 
> Also, everything should be kept in sync
> 
> * Gitpod
> * nvm
> * Docker
>   ... etc

https://github.com/EddieHubCommunity/LinkFree/issues/6649
Created an issue regarding it.

Can you tell me what other changes are needed.

2023-05-07 05:39 UTC, eddiejaoude commented
I am not sure, it is best to have these discussions in the issue before the pull request. So I will close this pull request and we can start at the beginning not at the end 🤓

2023-05-07 05:39 UTC, closed without merging