chage the name of file from VikRam.json to vikram-8290.json
EddieHubCommunity/LinkFree pull request #6678
Opened 2023-05-07 12:47 UTC by vikram-8290

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-07 14:03 UTC, SaraJaoude requested changes
You have added two profiles, please remove the one that does not match your GitHub username.

2023-05-08 21:15 UTC, HassanTanveer commented on data/vikram-8290
Please rename this file to `vikram-8290.json`

2023-05-08 21:15 UTC, HassanTanveer commented on data/VikRam.json
You may delete this file

2023-05-09 09:30 UTC, SaraJaoude commented
@HassanTanveer please avoid duplicating comments.  This causes confusion to the author as well as everyone else involved, plus it generates unnecessary notifications for the maintainers.

2023-05-15 05:36 UTC, vikram-8290 commented on data/VikRam.json
how can i delete this file.please help me this

2023-05-15 05:36 UTC, closed without merging

2023-05-15 05:37 UTC, vikram-8290 commented
> You have added two profiles, please remove the one that does not match your GitHub username.

i am new github please tell me how can i remove the other one