fix: card text consistent alignment on mobile
EddieHubCommunity/LinkFree pull request #668
Opened 2021-11-15 10:53 UTC by AbhinavMV

Closes #665
Made card text center for mobile view (max width 960px)
Current Alignment:
![image](https://user-images.githubusercontent.com/35369843/141769251-bb06ad04-a54b-45c4-8f31-07379b484568.png)

After Change:
![image](https://user-images.githubusercontent.com/35369843/141769338-44b7b4c6-12e8-475d-ae3b-ca4a7b328c4e.png)

No Change in Desktop View: 
![image](https://user-images.githubusercontent.com/35369843/141769447-5ed10d44-df5f-4608-bd1f-e9733a9ec752.png)

2021-11-16 05:42 UTC, mohan-murali commented
Can you please the prime react classes to achieve the same? you can just add `text-center` class to align text to center using prime react.
https://www.primefaces.org/primeflex/textalign

2021-11-16 07:25 UTC, krishguptadev requested changes

2021-11-16 07:25 UTC, krishguptadev commented on src/Components/Milestone.css
> +  .p-card-title,
```suggestion

  .p-card-title,
```

2021-11-16 07:26 UTC, krishguptadev commented
> Can you please use the prime react classes to achieve the same? you can just add `p-text-center` class to align text to center using prime react. https://primefaces.org/primereact/showcase/#/text

How can someone make responsive changes with just PrimeReact 😅

2021-11-16 07:48 UTC, mohan-murali commented
> > Can you please use the prime react classes to achieve the same? you can just add `p-text-center` class to align text to center using prime react. https://primefaces.org/primereact/showcase/#/text
> 
> How can someone make responsive changes with just PrimeReact 😅

We can. But I guess we can't change text align. Also I noted that these are changes to inbuilt prime react classes themselves. I don't know if there is anyway around this.

2021-11-16 15:06 UTC, AbhinavMV commented on src/Components/Milestone.css
> +  .p-card-title,
Done 👍

2021-11-16 19:02 UTC, emmalearnscode commented
> > > Can you please use the prime react classes to achieve the same? you can just add `p-text-center` class to align text to center using prime react. https://primefaces.org/primereact/showcase/#/text
> > 
> > 
> > How can someone make responsive changes with just PrimeReact 😅
> 
> We can. But I guess we can't change text align. Also I noted that these are changes to inbuilt prime react classes themselves. I don't know if there is anyway around this.

I believe this is a case where custom css is required

2021-11-16 19:03 UTC, emmalearnscode approved these changes

2021-11-17 02:44 UTC, mohan-murali approved these changes

2021-11-17 06:27 UTC, krishguptadev approved these changes

2021-11-17 06:32 UTC, shreyaansjain06 approved these changes
LGTM

2021-11-17 11:10 UTC, qwe123coder approved these changes
LGTM! :rocket:

2021-11-22 02:21 UTC, Vyvy-vi approved these changes
Looks good to me.
Thanks for contributing to LinkFree!

2021-11-22 02:21 UTC, merged