Create pavanh007
EddieHubCommunity/LinkFree pull request #6738
Opened 2023-05-10 13:59 UTC by pavanh007

Required changes are updated: PR #6714

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-10 14:51 UTC, khushalarora requested changes
Hey @pavanh007, thank you for contributing :tada: 
Please rename your file to **`data/pavanh007.json`** :+1:

2023-05-10 22:05 UTC, HassanTanveer submitted a review, later dismissed

2023-05-11 02:41 UTC, pavanh007 commented
> Hey @pavanh007, thank you for contributing 🎉 Please rename your file to **`data/pavanh007.json`** 👍

can you suggest me

2023-05-11 16:35 UTC, SurajPratap10 commented
> > Hey @pavanh007, thank you for contributing 🎉 Please rename your file to **`data/pavanh007.json`** 👍
> 
> can you suggest me

There's a `data` folder in the repo where every user's data is kept, you have to put your file under that folder.

2023-05-12 04:07 UTC, pavanh007 commented
> > > Hey @pavanh007, thank you for contributing 🎉 Please rename your file to **`data/pavanh007.json`** 👍
> > 
> > 
> > can you suggest me
> 
> There's a `data` folder in the repo where every user's data is kept, you have to put your file under that folder.

>> As you suggest, I removed existing file and added in data folder

2023-05-12 15:57 UTC, kumarsonsoff3 submitted a review, later dismissed
Please add the file extension `.json` in the end of your [filename here](https://github.com/pavanh007/LinkFree/edit/pavanh007-json/data/pavanh007).

Let us know if you need any help with this! :)

2023-05-20 19:44 UTC, Vishrut19 requested changes
Please change the filename to data/pavanh007.json

2023-05-21 02:28 UTC, SaraJaoude commented
> Please change the filename to data/pavanh007.json

@Vishrut19 we have brought to your attention a number of times not to duplicate comments.  As we have highlighted to you this causes confusion to the author, maintainers - and can also scare off contributors. If you do not have time to be looking through historical comments then perhaps you should not be reviewing PRs.

2023-05-21 04:12 UTC, Vishrut19 commented
> > Please change the filename to data/pavanh007.json
> 
> @Vishrut19 we have brought to your attention a number of times not to duplicate comments. As we have highlighted to you this causes confusion to the author, maintainers - and can also scare off contributors. If you do not have time to be looking through historical comments then perhaps you should not be reviewing PRs.

Hey Sara! First of I am extremely Sorry for duplicate comments but I tried to make pavan understand that this is the naming convention that needs to be followed i.e. `data/<yourname>/json`. I thought putting a comment like that would make him understand about the naming convention along with the file format. Hope it makes sense.

2023-05-22 05:43 UTC, Vishrut19 requested changes

2023-05-22 05:43 UTC, Vishrut19 commented on data/pavanh007
> +    "bio": "Backend developer" | "Tech enthusiast",
The format is incorrect. The correct format is "Backend developer | Tech enthusiast"

2023-05-26 20:51 UTC, Pradumnasaraf approved these changes
Hey everyone,

Thank you all for the review. Since the pull request has been open for a while, I will be merging it into a temporary branch to address any existing errors before merging it into the main branch.

2023-05-26 20:54 UTC, merged