Create ProyectoIntegrAccion.json
EddieHubCommunity/LinkFree pull request #6739
Opened 2023-05-10 14:14 UTC by Proyecto-IntegrAccion

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-10 16:12 UTC, kumarsonsoff3 requested changes
Your file should be in data directory. Please rename your [file here](https://github.com/Proyecto-IntegrAccion/LinkFree/edit/main/ProyectoIntegrAccion.json) to `data/Proyecto-IntegrAccion.json`. 

Change `ProyectoIntegrAccion.json`  ->  `data/Proyecto-IntegrAccion.json`. Let us know if you need any help with this.

2023-05-10 16:12 UTC, kumarsonsoff3 commented on ProyectoIntegrAccion.json
> +{
There us a missing `links` key. Please make sure you follow the [quickstart guide](https://linkfree.io/docs/quickstart). 

```suggestion
"links": [
    {
```

2023-05-10 16:14 UTC, SaraJaoude commented on ProyectoIntegrAccion.json
> +  "type": "comunidad",
currently we only support `personal`/actualmente solo apoyamos `personal`:
```suggestion
  "type": "personal",
```

2023-05-10 16:15 UTC, SaraJaoude commented on ProyectoIntegrAccion.json
> +  "bio": "un proyecto de cooperación entre la Universidad Católica San Pablo y ACNUR"
a comma is necessary / una coma es necesaria
```suggestion
  "bio": "un proyecto de cooperación entre la Universidad Católica San Pablo y ACNUR",
```

2023-05-26 20:56 UTC, Pradumnasaraf approved these changes
Hey everyone,

Thank you all for the review. Since the pull request has been open for a while, I will be merging it into a temporary branch to address any existing errors before merging it into the `main` branch.

2023-05-26 20:57 UTC, merged