B thomas22tech patch 1
EddieHubCommunity/LinkFree pull request #6741
Opened 2023-05-10 17:23 UTC by BThomas22tech

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-10 18:03 UTC, amandamartin-dev requested changes

2023-05-10 18:03 UTC, amandamartin-dev commented on data/BThomas22tech.json
> +  "avatar": "https:github.com/BThomas22tech.png",
```suggestion

```
no longer needed, please remove

2023-05-10 18:03 UTC, amandamartin-dev commented on data/BThomas22tech.json
> +  "displayStatsPublic": true,
```suggestion
 
```
no longer needed, please remove

2023-05-10 22:04 UTC, HassanTanveer requested changes

2023-05-10 22:04 UTC, HassanTanveer commented on data/BThomas22tech.json
> +},
```suggestion
}
```
Please remove the trailing comma

2023-05-11 00:29 UTC, SaraJaoude commented on data/BThomas22tech.json
> +  "bio": "Full Stack Python developer looking to change the world!"
needs a comma:
```suggestion
  "bio": "Full Stack Python developer looking to change the world!",
```

2023-05-12 13:22 UTC, amandamartin-dev approved these changes

2023-05-12 13:23 UTC, merged