data:ujjwalkirti
EddieHubCommunity/LinkFree pull request #6742
Opened 2023-05-10 18:53 UTC by ujjwalkirti

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-10 19:24 UTC, khushalarora requested changes
Hey @ujjwalkirti, thank you for contributing :tada:

2023-05-10 19:24 UTC, khushalarora commented on data/ujjwalkirti.json
> +    { "icon": "FaGithub", "url": "https://github.com/ujjwalkirti" },
Please remove the **'Comma'** from the end of this line :+1: 
```Suggestion
    { "icon": "FaGithub", "url": "https://github.com/ujjwalkirti" }
```

2023-05-10 22:02 UTC, HassanTanveer approved these changes

2023-05-11 00:31 UTC, SaraJaoude approved these changes
looks good

2023-05-11 00:31 UTC, merged