data: Stephanie Chester
EddieHubCommunity/LinkFree pull request #6743
Opened 2023-05-10 20:12 UTC by Stephanie-Chester

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-10 21:14 UTC, khushalarora requested changes
Hey @Stephanie-Chester, thank you for contributing :tada: 
Please rename your file to **`data/Stephanie-Chester.json`** :+1:

2023-05-10 21:29 UTC, Stephanie-Chester commented
> Hey @Stephanie-Chester, thank you for contributing 🎉 Please rename your file to **`data/Stephanie-Chester.json`** 👍

Thanks @khushalarora I have renamed the file, please let me know if it looks good now

2023-05-10 22:02 UTC, HassanTanveer approved these changes

2023-05-11 00:32 UTC, SaraJaoude approved these changes
looks good

2023-05-11 00:32 UTC, merged