updated my profile
EddieHubCommunity/LinkFree pull request #678
Opened 2021-11-19 03:29 UTC by hareom284

2021-11-19 04:34 UTC, Panquesito7 requested changes
Please revert the changes in the `package-lock.json` file.

2021-11-19 04:34 UTC, Panquesito7 commented on public/data/hareom284.json
> +}
Missing an endline.
```suggestion
}

```

2021-11-19 04:34 UTC, Panquesito7 commented on public/data/hareom284.json
> +            "title": "Started Using twiiter",
```suggestion
            "title": "Started Using Twitter",
```

2021-11-19 04:34 UTC, Panquesito7 commented on public/data/hareom284.json
> +            "description": "Creation content on twitter and share about my journey",
```suggestion
            "description": "Creation content on Twitter and sharing about my journey",
```

2021-11-19 04:35 UTC, krishguptadev requested changes
Please see the comments left above

2021-11-19 10:59 UTC, krishguptadev requested changes
Please see the above comments

2021-11-19 17:13 UTC, Panquesito7 requested changes

2021-11-19 17:13 UTC, Panquesito7 commented on public/data/hareom284.json
> +            "title": "Started Using twiiter",
```suggestion
            "title": "Started Using Twitter",
```

2021-11-19 17:13 UTC, Panquesito7 commented on public/data/hareom284.json
> +}
Still missing an endline.
```suggestion
}

```

2021-11-20 04:13 UTC, krishguptadev requested changes
Please check out the comments left above 🙂

2021-11-20 15:26 UTC, shreyaansjain06 requested changes
Please see suggestions above

2021-11-21 11:49 UTC, hareom284 commented
> Please see suggestions above

Please check in out I have correct that one

2021-11-21 12:59 UTC, krishguptadev requested changes
Can you format the file and revert the package files?

2021-11-21 12:59 UTC, krishguptadev commented on public/data/hareom284.json
> +}
```suggestion
}

```

2021-11-21 13:05 UTC, ssensalo reviewed
Please remove `package-lock.json` file also add @Panquesito7 's suggestions

2021-11-21 13:05 UTC, ssensalo commented on public/data/hareom284.json
> +            "description": "Create Content on Twitter and Shareing about  my journey",
```suggestion
            "description": "Create Content on Twitter and Sharing about  my journey",
```

2021-11-21 16:58 UTC, Panquesito7 requested changes
Please see the comments above.

2021-11-22 01:14 UTC, Vyvy-vi commented
:) Thanks for adding your profile to LinkFree!
We'll remove the `package-lock.json` file, while merging this in a staging branch

2021-11-22 01:16 UTC, merged

2021-11-22 01:16 UTC, krishguptadev commented
@Vyvy-vi it would be nice if you could format the file as well, before it is merged into main