Dhananjayan's Data
EddieHubCommunity/LinkFree pull request #679
Opened 2021-11-19 07:15 UTC by dhananjayandayalan

2021-11-19 09:43 UTC, krishguptadev requested changes

2021-11-19 09:43 UTC, krishguptadev commented on public/data/dhananjayan.json
> +  }
```suggestion
}

```

2021-11-19 13:51 UTC, Pradumnasaraf approved these changes
<img src="https://user-images.githubusercontent.com/51878265/142633310-4398fba0-9adf-4386-be51-1b382799c32d.png" height = 80>

2021-11-19 14:25 UTC, krishguptadev approved these changes

2021-11-19 17:09 UTC, Panquesito7 approved these changes

2021-11-20 15:23 UTC, shreyaansjain06 approved these changes

2021-11-20 16:07 UTC, dhananjayandayalan commented
What's workflow awaiting approval? Why It takes time to merge my pull request? I really don't know whether I can ask this question or not.

2021-11-21 03:32 UTC, krishguptadev commented
> What's workflow awaiting approval? Why It takes time to merge my pull request? I really don't know whether I can ask this question or not.

We need a actual maintainer to review your PR before it is merged 😊

2021-11-21 03:32 UTC, krishguptadev commented
Cc @schmelto

2021-11-21 10:45 UTC, dhananjayandayalan commented
> > What's workflow awaiting approval? Why It takes time to merge my pull request? I really don't know whether I can ask this question or not.
> 
> We need a actual maintainer to review your PR before it is merged 😊

Thanks for clarifying😊

2021-11-22 00:24 UTC, merged