data: HarshPanchal18
EddieHubCommunity/LinkFree pull request #6812
Opened 2023-05-12 12:40 UTC by HarshPanchal18

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/6812"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-05-12 12:56 UTC, HassanTanveer requested changes

2023-05-12 12:56 UTC, HassanTanveer commented on data/HarshPanchal18.json
> +Additionally, I enjoy listening to music, reading books, and acquiring new knowledge.",
```suggestion
  "bio": "Hi, I'm HARSH!\nI'm a Software engineer in growth mode, lifelong-learner, and reader.\nNative Android Programming, Backend, observing and developing tools always excite me.\nAdditionally, I enjoy listening to music, reading books, and acquiring new knowledge.",
```
Please use `\n` for new line

2023-05-12 13:34 UTC, iamthecloverly submitted a review, later dismissed

2023-05-12 15:43 UTC, kumarsonsoff3 submitted a review, later dismissed

2023-05-12 15:43 UTC, kumarsonsoff3 commented on data/HarshPanchal18.json
> +  "tags": ["Open Source", "DevSecOps", "Python", "Kotlin", "Android", "Jetpack Compose", "Linux"]
Please add the missing comma here. 
```suggestion
  "tags": ["Open Source", "DevSecOps", "Python", "Kotlin", "Android", "Jetpack Compose", "Linux"],
```

2023-05-12 21:35 UTC, HassanTanveer approved these changes

2023-05-13 00:45 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-05-13 01:57 UTC, SaraJaoude approved these changes
looks good

2023-05-13 01:58 UTC, merged