Create custom error page 404
EddieHubCommunity/LinkFree pull request #6814
Opened 2023-05-12 15:09 UTC by Segacnd

## Fixes Issue

Closes #6721 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
![image](https://github.com/EddieHubCommunity/LinkFree/assets/103945988/2a789f75-45f4-4dc0-95c3-27d266827d84)

## Note to reviewers

2023-05-12 22:27 UTC, eddiejaoude commented on pages/[username].js
> +  }
This is not needed, as it will go to the `search` page from the code below if no user is found, which I think is better user experience

2023-05-12 22:29 UTC, eddiejaoude requested changes
The package lock file changes are not required, because there are no changes to the package file - please revert these changes

2023-05-12 22:31 UTC, eddiejaoude commented on pages/404.js
> +          <h2 className="mb-8 font-extrabold text-9xl dark:text-gray-600">
I don't think there is any other h1 on the page, so we should probably use h1 here. Sorry I should have mentioned we have paid for Tailwind UI, so I can share the code for their page example, here it is...

```js
<div className="grid min-h-full place-items-center bg-white px-6 py-24 sm:py-32 lg:px-8">
        <div className="text-center">
          <p className="text-base font-semibold text-indigo-600">404</p>
          <h1 className="mt-4 text-3xl font-bold tracking-tight text-gray-900 sm:text-5xl">Page not found</h1>
          <p className="mt-6 text-base leading-7 text-gray-600">Sorry, we couldn’t find the page you’re looking for.</p>
          <div className="mt-10 flex items-center justify-center gap-x-6">
            <a
              href="#"
              className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
              Go back home
            </a>
            <a href="#" className="text-sm font-semibold text-gray-900">
              Contact support <span aria-hidden="true">&rarr;</span>
            </a>
          </div>
        </div>
      </div>
```

2023-05-13 13:40 UTC, eddiejaoude commented on pages/[username].js
> +
This change is not required

2023-05-13 13:41 UTC, eddiejaoude commented
Thank you for updating, please can you update the screenshot in the description

2023-05-13 14:37 UTC, Segacnd commented
> Thank you for updating, please can you update the screenshot in the description

@eddiejaoude  done 👍

2023-05-14 03:44 UTC, eddiejaoude commented
Thank you, I will merge into a temporary branch and fix

2023-05-14 03:44 UTC, merged