Added my data
EddieHubCommunity/LinkFree pull request #684
Opened 2021-11-20 15:21 UTC by Zishan-7

2021-11-20 15:23 UTC, krishguptadev requested changes

2021-11-20 15:23 UTC, krishguptadev commented on public/data/zishan.json
> +
```suggestion

```

2021-11-20 15:23 UTC, krishguptadev commented on public/data/zishan.json
> +  }
```suggestion
}
```

2021-11-20 15:23 UTC, krishguptadev commented on public/data/zishan.json
> +    "bio": "I am Zishan Mohd, currently pursuing my Masters in Computer Apllication from Panjab University, Chandigarh. I am a newbie to open source. Looking forward to collaborate with awesome peopl
```suggestion
    "bio": "Masters in Computer Application Student, Panjab University, Chandigarh. Exploring open source. 😎",
```

2021-11-20 15:34 UTC, krishguptadev requested changes

2021-11-20 15:34 UTC, krishguptadev commented on public/data/zishan.json
> +  }
```suggestion
}

```

2021-11-20 15:44 UTC, krishguptadev commented
Please do not just resolve this, but add this: https://github.com/EddieHubCommunity/LinkFree/pull/684#discussion_r753686071

Let us know if you need any help 🙂

2021-11-20 15:47 UTC, Zishan-7 commented
Thanks @krishguptadev I added your suggested changes.

2021-11-20 15:49 UTC, krishguptadev approved these changes

2021-11-21 01:33 UTC, Panquesito7 requested changes

2021-11-21 01:33 UTC, Panquesito7 commented on public/data/zishan.json
> +    "bio": "I am Zishan Mohd, currently pursuing my Masters in Computer Apllication from Panjab University, Chandigarh. I am a newbie to open source. Looking forward to collaborate with awesome peopl
```suggestion
    "bio": "I am Zishan Mohd, currently pursuing my Masters in Computer Application from Panjab University, Chandigarh. I am a newbie to open source. Looking forward to collaborating with awesome people!",
```

2021-11-21 11:22 UTC, Pradumnasaraf reviewed
LGTM, Some minor tweaks and spell errors.
See the above suggestions.👆

2021-11-21 11:37 UTC, Zishan-7 commented
Thanks for the suggestions!

2021-11-21 13:07 UTC, krishguptadev approved these changes

2021-11-21 16:53 UTC, Panquesito7 approved these changes

2021-11-22 00:23 UTC, Vyvy-vi reviewed
lgtm

2021-11-22 00:24 UTC, merged