data: vineetjaiss
EddieHubCommunity/LinkFree pull request #6877
Opened 2023-05-14 13:50 UTC by vineetjaiss

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-14 14:06 UTC, khushalarora requested changes
Hey @vineetjaiss, thank you for contributing :tada: 
Please rename your file to **`data/vineetjaiss.json`**.

2023-05-14 14:06 UTC, khushalarora commented on VinJai.json
> +    }
Please add a **'Comma'** at the end of this line :+1: 
```Suggestion
    },
```

2023-05-14 14:06 UTC, khushalarora commented on VinJai.json
> +    }
Also, add a **'Comma'** here :+1: 
```Suggestion
    },
```

2023-05-14 14:06 UTC, khushalarora commented on VinJai.json
> +      "icon":"FaLinkedin"
Also, add a **'Comma'** and **'bracket'** here :+1: 
```Suggestion
      "icon":"FaLinkedin"},
```

2023-05-14 14:06 UTC, khushalarora commented on VinJai.json
> +    }
Delete this extra bracket :+1: 
```Suggestion
```

2023-05-14 14:22 UTC, khushalarora requested changes
Hey @vineetjaiss, thanks for the changes :+1: 
Instead of Title, you need to rename your file to **`data/vineetjaiss.json`**  [HERE](https://github.com/vineetjaiss/LinkFree/edit/vineetjaiss-patch-1/VinJai.json)

2023-05-15 16:41 UTC, kumarsonsoff3 requested changes
Please read the review comments carefully. 

As suggested by Khushal, rename your file to exact `data/vineetjaiss.json` [here](https://github.com/vineetjaiss/LinkFree/edit/vineetjaiss-patch-1/vineetjaiss).

Change `vineetjaiss`  -->  `data/vineetjaiss.json`. Feel free to ask if you've any confusion.

2023-05-15 16:52 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-05-15 16:54 UTC, merged