added a profile of Gaurav Pandey
EddieHubCommunity/LinkFree pull request #688
Opened 2021-11-21 17:07 UTC by gaurtvin

2021-11-21 17:08 UTC, Panquesito7 approved these changes

2021-11-21 17:16 UTC, shreyaansjain06 requested changes

2021-11-21 17:16 UTC, shreyaansjain06 commented on public/data/gaurtvin.json
> +      "icon": "link"
```suggestion
      "icon": "linkedin"
```

2021-11-21 17:18 UTC, shreyaansjain06 approved these changes
LGTM

2021-11-21 17:33 UTC, Panquesito7 approved these changes

2021-11-22 00:12 UTC, merged

2021-11-22 00:57 UTC, krishguptadev approved these changes