Feature 6681
EddieHubCommunity/LinkFree pull request #6938
Opened 2023-05-17 11:27 UTC by AJcodes42

## Fixes Issue

Closes #6681 

## Changes proposed

1) Moved Notification logic out of IconCard.js to the Notification.js
2) Replaced Alert component uses in playground.js with Notification component

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Behavior on Icons page remains same:
<img width="1280" alt="Screenshot 2023-05-17 at 4 30 29 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/29297057/b76d6481-f1d1-400d-aee9-134bab082e53">

Error scenario in playground page show error notification:
<img width="1280" alt="Screenshot 2023-05-17 at 4 28 51 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/29297057/b590ca4b-443c-49e6-ad46-16cab50260ab">

Success scenario in playground page show success notification:
<img width="1280" alt="Screenshot 2023-05-17 at 4 29 26 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/29297057/505252ee-baa7-4c36-b63c-2e8b1ddb2f13">

## Note to reviewers

2023-05-17 17:30 UTC, eddiejaoude commented
Thank you for your contribution 👍 The notification style should be consistent for all pages

2023-05-17 17:33 UTC, eddiejaoude commented on components/Notification.js
> +    <>
I don't think this wrapper is required?

2023-05-17 17:35 UTC, eddiejaoude requested changes
The different position styles of the notification is not required - we can keep it simple for now

2023-05-18 05:02 UTC, AJcodes42 commented
Difference position styles removed from notification. Below are the screenshots

<img width="1280" alt="Screenshot 2023-05-18 at 10 24 44 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/29297057/1fe76658-db16-403b-a700-eecc8036af3b">
<img width="1280" alt="Screenshot 2023-05-18 at 10 24 31 AM" src="https://github.com/EddieHubCommunity/LinkFree/assets/29297057/b9bbe72b-68a6-41b4-a8c4-faf6c3e08ca3">

2023-05-18 11:26 UTC, eddiejaoude commented on components/IconCard.js
> +import { useState } from 'react'
Not consistent coding style with the single quotes

2023-05-18 11:26 UTC, eddiejaoude commented on components/IconCard.js
> +        type = "success"
extra spacing here, VScode Prettier plugin will fix these formatting styles

2023-05-18 11:33 UTC, eddiejaoude requested changes
Looks good 👍  I left some inline comments (note I didn't mention all the coding style items, as they are the same)

2023-05-18 11:34 UTC, eddiejaoude commented
It is so close to being merged, I will merged and reformat the files in a temporary branch

2023-05-18 11:34 UTC, merged