data: SagarSharma2809
EddieHubCommunity/LinkFree pull request #6945
Opened 2023-05-17 12:45 UTC by SagarSharma2809

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-17 12:56 UTC, khushalarora requested changes
Hey @SagarSharma2809, thank you for contributing :tada:

2023-05-17 13:43 UTC, khushalarora requested changes
Hey @SagarSharma2809, thank you for contributing :tada:

2023-05-17 13:43 UTC, khushalarora commented on data/SagarSharma2809.json
> +  "bio": "**Front-End Developer** and **Open Source Contributor**. I share my journey through blogs"
Please add a **'Comma'** at the end of this line :+1: 
```Suggestion
  "bio": "**Front-End Developer** and **Open Source Contributor**. I share my journey through blogs",
```

2023-05-17 13:43 UTC, khushalarora commented on data/SagarSharma2809.json
> +      "url": "https://www.linkedin.com/in/sagar-sharma-b8a894227/"
Also, add a **'Comma'** at the end of this line :+1: 
```Suggestion
      "url": "https://www.linkedin.com/in/sagar-sharma-b8a894227/",
```

2023-05-17 13:43 UTC, khushalarora commented on data/SagarSharma2809.json
> +      "url": "https://sagarcoding.hashnode.dev/"
Also, add a **'Comma'** at the end of this line :+1: 
```Suggestion
      "url": "https://sagarcoding.hashnode.dev/",
```

2023-05-18 03:06 UTC, SaraJaoude approved these changes
looks good

2023-05-18 03:06 UTC, merged

2023-05-18 16:58 UTC, SagarSharma2809 commented
thank you