data: zaidahmad25
EddieHubCommunity/LinkFree pull request #6968
Opened 2023-05-18 14:00 UTC by zaidahmad25

2023-05-18 15:10 UTC, ChinmayMhatre requested changes

2023-05-18 15:10 UTC, ChinmayMhatre commented on data/zaidahmad25.json
> +      "icon": "SiReact",
```suggestion
      "icon": "SiReact"
```

2023-05-18 15:11 UTC, ChinmayMhatre commented
Looks great! Added a comment regarding an extra comma which is failing the test

2023-05-18 15:18 UTC, ChinmayMhatre requested changes

2023-05-18 15:18 UTC, ChinmayMhatre commented on data/zaidahmad25.json
> +  "type": "public",
We no longer use the type property. You can remove this!

2023-05-18 15:34 UTC, zaidahmad25 commented
How do I delete this PR? 

I'll make a new PR with the right changes

2023-05-18 15:46 UTC, ChinmayMhatre requested changes

2023-05-18 15:55 UTC, zaidahmad25 commented on data/zaidahmad25.json
> +  "type": "public",
Oh, I did not know about that. My bad 😅

2023-05-18 16:49 UTC, closed without merging

2023-05-19 05:34 UTC, ChinmayMhatre commented
@zaidahmad25  it is okay for now, but you do not need to create a new PR you can push the changes in the same branch and they are reflected here!