data: gowthae
EddieHubCommunity/LinkFree pull request #6973
Opened 2023-05-18 18:07 UTC by gowthae

creating new profile : gowthae

2023-05-18 18:39 UTC, Panquesito7 requested changes

2023-05-18 18:39 UTC, Panquesito7 commented on data/gowthae.json
> +  "avatar": "https://github.com/gowthae.png",
I believe this field is no longer required. The avatar is automatically fetched from your profile.
```suggestion
```

2023-05-18 18:39 UTC, Panquesito7 commented on data/gowthae.json
> +  "displayStatsPublic":true,
Same as this one (stats are only available to you, AFAIK).
```suggestion
```

2023-05-19 03:11 UTC, harshsingh32 reviewed
Thanks for contribution.

2023-05-19 04:04 UTC, SaraJaoude approved these changes
looks good

2023-05-19 04:04 UTC, merged