fix: Use HTTPs links instead of HTTP
EddieHubCommunity/LinkFree pull request #700
Opened 2021-11-24 19:51 UTC by Panquesito7

## Changes proposed

- Use HTTPs links instead of HTTP.
  - Do let me know if all links work properly (except those like GitHub/Twitter). 😄

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2021-11-24 20:43 UTC, emmalearnscode requested changes
Can you remove the package-lock file from the PR?

2021-11-24 21:01 UTC, schmelto commented on Contributing.md
> +[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://makeapullrequest.com)
```suggestion
[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://github.com/EddieHubCommunity/LinkFree/pulls)

```

2021-11-24 21:41 UTC, Panquesito7 commented
> Can you remove the package-lock file from the PR?

By the way, I think that file should be updated in a PR or commit. 😅

2021-11-24 22:02 UTC, schmelto approved these changes

2021-11-24 23:26 UTC, merged

2021-11-25 02:28 UTC, krishguptadev reviewed
LGTM! But I believe this could be a `docs:` commit and didn't need a version bump