data : Rimpyyadav
EddieHubCommunity/LinkFree pull request #7000
Opened 2023-05-19 09:53 UTC by Rimpyyadav

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-19 10:19 UTC, khushalarora requested changes
Hey @Rimpyyadav, thank you for contributing :tada:

2023-05-19 10:19 UTC, khushalarora commented on data/Rimpyyadav.json
> +  "bio": "Finding my better place in tech as Newbie :) Aspiring Backend webdev , Love to do Shuffle "
Please add a **'Comma'** at the end of this line :+1: 
```suggestion
  "bio": "Finding my better place in tech as Newbie :) Aspiring Backend webdev , Love to do Shuffle ",
```

2023-05-20 03:26 UTC, SaraJaoude approved these changes
looks good

2023-05-20 03:26 UTC, merged

2023-05-20 13:06 UTC, Rimpyyadav commented
Huge Thanks to Eddie and Sara for all your Support !!!