data:NonsoBarn
EddieHubCommunity/LinkFree pull request #7009
Opened 2023-05-19 15:25 UTC by NonsoBarn

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-19 15:28 UTC, iamthecloverly commented on data/NonsoBarn.json
> +  "bio": "Web Developer. Web3 enthusiast, Games & Tech aficionado"
"bio": "Web Developer. Web3 enthusiast, Games & Tech aficionado"

2023-05-19 18:50 UTC, khushalarora requested changes
Hey @NonsoBarn, thank you for contributing :tada:

2023-05-19 18:50 UTC, khushalarora commented on data/NonsoBarn.json
> +  "bio": "Web Developer. Web3 enthusiast, Games & Tech aficionado"
Please add a **'Comma'** at the end of this line :+1: 
```Suggestion
  "bio": "Web Developer. Web3 enthusiast, Games & Tech aficionado",
```

2023-05-19 18:50 UTC, khushalarora commented on data/NonsoBarn.json
> +    }
Also, add a **'Comma'** here :+1: 
```Suggestion
    },
```

2023-05-19 18:50 UTC, khushalarora commented on data/NonsoBarn.json
> +    }
Also, add a **'Comma'** here :+1: 
```Suggestion
    },
```

2023-05-19 20:46 UTC, RohanSasne requested changes

2023-05-19 20:46 UTC, RohanSasne commented on data/NonsoBarn.json
> +      "icon": "FaGitHub"
Change the icon from FAGitHub to FaLinkedin:

```suggestion
      "icon": "FaLinkedin"
```

2023-05-19 20:46 UTC, RohanSasne commented on data/NonsoBarn.json
> +      "icon": "FaGitHub"
The h should be small in Github:
```suggestion
      "icon": "FaGithub"
```

2023-05-20 10:32 UTC, kumarsonsoff3 approved these changes
Looks good! 🎉

2023-05-20 10:33 UTC, merged