Create tanishqamitra.json
EddieHubCommunity/LinkFree pull request #7016
Opened 2023-05-19 20:01 UTC by tanishqamitra

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-20 03:37 UTC, SaraJaoude commented on tanishqamitra.json
> +  "bio": "Open Source 🥑 •  Co-founder at @zeal_yug •   Join me on a journey of constant learning & growth!"
add a comma:
```suggestion
  "bio": "Open Source 🥑 •  Co-founder at @zeal_yug •   Join me on a journey of constant learning & growth!",
```

2023-05-20 03:37 UTC, SaraJaoude commented on tanishqamitra.json
> +    }
add a comma:
```suggestion
    },
```

2023-05-20 03:38 UTC, SaraJaoude requested changes
Please move your file to the `data` folder. 

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-05-20 11:02 UTC, kumarsonsoff3 submitted a review, later dismissed

2023-05-20 11:02 UTC, kumarsonsoff3 commented on tanishqamitra.json
> +  "type": "personal",
Also, please remove the `type` key from your `json`.
```suggestion
```

2023-05-26 21:01 UTC, Pradumnasaraf approved these changes
Hey everyone,

Thank you all for the review. Since the pull request has been open for a while, I will be merging it into a temporary branch to address any existing errors before merging it into the main branch.

2023-05-26 21:02 UTC, merged