data: AliMora83
EddieHubCommunity/LinkFree pull request #7024
Opened 2023-05-20 09:17 UTC by AliMora83

## Fixes Issue

N/a

## Changes proposed

- Updated Twitter icon.
- Made icons white.
- Restructured tags to = MERN.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Icon change and color will be white.
<img width="337" alt="Screenshot 2023-05-20 at 10 42 08" src="https://github.com/EddieHubCommunity/LinkFree/assets/56822813/7b3d9e04-3d4d-423c-861e-a8982619dbef">

Adjusted to MERN first.
<img width="652" alt="Screenshot 2023-05-20 at 11 12 56" src="https://github.com/EddieHubCommunity/LinkFree/assets/56822813/7b8b6008-745d-4d91-8087-111fc5638215">

## Note to reviewers

I'm enjoying working with other developers 🥳
Thank you sooo much 🥳🙏🏼🤩

2023-05-20 14:27 UTC, amandamartin-dev requested changes

2023-05-20 14:27 UTC, amandamartin-dev commented on data/AliMora83.json
> +      "iconColor": "white"
```suggestion
      "color": "white"
```

2023-05-20 14:27 UTC, amandamartin-dev commented on data/AliMora83.json
> +      "iconColor": "white"
```suggestion
      "color": "white"
```

2023-05-20 15:51 UTC, AliMora83 commented on data/AliMora83.json
> +      "iconColor": "white"
Thank you, will update 🥳

2023-05-21 02:31 UTC, SaraJaoude approved these changes
looks good

2023-05-21 02:31 UTC, merged