data: piaseckijulian
EddieHubCommunity/LinkFree pull request #7059
Opened 2023-05-20 20:54 UTC by piaseckijulian

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-20 21:10 UTC, khushalarora requested changes
Hey @piaseckijulian, thank you for contributing :tada: 
Please rename your file and Add **`data/`** in the beginning [Here](https://github.com/piaseckijulian/LinkFree/edit/piaseckijulian-patch-1/piaseckijulian.json).
Your file name will look like **`data/piaseckijulian.json`**

2023-05-20 21:10 UTC, khushalarora commented on piaseckijulian.json
> +    "avatar": "https://github.com/piaseckijulian.png",
You can remove this line, it is not required anymore :+1: 
```Suggestion
```

2023-05-20 21:10 UTC, khushalarora commented on piaseckijulian.json
> +    "displayStatsPublic": true,
You can remove this line, it is not required anymore :+1: 
```Suggestion
```

2023-05-21 02:51 UTC, SaraJaoude commented
@piaseckijulian it appears that you have made these changes in a new Pull Request: https://github.com/EddieHubCommunity/LinkFree/pull/7061 so I will be closing this Pull Request. 

In future please close Pull Requests you no longer require - this helps maintainers manage the project.

2023-05-21 02:51 UTC, closed without merging