New profile
EddieHubCommunity/LinkFree pull request #707
Opened 2021-11-25 08:54 UTC by foxy4096

2021-11-25 12:05 UTC, krishguptadev requested changes

2021-11-25 12:05 UTC, krishguptadev commented on public/data/foxy4096.json
> +
```suggestion

```

2021-11-25 12:05 UTC, krishguptadev commented on public/data/foxy4096.json
> +  }
```suggestion
}
```

2021-11-25 13:13 UTC, krishguptadev requested changes

2021-11-25 13:13 UTC, krishguptadev commented on public/data/foxy4096.json
> +
Not yet fixed.

```suggestion

```

2021-11-25 15:44 UTC, krishguptadev commented on public/data/foxy4096.json
> +}
```suggestion
}

```

2021-11-25 16:31 UTC, Panquesito7 requested changes
Please see the comments above.

2021-11-26 10:25 UTC, schmelto approved these changes
LGTM

![image](https://user-images.githubusercontent.com/30869493/143566057-28aaeba4-df34-49d5-990e-487c2ac94465.png)

2021-11-26 11:15 UTC, krishguptadev approved these changes

2021-11-26 13:14 UTC, Vyvy-vi approved these changes
LGTM!

2021-11-26 13:14 UTC, merged

2021-11-26 15:55 UTC, Panquesito7 reviewed
LGTM! 🚀