(docs): add alert boxes
EddieHubCommunity/LinkFree pull request #7074
Opened 2023-05-21 12:13 UTC by NiazMorshed2007

This pr closes the issue #6957 

Wrapping the important message with Alert component in mdx file produces expected style discussed in the issue.
Currently, I'm using `type` of `warning` in `Alert` component. (different views for different types are discussed in #6957 )

2023-05-22 01:30 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 

- please add a screenshot in the PR description
- GitHub Action is failing `./pages/docs/quickstart.mdx
Module not found: Can't resolve '@components/alert.js'` I think this needs to be `@components/Alert.js` as it is case sensitive

2023-05-22 05:54 UTC, NiazMorshed2007 commented
@eddiejaoude fixed!
And here is a screen shot of it currently looks like

![image](https://github.com/EddieHubCommunity/LinkFree/assets/77217706/295f8922-1aa6-46e9-94f2-abbbaed8f4ec)

If you want to see the different views for different types please check my message on #6957

2023-05-22 06:09 UTC, eddiejaoude commented
Thank you 👍 The markdown does not render, I think we have 2 options

- add functionality for the markdown, this can come later
- remove markdown from the messages

2023-05-22 06:10 UTC, eddiejaoude commented
Also I think this PR should update all "important" information in the docs, for example https://github.com/EddieHubCommunity/LinkFree/blob/main/pages/docs/environments/local-development.mdx?plain=1#L6

2023-05-24 14:18 UTC, NiazMorshed2007 commented
@eddiejaoude All good. I'm currently removing markdown from the message.
And updating all the important messages ✌️

2023-05-26 02:10 UTC, eddiejaoude commented
Great! thank you 👍

2023-05-31 15:55 UTC, eddiejaoude commented
@NiazMorshed2007 do you need any help?

2023-06-01 15:45 UTC, NiazMorshed2007 commented
Hey @eddiejaoude ,
Sorry for the late. I was going busy for the Appwrite hackathon,, 
Check this commit & let me know if any changes are needed.

Note: I've updated the `message` props with `jsx` instead of `string` to add bold/italic/other (because we can't use markdown) formats in message.

2023-06-01 16:01 UTC, NiazMorshed2007 commented
Conflict resolved.
But, does the warning message in the gitpod docs looks fine?

![image](https://github.com/EddieHubCommunity/LinkFree/assets/77217706/413122aa-b961-41b3-a5ca-afe0487c1790)

2023-06-02 01:34 UTC, eddiejaoude commented
Yes I think it looks good 👍 

Are there any more alerts to be added to the docs?

2023-06-03 09:12 UTC, NiazMorshed2007 commented
All good.
I checked all docs, all covered!

2023-06-04 00:13 UTC, eddiejaoude commented on pages/docs/quickstart.mdx
> +      JSON file is <i>error free</i> before committing your pull request.
```suggestion
      <strong>NOTE</strong>: Please use our online{" "}
      <Link href="https://linkfree.io/playground">Playground</Link> tool to check your
      JSON file is <I>valid</i> before committing your pull request.
```

2023-06-04 00:16 UTC, eddiejaoude commented on pages/docs/quickstart.mdx
> +      JSON file is <I>valid</i> before committing your pull request.
```suggestion
      JSON file is <i>valid</i> before committing your pull request.
```

2023-06-04 00:19 UTC, eddiejaoude commented on pages/docs/environments/gitpod.mdx
> +      </i>{" "}
This note seems to have italic but the other note does not.

2023-06-04 00:19 UTC, eddiejaoude approved these changes
Looks good! Thank you 👍 

 I will merge and fix the inline comment in a temporary branch

2023-06-04 00:20 UTC, merged