added check for links count
EddieHubCommunity/LinkFree pull request #7098
Opened 2023-05-22 10:52 UTC by Akhilbisht798

## Fixes Issue
#7011 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-23 00:43 UTC, eddiejaoude requested changes
Thank you for your contribution 👍 

I left an inline comment, I think the code can be simplified and reduced

2023-05-23 03:24 UTC, Akhilbisht798 commented on pages/api/users/[username]/links/[url].js
> +    isOwner = true;
Oh. thats a great idea. We can remove all the checks for below by simply returning early.

2023-05-23 03:31 UTC, Akhilbisht798 commented
Hey, I have made the changes you have suggested in the file.

2023-05-24 03:51 UTC, eddiejaoude approved these changes
Thank you 👍

2023-05-24 03:52 UTC, merged