data: chaddyc
EddieHubCommunity/LinkFree pull request #7113
Opened 2023-05-22 19:07 UTC by chaddyc

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-22 19:47 UTC, khushalarora requested changes
Hey @chaddyc, thank you for contributing :tada:

2023-05-22 19:47 UTC, khushalarora commented on data/chaddyc.json
> +    }
Please add a **'Comma'** at the end of this line :+1: 
```Suggestion
    },
```

2023-05-22 19:47 UTC, khushalarora commented on data/chaddyc.json
> +    }
Also, add a **'Comma'** here :+1: 
```Suggestion
    },
```

2023-05-23 05:06 UTC, SaraJaoude approved these changes
looks good

2023-05-23 05:06 UTC, merged