feat: added skip links to pages
EddieHubCommunity/LinkFree pull request #7125
Opened 2023-05-23 07:21 UTC by shoebilyas123

## Fixes Issue

Closes #7038 

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots
![Screenshot from 2023-05-23 12-47-25](https://github.com/EddieHubCommunity/LinkFree/assets/73349037/0af182d9-0312-4ab7-875f-0a6924575a38)

## Note to reviewers

2023-05-31 10:09 UTC, eddiejaoude commented on components/skiplink/index.jsx
> +    <a
Should this be our `Link` component?

2023-05-31 10:10 UTC, eddiejaoude commented on components/skiplink/index.jsx
> +      style={{ zIndex: 1000 }}
I think we should use tailwind as much as possible https://tailwindcss.com/docs/z-index

2023-05-31 10:12 UTC, eddiejaoude commented on components/layouts/DocsLayout.js
> +};
Not sure why `MultiLayout` is added to the `DocsLayout`? I think it would be better to be like before but add your new component `SkipLink`

2023-05-31 10:14 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 Looks good!

Btw `SkipLink` component should have the same extension as other components `.js` and doesn't need its own folder as it will only be 1 component - I suggest moving and renaming it to `components/SkipLink.js`

2023-06-01 06:54 UTC, shoebilyas123 commented on components/skiplink/index.jsx
> +    <a
Yes this is out SkipLink component

2023-06-02 00:45 UTC, eddiejaoude commented on components/SkipLink.js
> +);
This component doesn't follow the same style as the other project components....

```suggestion
export default function SkipLink() {
  return (
    <div className={`flex w-screen justify-center`}>
      <a
        className={`absolute p-2 bg-primary-low text-primary-high border-2 border-primary-low-medium dark:bg-primary-high dark:text-primary-low dark:border-primary-low  -translate-y-full focus:translate-y-0 transition duration-400 ease-in-out z-[1000]`}
        href="#main"
      >
        Skip to Main Content
      </a>
    </div>
  );
}
```

2023-06-02 00:45 UTC, eddiejaoude commented on components/layouts/MultiLayout.js
> +import { SkipLink } from "@components/SkipLink";
When updating the component style, this will need to change also

```suggestion
import SkipLink from "@components/SkipLink";
```

2023-06-02 00:46 UTC, eddiejaoude requested changes
Looks good, 1 last inline comment then we can merge 🎉

2023-06-02 13:37 UTC, eddiejaoude approved these changes
Thank you 👍 

I resolved the last comments, so we can get this merged

2023-06-02 13:39 UTC, merged