data: tanishkamakode
EddieHubCommunity/LinkFree pull request #7158
Opened 2023-05-24 12:15 UTC by tanishkamakode

Add socials links

2023-05-24 12:55 UTC, khushalarora requested changes
Hey @tanishkamakode, thank you for contributing :tada: 
Please rename your file and Add **`.json`** at the end, [Here](https://github.com/tanishkamakode/LinkFree/edit/tanishkamakode-patch-2/data/tanishkamakode)
Your filename will look like **`data/tanishkamakode.json`**

2023-05-24 14:10 UTC, tanishkamakode commented
I have changed the filename to tanishkamakode.json. Kindly, review it again.

2023-05-24 23:32 UTC, bkpecho approved these changes

2023-05-25 00:45 UTC, SaraJaoude approved these changes
looks good

2023-05-25 00:45 UTC, merged