Changed the borderColor of milestone items
EddieHubCommunity/LinkFree pull request #7159
Opened 2023-05-24 14:56 UTC by rustybatmobile

…t as asked

## Fixes Issue

## Changes proposed

The border color of the milestone items have been changed to lightgrey as requested. 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-24 21:46 UTC, eddiejaoude commented on components/user/UserMilestone.js
> +        borderColor: "lightgrey",
This can be achieved with a tailwind css class and the style is no longe required

2023-05-24 21:46 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 I left an inline comment

2023-05-25 00:47 UTC, SaraJaoude commented
@rustybatmobile please can you update the comment to link to the Issue this would solve

2023-05-29 01:48 UTC, SaraJaoude commented
> rustybatmobile please can you update the comment to link to the Issue this would solve

@rustybatmobile I have now updated this - please ensure that in any future contributions you link the Issue that your PR is looking to solve. How are you getting on with the comments made by the reviewers?

2023-06-05 02:11 UTC, SaraJaoude commented
I will be closing this PR due to lack of activity.

2023-06-05 02:11 UTC, closed without merging