Add App-Choreography
EddieHubCommunity/LinkFree pull request #720
Opened 2021-11-26 17:25 UTC by CodingSpecies

## Changes proposed
I added the App-Choreography organisation, as I am the founder of it. Thank you

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2021-11-26 17:33 UTC, Panquesito7 requested changes

2021-11-26 17:33 UTC, Panquesito7 commented on public/data/App-Choreography.json
> +      "description": "We had the awesome idea, to create and bring an open source org, inspiration from EddieHub Community!",
```suggestion
      "description": "We had the awesome idea, to create and bring an open source org, inspiration from EddieHub Community!"
```

2021-11-26 18:47 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-11-26 18:47 UTC, merged

2021-11-27 03:56 UTC, krishguptadev reviewed
LGTM!