Pavanh007 patch 1
EddieHubCommunity/LinkFree pull request #7201
Opened 2023-05-27 03:35 UTC by pavanh007

## Fixes Issue
Fixed the changes required

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-27 06:30 UTC, ChinmayMhatre requested changes
Please change the filename to `pavanh007.json` and move it to the `data` folder

2023-05-27 06:30 UTC, ChinmayMhatre commented on pavanh007-initial-commit
> +    "avatar": "https://i.ibb.co/vHWZ959/linkedIn.png"
```suggestion
```
Avatar property is no longer needed

2023-05-27 10:42 UTC, kumarsonsoff3 requested changes

2023-05-27 10:42 UTC, kumarsonsoff3 commented on pavanh007-initial-commit
> +    "displayStatsPublic": true,
In addition to the above requested changes, please remove `type`, & `displayStatsPublic` keys from your `json` as we no longer need them. 

[Edit Your File Here](https://github.com/pavanh007/LinkFree/edit/pavanh007-patch-1/pavanh007-initial-commit)

```suggestion
```

2023-06-07 10:48 UTC, merged

2023-06-07 10:53 UTC, SaraJaoude commented
Temporary branch was not merged as exact Profile already exists: https://github.com/EddieHubCommunity/LinkFree/blob/main/data/pavanh007.json