Create AbdulKaderJailani.json
EddieHubCommunity/LinkFree pull request #7251
Opened 2023-05-29 15:30 UTC by prjailani

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-30 04:13 UTC, SaraJaoude commented on data/AbdulKaderJailani.json
> +  "bio": "Web Developer and Digital Marketer at Anavara | CSE'26 | OpenSource Contributor - SSOC'22, SWOC'23, GSSOC'23"
add a comma:
```suggestion
  "bio": "Web Developer and Digital Marketer at Anavara | CSE'26 | OpenSource Contributor - SSOC'22, SWOC'23, GSSOC'23",
```

2023-05-30 04:14 UTC, SaraJaoude requested changes
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/AbdulKaderJailani.json` it should be `data/prjailani.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-05-30 14:16 UTC, prjailani commented
Now got it @SaraJaoude. Pls, check now. Thanks.

2023-05-31 03:45 UTC, SaraJaoude approved these changes
looks good

2023-05-31 03:46 UTC, merged