data: aarpardev
EddieHubCommunity/LinkFree pull request #7255
Opened 2023-05-29 21:54 UTC by aarpardev

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-05-29 22:03 UTC, khushalarora requested changes
Hey @aarpardev, thank you for contributing :tada:

2023-05-29 22:03 UTC, khushalarora commented on data/aarpardev.json
> +  "displayStatsPublic": false,
You can remove this line, it is not required anymore :+1: 
```Suggestion
```

2023-05-29 22:03 UTC, khushalarora commented on data/aarpardev.json
> +  "avatar": "https://avatars.githubusercontent.com/u/115501471?s=96&v=4",
You can also remove this line, it is not required anymore :+1: 
```Suggestion
```

2023-05-30 00:39 UTC, aarpardev commented
Hi, khushalarora!

Thank you for the suggested updates. I commited the changes in my branch and will look over the complete LinkFree documentation further before I make any further updates.

2023-05-30 02:43 UTC, Sindhuinti submitted a review, later dismissed
Looks good 🎉

2023-05-30 04:21 UTC, SaraJaoude commented on data/aarpardev.json
> +  "type": "personal",
due to a recent update this is no longer required:
```suggestion
```

2023-05-30 04:27 UTC, SaraJaoude approved these changes
looks good

2023-05-30 04:27 UTC, merged