Create AndroGari.json
EddieHubCommunity/LinkFree pull request #7287
Opened 2023-05-31 12:14 UTC by AndroGari

My portfolio

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

2023-05-31 15:59 UTC, kumarsonsoff3 commented on data/AndroGari.json
> +  "tag": "SIH'22 Winner | Ex Jr. ML Engineer @JupiterAILabs | CSE(AI&ML) '24"
As far as I know, there is no valid key named `tag`. Please remove this from your `json`

You can add this info to your bio if you want. 

```suggestion
```

2023-06-04 23:34 UTC, krishstwt requested changes

2023-06-04 23:34 UTC, krishstwt commented on data/AndroGari.json
> +  "tag": "SIH'22 Winner | Ex Jr. ML Engineer @JupiterAILabs | CSE(AI&ML) '24"
Updating on it because the issue wasn't resolved, but it was marked resolved,

```suggestion
```

Please have a look at the docs for more info

2023-06-10 14:02 UTC, ChinmayMhatre commented
@AndroGari do you need any help with the changes suggested by the reviewers?

2023-06-11 17:54 UTC, ChinmayMhatre commented
Closing Issue due to no response, @AndroGari  Please feel free to create a new PR if you wish to add your profile, Thank you!

2023-06-11 17:54 UTC, closed without merging