Added YouTube video to contributing file with the img
EddieHubCommunity/LinkFree pull request #7304
Opened 2023-06-01 08:45 UTC by luckyklyist

## Fixes Issue
Added a YouTube video thumbnail with a link to the Contributing Guide video for LinkFree.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot from 2023-06-01 14-25-27](https://github.com/EddieHubCommunity/LinkFree/assets/35479077/f0a2ddd0-9d3b-4833-b4d1-45d4ed47d904)

2023-06-01 13:23 UTC, eddiejaoude commented on CONTRIBUTING.md
> +## Issues & Pull Requests (not for Profiles)
This is a duplicate title

2023-06-01 13:24 UTC, eddiejaoude commented on CONTRIBUTING.md
> +[![LinkFree Contributing Guide](https://github-production-user-asset-6210df.s3.amazonaws.com/35479077/242535587-d33e07a3-5732-465e-955a-7d7bd504b99b.jpg)](https://youtu.be/dfeSpGd8leU)
It would be good to have some text below to show this is a video

2023-06-01 13:26 UTC, eddiejaoude requested changes
Thank you, I left some inline comments

2023-06-01 13:26 UTC, eddiejaoude requested changes
Thank you, I left some inline comments

2023-06-05 16:45 UTC, luckyklyist commented
![image](https://github.com/EddieHubCommunity/LinkFree/assets/35479077/2ee34ace-0e29-4bf4-8c17-37f1b1a7b58d)
I have added the text below to describe the image: #7289.

2023-06-07 16:03 UTC, eddiejaoude commented on CONTRIBUTING.md
> +
```suggestion
```

2023-06-07 16:04 UTC, eddiejaoude commented on CONTRIBUTING.md
> +You can watch the video that Eddie created as a contributing guide. Click on the image to watch the video.
```suggestion

You can watch the video that Eddie created as a contributing guide. Click on the image to watch the video.
```

2023-06-07 16:04 UTC, eddiejaoude approved these changes
Looks good 👍

2023-06-07 16:05 UTC, merged