data :rishu6263
EddieHubCommunity/LinkFree pull request #7307
Opened 2023-06-01 12:32 UTC by rishu6263

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-01 13:32 UTC, khushalarora requested changes
Hey @rishu6263, thank you for contributing :tada:

2023-06-01 13:32 UTC, khushalarora commented on data/rishu6263.json
> +"type": "personal",
You can remove these lines, these are not required now :+1: 
```Suggestion
```

2023-06-01 13:32 UTC, khushalarora commented on data/rishu6263.json
> +"avatar": "https://github.com/rishu6263.png",
You can also remove this line, it is not required now :+1: 
```Suggestion
```

2023-06-01 13:32 UTC, khushalarora commented on data/rishu6263.json
> +},
Please remove this extra **'Comma'** from this line :+1: 
```Suggestion
}
```

2023-06-02 03:33 UTC, SaraJaoude approved these changes
looks good

2023-06-02 03:34 UTC, merged