Improve user search experience #6872
EddieHubCommunity/LinkFree pull request #7392
Opened 2023-06-05 08:40 UTC by itsdevdeepak

## Fixes Issue

Closes #6872 

## Changes proposed

- [x] Updated the `filterData` method to to filler users that matches all searched keywords (comma separated values). 
- [x] Updated the `search` method to use `cleanInput` and  use `searchTagNameInInput` to search tag name form search input.
- [x] Ignores the extra spaces and commas in search input. 
- [x] Moved the `useEffect` hook to top of the components according to the rule of hooks.
- [x] Moved the `result` to the bottom of the hooks.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

[video preview](https://imgur.com/a/VdW8o3S)

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7392"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-06-05 16:58 UTC, Vishrut19 approved these changes
Looks good to me! 👍

2023-06-09 04:34 UTC, eddiejaoude commented on pages/search.js
> +
Blank spaces not required, you can setup Prettier to format this correctly on save in VScode

```suggestion

```

2023-06-09 04:34 UTC, eddiejaoude commented on pages/search.js
> +
```suggestion

```

2023-06-09 04:38 UTC, eddiejaoude requested changes
Looks good 👍 I am not sure if the results are always correct though

Searching for `Eddie` on production...

<img width="1658" alt="Screenshot 2023-06-09 at 11 37 16" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/87283d26-2878-4f39-aa3e-bc957abbde86">

Searching on your PR... (I think 2 results should not be there as they are not in their `username`, `name` or `tags`?)

<img width="1665" alt="Screenshot 2023-06-09 at 11 36 44" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/31a39643-3be1-454e-9e29-799c033b2fa9">

2023-06-09 04:42 UTC, itsdevdeepak commented
> Looks good 👍 I am not sure if the results are always correct though
> 
> Searching for `Eddie` on production...
> <img alt="Screenshot 2023-06-09 at 11 37 16" width="1658" src="https://user-images.githubusercontent.com/624760/244593016-87283d26-2878-4f39-aa3e-bc957abbde86.png">
> 
> Searching on your PR... (I think 2 results should not be there as they are not in their `username`, `name` or `tags`?)
> <img alt="Screenshot 2023-06-09 at 11 36 44" width="1665" src="https://user-images.githubusercontent.com/624760/244593058-31a39643-3be1-454e-9e29-799c033b2fa9.png">

i think its because they are using `eddiehub`  tag in their profile

2023-06-09 05:30 UTC, eddiejaoude commented
>> i think its because they are using `eddiehub` tag in their profile.
> 
> should i change the code to only search for tags if they are complete matched ?

Oh my bad, let me double check their tags - if they are then the results are correct

2023-06-09 05:30 UTC, eddiejaoude commented
Yes you are correct 👍 , they have it in their tags https://github.com/EddieHubCommunity/LinkFree/blob/main/data/LinuxGamer.json#L4

2023-06-09 05:32 UTC, eddiejaoude approved these changes
Thank you 👍

2023-06-09 05:33 UTC, merged