data: jegrami
EddieHubCommunity/LinkFree pull request #7399
Opened 2023-06-05 15:26 UTC by jegrami

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-05 16:51 UTC, kumarsonsoff3 requested changes

2023-06-05 16:51 UTC, kumarsonsoff3 commented on data/jegrami.json
> + {
You're missing some required properties link `name`, `bio`, etc. Please read the [QuickStart Docs](https://linkfree.io/docs/quickstart) for more information on how to add Your Profile. 

Please add your name, and bio as suggested below.

```suggestion
 {
  "name": "Jeremiah Igrami",
  "bio": "YOUR__BIO",
  "links": [
    {
```

2023-06-07 10:01 UTC, jegrami reviewed
Thanks for the change! What should I do next?

2023-06-07 16:19 UTC, kumarsonsoff3 commented on data/jegrami.json
> +  "bio": "YOUR__BIO",
Please add your bio/about/headline here instead in place of `YOUR__BIO` placeholder.

2023-06-08 09:49 UTC, jegrami reviewed
I have made the correction. Thanks again.

2023-06-08 15:12 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for Contributing! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></a></p>

2023-06-08 15:13 UTC, merged