Added my profile
EddieHubCommunity/LinkFree pull request #741
Opened 2021-11-28 14:45 UTC by Mohasin-Haque

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-11-28 16:12 UTC, mohan-murali approved these changes

2021-11-28 18:48 UTC, Vyvy-vi requested changes
The file needs formatting...
If you have a local clone of the repo, it would be great if you can run prettier on this...
Or if you can edit the file with this version -
```
{
  "name": "Mohasin Haque",
  "bio": "Techie Teacher at Techie Tessie.",
  "avatar": "https://github.com/Mohasin-Haque.png",
  "links": [
    {
      "name": "Follow me on GitHub",
      "url": "https://github.com/Mohasin-Haque",
      "icon": "github"
    },
    {
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/mohasin_haque",
      "icon": "twitter"
    },
    {
      "name": "Follow me on Linkedin",
      "url": "https://www.linkedin.com/in/mohasin-haque-759786200/",
      "icon": "linkedin"
    },
    {
      "name": "Follow me on Facebook",
      "url": "https://www.facebook.com/ajad.ali.3766",
      "icon": "facebook"
    }
  ],
  "milestones": [
    {
      "title": "Started YouTube",
      "image": "https://github.com/Mohasin-Haque",
      "date": "August 2021",
      "icon": "youtube",
      "color": "red",
      "description": "Free programming videos every Friday",
      "url": "https://www.youtube.com/techietessie"
    }
  ]
}

```

2021-11-28 18:50 UTC, Panquesito7 submitted a review, later dismissed
Please see the comments above.

2021-11-29 11:02 UTC, Mohasin-Haque commented
I have formatted the file.. Now please correct me if I have to do anything more. Thanks for comments.

2021-11-29 11:32 UTC, Vyvy-vi approved these changes
looks good to me!

2021-11-29 11:44 UTC, schmelto approved these changes

2021-11-29 11:45 UTC, merged

2021-11-29 11:45 UTC, schmelto commented
**Thanks for your contribution** 🚀

2021-11-29 11:58 UTC, krishguptadev reviewed
LGTM!

2021-11-29 15:52 UTC, Panquesito7 commented on public/data/Mohasin-Haque.json
> +}
Missing an endline. I'll make a PR for it.
```suggestion
}

```