add donlouie
EddieHubCommunity/LinkFree pull request #742
Opened 2021-11-28 15:32 UTC by donlouie

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-11-28 18:42 UTC, Vyvy-vi requested changes
Looks good to me, however, this file needs formatting...

It would be great if it can be changed to -
```json
{
  "name": "Louie",
  "bio": "Web Developer, Exploring Open Source",
  "avatar": "https://github.com/donlouie.png",
  "links": [
    {
      "name": "Follow me on GitHub",
      "url": "https://github.com/donlouie",
      "icon": "github"
    }
  ]
}

```

2021-11-28 18:47 UTC, Panquesito7 requested changes
Please see the comments above.

2021-11-29 00:53 UTC, Panquesito7 commented on public/data/donlouie.json
> +
```suggestion
```

2021-11-29 00:53 UTC, donlouie reviewed
-

2021-11-29 02:16 UTC, Panquesito7 approved these changes

2021-11-29 02:17 UTC, merged

2021-11-29 02:52 UTC, krishguptadev reviewed
LGTM!