data: jegrami
EddieHubCommunity/LinkFree pull request #7466
Opened 2023-06-09 09:40 UTC by jegrami

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-09 10:53 UTC, jaydeepkhatri requested changes

2023-06-09 10:53 UTC, jaydeepkhatri commented on data/jegrami.json
> +    "plotly.express",
Hi @jegrami ,

Remove the `,` (comma) at the end of the tags array. JSON is invalid due to that.

```suggestion
    "plotly.express"
```

You can test your code here -> https://linkfree.io/playground

Thank you :)

2023-06-09 18:14 UTC, kumarsonsoff3 requested changes
As you're Editing your recently merged profile, you might forgot to update your branch which causes merge conflicts.

Please update your branch to resolve conflicts. (Refer these docs for help - https://linkfree.io/docs/how-to-guides/editing#edit-your-profile, *especially point no. 4* )

2023-06-19 02:19 UTC, SaraJaoude approved these changes

2023-06-20 08:24 UTC, CBID2 commented on data/jegrami.json
> +  "bio": "**Technical Writer** and **Data Scientist**. I love uncovering insights from huge, messy data.",
[Recommendation] I think it’d be great to add some of the statements you had about being a technical writer in your old bio. It’ll highlight both of your interests.
```suggestion
  "bio": "**Technical Writer** and **Data Scientist**. I love uncovering insights from huge, messy data.",
```

2023-06-20 08:25 UTC, CBID2 requested changes
Hi @jegram! Aside from your bio needing improvement, you are off to a great start! :)

2023-06-28 01:39 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to resolve the conflicts I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing

2023-06-28 01:39 UTC, closed without merging