data: chaitali-khangar
EddieHubCommunity/LinkFree pull request #7468
Opened 2023-06-09 10:59 UTC by chaitali-khangar

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-09 13:00 UTC, amandamartin-dev requested changes

2023-06-09 13:00 UTC, amandamartin-dev commented on data/chaitali-khangar.json
> +  "avatar": "https://github.com/chaitali-khangar.png",
avatar is no longer needed
```suggestion
```

2023-06-09 13:00 UTC, amandamartin-dev commented on data/chaitali-khangar.json
> +  "displayStatsPublic": true,
stats is not needed
```suggestion
```

2023-06-09 13:11 UTC, chaitali-khangar commented
Hi @amandamartin-dev Thank you for pointing it out.

2023-06-09 18:23 UTC, kumarsonsoff3 submitted a review, later dismissed

2023-06-09 18:23 UTC, kumarsonsoff3 commented on data/chaitali-khangar.json
> +  "type": "personal",
We no longer need the `type` key as we only accept personal profiles by default now. Please remove this from your `json` .

```suggestion
```

2023-06-10 02:04 UTC, SaraJaoude approved these changes
looks good

2023-06-10 02:04 UTC, merged