rowland adimoha profile contribution to open source
EddieHubCommunity/LinkFree pull request #747
Opened 2021-11-30 17:23 UTC by rowjay007

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-11-30 17:25 UTC, rowjay007 commented
This is my first contribution the this react open source project

2021-11-30 17:44 UTC, Panquesito7 requested changes

2021-11-30 17:44 UTC, Panquesito7 commented on public/data/rowjay007.json
> +  "bio": "Software developer | Open Sorcerer",
```suggestion
  "bio": "Software developer | Open Sourcerer",
```

2021-11-30 17:44 UTC, Panquesito7 commented on public/data/rowjay007.json
> +      "name": "Connect with me on Linkedin",
```suggestion
      "name": "Connect with me on LinkedIn",
```

2021-11-30 17:44 UTC, Panquesito7 commented on public/data/rowjay007.json
> +      "name": "Follow me on Github",
```suggestion
      "name": "Follow me on GitHub",
```

2021-12-06 15:13 UTC, emmalearnscode approved these changes

2021-12-06 19:18 UTC, Panquesito7 approved these changes

2021-12-06 19:18 UTC, merged