data: zaktech96
EddieHubCommunity/LinkFree pull request #7544
Opened 2023-06-12 16:21 UTC by zaktech96

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-12 17:05 UTC, kumarsonsoff3 requested changes

2023-06-12 17:05 UTC, kumarsonsoff3 commented on data/zaktech96.json
> +  "avater":"https://github.com/zaktech96.png"
We don't need these properties anymore. Please remove these from your `json`! 

```suggestion
  "bio": "Front end developer"
```

2023-06-13 02:19 UTC, SaraJaoude commented on data/zaktech96.json
> +  "bio": "Front end developer"
add a comma:
```suggestion
  "bio": "Front end developer",
```

2023-06-13 02:22 UTC, SaraJaoude approved these changes
looks good

2023-06-13 02:22 UTC, merged