fix: Profile page links shows background color on hover
EddieHubCommunity/LinkFree pull request #7556
Opened 2023-06-13 12:49 UTC by yashug

## Fixes Issue

Closes #7042  -->

## Changes proposed

- [X] - Added background color on hover for light theme
- [X] - Added background color on hover for dark theme

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

<img width="1510" alt="Screenshot 2023-06-13 at 5 59 48 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/14201280/e20d4e85-44bc-4ef8-95cc-65da153e820f">
<img width="1509" alt="Screenshot 2023-06-13 at 6 00 00 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/14201280/7532c5e1-87e6-4a59-9f93-d544557124c6">

## Note to reviewers

Could you please suggest an alternative background color for both light and dark themes? I have currently used a secondary-low color, as I find it more prominent than other colors. I would appreciate any suggestions you may have. Thank you!

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7556"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-06-13 13:19 UTC, dan-mba requested changes

2023-06-13 14:19 UTC, yashug commented on components/user/UserLink.js
> +      className="rounded-full border border-primary-medium-low dark:border-primary-medium-low dark:hover:border-[color:var(--hover-color)] hover:border-[color:var(--hover-color)] hover:shadow-xl p-4
@dan-mba changed the contrast from 1.99 to 7.1 in dark mode

<img width="1507" alt="Screenshot 2023-06-13 at 7 45 42 PM" src="https://github.com/EddieHubCommunity/LinkFree/assets/14201280/fdbe7f68-eddb-4df6-a79d-0a31f7b497d3">

2023-06-13 16:01 UTC, dan-mba submitted a review, later dismissed
The change meets the accessibility guidelines.
As UI outside my area of expertise, I will let another maintainer approve your color choices.

2023-06-14 03:45 UTC, eddiejaoude commented on components/user/UserLink.js
> +      className="rounded-full border border-primary-medium-low dark:border-primary-medium-low dark:hover:border-[color:var(--hover-color)] hover:border-[color:var(--hover-color)] hover:shadow-xl p-4
I feel `/40` for the light mode hover looks better also - we will update these later with the full rebrand.

```suggestion
      className="rounded-full border border-primary-medium-low dark:border-primary-medium-low dark:hover:border-[color:var(--hover-color)] hover:border-[color:var(--hover-color)] hover:shadow-xl p-4 my-2 w-full content-start flex flex-row gap-4 items-center dark:bg-primary-medium dark:hover:bg-secondary-low/40 hover:bg-secondary-low/40"
```

<img width="1677" alt="Screenshot 2023-06-14 at 10 44 50" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/ab674e3b-ece1-4507-8e12-9280c6a04965">

2023-06-14 03:46 UTC, eddiejaoude commented
<img width="1677" alt="Screenshot 2023-06-14 at 10 44 50" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/04028401-d267-49dd-960b-4d24a4b9dbd1">

2023-06-14 03:58 UTC, eddiejaoude commented
Great collaboration 👍

2023-06-14 03:58 UTC, eddiejaoude approved these changes
Thank you 👍

2023-06-14 03:59 UTC, merged