data:DevasyaRajguru
EddieHubCommunity/LinkFree pull request #7578
Opened 2023-06-14 14:26 UTC by devasyarajguru

## Changes proposed

Added name and social media handles to get my LinkFree account

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots
<img width="872" alt="Capture" src="https://github.com/EddieHubCommunity/LinkFree/assets/84851506/6a94337c-51d6-461f-ad74-4490ede032e0">

## Note to reviewers

None

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7578"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-06-14 14:35 UTC, FahimFBA commented
> ## Changes proposed
> Added name and social media handles to get my LinkFree account
> 
> ## Check List (Check all the applicable boxes)
> * [ x] My code follows the code style of this project.
> * [ x] My change requires changes to the documentation.
> * [ x] I have updated the documentation accordingly.
> * [ x] All new and existing tests passed.
> * [ x] This PR does not contain plagiarized content.
> * [ x] The title of my pull request is a short description of the requested changes.
> 
> ## Screenshots
> <img alt="Capture" width="872" src="https://user-images.githubusercontent.com/84851506/245824788-6a94337c-51d6-461f-ad74-4490ede032e0.PNG">
> ## Note to reviewers
> None
> 
> [![](https://camo.githubusercontent.com/76e60919474807718793857d8eb615e7a50b18b04050577e5a35c19421f260a3/68747470733a2f2f676974706f642e696f2f627574746f6e2f6f70656e2d696e2d676974706f642e737667)](https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/7578)

Make sure not to put any space between `[` and `x`. It would be `[x]` to get a tick mark.

2023-06-14 14:38 UTC, FahimFBA requested changes

2023-06-14 14:38 UTC, FahimFBA commented on data/DevasyaRajguru.json
> +
Remove extra new line.

2023-06-14 15:23 UTC, Sindhuinti requested changes
Please rename your filename to your github username `data/
devasyarajguru.json`

2023-06-16 02:14 UTC, SaraJaoude commented on data/devasyarajguu.json
> +  "bio": "Lawyer turned Hey it's me Devasya Rajguru. I have a keen interest in Web development and have a huge fascination in Open Source and technology.",
@devasyarajguru we can now merge your PR but are you sure you want the section `Lawyer turned`? This seems to be a copy of the template profile and you may have forgotten to delete it?
```suggestion
  "bio": "Hey it's me Devasya Rajguru. I have a keen interest in Web development and have a huge fascination in Open Source and technology.",
```

2023-06-16 03:41 UTC, FahimFBA commented
> @FahimFBA please check out my code is correct or not?

Resolve the review from @SaraJaoude

2023-06-16 05:26 UTC, devasyarajguru reviewed
@SaraJaoude Thanks for mentioning my mistake, I think the problem is solved. Please check it ou!

2023-06-16 06:14 UTC, FahimFBA requested changes

2023-06-16 06:14 UTC, FahimFBA commented on data/devasyarajguu.json
> +  "bio": "Hey it's me Devasya Rajguru. I have a keen interest in Web development and have a huge fascination in Open Source and technology.",
```suggestion
  "bio": "Hey, it's me Devasya Rajguru. I have a keen interest in Web development and have a huge fascination in Open Source and technology.",
```

2023-06-16 07:04 UTC, SaraJaoude approved these changes
looks good

2023-06-16 07:04 UTC, merged

2023-06-21 04:15 UTC, devasyarajguru commented
I cannot find my profile in the Linkfree project, Please help me with that! @SaraJaoude

2023-06-21 04:39 UTC, devasyarajguru commented
I cannot see my Profile Photo on my LinkFree Account. Please help me with that! @SaraJaoude 
<img width="867" alt="abcd" src="https://github.com/EddieHubCommunity/LinkFree/assets/84851506/aa85f673-f60e-429a-b241-9580500ca3db">

2023-06-22 09:56 UTC, devasyarajguru commented
Hey @SaraJaoude , Please check out my query! Thanks!