Profile Creation
EddieHubCommunity/LinkFree pull request #7622
Opened 2023-06-16 12:32 UTC by diksha1159

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-16 12:37 UTC, RohanSasne requested changes

2023-06-16 12:37 UTC, RohanSasne commented on diksha1159.json
> +  "bio": "Just a CS student trying to learn new exciting stuff"
```suggestion
  "bio": "Just a CS student trying to learn new exciting stuff",
```

Include a `,` to parse the json correctly

2023-06-17 02:08 UTC, SaraJaoude approved these changes
Please move your file to the `data` folder. 

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-06-17 02:20 UTC, SaraJaoude requested changes
Please move your file to the `data` folder. 

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-06-17 15:56 UTC, diksha1159 commented
hi please help me understand the problem here
I think the format here seems correct 

take a look please 
![image](https://github.com/EddieHubCommunity/LinkFree/assets/76660222/f3481184-bd88-4807-815f-cfb93fafe85c)

2023-06-18 01:26 UTC, eddiejaoude commented
> how to move the file to the data folder? or should I create a new file instead? or will a simple drag and drop help?

You can edit the file (this includes the path), and you can learn more about it from our docs (there is a there video at the top of the docs file also)

Any questions let us know

2023-06-28 01:42 UTC, merged