Create Chandra-Sekhar-Bala.json
EddieHubCommunity/LinkFree pull request #7686
Opened 2023-06-19 17:16 UTC by Chandra-Sekhar-Bala

data: Chanra-Sekhar-Bala

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-19 22:58 UTC, CBID2 commented on data/Chandra-Sekhar-Bala.json
> +			"name": "Connet on Twitter",
[Proofreading] 
```suggestion
			"name": "Connect with me on Twitter",
```

2023-06-19 22:59 UTC, CBID2 commented on data/Chandra-Sekhar-Bala.json
> +			"name": "Github",
[Proofreading]
```suggestion
			"name": "Follow me on GitHub",
```

2023-06-19 23:00 UTC, CBID2 commented on data/Chandra-Sekhar-Bala.json
> +			"name": "Personal Blog",
```suggestion
			"name": "Follow my personal blog",
```

2023-06-19 23:00 UTC, CBID2 commented on data/Chandra-Sekhar-Bala.json
> +			"name": "Instagram",
[Proofreading] 
```suggestion
			"name": " Follow me on Instagram",
```

2023-06-19 23:03 UTC, CBID2 requested changes
Hi, @Chandra-Sekhar-Bala! :) I just gave you some recommendations on how to improve your Linkfree profile. If you need more suggestions, check out the [profile tips guide](https://linkfree.io/docs/profile-tips) on Linkfree's website. Happy Coding! :)

2023-06-20 02:36 UTC, Chandra-Sekhar-Bala commented
Hey @CBID2 Thanks for the review . I have made changes as you suggested, please check : )

2023-06-20 02:37 UTC, CBID2 approved these changes
Looks better now @Chandra-Sekhar-Bala! :) Great job and welcome to EddieHub! :)

2023-06-20 06:43 UTC, SaraJaoude approved these changes
looks good

2023-06-20 06:44 UTC, merged

2023-06-20 10:12 UTC, Chandra-Sekhar-Bala commented
Thank for reviewing @CBID2  and @SaraJaoude for adding me toLinkfree. But when I open  [my linkfree](https://linkfree.io/Chandra-Sekhar-Bala) it's showing my old github profile picture. I updated it before making this PR. Please look linto it!