data: Pyth0nHere
EddieHubCommunity/LinkFree pull request #7697
Opened 2023-06-20 07:09 UTC by Pyth0nHere

2023-06-20 08:37 UTC, krishstwt requested changes

2023-06-20 08:37 UTC, krishstwt commented on data/Pyth0nHere.json
> +    },
Trailing comma not allowed in JSON

```suggestion
    }
```

2023-06-20 08:56 UTC, krishstwt approved these changes

2023-06-20 09:03 UTC, Pyth0nHere reviewed
Merge it

2023-06-20 09:08 UTC, RohanSasne requested changes

2023-06-20 09:08 UTC, RohanSasne commented on data/Pyth0nHere.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

Icons are case sensitive :)

2023-06-20 10:16 UTC, Pyth0nHere reviewed
made changes.

2023-06-20 22:19 UTC, CBID2 approved these changes
LGTM! :)

2023-06-21 02:30 UTC, SaraJaoude commented
> Merge it

@Pyth0nHere please consider that this sounds unnecessarily aggressive. Also this cannot be merged yet as the JSON is not valid - please look at the GitHub Actions in future.

2023-06-21 02:31 UTC, SaraJaoude commented
@CBID2 @krishstwt as I have mentioned to you both in the past please do not approve a PR before reviewing it properly.  In this case the GitHub Actions were not passing as the JSON is still invalid.

2023-06-21 02:32 UTC, SaraJaoude commented on data/Pyth0nHere.json
> +  ]
add the missing bracket:
```suggestion
  ]
  }
```

2023-06-21 02:33 UTC, CBID2 commented
> @CBID2 @krishstwt as I have mentioned to you both in the past please do not approve a PR before reviewing it properly.  In this case the GitHub Actions were not passing as the JSON is still invalid.

Oh no I didn't catch that other brackets. 🤦🏾‍♀️

2023-06-21 02:34 UTC, SaraJaoude approved these changes
I have added the missing comma for a valid JSON and committed this - as the GitHub Action is now passing I will merge this PR.

2023-06-21 02:34 UTC, merged

2023-06-21 06:35 UTC, Pyth0nHere commented
> > Merge it
> 
> @Pyth0nHere please consider that this sounds unnecessarily aggressive. Also this cannot be merged yet as the JSON is not valid - please look at the GitHub Actions in future.

@SaraJaoude  Thank you for your feedback. I apologize if my previous message came across as unnecessarily aggressive. I'll make sure to be more mindful of my tone in future communications. Regarding the merge, I understand that the JSON is currently invalid, and I'll take a closer look at the GitHub Actions to resolve any issues before proceeding with the merge. Your input is appreciated, and I'll ensure better communication going forward. Let me know if there's anything specific you'd like me to address or if you have any further concerns.