Create saurabh
EddieHubCommunity/LinkFree pull request #771
Opened 2021-12-07 06:40 UTC by saurabhmehta1601

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-12-07 06:41 UTC, krishguptadev requested changes
Should be JSON file

2021-12-07 09:49 UTC, saurabhmehta1601 commented
I have corrected the syntax error in json file as well as renamed the file .

2021-12-07 11:45 UTC, krishguptadev commented on public/data/saurabhmehta1601.json
> +    "name": "Follow me on Twitter",
```suggestion
      "name": "Follow me on Twitter",
```

2021-12-07 11:45 UTC, krishguptadev commented on public/data/saurabhmehta1601.json
> +    "url": "https://twitter.com/saurabh__mehta",
```suggestion
      "url": "https://twitter.com/saurabh__mehta",
```

2021-12-07 11:45 UTC, krishguptadev commented on public/data/saurabhmehta1601.json
> +    "icon": "twitter"
```suggestion
      "icon": "twitter"
```

2021-12-07 17:11 UTC, Panquesito7 requested changes

2021-12-07 17:11 UTC, Panquesito7 commented on public/data/saurabhmehta1601.json
> +  "links":[
```suggestion
  "links": [
```

2021-12-07 17:11 UTC, Panquesito7 commented on public/data/saurabhmehta1601.json
> +  "bio": "Javascript Full Stack Developer ",
```suggestion
  "bio": "JavaScript Full Stack Developer",
```

2021-12-08 03:11 UTC, Panquesito7 commented on public/data/saurabhmehta1601.json
> +    "icon": "twitter"
*Suggested by @krishguptadev previously; just to bump and remind.*
```suggestion
      "icon": "twitter"
```

2021-12-08 03:13 UTC, Panquesito7 requested changes

2021-12-08 03:13 UTC, Panquesito7 commented on public/data/saurabhmehta1601.json
> +  "name": "Saurabh Mehta",
```suggestion
  "name": "Saurabh Mehta",
  "type": "personal",
```

2021-12-08 03:24 UTC, krishguptadev approved these changes

2021-12-08 04:31 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-12-08 04:36 UTC, merged