Update Profile: Pravesh-Sudha
EddieHubCommunity/LinkFree pull request #7734
Opened 2023-06-22 09:33 UTC by Pravesh-Sudha

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-22 16:08 UTC, Ananya2001-an approved these changes
Looks good!

2023-06-23 02:37 UTC, SaraJaoude approved these changes
looks good

2023-06-26 08:47 UTC, thisisdishang approved these changes
Kindly update the title example "data: your github username"

2023-06-26 17:13 UTC, accodes21 reviewed
Resolve the conflict by making your fork up to date

2023-06-27 01:25 UTC, SaraJaoude commented
> Resolve the conflict by making your fork up to date

@accodes21 please avoid duplicating comments - this adds extra unnecessary notifications and can confuse the author

2023-06-30 18:15 UTC, RohanSasne requested changes

2023-06-30 18:15 UTC, RohanSasne commented on data/Pravesh-Sudha.json
> +      "icon": "FaLinkedIn"
```suggestion
      "icon": "FaLinkedin"
```

Symbols are case sensitive :)

2023-07-01 05:42 UTC, closed without merging