data:shreyanshs31
EddieHubCommunity/LinkFree pull request #7740
Opened 2023-06-22 17:09 UTC by shreyanshs31

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-22 18:28 UTC, Krishnapro commented on data/shreyanshs31.json
> +  "bio": "Student👨🏽‍🎓 • DSA👨🏽‍💻 • Python • Java •  Learning in Public👤 • Love Open Source💜"
Add `,` at the end of line 4

2023-06-22 18:43 UTC, Krishnapro requested changes
The rest of the code looks good to me :+1:

2023-06-22 21:17 UTC, RohanSasne requested changes

2023-06-22 21:17 UTC, RohanSasne commented on data/shreyanshs31.json
> +  "avatar":"https://github.com/shreyanshs31.png",
No need to add an avatar i guess, It automatically fetches profile picture which you use for github
```suggestion
```

2023-06-23 02:44 UTC, SaraJaoude commented on data/shreyanshs31.json
> +  "bio": "Student👨🏽‍🎓 • DSA👨🏽‍💻 • Python • Java •  Learning in Public👤 • Love Open Source💜"
```suggestion
  "bio": "Student👨🏽‍🎓 • DSA👨🏽‍💻 • Python • Java •  Learning in Public👤 • Love Open Source💜",
```

2023-06-23 02:45 UTC, SaraJaoude commented on data/shreyanshs31.json
> +  "type": "personal",
the following are no longer necessary:
```suggestion
  "bio": "Student👨🏽‍🎓 • DSA👨🏽‍💻 • Python • Java •  Learning in Public👤 • Love Open Source💜",
```

2023-06-23 02:53 UTC, SaraJaoude approved these changes
I have committed the changes suggested by the other reviewers and made some further changes for the JSON to be valid - I will now merge this PR.

2023-06-23 02:53 UTC, merged