data:devWonderkind.json
EddieHubCommunity/LinkFree pull request #7764
Opened 2023-06-24 05:20 UTC by devWonderkind

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-24 06:28 UTC, ChinmayMhatre requested changes

2023-06-24 06:28 UTC, ChinmayMhatre commented on data/devWonderkind.json
> +  ]
Missing curly bracket at the end
```suggestion
  ]
}
```

2023-06-24 06:29 UTC, ChinmayMhatre commented on data/devWonderkind.json
> +      "url": "https://www.linkedin.com/in/devWonderkind/",
I guess you need to update this to a hashnode link

2023-06-24 06:30 UTC, ChinmayMhatre commented
Hey @devWonderkind , Thank you for contributing. You have a missing bracket as mentioned in the review which is why the action is failing. Do let us know if you need help with implementing the changes.

2023-06-25 05:33 UTC, devWonderkind commented
@ChinmayMhatre changes commit successfully.

2023-06-25 06:53 UTC, ChinmayMhatre approved these changes

2023-06-26 01:43 UTC, SaraJaoude approved these changes
looks good

2023-06-26 01:43 UTC, merged