data: Aayushpatil77
EddieHubCommunity/LinkFree pull request #7775
Opened 2023-06-24 18:11 UTC by Aayushpatil77

2023-06-24 18:53 UTC, rohan-kulkarni-25 approved these changes

2023-06-25 01:55 UTC, SaraJaoude requested changes
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/AyushPatil.json`  it should be `data/Aayushpatil77.json`

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart to help you update this Pull Request.

2023-06-25 01:56 UTC, SaraJaoude commented
@rohan-kulkarni-25 please do not approve a PR without doing a full check as this confuses the author

2023-06-26 01:44 UTC, SaraJaoude approved these changes

2023-06-26 01:44 UTC, merged