data: hzpeng57
EddieHubCommunity/LinkFree pull request #7835
Opened 2023-06-29 07:57 UTC by hzpeng57

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-06-29 09:56 UTC, sandramsc requested changes
Hi, you have a comma missing on line 13, rendering the json file invalid.

2023-06-29 09:56 UTC, sandramsc commented on data/hzpeng57.json
> +      "url": "https://www.linkedin.com/in/hzpeng/"
Hi, you have a comma (**,**) missing on **line 13,** rendering the json file invalid.

2023-06-29 09:58 UTC, sandramsc requested changes
Hi, you have a comma (**,**) missing on **line 13**, rendering the json file invalid.

2023-06-29 11:17 UTC, pushkaraj2007 requested changes
Hello,

On line 13, there appears to be a missing comma, which is causing errors during JSON rendering. In order to ensure the smooth functioning of the project, it is necessary to add a comma at the appropriate position.

Could you add the comma at the end of line 13?

2023-06-30 01:16 UTC, SaraJaoude commented on data/hzpeng57.json
> +      "url": "https://www.linkedin.com/in/hzpeng/"
add a comma
```suggestion
      "url": "https://www.linkedin.com/in/hzpeng/",
```

2023-06-30 01:23 UTC, SaraJaoude commented
> Hello,
> 
> On line 13, there appears to be a missing comma, which is causing errors during JSON rendering. In order to ensure the smooth functioning of the project, it is necessary to add a comma at the appropriate position.
> 
> Could you add the comma at the end of line 13?

@pushkaraj2007 please avoid duplicating a comment - this was just mentioned above  - and mentioning it again can cause confusion to the author as well as unnecessary extra notifications

2023-06-30 01:23 UTC, SaraJaoude approved these changes
looks good

2023-06-30 01:24 UTC, merged

2023-06-30 02:16 UTC, hzpeng57 commented
@SaraJaoude Thank you for correcting my mistake.

2023-06-30 08:16 UTC, pushkaraj2007 commented
> > Hello,
> > On line 13, there appears to be a missing comma, which is causing errors during JSON rendering. In order to ensure the smooth functioning of the project, it is necessary to add a comma at the appropriate position.
> > Could you add the comma at the end of line 13?
> 
> @pushkaraj2007 please avoid duplicating a comment - this was just mentioned above - and mentioning it again can cause confusion to the author as well as unnecessary extra notifications

@SaraJaoude I'm sorry for duplicating the comment, actually I didn't notice the comment of @sandramsc. I'll definitely take care of this in the future.

Sorry once again!