[FEATURE] Disable save button until changes are made to the profile through forms #7853
EddieHubCommunity/LinkFree pull request #7944
Opened 2023-07-03 11:11 UTC by mianakbarjan

## [Feature] Issue #7853 

Closes #7853 

## Changes proposed
[save button disable when no changes made](https://github.com/EddieHubCommunity/LinkFree/commit/36600b897e000e3c43d3ef52b8889ab50e427669)
[save button in link form disabled if no changes are made](https://github.com/EddieHubCommunity/LinkFree/commit/02ef6a014b7cee7af06cbe081a32971c1120d322)
[save button in milestone form disabled if no changes are made](https://github.com/EddieHubCommunity/LinkFree/commit/5f9ab0b3f850bb6fb2dc38af56ff639403123532)
[save button in event form disabled if no changes are made](https://github.com/EddieHubCommunity/LinkFree/commit/17373564fe93ec284361baf84927973e63728d5d)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
# Before of all 4 forms:
Profile form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/1ee646df-4ba8-4c44-bfe3-93f55a99c02e)
Link form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/317ad2ae-4899-4221-ae5b-cb78453579ab)
Milestone form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/1602da4a-4e9e-4208-a8a3-37ac3b11ca41)
Event form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/ed3202fb-9b9f-46d1-ac31-88e48bfffde2)

# After of all 4 forms:
Profile form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/e143bffa-1b64-4705-b1e5-7115ef29c672)
Link form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/1f3744a7-7f88-4a56-8fa4-36a57d73641d)
Milestone form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/5756c3c5-83e3-48aa-b60d-320ae59aad87)
Event form:
![image](https://github.com/EddieHubCommunity/LinkFree/assets/85061005/66dfdae7-9d03-4c8a-a713-aecd2cf8f22a)

## Note to reviewers
The code for the date formatting in the event form was slightly changed because refreshing the page of an event would make the start and end dates input blank whereas now it shows the correct start and end dates of the events. There was also a typo in the title of the Manage Milestone page which was fixed.

2023-07-03 12:28 UTC, amandamartin-dev commented
@EmmaDawsonDev if you have time, would love your expertise on accessibility and disabled buttons here. I read some articles, but didn't find a conclusive answer. Want to make sure this is a good practice.

2023-07-03 16:48 UTC, EmmaDawsonDev commented
Disabled buttons don't get read out by screen readers so they are basically invisible. I think most accessibility specialists would advise you to just let users submit the form anyway and use client side validation and feedback to the user instead of disabling buttons.

2023-07-03 18:15 UTC, mianakbarjan commented
What do I do now? Is this issue going to be edited to cater to the client side validation and feedback or will it be closed and a new issue opened?

2023-07-07 07:34 UTC, eddiejaoude commented on pages/account/manage/event/[[...data]].js
> +      price !== (event.price?.startingFrom || 0);
This is difficult to read 🤔

2023-07-07 07:36 UTC, eddiejaoude requested changes
Is there a way to make it more readable and also more manageable - I feel if there are more form fields in the future they will be forgotten to be added to the checks

2023-07-07 12:36 UTC, amandamartin-dev commented
> Disabled buttons don't get read out by screen readers so they are basically invisible. I think most accessibility specialists would advise you to just let users submit the form anyway and use client side validation and feedback to the user instead of disabling buttons.

Thank you @EmmaDawsonDev, I had a feeling this was the case.  @eddiejaoude please see Emmas thoughts on accessibility and disabled buttons. Perhaps we should not implement this change in this way

2023-07-08 08:21 UTC, eddiejaoude commented
Oh I missed the previous comment 😱 - thanks @amandamartin-dev for highlighting it (and thanks @EmmaDawsonDev for the explanation)

Maybe for now we should close the issue and PR - then have a discussion on the best way to handle this

2023-07-08 08:23 UTC, eddiejaoude commented
As there are accessibility concerns...

Thank you @mianakbarjan for your great work 👍  but I think for now we should close this PR and issue, then continue the discussion elsewhere

2023-07-08 08:23 UTC, closed without merging

2023-07-08 08:47 UTC, mianakbarjan commented
> As there are accessibility concerns...
> 
> Thank you @mianakbarjan for your great work 👍  but I think for now we should close this PR and issue, then continue the discussion elsewhere 

Thank you, had a great time working on it. Will check the issues and ask for another issue soon!

2023-07-08 09:23 UTC, eddiejaoude commented
Sorry again @mianakbarjan for having to close the issue, I really appreciate your hard work and for your understanding