data: Abhish7k
EddieHubCommunity/LinkFree pull request #7961
Opened 2023-07-04 05:58 UTC by Abhish7k

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-04 11:42 UTC, Vishrut19 commented
Thanks for contributing. LGTM 👍

2023-07-04 13:24 UTC, kumarsonsoff3 requested changes

2023-07-04 13:24 UTC, kumarsonsoff3 commented on data/Abhish7k.json
> +    {
Please add the `name` key of the link. For `links` it's necessary to use `name` key. 

```suggestion
  "links": [
   {
  "name": "Follow me on GitHub",
```

 Or modify it to use as socials on your profile

```suggestion
  "socials": [
    {
```

2023-07-05 02:04 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-07-05 02:04 UTC, merged

2023-07-05 02:36 UTC, Abhish7k commented
Thank you 😁