feat: redirect router
EddieHubCommunity/LinkFree pull request #7966
Opened 2023-07-04 14:27 UTC by ManishBisht777

## Fixes Issue #7929 

closes #7929 

## Changes proposed

 - link: after successful save on add/edit, redirect back to manage link list page with successful message
 - event: after successful save on add/edit, redirect back to the manage event list page with a successful message
 - milestone: after successful save on add/edit, redirect back to the milestone link list page with the successful message

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-04 14:50 UTC, eddiejaoude requested changes
Thank you for the contribution

- I could not see the successful message code?

2023-07-04 14:50 UTC, eddiejaoude commented on pages/account/manage/event/[[...data]].js
> +    router.back();
I think it would be safer to go to the list page

2023-07-04 15:11 UTC, ManishBisht777 commented
> Thank you for the contribution
> 
> * I could not see the successful message code?

I might be wrong but I think with the current implementation we can't show the `toast` along with redirecting back to the list page

ex- the `notification/toast` component lies in the `account/manage/link/64a4284da005543636769ca0` page when the notification appears we immediately push the router with a new URL(list page) since the notification box is part of the `/manage/link/:id` when the new route renders it renders a new page where no notification box is present.

To fix this  we can wrap our whole app to a `toast/notification provider` that way the notification box is present throughout the app and do not closes due to `page transition`

2023-07-05 00:03 UTC, eddiejaoude commented
> I might be wrong but I think with the current implementation we can't show the `toast` along with redirecting back to the list page
> 
> ex- the `notification/toast` component lies in the `account/manage/link/[[..id]]` page when the notification appears we immediately push the router with a new URL(list page) since the notification box is part of the `/manage/link/:id` when the new route renders it renders a new page where no notification box is present.
> 
> I mean it is visible but for a very short amount of time
> 
> To fix this we can wrap our whole app to a `toast/notification provider` that way the notification box is present throughout the app and does not close due to `page transition`

Yes the toast can't be used because of the direct, I think we will need to use the alert notification instad and remove the success part of the toast on the add/edit pages

2023-07-05 02:33 UTC, ManishBisht777 commented
Cool will make the changes

2023-07-05 14:40 UTC, ManishBisht777 commented
I checked the `components/Alert.js` component the problem

> > I might be wrong but I think with the current implementation we can't show the `toast` along with redirecting back to the list page
> > ex- the `notification/toast` component lies in the `account/manage/link/[[..id]]` page when the notification appears we immediately push the router with a new URL(list page) since the notification box is part of the `/manage/link/:id` when the new route renders it renders a new page where no notification box is present.
> > I mean it is visible but for a very short amount of time
> > To fix this we can wrap our whole app to a `toast/notification provider` that way the notification box is present throughout the app and does not close due to `page transition`
> 
> Yes the toast can't be used because of the direct, I think we will need to use the alert notification instead and remove the success part of the toast on the add/edit pages

This means there will be no notification for success right? And for errors, we will show an alert, let me know if I am correct

2023-07-10 08:47 UTC, eddiejaoude commented on pages/account/manage/links.js
> +            message={success ? "Link Created/Updated Successfully" : ""}
I don't think the ternary here is needed because the component is not displayed when `false`

2023-07-10 08:48 UTC, eddiejaoude commented on pages/account/manage/links.js
> +        {success ? (
Ternary not needed, just a check if `true`, that way we can reduce the code required and keep it simple

```suggestion
        {success && (
```

2023-07-10 08:48 UTC, eddiejaoude commented on pages/account/manage/links.js
> +        ) : null}
This can do when ternary is removed

2023-07-10 18:50 UTC, eddiejaoude approved these changes
Looks good 👍

2023-07-10 18:51 UTC, eddiejaoude commented
Please can you resolve conflicts then we can get it merged

2023-07-11 15:01 UTC, ManishBisht777 commented
Done :)

2023-07-12 06:40 UTC, eddiejaoude commented
Please can you fix the failing build - I think there is a lint error

2023-07-12 16:02 UTC, ManishBisht777 commented
Done, this time for sure :(

2023-07-14 09:28 UTC, eddiejaoude approved these changes
Looks good 👍 

I think we need to do the same for "delete" but this can come in another PR

2023-07-14 09:28 UTC, merged