Added my profile to the App
EddieHubCommunity/LinkFree pull request #799
Opened 2021-12-11 18:06 UTC by AmrMonier

added new json file **AmrMonier.json** to the ```/public/data```

2021-12-11 22:41 UTC, CodingSpecies requested changes
On line 4. Please can you remove the comma at the end of your bio @AmrMonier 
Thank you

2021-12-11 22:42 UTC, CodingSpecies commented
Sorry at @AmrMonier didn’t see your second commit where you fixed your syntax

2021-12-11 22:43 UTC, AmrMonier commented
@CodingSpecies  no problem

2021-12-11 22:46 UTC, CodingSpecies requested changes
Actually, @AmrMonier I realised that you fixed every other syntax but this one:
![image](https://user-images.githubusercontent.com/70807500/145693876-4a81a18a-6852-433b-a922-38b8b802e997.png)
the comma is in the string. After, that, I will approve. Thank you.

2021-12-11 22:55 UTC, AmrMonier commented
@CodingSpecies i have just fixed it

2021-12-12 01:08 UTC, Panquesito7 requested changes

2021-12-12 01:08 UTC, Panquesito7 commented on public/data/AmrMonier.json
> +  "bio": "Backend Developer, JS enthusiast, and a learning JUNKY😁😁",
```suggestion
  "bio": "Backend Developer, JS enthusiast, and a learning JUNKY 😁",
```

2021-12-12 01:08 UTC, Panquesito7 commented on public/data/AmrMonier.json
> +      "name": "Follow me on LinkedIn",
```suggestion
      "name": "Connect with me on LinkedIn",
```

2021-12-12 01:08 UTC, Panquesito7 commented on public/data/AmrMonier.json
> +      "title": "Looking for an opportunity as Backend web devloper",
```suggestion
      "title": "Looking for opportunities as a Backend Web Developer",
```

2021-12-12 01:08 UTC, Panquesito7 commented on public/data/AmrMonier.json
> +      "description": "currentl i'm buuilding side projects and looking for a job as Backend Developer"
```suggestion
      "description": "Currently, I'm building side-projects and looking for a job as a Backend Developer"
```

2021-12-12 02:19 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-12-12 02:19 UTC, merged