Create RohitPrakash.json
EddieHubCommunity/LinkFree pull request #8018
Opened 2023-07-07 04:57 UTC by hakkanoodles

data: Rohit Prakash

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-07 05:52 UTC, SaraJaoude reviewed
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/RohitPrakash.json`  it should be `data/hakkanoodles.json`.

I would suggest you look at our QuickStart Guide in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

2023-07-07 05:52 UTC, SaraJaoude requested changes
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/RohitPrakash.json`  it should be `data/hakkanoodles.json`.

I would suggest you look at our QuickStart Guide in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

2023-07-07 19:19 UTC, sandramsc requested changes

2023-07-09 08:14 UTC, SaraJaoude approved these changes

2023-07-09 08:14 UTC, merged