data: added events to Viveksati5143
EddieHubCommunity/LinkFree pull request #8041
Opened 2023-07-07 19:46 UTC by Viveksati5143

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-07 20:41 UTC, sandramsc requested changes

2023-07-07 20:41 UTC, sandramsc commented on data/Viveksati5143/events/2023-06-17-first-in-person-meetup.json
> +  "isVirtual": false,
This field is no longer needed, consider removing it, see reference [here](https://linkfree.io/docs/quickstart-json)
![nolongern](https://github.com/EddieHubCommunity/LinkFree/assets/19821445/766faa33-2b03-4eb9-a792-d832ffb175e6)
```suggestion
```

2023-07-07 20:41 UTC, sandramsc commented on data/Viveksati5143/events/2023-06-17-first-in-person-meetup.json
> +  "isInPerson": true,
This field is no longer needed, consider removing it (see above reference).
```suggestion
```

2023-07-08 06:25 UTC, SaraJaoude approved these changes
looks good

2023-07-08 06:25 UTC, merged