Updates
EddieHubCommunity/LinkFree pull request #8082
Opened 2023-07-09 14:01 UTC by ibilalkayy

Some minor update in the profile

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-09 14:43 UTC, accodes21 reviewed
Looks Good. It would help the maintainers if you clearly mention in the PR title about what it intends to do like ``` Update : ibikalkayy.json```

2023-07-09 18:45 UTC, amandamartin-dev requested changes

2023-07-09 18:45 UTC, amandamartin-dev commented on data/ibilalkayy.json
> +  "type": "personal",
```suggestion
```

This field is no llonger needed, otherwise looks good!

2023-07-10 07:31 UTC, SaraJaoude approved these changes
looks good

2023-07-10 07:31 UTC, merged