data: PandeyHarsh433
EddieHubCommunity/LinkFree pull request #8086
Opened 2023-07-09 15:49 UTC by PandeyHarsh433

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-09 20:38 UTC, Vishrut19 requested changes

2023-07-09 20:38 UTC, Vishrut19 commented on data/PandeyHarsh433.json
> +  "type" : "personal",
These are not needed

2023-07-09 20:44 UTC, Vishrut19 commented on data/PandeyHarsh433.json
> +    },
`.` is not needed if you are not planning to add more items in the object.

2023-07-10 07:33 UTC, SaraJaoude commented on data/PandeyHarsh433.json
> +  "type" : "personal",
no longer required:
```suggestion
```

2023-07-10 07:34 UTC, SaraJaoude commented on data/PandeyHarsh433.json
> +    },
remove comma:
```suggestion
    }
```

2023-07-10 07:38 UTC, SaraJaoude approved these changes
looks good

2023-07-10 07:38 UTC, merged