Added Profile - Goutam Nath
EddieHubCommunity/LinkFree pull request #809
Opened 2021-12-13 15:40 UTC by nathgoutam93

## Changes proposed

added new profile Goutam Nath

## Check List

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

2021-12-13 17:13 UTC, Pradumnasaraf requested changes

2021-12-13 17:13 UTC, Pradumnasaraf commented on public/data/nathgoutam93.json
> +        "title": "Started Web developing",
```suggestion
        "title": "Started Web Development",
```

2021-12-13 17:13 UTC, Pradumnasaraf commented on public/data/nathgoutam93.json
> +        "description": "Started Contibuting To open source projects"
```suggestion
        "description": "Started contributing to Open Source projects"
```

2021-12-13 17:13 UTC, Pradumnasaraf commented on public/data/nathgoutam93.json
> +        "title": "Started Open Source",
```suggestion
        "title": "Started Open Source contribution",
```

2021-12-13 17:13 UTC, Pradumnasaraf commented on public/data/nathgoutam93.json
> +        "description": "got to learn about Web dev tools like Html, css, js, node and now playing with js/css frameworks"
```suggestion
        "description": "Got to learn about Web dev tools like HTML, CSS, JS, node and now playing with JS/CSS frameworks"
```

2021-12-13 17:13 UTC, Pradumnasaraf commented on public/data/nathgoutam93.json
> +        "title":"Started Game Developing",
```suggestion
        "title":"Started Game Development",
```

2021-12-13 17:38 UTC, Panquesito7 commented on public/data/nathgoutam93.json
> +        "name": "Portfolio",
```suggestion
        "name": "Check out my portfolio",
```

2021-12-13 20:58 UTC, closed without merging

2022-05-17 07:22 UTC, eddiejaoude commented
@nathgoutam93 did you resolve the problem?

2022-05-17 14:11 UTC, nathgoutam93 commented
> @nathgoutam93 did you resolve the problem?

yes, It is resolved, it was an issue with the git configuration for my forked repo. the author was set to a different Github handler instead of mine

2022-05-18 07:34 UTC, eddiejaoude commented
ok thank you for letting me know 👍