Create bellsofaba.json
EddieHubCommunity/LinkFree pull request #8197
Opened 2023-07-14 18:15 UTC by bellsofaba

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-14 18:17 UTC, bellsofaba commented
Thanks for the opportunity!

2023-07-14 19:55 UTC, sandramsc requested changes

2023-07-14 19:55 UTC, sandramsc commented on data/bellsofaba.json
> +  "displayStatsPublic": true,
The displayStatsPublic, avatar and type tags are no longer required, take a look at the [QuickStart Doc.](https://linkfree.io/docs/quickstart-json) if you haven't already.
![screen](https://github.com/EddieHubCommunity/LinkFree/assets/19821445/af33f593-8e59-4e5a-9739-2b54e47caf32)

```suggestion
```

2023-07-14 19:55 UTC, sandramsc commented on data/bellsofaba.json
> +  "type": "personal",
See above comment - tag no longer required.
```suggestion
```

2023-07-14 19:55 UTC, sandramsc commented on data/bellsofaba.json
> +  "avatar": "https://github.com/bellsofaba.png",
See above comment - tag no longer required.
```suggestion
```

2023-07-14 22:00 UTC, bellsofaba reviewed
The recommended changes have been taken care of.

2023-07-15 06:43 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks for Contributing! 🎉 

<p align="center"><a href="https://linkfree.io/docs/how-to-guides/editing"><img src="https://user-images.githubusercontent.com/88786642/219881471-85cabf28-d29b-41e0-95fe-52577bf69e6a.png" /></a></p>

2023-07-15 06:43 UTC, merged