[BUG] Duplicate select form element #8147
EddieHubCommunity/LinkFree pull request #8220
Opened 2023-07-16 17:12 UTC by mianakbarjan

## Fixes Issue #8147 

Closes #8147 

## Changes proposed

[x] Deleted Dropdown.js form component
[x] Created a new Select form component including common and individual variables from both Dropdown and the previous Select component. 
[x] Replaced the Dropdown component in userEvents.js with the new Select component.
[x] Fixed the Manage Event and Manage Milestone Typos.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

No screenshots applicable as changes are only made to the code and there are no visible changes in the UI.

## Note to reviewers
Sorry for closing the previous pull request since the naming convention of the variables was not up to the mark.

2023-07-16 18:33 UTC, eddiejaoude requested changes
Storybook needs updating `stories/components/form/DropDown.stories.js`

2023-07-18 06:58 UTC, eddiejaoude requested changes
Thank you for your contribution but I seem to get many errors ...

EVENTS page

<img width="1073" alt="Screenshot 2023-07-18 at 07 56 32" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/434b3020-00d5-4daa-9ddc-ef9cf0230fde">

ACCOUNT STATISTICS page


<img width="1026" alt="Screenshot 2023-07-18 at 07 57 02" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/d4b406ff-e0c2-4c1f-88e3-f2796b6e6e30">


Please test your changes before requesting a review

2023-07-19 19:47 UTC, mianakbarjan commented
Hi @eddiejaoude, I've fixed the errors you got. However, I don't know further tests that I can do because the Select component is only visible on a few pages, where the tests are now successful. Sorry for any inconvenience caused since I'm new to open-source development and still learning. I will now request a review again.

2023-07-23 14:08 UTC, eddiejaoude commented on components/form/Select.js
> +        id="dropdown-select"
I think `id` should be the same as `name`

2023-07-23 14:09 UTC, eddiejaoude requested changes
Thank you for making the changes.

Some of the dropdowns don't work though...

<img width="572" alt="Screenshot 2023-07-23 at 15 05 17" src="https://github.com/EddieHubCommunity/LinkFree/assets/624760/427417eb-e815-461c-9dd2-f277fc9d2841">

2023-07-24 20:38 UTC, mianakbarjan commented
Hi @eddiejaoude, sorry for the poor PRs made previously. I have finally made all tests and fixed the dropdowns wherever they are visible in the frontend. They all seem to be working now. I will now request for changes again. Sorry again for the delay and the inconvenience caused.

2023-07-24 21:16 UTC, mianakbarjan commented
The PR seems to have failed some tests, don't know exactly what they mean by the errors. If you want, I can try to look into them  but I'd appreciate it if I get some help.

2023-07-25 10:27 UTC, eddiejaoude commented
> The PR seems to have failed some tests, don't know exactly what they mean by the errors. If you want, I can try to look into them but I'd appreciate it if I get some help.

The error message is `Ensures select element has an accessible name` with solutions...
- "message": "Form element does not have an implicit (wrapped) <label>",
- "message": "Form element does not have an explicit <label>",
- "message": "aria-label attribute does not exist or is empty",
- "message": "aria-labelledby attribute does not exist, references elements that do not exist or references elements that are - "message": "Element has no title attribute",
- "message": "Element's default semantics were not overridden with role=\"none\" or role=\"presentation\"",

> Fix any of the following:
    +   Form element does not have an implicit (wrapped) <label>
    +   Form element does not have an explicit <label>
    +   aria-label attribute does not exist or is empty
    +   aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
    +   Element has no title attribute

2023-07-25 12:21 UTC, mianakbarjan commented
@eddiejaoude I've now added the label attribute to all the components, hopefully this time the tests will be successful. Requesting for a review again.

2023-07-29 11:44 UTC, eddiejaoude commented
Thank you for making the changes 👍  There are still a couple of issues before we can merge the PR...

- please resolve the conflicts (the `navigation` file got renamed, please move your changes into the new file)
- `/events` page does not work

2023-07-31 20:13 UTC, mianakbarjan commented
Hey @eddiejaoude, I don't know how to work this out since my local git repository and LinkFree's main repository have conflicts so I cannot change file names or make proper changes even though I've changed the local repository's filenames to try and fix it, but they won't get pushed. I don't know how to bring my forked repository and LinkFree's repository to the same level so that I can then work on it locally.

2023-07-31 20:38 UTC, mianakbarjan commented
I have made the necessary changes and removed all conflicts, hopefully this time, the code will work fine.

2023-08-01 11:28 UTC, mianakbarjan commented
It failed one test again, I've been trying to run the tests locally however I get the error tests/setup/global-setup.js saying fetch is not defined.

2023-08-04 13:45 UTC, dan-mba commented
> It failed one test again, I've been trying to run the tests locally however I get the error tests/setup/global-setup.js saying fetch is not defined.

Make sure you are using Node 18 or newer.
Fetch was added in node 18.

2023-08-05 20:58 UTC, mianakbarjan commented
Hopefully the errors are now fixed as all tests run successfully locally. A change had to be made in the events test file.

2023-08-06 07:41 UTC, eddiejaoude commented on components/account/manage/Navigation.js
> +
This change is not required?

2023-08-06 07:43 UTC, eddiejaoude commented on components/user/UserEvents.js
> +
This extra spaces is not required

2023-08-06 07:43 UTC, eddiejaoude commented on components/user/UserEvents.js
> +
Same here

2023-08-06 07:53 UTC, eddiejaoude commented on components/account/manage/Navigation.js
> +
```suggestion
```

2023-08-06 07:54 UTC, eddiejaoude commented on stories/components/form/DropDown.stories.js
>  };
The `DropDown.stories.js` file should be renamed to `Select.stories.js` to match the component

2023-08-06 07:54 UTC, eddiejaoude commented on components/user/UserEvents.js
> +
```suggestion

```

2023-08-06 07:54 UTC, eddiejaoude commented on components/user/UserEvents.js
> +
```suggestion

```

2023-08-06 07:55 UTC, eddiejaoude commented on components/user/UserEvents.js
> +
```suggestion

```

2023-08-06 08:03 UTC, eddiejaoude commented on components/Tabs.js
> +
```suggestion
```

2023-08-06 08:03 UTC, eddiejaoude commented on components/Tabs.js
> +import Select from "@components/form/Select"
Please run the linter, missing semi colon to match our project coding standards

```suggestion
import Select from "@components/form/Select";
```

2023-08-06 08:05 UTC, eddiejaoude commented on components/form/Select.js
> +          restProps.className || ''
Does not match our project coding standards, double quotes required

```suggestion
          restProps.className || ""
```

2023-08-06 08:07 UTC, eddiejaoude commented on components/user/UserEvents.js
> +
```suggestion
```

2023-08-06 08:20 UTC, eddiejaoude approved these changes
Looks good, thank you 👍

2023-08-06 08:20 UTC, merged

2023-08-06 08:37 UTC, mianakbarjan commented
Thank you for giving me the opportunity Eddie! This was my first ever pull request that got merged and hopefully, I'll keep contributing to LinkFree!!!