Fixed padding issue
EddieHubCommunity/LinkFree pull request #8236
Opened 2023-07-17 20:05 UTC by wx-it

## Fixed Issue of padding between horizontal line and hover line 

fixes #8196

### Changes proposed
- Added a margin top to the cards, and it fixed the issue.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/LinkFree/pull/8236"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-07-18 06:47 UTC, eddiejaoude commented on pages/docs/index.js
> +                      //added margin top to fix the issue
This comment is not needed, otherwise we would have so many, one for each class

2023-07-18 06:50 UTC, eddiejaoude commented on pages/docs/index.js
> +                        className="border border-transparent hover:border hover:border-orange-600 transition-all duration-250 ease-linear rounded px-6 py-2 mt-4 block"
I don't think it need to be added to every link item? The ones on the 2nd row will now have a bigger gap at the top and that is not required. Suggest adding to the wrapping item

2023-07-18 06:50 UTC, eddiejaoude requested changes
Thank you for the contribution, but I think the margin should be move - I have left inline comments

2023-07-23 13:46 UTC, eddiejaoude requested changes
The indentation doesn't look correct?

Please also add a screenshot of before and after

2023-08-04 11:57 UTC, SaraJaoude commented
As there has been no activity for two weeks I will be closing this PR.

2023-08-04 11:57 UTC, closed without merging