Create devgossips.json
EddieHubCommunity/LinkFree pull request #831
Opened 2021-12-20 15:37 UTC by devgossips

2021-12-20 18:14 UTC, emmalearnscode approved these changes

2021-12-20 18:22 UTC, Panquesito7 requested changes

2021-12-20 18:22 UTC, Panquesito7 commented on public/data/devgossips.json
> +  "name": "SAGNIK SAHOO",
```suggestion
  "name": "Sagnik Sahoo",
```

2021-12-20 18:22 UTC, Panquesito7 commented on public/data/devgossips.json
> +      "description": "❤️ Open Source ",
```suggestion
      "description": "❤️ Open Source "
```

2021-12-21 03:13 UTC, Panquesito7 commented on public/data/devgossips.json
> +      "description": "❤️ Open Source "
```suggestion
      "description": "❤️ Open Source"
```

2021-12-21 03:18 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-12-21 03:18 UTC, merged