data: AdrianAcostaPR
EddieHubCommunity/LinkFree pull request #8356
Opened 2023-07-25 20:58 UTC by AdrianAcostaPR

Created AdrianAcostaPR.json file with information about my social media links and bio.

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-26 11:42 UTC, Pradumnasaraf requested changes
Hey,
Remove these two properties. By default, it's a `personal` type, and we no longer support public stats.

2023-07-26 11:42 UTC, Pradumnasaraf commented on data/AdrianAcostaPR.json
> +  "type": "personal",
```suggestion
```

2023-07-26 11:48 UTC, Pradumnasaraf submitted a review, later dismissed

2023-07-26 11:48 UTC, Pradumnasaraf commented on data/AdrianAcostaPR.json
> +  "type": "personal",
```suggestion
```

2023-07-26 11:48 UTC, Pradumnasaraf commented on data/AdrianAcostaPR.json
> +  "avatar": "https://github.com/AdrianAcostaPR.png",
```suggestion
```

2023-07-26 11:48 UTC, Pradumnasaraf commented on data/AdrianAcostaPR.json
> +  "bio": "Software Engineer (don't be fulled by the title, I'm still learning.). I work with Java on my 9-5, and I try to learn as much as I can from other technologies."
```suggestion
  "bio": "Software Engineer (don't be fulled by the title, I'm still learning.). I work with Java on my 9-5, and I try to learn as much as I can from other technologies.",
```

2023-07-26 16:34 UTC, merged

2023-07-26 20:59 UTC, AdrianAcostaPR commented
Thank you @kumarsonsoff3 and @Pradumnasaraf for the help! 
I apologize for the errors.  I kinda went on "Auto-pilot" with Eddie's video and didn't realize these errors.

2023-07-27 02:14 UTC, kumarsonsoff3 commented
It's okay, Adrian. It does happen! 😄