data : rickmondal-2004
EddieHubCommunity/LinkFree pull request #8378
Opened 2023-07-28 07:38 UTC by rickmondal-2004

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-07-28 08:26 UTC, SaraJaoude commented on data/rickmondal_2004
> +  "type" : "personal",
no longer required:
```suggestion
```

2023-07-28 08:26 UTC, SaraJaoude commented on data/rickmondal_2004
> +  "avatar" : "https://github.com/rickmondal-2004.png"
no longer required:
```suggestion
```

2023-07-28 08:27 UTC, SaraJaoude commented on data/rickmondal_2004
> +    },
remove comma:
```suggestion
    }
```

2023-07-28 08:30 UTC, SaraJaoude requested changes
Please make sure your file name matches your GitHub username exactly (it is case sensitive). Instead of `data/rickmondal_2004`   it should be `data/rickmondal-2004.json` (essentially you have `_` instead of a `-`).

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

2023-07-28 13:44 UTC, rickmondal-2004 reviewed
Accept pull requiest

2023-07-29 04:01 UTC, Sindhuinti requested changes
Hey @rickmondal-2004 inorder to accept your PR please make the requested changes
file name should be `data/rickmondal-2004.json`

2023-07-29 07:43 UTC, SaraJaoude commented
> Accept pull requiest

@rickmondal-2004 this type of behaviour is not tolerated in the EddieHub community. Maintainers cannot merge your PR until the requested changes have been made.

2023-08-11 10:01 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the following Docs which will help with the suggested changes the maintainers have proposed:

Quickstart: https://linkfree.io/docs/quickstart-json

Editing your Profile: https://linkfree.io/docs/how-to-guides/editing-json

You can also create your Profile using Forms: https://linkfree.io/docs/quickstart-forms

2023-08-11 10:01 UTC, closed without merging