Added an autocomplete input for grouping links
EddieHubCommunity/LinkFree pull request #8428
Opened 2023-07-31 20:17 UTC by Elijah-trillionz

## Fixes Issue

Closes: 8343

## Changes proposed

[x] - Fetched all existing links of user to get existing groups of user (without any additional delay in loading the UI)
[x] - Used [headless Combobox](https://headlessui.com/react/combobox) to render the existing groups in an autocomplete input

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Screenshots
<img width="755" alt="linkfree-solution1-pr" src="https://github.com/EddieHubCommunity/LinkFree/assets/60356516/ff00a561-9670-4a4b-b470-33444c856b36">

## Note to reviewers

2023-08-07 12:22 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 

- the changes to the package lock file are not required 
- we already have a dropdown component, can that be reused?

2023-08-08 09:43 UTC, Elijah-trillionz commented
> * the changes to the package lock file are not required

I didn't make any changes to the package lock file.
It was during pulling to update with the current linkfree main branch (as at the time of creating this pr) that it the version of linkfree got updated.

2023-08-08 10:45 UTC, Elijah-trillionz commented
> * we already have a dropdown component, can that be reused?

The Select component (which recently replaced the DropDown component) because it is a select input. and I can't reuse it for an autocomplete input.

2023-08-08 11:20 UTC, eddiejaoude commented
- Did you mean to close this PR?
- Please explain why you can reuse it?

2023-08-08 12:12 UTC, Elijah-trillionz commented
I didn't mean to close it, I had to discard my remote changes so as to sync to the current version of the linkfree on my local devices. I still have the changes it on my PC.

Secondly, the Select component is a select input like I said before. With the newest updates to LinkFree, there isn't anymore Dropdown component as that has been replaced with the Select component.

The Combobox component I'm using is from headless/ui, and it is an autocomplete component with an input and a dropdown (customizable).

The select component only supports selecting. Using this means, the user must have existing groups (first) can't type in a new group. But what I need is an autocomplete with the ability to create a non-existing value while being able to select from a set of values.

2023-08-11 05:53 UTC, azhechkova commented on components/form/InputDropDown.js
> +                    selected
You can use `classNames` util for more readable classes, you can find it at `services/utils/classNames.js`

2023-08-11 05:53 UTC, azhechkova commented on package-lock.json
>        "name": "linkfree",
Fix conflict in package-lock or remove the changes, please

2023-08-11 05:53 UTC, azhechkova commented on components/form/InputDropDown.js
> +          {filteredLinkGroups.map((_group, index) => (
Not sure why we need an underscore for `group` var

2023-08-21 06:27 UTC, Elijah-trillionz commented
Thought this community would be a good place to start open-source contributing proper. But I was wrong.
It's the worst place

2023-08-21 06:27 UTC, closed without merging

2023-08-21 11:05 UTC, eddiejaoude commented
Sorry to hear that @Elijah-trillionz , please can you explain why? I know I am behind on notifications but I am trying my best 😢