Update README.md with newly introduced icons
EddieHubCommunity/LinkFree pull request #844
Opened 2021-12-22 13:58 UTC by RanjeetNSuthar

## Fixes Issue

Closes #829 

## Changes proposed

Following is the list of newly added icons:
1. Instagram
2. Linkedin
3. twitch
4. dev.to
5. Codewars
6. Hashnode
7. Graduation-hat
8. Send
9. Tiktok ( as suggested by @emmalearnscode )
10. Search
11. Left Arrow

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/76241195/147104023-0fd982f1-f4b7-4c31-a575-b74fcd896d90.png)

## Note to reviewers

Recently added Search and Arrow icons are also included

2021-12-22 14:39 UTC, emmalearnscode approved these changes

2021-12-22 19:09 UTC, Panquesito7 requested changes

2021-12-22 19:09 UTC, Panquesito7 commented on README.md
> +| Linkedin     | <img src="https://user-images.githubusercontent.com/76241195/147094289-252d533d-aeae-493c-a21a-21538162cea6.png" width=100% height=30%> |  Twitch   | <img src="https://user-images.gi
```suggestion
| LinkedIn     | <img src="https://user-images.githubusercontent.com/76241195/147094289-252d533d-aeae-493c-a21a-21538162cea6.png" width=100% height=30%> |  Twitch   | <img src="https://user-images.githubusercontent.com/76241195/147094354-12d3b38d-bb87-4c52-a3b7-4d934498da31.png" width=100% height=30%> |   DEV.to   | <img src="https://user-images.githubusercontent.com/76241195/147094431-b194a188-0a63-4ce3-89c9-1d7578405318.png" width=100% height=30%>  |
```

2021-12-22 19:09 UTC, Panquesito7 commented on README.md
> +| Tiktok     | <img src="https://user-images.githubusercontent.com/76241195/147094674-a0b67f90-c62e-4162-93b5-dd313611ff28.png" width=100% height=30%> |  Send   | <img src="https://user-images.github
```suggestion
| TikTok     | <img src="https://user-images.githubusercontent.com/76241195/147094674-a0b67f90-c62e-4162-93b5-dd313611ff28.png" width=100% height=30%> |  Send   | <img src="https://user-images.githubusercontent.com/76241195/147096133-20e75d9a-0f96-4881-a165-5e7edf1bfe96.png"  width=100% height=30%> | Search    | <img src="https://user-images.githubusercontent.com/76241195/147102645-0d50ba65-5f21-4245-9275-6c3aec7d193c.png" width=100% height=30%>  |
```

2021-12-23 03:32 UTC, Pradumnasaraf reviewed
The list of icons is becoming long as well as the README.
Either we need to change it from 3 columns to 4 columns or put the Icons in a separate MarkDown File. We can add some regular ones on the README.

2021-12-23 03:53 UTC, krishguptadev commented on README.md
> + </details>
```suggestion
</details> 
```

2021-12-23 03:55 UTC, eddiejaoude commented
Separate markdown file could be a good idea 👍

2021-12-23 09:44 UTC, emmalearnscode commented
> The list of icons is becoming long as well as the README.
> Either we need to change it from 3 columns to 4 columns or put the Icons in a separate MarkDown File. We can add some regular ones in the README.

Maybe we can get this pr merged then open a new issue to move them to their own file.

2021-12-23 09:47 UTC, Pradumnasaraf commented
> > The list of icons is becoming long as well as the README.
> > Either we need to change it from 3 columns to 4 columns or put the Icons in a separate MarkDown File. We can add some regular ones in the README.
> 
> Maybe we can get this pr merged then open a new issue to move them to their own file.

Yeah, I was also thinking of same.

2021-12-23 17:29 UTC, Panquesito7 requested changes
My comments are still not resolved. See https://github.com/EddieHubCommunity/LinkFree/pull/844#discussion_r774108323 https://github.com/EddieHubCommunity/LinkFree/pull/844#discussion_r774108158

2021-12-23 17:47 UTC, emmalearnscode commented
> My comments are still not resolved. See [#844 (comment)](https://github.com/EddieHubCommunity/LinkFree/pull/844#discussion_r774108323) [#844 (comment)](https://github.com/EddieHubCommunity/LinkFree/pull/844#discussion_r774108158)

Have a little patience @Panquesito7 it’s been less than a day since you requested changes and not everyone has time to code every day. I’m sure @RanjeetNSuthar will make the changes when they have time.

2021-12-23 23:39 UTC, eddiejaoude approved these changes
Thank you @RanjeetNSuthar for the great PR and everyone for the collaboration 👍

2021-12-23 23:42 UTC, merged

2021-12-24 00:51 UTC, Panquesito7 commented
> Have a little patience @Panquesito7 it’s been less than a day since you requested changes and not everyone has time to code every day. I’m sure @RanjeetNSuthar will make the changes when they have time.

Yeah, I just realized 😓 Sorry for that. Thanks.