data: AyushRay06
EddieHubCommunity/LinkFree pull request #8465
Opened 2023-08-02 16:40 UTC by AyushRay06

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

You'll are doing a great job. I would like my LinkFree profile to be updated.

2023-08-02 17:23 UTC, sital002 requested changes

2023-08-02 17:23 UTC, sital002 commented on data/AyushRay06.json
> +	"Socials": [{
Socials shouldn't be capitalized. It should be socials

2023-08-02 17:32 UTC, sital002 commented on data/AyushRay06.json
> +	"Socials": [{
```suggestion
	"socials": [{
```

2023-08-02 17:33 UTC, sital002 requested changes

2023-08-02 17:33 UTC, sital002 commented on data/AyushRay06.json
> +	"Socials": [{
"Socials" shouldn't be capitalized. It should be "socials"

2023-08-03 06:46 UTC, SaraJaoude approved these changes
looks good

2023-08-03 06:47 UTC, merged