data: Zaid hassan
EddieHubCommunity/LinkFree pull request #8567
Opened 2023-08-08 14:51 UTC by zaid-hassan

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-08 17:21 UTC, kumarsonsoff3 requested changes
Hey @zaid-hassan, 

You'd merge conflicts due to an outdated branch. Please update your fork branch to resolve conflicts! 

If you need any help, you can checkout: https://youtu.be/eze7Y4Rxwtc

2023-08-08 20:15 UTC, SaraJaoude commented on data/zaid-hassan.json
> +  "type": "personal",
this is no longer required:
```suggestion
```

2023-08-12 05:52 UTC, Sindhuinti approved these changes

2023-08-12 11:19 UTC, SaraJaoude commented
@Sindhuinti please do not approve changes where there are comments which have not been addressed. This is confusing for the author and also the maintainers.

2023-08-25 07:45 UTC, closed without merging

2023-08-25 07:45 UTC, SaraJaoude commented
We look forward to seeing your Profile on LinkFree, but as there is no recent activity from you to make the changes suggested I am going to close this pull request.

We hope you will raise a new pull request to create your Profile and when you do, you might want to take a look at the Docs which will help with the suggested changes the maintainers have proposed: https://linkfree.io/docs