updating some infos
EddieHubCommunity/LinkFree pull request #858
Opened 2021-12-25 10:32 UTC by abdussalam02

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-12-25 10:36 UTC, schmelto requested changes
Lgtm could you resolve the merge conflicts

2021-12-25 11:17 UTC, Pradumnasaraf requested changes

2021-12-25 11:17 UTC, Pradumnasaraf commented on public/data/Abdus_Salam.json
> +}
```suggestion
}

```

2021-12-25 13:53 UTC, krishguptadev commented on public/data/Abdus_Salam.json
> +  "bio": "Hi there!, I am Python Developer and doing my best to contribute to open source. I'm not limited to Python only, I can do more fun things! (it's a long list) Connect with me and find out😉",
```suggestion
  "bio": "Hi there! I am Python Developer and doing my best to contribute to open source. I'm not limited to Python only, I can do more fun things (it's a long list)! Connect with me and find out😉",
```

2021-12-25 14:06 UTC, abdussalam02 reviewed
committed the changes

2021-12-25 16:36 UTC, nathgoutam93 commented on public/data/Abdus_Salam.json
> +      "url": "https://twitter.com/abdussalam_02",
Why you removed the icon ?
Also the GitHub actions complaining on the trailing comma you left after the URL as you removed the icon. Fix that

2021-12-26 02:24 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-12-26 02:29 UTC, Pradumnasaraf approved these changes
LGTM :)

2021-12-26 02:33 UTC, merged