data: ralphsulit
EddieHubCommunity/LinkFree pull request #8601
Opened 2023-08-10 13:10 UTC by ralphsulit

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-10 13:37 UTC, sital002 requested changes

2023-08-10 13:37 UTC, sital002 commented on data/ralphsulit.json
> +    },
```suggestion
    }
```
This is a trailing comma which isnot required.  Please remove it.

2023-08-10 13:40 UTC, sandramsc requested changes

2023-08-10 13:40 UTC, sandramsc commented on data/ralphsulit.json
> +    },
Hi, consider removing this comma (**,**) on line 20, otherwise it renders th efile invalid.
```suggestion
    }
```

2023-08-10 13:50 UTC, accodes21 requested changes
No need for ```avatar``` kindly remove it.

2023-08-10 18:08 UTC, ralphsulit commented
removed avatar and trailing comma. thank you.

2023-08-10 23:26 UTC, sital002 approved these changes
Looks good 👍

2023-08-11 04:12 UTC, kumarsonsoff3 approved these changes
Looks good, Thanks! 🎉

2023-08-11 04:12 UTC, merged