data: ismailwafid
EddieHubCommunity/LinkFree pull request #8727
Opened 2023-08-21 12:54 UTC by ismailwafid

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-21 13:14 UTC, accodes21 requested changes
Please ```.json``` to your filename.

2023-08-21 14:57 UTC, sital002 requested changes
The trailing comma isnot required. Please remove it.

2023-08-21 14:57 UTC, sital002 commented on ismailwafid.json
> +    },
```suggestion
    }
```

2023-08-22 00:54 UTC, sital002 approved these changes
Looks good 👍
Welcome to Eddie Hub Community 🎉🎉

2023-08-22 04:24 UTC, kumarsonsoff3 requested changes
Your file should be in `data` directory. Please rename your [file here](https://github.com/ismailwafid/LinkFree/edit/ismailwafid-patch-1/ismailwafid.json) to `data/ismailwafid.json`

Change `ismailwafid.json`  -->  `data/ismailwafid.json`

Let us know if you need any help with this! :)

2023-08-22 05:49 UTC, kumarsonsoff3 commented
> Can't believe I missed that

It's okay, sital. It does happen! 😄 
Love seeing your amazing PR reviews though! 👍

2023-08-23 01:13 UTC, merged