data: sree-hari-s.json
EddieHubCommunity/LinkFree pull request #8728
Opened 2023-08-21 16:31 UTC by sree-hari-s

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-21 20:48 UTC, sandramsc requested changes

2023-08-21 20:48 UTC, sandramsc commented on data/sree-hari-s.json
> +  "displayStatsPublic": true,
Hi, this line is no longer supported, consider removing it while taking a look a look at the Quick Start guide [here](https://linkfree.io/docs/quickstart-json) if you haven't already.
```suggestion

```

2023-08-21 20:48 UTC, sandramsc commented on data/sree-hari-s.json
> +  "type": "personal",
THis line is also no longer required.
```suggestion

```

2023-08-22 05:45 UTC, kumarsonsoff3 approved these changes
Looks good! 👍

2023-08-22 05:46 UTC, merged