Create mdwasim74.jason
EddieHubCommunity/LinkFree pull request #8762
Opened 2023-08-25 03:49 UTC by mdwasim74

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-25 04:00 UTC, sital002 commented on Data/mdwasim74.jason
> +   "Links" : [
```suggestion
   "links" : [
```

2023-08-25 04:03 UTC, sital002 requested changes
Your file must be in data folder instead of ``` Data/mdwasim74.jason ``` It must be in ``` data/mdwasim74.json ```.

2023-08-25 08:01 UTC, SaraJaoude commented
> Your file must be in data folder instead of `Data/mdwasim74.jason` It must be in `data/mdwasim74.json`.

@sital002 good spot.  I will add this as a requested change so that it blocks the merge (and prevents this PR being merged by mistake without the changes being addressed).

2023-08-25 08:01 UTC, SaraJaoude requested changes
Please move your file to the `data` folder. Instead of `Data/mdwasim74.jason` It must be in `data/mdwasim74.json`.

I would suggest you look at our QuickStart Guide (especially section 7) in Docs: https://linkfree.io/docs/quickstart-json to help you update this Pull Request.

2023-08-26 09:08 UTC, SaraJaoude commented
I will close this PR as it appears to be a duplicate of https://github.com/EddieHubCommunity/LinkFree/pull/8767 and we will take your latest PR with the most recent changes as the one you want to keep. 

In future, to reduce extra work for maintainers, please either edit (you might find [these Docs](https://linkfree.io/docs/how-to-guides/editing-json) helpful) or close PRs that you no longer want.

2023-08-26 09:08 UTC, closed without merging