add srkds.json
EddieHubCommunity/LinkFree pull request #877
Opened 2021-12-31 10:10 UTC by srkds

- add srkds.json

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-12-31 14:10 UTC, kumarsonsoff3 commented
Also change edit you PR name to  **"add Profile type"** or **"add your_username_here"**,
Meaning to say remove **_".json"_** from your PR name.

2021-12-31 17:37 UTC, syedsohan requested changes
Change the PR title to - `fix: add srkds/Nirav`

2021-12-31 20:40 UTC, Panquesito7 requested changes

2021-12-31 20:40 UTC, Panquesito7 commented on public/data/srkds.json
> +      "description": "Started Contributing to opensource by participating in Hacktoberfest2021",
```suggestion
      "description": "Started Contributing to open source by participating in Hacktoberfest 2021"
```

2022-01-01 07:38 UTC, syedsohan approved these changes

2022-01-01 09:16 UTC, krishguptadev commented on public/data/srkds.json
> +      "description": "Started Contributing to open source by participating in Hacktoberfest 2021"
```suggestion
      "description": "Started contributing to open source by participating in Hacktoberfest 2021"
```

2022-01-02 03:47 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-02 03:48 UTC, merged

2022-01-02 04:04 UTC, srkds commented
Great 😀  🙌
Thank you for your support all reviewers 👍