Create mohit1607.json
EddieHubCommunity/LinkFree pull request #880
Opened 2021-12-31 15:02 UTC by mohit1607

Here is my data. I want to be a part of this community and want to contribute and learn.

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2021-12-31 17:45 UTC, syedsohan requested changes

2021-12-31 17:45 UTC, syedsohan commented on public/data/mohit1607.json
> +  "name": "MOHIT ASHLIYA",
```suggestion
  "name": "Mohit Ashliya",
```

2021-12-31 17:51 UTC, syedsohan requested changes

2021-12-31 17:51 UTC, syedsohan commented on public/data/mohit1607.json
> +      "title":"Started OpenSource Contribution",
```suggestion
      "title":"Started Open Source Contribution",
```

2021-12-31 17:51 UTC, syedsohan commented on public/data/mohit1607.json
> +      "description":"From a day before 2023 I started my open-source journey."
```suggestion
      "description":"From a day before 2023, I started my open source journey."
```
Maybe a the year `2023` is a typo so fix it.

2021-12-31 17:52 UTC, syedsohan requested changes
Change the PR title to - `fix: add mohit1607`

2021-12-31 20:17 UTC, Panquesito7 requested changes

2021-12-31 20:17 UTC, Panquesito7 commented on public/data/mohit1607.json
> +      "icon":"github"
```suggestion
      "name": "Follow me on Github",
      "url": "https://github.com/mohit1607",
      "icon": "github"
```

2021-12-31 20:17 UTC, Panquesito7 commented on public/data/mohit1607.json
> +      "icon":"twitter"
```suggestion
      "name": "Follow me on Twitter",
      "url": "https://twitter.com/ashliya_mohit",
      "icon": "twitter"
```

2021-12-31 20:17 UTC, Panquesito7 commented on public/data/mohit1607.json
> +      "description":"From a day before 2023 I started my open-source journey."
```suggestion
      "title": "Started OpenSource Contribution",
      "data": "December 2021",
      "icon": "dollor",
      "color": "grey",
      "description": "From a day before 2023 I started my open-source journey."
```

2022-01-01 05:47 UTC, syedsohan requested changes

2022-01-01 05:47 UTC, syedsohan commented on public/data/mohit1607.json
> +  "avatar":"https://github.com/SuperSet1607.png",
```suggestion
  "avatar": "https://github.com/SuperSet1607.png",
```

2022-01-03 09:23 UTC, syedsohan requested changes

2022-01-03 09:23 UTC, syedsohan commented on public/data/mohit1607.json
> +      "description":"From a day before 2023, I started my open source journey."
```suggestion
      "description": "From a day before 2023, I started my open source journey."
```

Is it `2023` or something else?

2022-01-03 09:23 UTC, syedsohan commented on public/data/mohit1607.json
> +      "title":"Started Open Source Contribution",
```suggestion
      "title": "Started Open Source Contribution",
```

2022-01-03 09:23 UTC, syedsohan commented on public/data/mohit1607.json
> +      "data":"December 2021",
```suggestion
      "data": "December 2021",
```

2022-01-03 09:23 UTC, syedsohan commented on public/data/mohit1607.json
> +      "icon":"dollor",
```suggestion
      "icon": "dollor",
```

2022-01-03 09:23 UTC, syedsohan commented on public/data/mohit1607.json
> +      "color":"grey",
```suggestion
      "color": "grey",
```

2022-01-03 12:32 UTC, krishguptadev commented on public/data/mohit1607.json
> +      "description":"From a day before 2023, I started my open source journey."
I think you meant =>
```suggestion
      "description": "From a day before 2022, I started my open source journey."
```

2022-01-03 13:27 UTC, emmalearnscode commented on public/data/mohit1607.json
> +      "icon":"dollor",
Change spelling to dollar

2022-01-03 13:40 UTC, syedsohan requested changes

2022-01-03 13:40 UTC, syedsohan commented on public/data/mohit1607.json
> +      "icon":"dollor",
```suggestion
      "icon": "dollar",
```

2022-01-03 13:40 UTC, syedsohan commented on public/data/mohit1607.json
> +  "bio": "Yo this is Superset for OpenSource Contribution.",
```suggestion
  "bio": "Yo! this is Superset for Open Source Contribution.",
```

2022-01-03 14:04 UTC, krishguptadev commented on public/data/mohit1607.json
> +      "icon":"dollor",
```suggestion
      "icon": "dollar",
```

2022-01-03 18:53 UTC, Panquesito7 requested changes

2022-01-03 18:53 UTC, Panquesito7 commented on public/data/mohit1607.json
> +  "avatar": "https://github.com/SuperSet1607.png",
Wrong link.
```suggestion
  "avatar": "https://github.com/mohit1607.png",
```

2022-01-05 14:48 UTC, krishguptadev commented on public/data/mohit1607.json
> +      "description": "From a day before 2023, I started my open source journey."
```suggestion
      "description": "From a day before 2022, I started my open source journey."
```

2022-01-17 18:54 UTC, emmalearnscode commented
@mohit1607 do you need any help updating this pull request?

2022-02-10 19:05 UTC, emmalearnscode commented
@mohit1607 ill close this pull request for now. Feel free to open it up again if you want to make the final changes.

2022-02-10 19:05 UTC, closed without merging