Added : Chaitanya7666
EddieHubCommunity/LinkFree pull request #881
Opened 2021-12-31 17:35 UTC by Chaitanya7666

I have added my social media data to the public folder.

2021-12-31 17:41 UTC, syedsohan requested changes
Could you please revert the `package-lock.json` file? There's no need to change that file.

2021-12-31 17:42 UTC, syedsohan requested changes
Change the PR title to - `fix: add Chaitanya7666`

2022-01-01 09:50 UTC, Pradumnasaraf requested changes
### Changes 
 - revert `package-lock.json` chnages.

2022-01-01 13:49 UTC, krishguptadev commented on public/data/Chaitanya7666.json
> +      "description": "Started freelancing"
I suggest a little touch to make it a bit more like a sentence than a heading 😉 

```suggestion
      "description": "Started freelancing!"
```

2022-01-01 14:23 UTC, Chaitanya7666 commented
Hey folks! I have made the suggested changes. Could you please merge the branches now? Thanks for your suggestions!

2022-01-02 03:59 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-02 04:17 UTC, Pradumnasaraf approved these changes
LGTM

2022-01-02 10:14 UTC, nathgoutam93 approved these changes

2022-01-02 17:43 UTC, emmalearnscode approved these changes

2022-01-02 17:44 UTC, merged

2022-01-02 17:44 UTC, emmalearnscode commented
Thanks for your contribution @Chaitanya7666