Add json file in data directory
EddieHubCommunity/LinkFree pull request #889
Opened 2022-01-01 14:49 UTC by harshsinghatz

Add harshsinghatz.json file with social information in public/data

2022-01-01 15:44 UTC, krishguptadev requested changes
You need to revert `package-lock.json`

2022-01-01 15:44 UTC, krishguptadev commented on public/data/harshsinghatz.json
> +  "bio": "I am an Aspiring full stack developer. I am proficient with JavaScript and looking to do open source contributions frequently",
```suggestion
  "bio": "I am an Aspiring full stack developer. I am proficient with JavaScript and looking to do open source contributions frequently!",
```

2022-01-01 16:13 UTC, syedsohan requested changes

2022-01-01 16:13 UTC, syedsohan commented on public/data/harshsinghatz.json
> +  "bio": "I am an Aspiring full stack developer. I am proficient with JavaScript and looking to do open source contributions frequently",
```suggestion
  "bio": "I am an aspiring full stack developer. I am proficient with JavaScript and looking forward to doing open source contributions frequently!",
```

2022-01-02 03:54 UTC, Panquesito7 requested changes
Hey there! Please revert the changes in the `package-lock.json` file. Let us know if you need any help! 😃

2022-01-02 03:58 UTC, krishguptadev commented on public/data/harshsinghatz.json
> +  "bio": "I am an Aspiring full stack developer. I am proficient with JavaScript and looking to do open source contributions frequently",
I am unsure why you marked that comment as resolved, it is a nice suggestion!

```suggestion
  "bio": "I am an aspiring full stack developer. I am proficient with JavaScript and looking to do open source contributions frequently!",
```

2022-01-02 10:20 UTC, harshsinghatz commented
I have done the changes in the public/data/harshsinghatz.json but am not sure how to revert the package-lock.json

2022-01-02 12:57 UTC, ssensalo commented
You can copy the current `package-lock.json` from the main branch into your branch and replace then commit the changes

2022-01-02 17:46 UTC, emmalearnscode requested changes
Your profile looks good. Please remove the package-lock file from the commit then we can get this merged :)

2022-01-03 04:55 UTC, Panquesito7 approved these changes

2022-01-03 05:03 UTC, merged