add new file to public/data directory
EddieHubCommunity/LinkFree pull request #893
Opened 2022-01-02 10:53 UTC by vaishnav-sh

## Changes proposed
Added new vaishnav-sh.json file in `public/data`

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-01-02 14:00 UTC, syedsohan requested changes

2022-01-02 14:00 UTC, syedsohan commented on public/data/vaishnav-sh.json
> +    "bio": "Frontend developer | open source enthusiast",
```suggestion
    "bio": "Frontend developer | Open source enthusiast",
```

2022-01-02 14:03 UTC, syedsohan requested changes
Change the PR title to - `fix: add Vaishnav Shyam`

2022-01-02 15:26 UTC, krishguptadev commented on public/data/vaishnav-sh.json
> +  }
```suggestion
}

```

2022-01-02 17:53 UTC, emmalearnscode approved these changes

2022-01-02 18:49 UTC, ssensalo approved these changes

2022-01-03 04:29 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-03 04:30 UTC, merged