Added
EddieHubCommunity/LinkFree pull request #896
Opened 2022-01-02 17:11 UTC by Subhojit-Dey1234

I have added  Subhojit-Dey1234.json in the public/data folder.

2022-01-02 17:54 UTC, syedsohan requested changes

2022-01-02 17:54 UTC, syedsohan commented on public/data/Subhojit-Dey1234.json
> +  }
```suggestion
}

```

2022-01-02 17:54 UTC, syedsohan commented on public/data/Subhojit-Dey1234.json
> +        "icon": "LinkedIn"
```suggestion
        "icon": "linkedin"
```

2022-01-02 17:55 UTC, syedsohan requested changes
Change the PR title to - `fix: add Subhojit Dey`

2022-01-03 04:31 UTC, Panquesito7 commented on public/data/Subhojit-Dey1234.json
> +        "description": "My main goal is to progress in Open Source and make some contribution"
```suggestion
        "description": "My main goal is to progress in Open Source and make some contributions"
```

2022-01-03 05:37 UTC, krishguptadev commented on public/data/Subhojit-Dey1234.json
> +        "description": "My main goal is to progress in Open Source and make some contribution"
```suggestion
        "description": "My main goal is to progress in Open Source and make some contribution!"
```

2022-01-03 09:24 UTC, syedsohan approved these changes

2022-01-05 14:58 UTC, emmalearnscode approved these changes

2022-01-05 15:02 UTC, krishguptadev approved these changes

2022-01-05 18:05 UTC, Panquesito7 approved these changes

2022-01-05 18:06 UTC, merged