adding johns profile
EddieHubCommunity/LinkFree pull request #897
Opened 2022-01-02 17:32 UTC by johnbabu021

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-01-02 17:41 UTC, syedsohan requested changes
Change the PR title to - `fix: add John Babu`

2022-01-02 17:43 UTC, syedsohan requested changes

2022-01-02 17:43 UTC, syedsohan commented on public/data/john.json
> +  "name": "johnbabu",
```suggestion
  "name": "John Babu",
```

2022-01-02 17:43 UTC, syedsohan commented on public/data/john.json
> +  "bio": "open source enthusiast",
```suggestion
  "bio": "Open source enthusiast",
```

2022-01-02 17:43 UTC, syedsohan commented on public/data/john.json
> +      "title": "joined gitHub",
```suggestion
      "title": "Joined GitHub",
```

2022-01-02 17:43 UTC, syedsohan commented on public/data/john.json
> +      "description": "started coding"
```suggestion
      "description": "Started coding"
```

2022-01-03 19:34 UTC, Vyvy-vi approved these changes
Looks good to me!

2022-01-03 19:34 UTC, merged