ci: add lighthouse CI
EddieHubCommunity/LinkFree pull request #927
Opened 2022-01-07 14:45 UTC by krishguptadev

This is not the final copy of the action probably, this is just to get started, we can improve it as we use :D

2022-01-07 18:33 UTC, emmalearnscode commented
This repo has the action I mentioned on the livestream. You also need to add a config file though and allow lighthouse ci access to the repo. I’m not sure how the two compare, but mine stops a deploy if scores fall below a certain level. We maybe need to decide if that is something we want or if lighthouse scores are just a nice to have that we can keep an eye on and raise issues ourselves if values fall below a certain level. https://github.com/emmalearnscode/learn-cool-problems/blob/main/lighthouserc.json

2022-01-08 11:34 UTC, emmalearnscode requested changes
As Cahl has a PR open to update node version to 16, it’s probably a good idea that this one matches too.

2022-01-08 12:19 UTC, krishguptadev commented on .github/workflows/lighthouse.yml
> +      - name: Use Node.js 12.x
```suggestion
      - name: Use Node.js 16.x
```

2022-01-08 12:19 UTC, krishguptadev commented on .github/workflows/lighthouse.yml
> +          node-version: 12.x
```suggestion
          node-version: 16.x
```

2022-02-27 04:20 UTC, krshdev commented
Hi @emmalearnscode, could you review this once? 🙂

2022-02-27 04:21 UTC, nhcarrigan requested changes

2022-02-27 04:21 UTC, nhcarrigan commented on .github/workflows/lighthouse.yml
> +        uses: actions/setup-node@v1
```suggestion
        uses: actions/setup-node@v3
```
v1 is very outdated.

2022-02-28 04:18 UTC, closed without merging

2022-02-28 04:19 UTC, krshdev commented
#1152 (Sorry, I think I deleted the branch)