chore: add cerulean coders
EddieHubCommunity/LinkFree pull request #953
Opened 2022-01-10 05:16 UTC by krishguptadev

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-01-10 05:20 UTC, Panquesito7 approved these changes

2022-01-10 10:44 UTC, syedsohan requested changes

2022-01-10 10:44 UTC, syedsohan commented on public/data/CeruleanCodersComm.json
> +  "milestones": []
```suggestion
```

2022-01-10 10:44 UTC, syedsohan commented on public/data/CeruleanCodersComm.json
> +  ],
```suggestion
  ]
```

2022-01-10 12:31 UTC, schmelto commented on public/data/CeruleanCodersComm.json
> +  "bio": "Community of inclusive Open Source people - Collaboration 1st, Code 2nd!",
```suggestion
  "bio": "An student-run open source community focusing on project based learning.",
```

2022-01-17 10:46 UTC, schmelto approved these changes

2022-01-17 17:58 UTC, emmalearnscode approved these changes

2022-01-17 17:58 UTC, merged