links css edited
EddieHubCommunity/LinkFree pull request #960
Opened 2022-01-10 22:33 UTC by git-devansh

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-01-11 04:47 UTC, vikasganiga05 requested changes
Please remove the `package-lock.json` files from the commit.

2022-01-11 07:54 UTC, emmalearnscode requested changes
Thanks for working on this. Just a couple of things:
- remove the package-lock.json from this commit
- remove your profile from this commit and make a separate pull request with just that
- line 23 in links.js is missing the md:w-7 class, please add that in.
If you need any help, please let us know :)

2022-01-11 07:55 UTC, emmalearnscode commented on src/Components/Links.js
> +      <div className="flex flex-column sm:w-9">
```suggestion
      <div className="flex flex-column sm:w-9 md:w-7">
```

2022-01-11 21:56 UTC, git-devansh commented
Sorry, I'm new to GitHub. I don't know how can I remove files from commit. Any help would be good. Thanks

2022-01-14 10:40 UTC, emmalearnscode commented
> Sorry, I'm new to GitHub. I don't know how can I remove files from commit. Any help would be good. Thanks

I think because yours has just updated the version numbers on lines 3 and 9, if you change them back to what they were and commit the changes the file will remove itself from the PR as there will no longer be any differences.

2022-01-14 10:41 UTC, emmalearnscode requested changes

2022-01-14 10:41 UTC, emmalearnscode commented on package-lock.json
> +  "version": "0.59.0",
```suggestion
  "version": "0.58.1",
```

2022-01-14 10:41 UTC, emmalearnscode commented on package-lock.json
> +      "version": "0.59.0",
```suggestion
      "version": "0.58.1",
```

2022-02-08 19:21 UTC, emmalearnscode commented
@git-devansh how are you getting on with this?

2022-02-27 15:45 UTC, emmalearnscode commented
Hi @git-devansh since there are still unresolved conflicts in this file I’m going to close this pull request. Please feel free to make new separate pull requests for your profile and the css issue if you want to and don’t hesitate to reach out for help either here or in discord if you’re unsure of how to do something.

2022-02-27 15:45 UTC, closed without merging

2022-02-27 22:13 UTC, git-devansh commented
Thank you I will try to do it