[FEATURE] Custom title
EddieHubCommunity/LinkFree pull request #968
Opened 2022-01-11 16:43 UTC by aliraza944

## Fixes Issue
Closes #964 

## Changes proposed
Dynamically changing the document title on the user profile page.

The profile document title is changing based on the name of the user
- Added document.title to the useEffect of User.js file
- The user name will be displayed on the document title
- Added the cleanup function to revert back to the original document title

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

#### Before changes
![before](https://user-images.githubusercontent.com/50791045/148984504-5fd7557a-63c2-48dc-8bcd-d9d09587c527.PNG)

#### After changes
![document title](https://user-images.githubusercontent.com/50791045/148983982-98a1f714-01bc-4905-a736-ad51c57b72da.PNG)

## Note to reviewers

2022-01-11 17:04 UTC, emmalearnscode requested changes
Could you remove the package.json and package-lock.json files from your commit and also your profile? The profile can be added as a separate pull request so that we can keep each pull request to one change only. Thanks 😊

2022-01-17 09:02 UTC, schmelto requested changes
Please don't delete the package.json and package-lock.json file. Only do not commit any changes made there to the PR.
Your PR should only contain changes made in `src/Components/UserPRofile/User.js`.

2022-01-28 19:23 UTC, KendallDoesCoding approved these changes
this is a good idea!

2022-02-08 19:20 UTC, emmalearnscode commented
Unfortunately deleting the files causes problems, either revert your commit history and only add the file containing the custom title, or copy-paste the package-lock and page.json files from the main repo back into your fork and commit them.

2022-02-27 15:49 UTC, emmalearnscode commented
Do you need any help @aliraza944 ?

2022-04-13 10:03 UTC, schmelto commented on package.json
> +  "homepage": "http://linkfree.eddiehub.org",
```suggestion
  "homepage": "http://linkfree.eddiehub.org/",
```

2022-04-13 10:05 UTC, schmelto commented on package-lock.json
> +  "version": "0.62.3",
```suggestion
  "version": "0.58.1",
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-04-13 10:05 UTC, schmelto commented on package-lock.json
> +      "version": "0.59.1",
```suggestion
      "version": "0.58.1",
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-04-27 09:10 UTC, krshdev requested changes
## Merge Conflict

Thank you for your contribution. Your pull request currently has conflicting changes with our `main` branch. In order to review this pull request, we will need those conflicts to be resolved.

We recommend doing this with the `git rebase` command. If you are unsure of how to fix this, let us know and we would be happy to assist you.
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-11 14:22 UTC, closed without merging