Your branch name
EddieHubCommunity/LinkFree pull request #974
Opened 2022-01-12 10:44 UTC by imlakshay08

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-01-12 14:19 UTC, emmalearnscode requested changes
You're profile looks great! However, please remove (un-commit, not delete) the package-lock.json file from the pull request.

2022-01-12 15:18 UTC, krishguptadev approved these changes
Just package-lock then 🚀

2022-01-12 16:53 UTC, Panquesito7 approved these changes

2022-01-13 04:34 UTC, krishguptadev approved these changes

2022-01-13 04:53 UTC, merged