`closes #969`
EddieHubCommunity/LinkFree pull request #976
Opened 2022-01-12 11:51 UTC by Hat52

I have resolved issue #969

2022-01-12 13:00 UTC, emmalearnscode requested changes
Please remove your profile from the pull request. That should solve the merge conflict.

2022-01-12 15:16 UTC, krishguptadev commented on public/data/HAT52.json
> +{
Please move this to another PR?

2022-01-12 15:17 UTC, krishguptadev commented on Contributing.md
> +⚠️ **Make sure** not to run the command `git add .` or `git add *`
```suggestion
⚠️ **Make sure** not to run the command `git add .` or `git add *` instead stage your changes for each file/folder
```

2022-01-12 17:04 UTC, Panquesito7 commented on Contributing.md
> +⚠️ **Make sure** not to run the command `git add .` or `git add *`instead stage your changes for each file/folder
```suggestion
⚠️ **Make sure** not to run the commands `git add .` or `git add *`. Instead, stage your changes for each file/folder
```

2022-01-12 17:04 UTC, Panquesito7 commented on Contributing.md
> +⚠️ **Make sure** not to commit package.json or package-lock.json file
```suggestion
⚠️ **Make sure** not to commit `package.json` or `package-lock.json` file
```

2022-01-21 20:16 UTC, Hat52 commented
Are there any issues with this pull request?
I have removed my profile from the pull request.

2022-01-21 20:31 UTC, emmalearnscode commented
There are a couple of suggestions from @Panquesito7  which help to make it more readable. If you could make these small updates this should be good to go 👍🏻

2022-01-21 20:33 UTC, Hat52 commented
Ok

2022-01-24 18:35 UTC, emmalearnscode approved these changes

2022-01-24 18:50 UTC, Panquesito7 reviewed
Could you please take a look at my suggestion https://github.com/EddieHubCommunity/LinkFree/pull/976/files#r783273119 and let me know what do you think? Thanks. 🙂

2022-01-25 15:12 UTC, krshdev approved these changes

2022-01-25 15:48 UTC, Panquesito7 approved these changes

2022-01-25 18:48 UTC, merged