my info added
EddieHubCommunity/LinkFree pull request #994
Opened 2022-01-15 13:50 UTC by Srinika99

## Fixes Issue

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2022-01-15 15:20 UTC, emmalearnscode approved these changes

2022-01-15 17:11 UTC, syedsohan requested changes

2022-01-15 17:11 UTC, syedsohan commented on public/data/Srinika99.json
> +}
```suggestion
}

```

2022-01-15 20:41 UTC, syedsohan approved these changes

2022-01-16 02:10 UTC, Panquesito7 commented on public/data/Srinika99.json
> +
```suggestion
```

2022-01-16 02:10 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-16 02:13 UTC, merged